jscomp/j.ml, jscomp/j_helper.ml, jscomp/j_helper.mli, jscomp/js_fold.ml, jscomp/js_map.ml, jscomp/js_op.ml, jscomp/js_op_util.ml, jscomp/js_op_util.mli, jscomp/lam_compile_group.ml, jscomp/lam_compile_primitive.ml, jscomp/lam_dispatch_primitive.ml, jscomp/stdlib/pervasives.js, jscomp/stdlib/sys.js, jscomp/test/.depend, jscomp/test/buffer_test.js, jscomp/test/buffer_test.ml, jscomp/test/empty_obj.d.ts, jscomp/test/empty_obj.js, jscomp/test/empty_obj.ml, jscomp/test/test_per.js
Squashed commits:
[72476aa] fix {!Sys.max_string_length}
[e628e34] micro-optimize band (when its inner is `|`) (+1 squashed commit)
Squashed commits:
[f9bf7d1] micro-optimize int32_lsr (+1 squashed commit)
Squashed commits:
[918fe00] now it works, there is a bug in precedence printer, tweak and micro-optimize it later (+3 squashed commits)
Squashed commits:
[6ed0c1b] using js integer semantics for js ir
1. this is consistent with what we did
2. easy for optimizations, we don't want to add another JS IR after all, if we do too much compilation in [js_dump], that will
make some simple cases hard to optimize like [ (x >>> (i * 8) | 0 )  & 255]
[935b94f] migrate div to int32_div
[1120b77] prepare int 32 operation support
=> add empty obj unit test (+2 squashed commits)

jscomp/ext_log.mli, jscomp/j.ml, jscomp/js_fold.ml, jscomp/js_helper.ml, jscomp/js_helper.mli, jscomp/js_map.ml, jscomp/lam_compile_primitive.ml, jscomp/lam_dispatch_primitive.ml, jscomp/runtime/caml_primitive.js, jscomp/runtime/caml_primitive.ts, jscomp/test/ext_filename.js, jscomp/test/test_char.d.ts, jscomp/test/test_char.js, jscomp/test/test_char.ml, jscomp/test/test_fastdt.js
and also warning in the compile time, also it will return undefined
=> when primitive is missing, we do `console.error` for a better error message

jscomp/js_output.ml, jscomp/lam_analysis.ml, jscomp/lam_analysis.mli, jscomp/lam_compile.ml, jscomp/lam_util.ml, jscomp/lam_util.mli, jscomp/runtime/caml_string.js, jscomp/stdlib/camlinternalFormat.js, jscomp/stdlib/filename.js, jscomp/stdlib/hashtbl.js, jscomp/stdlib/list.js, jscomp/stdlib/map.js, jscomp/stdlib/printexc.js, jscomp/stdlib/set.js, jscomp/test/a_string_test.js, jscomp/test/ext_string.js, jscomp/test/int_map.js, jscomp/test/map_test.js, jscomp/test/map_test.ml, jscomp/test/test_for_map.js, jscomp/test/test_internalOO.js, jscomp/test/test_list.js, jscomp/test/test_order_tailcall.js, jscomp/test/test_set.js, jscomp/test/test_string.js, jscomp/test/ticker.js
for things like `return +(code>31 && code< 96)`,  we can improve it later
=> fix && || tail call, it generates some large expressions (Fix #50)

jscomp/j.ml, jscomp/js_analyzer.ml, jscomp/js_dump.ml, jscomp/js_fold.ml, jscomp/js_helper.ml, jscomp/js_helper.mli, jscomp/js_map.ml, jscomp/js_op.ml, jscomp/lam_compile.ml, jscomp/lam_compile_external_call.ml, jscomp/lam_dispatch_primitive.ml, jscomp/runtime/caml_obj.d.ts, jscomp/runtime/caml_obj.js, jscomp/runtime/caml_obj.ml, jscomp/runtime/caml_obj.mli, jscomp/stdlib/obj.js, jscomp/stdlib/parsing.js, jscomp/stdlib/printexc.js, jscomp/test/.depend, jscomp/test/obj_magic_test.d.ts, jscomp/test/obj_magic_test.js, jscomp/test/obj_magic_test.ml
1. use a uniform Length for various objects,
2. specialize handling `caml_obj_is_block`, we can not use `js_object_length` since it alreay assumes that it is a block
=> Simplify length

jscomp/lam_compile_external_call.ml, jscomp/lib/bench.ml, jscomp/lib/js.ml, jscomp/lib/js.mli, jscomp/lib/js_date.ml, jscomp/runtime/caml_float.ml, jscomp/runtime/caml_io.ml, jscomp/test/.depend, jscomp/test/ffi_test.d.ts, jscomp/test/ffi_test.js, jscomp/test/ffi_test.ml, jscomp/test/test.mllib, jscomp/test/test_react.ml
so we can write both
```ocaml
external ff : int -> int = "a" [@@js.call]
external ff : int -> int = "" [@@js.call "a"]
```
Note that names in `js.call` has a higher priority
TODO: finish `js.set` and `js.get`
=> enhance external part of ffi a bit

CONTRIBUTING.md, DCO.md
There is a slight inconsistency here as the LICENSE file still contains a copy of GPLv2, but I don't want to change that in this commit. That will get fixed next week when the licensing cleanup is completed.
=> Add contribution process guidelines and DCO

jscomp/build.sh, jscomp/ppx_entry.ml, jscomp/test/unsafe_ppx_test.js, jscomp/test/unsafe_ppx_test.ml
such as 
```ocaml
let f : float -> float -> float = [%js.raw "Math.max" ]
```
the type annotation will be used in arity inference
=> allow more flexible type annotation in `js.raw`

jscomp/ext_ident.ml, jscomp/lam_dispatch_primitive.ml, jscomp/lib/js.ml, jscomp/runtime/.depend, jscomp/runtime/caml_format.js, jscomp/runtime/caml_format.ml, jscomp/runtime/caml_format.mli, jscomp/runtime/caml_int64.js, jscomp/runtime/caml_int64.ml, jscomp/runtime/caml_int64.mli, jscomp/stdlib/camlinternalFormat.js, jscomp/stdlib/int64.js, jscomp/test/.depend, jscomp/test/caml_format_test.js, jscomp/test/caml_format_test.ml, jscomp/test/hamming_test.ml, jscomp/test/int64_mul_div_test.js, jscomp/test/int64_mul_div_test.ml, jscomp/test/int64_test.js, jscomp/test/int64_test.ml, jscomp/test/lazy_test.js, jscomp/test/lazy_test.ml, jscomp/test/stringmatch_test.js, jscomp/test/stringmatch_test.ml, jscomp/test/test.mllib
also fix a minor bug when escaping ` (%) `
=> caml_int64_format support, clean up the implementation next revision

jscomp/lib/js.ml, jscomp/runtime/caml_io.js, jscomp/runtime/caml_io.ml, jscomp/test/.depend, jscomp/test/printf_sim.js, jscomp/test/printf_sim.ml, jscomp/test/test.mllib
`Printf.printf` is involved in io, however, since it is widely used, it make senses to get it working, here we made a naive simulation using `console.log` stay tuned
=> simulate stdout using console.log -- get Printf.printf to work

jscomp/ext_string.ml, jscomp/ext_string.mli, jscomp/lam_compile.ml, jscomp/lib/js_fn.ml, jscomp/test/.depend, jscomp/test/ext_string.js
also rename `00_js_fn_mk` to `js_fn_mk_00` to follow the same convention `js_blabla`
=> avoid allocation when check the arity

jscomp/ext_string.ml, jscomp/ext_string.mli, jscomp/lam_compile.ml, jscomp/lam_util.ml, jscomp/lam_util.mli, jscomp/lib/js_fn.ml, jscomp/test/.depend, jscomp/test/event_ffi.js, jscomp/test/event_ffi.ml, jscomp/test/ext_string.js, jscomp/test/ffi_arity_test.js, jscomp/test/ffi_arity_test.ml, jscomp/test/test.mllib
TODO: we need make `Js_fn.mk0` a little nice, the hack that remove unused single parameter seems to be unnecessary any more
=> fix a bug in Js_fn module

jscomp/Makefile, jscomp/config_util.ml, jscomp/config_util.mli, jscomp/js_cmj_datasets.mli, jscomp/js_cmj_format.ml, jscomp/js_cmj_format.mli, jscomp/js_config.ml, jscomp/js_config.mli, jscomp/lam_compile_env.ml, jscomp/lam_compile_env.mli, jscomp/lam_stats_export.ml, jscomp/lam_stats_export.mli, jscomp/lib/.libdepend, jscomp/lib/Makefile, jscomp/runtime/.runtimedepend, jscomp/runtime/Makefile, jscomp/runtime/caml_format.ml, jscomp/runtime/caml_int64.ml, jscomp/runtime/caml_io.js, jscomp/runtime/caml_io.ml, jscomp/runtime/caml_md5.ml, jscomp/runtime/runtime.mllib, jscomp/stdlib/.depend, jscomp/stdlib/Makefile.shared, jscomp/test/.libdepend, jscomp/test/.runtimedepend, jscomp/test/Makefile
=> [refact] clean up the dependency, make sure runtime will not read files from stdlib

jscomp/compiler.mllib, jscomp/ext_list.ml, jscomp/ext_list.mli, jscomp/ext_ref.ml, jscomp/ext_ref.mli, jscomp/ppx_entry.ml, jscomp/test/.depend, jscomp/test/http_types.ml, jscomp/test/test_index.ml, lib/js/test/ext_list.js, lib/js/test/test_index.js
=> [feature] provide `[%uncurry: < x : int ; y : int > Js.t ] syntactic sugar`

jscomp/ppx_entry.ml, jscomp/test/.depend, jscomp/test/demo.ml, jscomp/test/nested_obj_literal.ml, jscomp/test/nested_obj_test.ml, jscomp/test/test.mllib, lib/js/test/nested_obj_literal.js, lib/js/test/nested_obj_test.js
```ocaml
let f : < x : < y : < z : int > > > [@bs.obj]  = {x = { y = { z = 3 }}} [@bs.obj]
```
=> Continue ppx obj, provide nested object literal/type support

jscomp/Makefile
BSD systems have GNU make installed as "gmake". Make subprocesses should
use the same binary as the one specified from the command line (which is
$(MAKE)). Successfully tested with DragonFly BSD.
Signed-Off-By: Michael Neumann <mneumann@ntecs.de>
=> Do not hardcode "make", use $(MAKE) instead.

jscomp/core.mllib, jscomp/js_main.ml, jscomp/lam_compile_external_call.ml, jscomp/lam_external_def.ml, jscomp/lam_external_def.mli, jscomp/test/.depend, jscomp/test/gpr_441.ml, jscomp/test/test.mllib, lib/js/test/gpr_441.js
=> add check mode to address #441

jscomp/syntax/ppx_entry.ml, jscomp/test/chain_code_test.ml, jscomp/test/config2_test.ml, jscomp/test/config2_test.mli, jscomp/test/demo.ml, jscomp/test/gpr_459_test.ml, jscomp/test/http_types.ml, jscomp/test/method_name_test.ml, jscomp/test/nested_obj_literal.ml, jscomp/test/nested_obj_test.ml, jscomp/test/obj_literal_ppx.ml, jscomp/test/promise.ml, jscomp/test/test_index.ml, lib/js/test/nested_obj_test.js
TO justify we move from `[@bs.obj]` into `[%bs.obj]`
we want to support such cases
```ocaml
[%bs.obj                                                                                                                                                                                  
[                                                                                                                                                                                       
{ x = { y = { z = 3 }}} ;                                                                                                                                                             
{ x = { y = { z = 31 }}} ; …
```
=> use extension point for bs.obj instead

jscomp/syntax/ast_attributes.ml, jscomp/syntax/ast_attributes.mli, jscomp/syntax/ppx_entry.ml, jscomp/test/class_type_ffi_test.js, jscomp/test/class_type_ffi_test.ml
so user can use short-cut syntax without declaring class type
```ocaml
let f (x : < bark : string  -> unit [@bs.meth] > Js.t) = 
x ##bark "hi"
```
TODO: documentation
@mransan can not use `method` since `method` is a keyword
=> support bs.method

docs/SUMMARY.md
The Extensions.md document was deleted in 0f12773
=> Remove "Language Extensions" from SUMMARY.md

jscomp/runtime/caml_lexer.ml, lib/js/caml_lexer.js
=> should work with flow now

js-demo/examples/examples.json, js-demo/index.html
The reason why I changed "Examples:" to "Default Example" is because the "Example: " nav item by itself doesn't easily position itself correctly on small screen.
Also make some title casing consistent.
Before:
After:
=> [Docs] Make live demo header better on small screen width

js-demo/edit.js
Editor happened to strip the trailing whitespace if you don't mind.
(I also changed the "Eval" label into "Evaluate" instead. Slightly clearer for newcomers that it's not a technical OCaml concept e.g. "turn on eval").
=> [Docs] Eval on checkbox toggle on

.gitattributes
So that github & git viewing tools don't have to display the huge diff
=> [Docs] Prevent compiled output from display in diff views

docs/Manual.html, site/docsource/OCaml-call-JS.adoc
See (here)[http://bloomberg.github.io/bucklescript/Manual.html#_binding_to_method_bs_send_bs_send_pipe].
=> Fix typo in manual getElementById should be get_by_id

CHANGELOG.adoc, jscomp/syntax/ppx_entry.ml, jscomp/test/CCSexpM.js, jscomp/test/chain_code_test.js, jscomp/test/chain_code_test.ml, jscomp/test/ppx_this_obj_field.js, jscomp/test/ppx_this_obj_field.ml
Note that another issue: `h##property`  will not generate constraints for `h##property#=` (and vice versa), this in general will not be an issue, since users  can not create such object, but   we have to wait for users to call it to cause type error), actually it is not very easy to generate constraints since nullable/undefined)
=> enforce #= always return unit for better error message

docs/Manual.html, site/docsource/Get_started.adoc
Neither `0.9.3` nor `0.9.4` included `bs.send.pipe`, the installed version has to be the latest to make the example work.
=> correct the installed version in documentation

jscomp/bin/bs_ppx.ml, jscomp/bin/compiler.ml, jscomp/common/js_config.ml, jscomp/common/js_config.mli, jscomp/ext/ext_list.ml, jscomp/ext/ext_list.mli, jscomp/js_main.ml, jscomp/lam_compile_group.ml, jscomp/test/ext_list.js
```
bsc -bs-sort-imports xx.ml
```
will sort the name by lexical order, cc @chenglou
=> add an option -bs-sort-imports to get a more stable js output

jscomp/runtime/caml_sys.ml
It was subtracting a result that was already `*. 0.001` and then doing `*. 0.001` again, fixed.
=> Fix Sys.time

jscomp/bin/bsdep.ml, jscomp/bin/bsppx.ml, jscomp/bin/compiler.ml, jscomp/bin/whole_compiler.ml, jscomp/common/js_config.ml, jscomp/common/js_config.mli, jscomp/js_implementation.ml, jscomp/js_main.ml, package.json
jscomp>bsc.exe -bs-syntax-only -dparsetree -bs-eval 'let a = 3'
[
structure_item (//toplevel//[1,0+0]..[1,0+9])
Pstr_value Nonrec
[
<def>
pattern (//toplevel//[1,0+4]..[1,0+5])
Ppat_var "a" (//toplevel//[1,0+4]..[1,0+5])
expression (//toplevel//[1,0+8]..[1,0+9])
Pexp_constant Const_int 3
]
]
=> provide -bs-syntax-only

site/docsource/CHANGELOG.adoc
The CHANGELOG.adon file did not have a `/` after `{issues}` unlike the rest of the docs.  The `/` is required as the URL in `{issues}` does not end with a trailing `/`.
=> Correct issue links so they point to a valid URL.

.gitignore, bsconfig.json, jscomp/Makefile, jscomp/all.depend, jscomp/bin/bsb.d, jscomp/bin/bsb.ml, jscomp/bsb/bs_build_util.ml, jscomp/bsb/bs_ninja.ml, jscomp/bsb/bsb_config.ml, jscomp/bsb/bsb_config.mli, jscomp/bsb/bsb_main.ml
Currently, `bsb.exe` assume that `bsc.exe` and `bsdep.exe` are sitting in the same directory as `bsb.exe`.
And it try to figure out the path of `bsc.exe` by using Sys.executable_name.
Note this is not nice that Sys.executable_name does not always return an absolute path, if it returns
a relative path(it can in theory change each time of invocation), we have to adjust it to the working dir `lib/bs`, the worse thing is that if we change the path of `bsb.exe`, it may impact the path, and ninja will recalculate all deps (the ninja behavior is correct)
A simple solution in the future would be just hard code the absolute path of `bsb.exe` during configuration, and we add a check if `bsb.exe`'s path has changed during each execution
Also allow people to configure `bsc.exe` and `bsdep.exe` seems …
=> quick fix for bsc, bsdep path

.gitignore, jscomp/bin/bsb.ml, jscomp/bin/bsdep.ml, jscomp/bin/bspp.ml, jscomp/bin/bsppx.ml, jscomp/bin/whole_compiler.ml, jscomp/bsb/bs_dep_infos.ml, jscomp/bsb/bs_json.ml, jscomp/bsb/bsb_main.ml, jscomp/common/binary_ast.ml, jscomp/common/binary_cache.ml, jscomp/core/bspack_main.ml, jscomp/core/bspp_main.ml, jscomp/ext/ext_io.ml, jscomp/ext/ext_pervasives.ml, jscomp/test/ext_pervasives.js, jscomp/test/qcc.js, jscomp/test/qcc.ml, jscomp/test/sexpm.js, jscomp/test/sexpm.ml
Note `output_value`, `input_value` requires channel to be opened in binary mode
https://caml.inria.fr/mantis/view.php?id=5639
TODO:
Reading directories from `sources`, we need convert linux path to platform dependent path,
however, we should only convert it into absolute path for once? (or it maybe not necessary since source files have to be in the project directory)
=> use open_out_bin (open_out does not work with marshal on windows)

jscomp/bin/whole_compiler.ml, jscomp/core/Boolean.adoc, jscomp/core/j.ml, jscomp/core/js_analyzer.ml, jscomp/core/js_dump.ml, jscomp/core/js_exp_make.ml, jscomp/core/js_fold.ml, jscomp/core/js_map.ml, jscomp/core/js_stmt_make.ml, jscomp/test/.depend, jscomp/test/Makefile, jscomp/test/flow_parser_reg_test.js, jscomp/test/gpr_904_test.js, jscomp/test/gpr_904_test.ml, jscomp/test/js_json_test.js, jscomp/test/js_json_test.ml, jscomp/test/ocaml_proto_test.js, jscomp/test/stack_comp_test.js, lib/js/caml_int64.js, lib/js/caml_obj.js, lib/js/caml_weak.js, lib/js/camlinternalFormat.js, lib/js/js_json.js
Note we still introduce `Js_not` and `Caml_not` since the optimization will introduce JS_not under conditional context
=> Fix not semantics (#904)

site/docsource/Dev-mode-How-to.adoc
Some of the `make` commands require having ocaml built; otherwise they'll print slightly confusing errors.
=> [Docs] Correct `make lib` command & add instructions on building OCaml

jscomp/bin/bsb.ml, jscomp/bsb/bsb_default.ml, jscomp/bsb/bsb_default.mli, jscomp/bsb/bsb_gen.ml, jscomp/bsb/bsb_gen.mli, jscomp/bsb/bsb_main.ml, jscomp/bsb/bsb_ninja.ml
This makes refmt resolve the same way ppx resolve. See the path resolution comment.
One difference is that this defaults to refmt rather than nothing. Not sure about this behavior.
=> [bsb] Support refmt path

bsconfig.json, docs/docson/build-schema.json, jscomp/all.depend, jscomp/bin/all_ounit_tests.ml, jscomp/bin/bsb.ml, jscomp/bin/bsb_helper.ml, jscomp/bin/bsdep.ml, jscomp/bin/bsppx.ml, jscomp/bin/whole_compiler.ml, jscomp/bsb/bsb.adoc, jscomp/bsb/bsb_build_schemas.ml, jscomp/bsb/bsb_config.ml, jscomp/bsb/bsb_config.mli, jscomp/bsb/bsb_default.ml, jscomp/bsb/bsb_default.mli, jscomp/bsb/bsb_gen.ml, jscomp/bsb/bsb_gen.mli, jscomp/bsb/bsb_main.ml, jscomp/bsb/bsb_ninja.ml, jscomp/bsb/bsb_ninja.mli, jscomp/ext/literals.ml, jscomp/ext/literals.mli, jscomp/test/literals.js
catches: its dependency has to be built  with such support two (improve its error message) the rule output has to be update (otherwise users have to create directories beforehand) the flags (currently) has to be updated for each target (due to that we need to specify the output location and new outputs)
=> 1. provide amdjs and google module support in the build system 

.travis.yml, jscomp/all.depend, jscomp/bin/whole_compiler.ml, jscomp/core/lam_dispatch_primitive.ml, jscomp/runtime/js_primitive.ml, jscomp/runtime/js_primitive.mli, jscomp/test/.depend, jscomp/test/Makefile, jscomp/test/gpr_974_test.js, jscomp/test/gpr_974_test.ml, jscomp/test/map_test.ml, lib/js/caml_weak.js, lib/js/js_primitive.js
note current architecture requires primitive/ external call to return an expression(not a block), in the future, when refactoring, we should lift such restriction for better inlining
=> fix grr #974 

jscomp/runtime/caml_obj.ml, lib/js/caml_obj.js
This does the reference comparison first before trying the structural one.
=> Add quick path to caml_obj.caml_equal

bsconfig.json, jscomp/bin/bsb.ml, jscomp/bsb/bsb_default.ml, jscomp/bsb/bsb_default.mli, jscomp/bsb/bsb_main.ml
if we have `bs-mocha` in the dependencies:
```
S /Users/hzhang295/git/bucklescript-addons/bindings/bs-string/node_modules/bs-mocha/lib/ocaml
B /Users/hzhang295/git/bucklescript-addons/bindings/bs-string/node_modules/bs-mocha/lib/ocaml
```
To make peek source definition work, our installation should also install source files (cc @chenglou )
=> address #986 and #984

jscomp/.merlin, jscomp/all.depend, jscomp/bin/all_ounit_tests.d, jscomp/bin/all_ounit_tests.ml, jscomp/bin/whole_compiler.d, jscomp/bin/whole_compiler.ml, jscomp/core/lam_compile_group.ml, jscomp/depends/bs_exception.ml, jscomp/depends/bs_exception.mli, jscomp/ext/hash_set.ml, jscomp/ext/hash_set.mli, jscomp/ext/hash_set_gen.ml, jscomp/ext/int_hash_set.ml, jscomp/ext/int_hash_set.mli, jscomp/ext/string_hash_set.ml, jscomp/ext/string_hash_set.mli, jscomp/ext/string_hashtbl.ml, jscomp/ounit_tests/ounit_bal_tree_tests.ml, jscomp/ounit_tests/ounit_hash_set_tests.ml, jscomp/ounit_tests/ounit_hash_stubs_test.ml, jscomp/test/fail/gpr_978.ml, jscomp/test/fail/gpr_978.mli, jscomp/test/fail/gpr_978_module.ml
address #978 
so we will do a sanity check to reject such program:
```x.mli
exception M of int
module M : sig 
end
```
```x.ml
exception M of int
module M = struct 
end
```
This rates happen in practice (export two components with the same name, it is fine to have two components with the same name, the error only happens when user tries to export two components at the same time with the same name)
Error message is like this:
```
Error: M are exported as twice   
```
=> fix #978, add check_add function in hash_set

jscomp/bin/bsb.ml, jscomp/bsb/bsb_main.ml
1. better error message when ninja is not installed #1044 
2. -d keepdepfile is not actually needed (we dont use deps trick)
=> better error message when ninja not installed #1044 

jscomp/others/.depend, jscomp/others/js_null_undefined.ml, jscomp/runtime/js_null.ml, jscomp/runtime/js_undefined.ml
https://github.com/bloomberg/bucklescript/pull/1061/files?w=1
There's a new `js_math.cmj` when I ran `make depend` in `others`
=> Implement from_opt for Js_null, js_undefined, js_null_undefined

jscomp/others/js_null_undefined.mli, jscomp/runtime/js_null.mli, jscomp/runtime/js_undefined.mli, lib/js/js_null.js, lib/js/js_null_undefined.js, lib/js/js_undefined.js
Follow-up to #1061.
Sorry about this. This was implemented but not exposed. Now tested and works.
=> Expose Js_(null|undefined|null_undefined).from_opt in mli

site/docsource/Dev-mode-How-to.adoc, site/docsource/Runtime-representation.adoc
Do we need to link to `bs.obj` here? Seems appropriate.
=> [Docs] Add contrib to docs; add from_opt in runtime representation

bin/bsb, docs/docson/build-schema.json, jscomp/Makefile, jscomp/all.depend, jscomp/bin/bsb.ml, jscomp/bin/whole_compiler.ml, jscomp/bsb/bsb_default.ml, jscomp/bsb/bsb_default.mli, jscomp/bsb/bsb_main.ml, jscomp/bsb/bsb_unix.ml, jscomp/bsb/bsb_unix.mli, jscomp/core/js_main.ml
1,
```
bsb -clean-world -make-world -w
```
2. allow user to override package-spec from his repo, 
suppose he has package a, which depends on package b, package c.
as long as package a asks to build goog module, we do the same for b and c regardless of how b and c is set up
=> stream line clean-world, make-world, allow user to override package-specs

jscomp/bin/bsb.ml, jscomp/bsb/bsb_gen.ml
Reason changed the `refmt` command's defaults to output Reason syntax. To output binary, it's now `refmt --print binary`.
https://github.com/bloomberg/bucklescript/pull/1139/files?w=1
=> Quote `refmt` in build.ninja

jscomp/bin/bsb.ml, jscomp/bsb/bsb_default.ml
I didn't change refmt to "reason/refmt_impl.native" yet. Esy might be able to kill this implementation detail and put `refmt` into the environment correctly.
=> [bsb] default refmt-flags to ["--print", "binary"]

jscomp/Makefile, jscomp/all.depend, jscomp/bin/all_ounit_tests.i.ml, jscomp/bin/bsdep.ml, jscomp/bin/bsppx.ml, jscomp/bin/whole_compiler.ml, jscomp/common/js_config.ml, jscomp/common/js_config.mli, jscomp/core/config_util.ml, jscomp/core/config_util.mli, jscomp/core/js_dump.ml, jscomp/core/js_program_loader.ml, jscomp/core/lam_compile_env.ml, jscomp/core/lam_compile_env.mli
This commit introduces two package format, amdjs-global and es6-global, which will use relative path so that for some bundlers like rollup or google closure, it does not need have knowledge of node_modules path resolution
couple of design issues:
1. how to know the path of external JS library, currently we leave it as it
Implementation details:
we might need have a global view of dependencies and pass a package map unlike current implementation which did lots of path calculation
=> experimental support of es6 global module

jscomp/others/js_array.ml, jscomp/others/js_string.ml, jscomp/test/Makefile, jscomp/test/array_subtle_test.ml, jscomp/test/js_array_test.js, jscomp/test/js_array_test.ml, jscomp/test/js_re_test.ml, jscomp/test/js_string_test.js, jscomp/test/js_string_test.ml
This more or less brings js_array and js_string to es2015 compliance.
It has the following breaking changes:
* `Array.slice_copy` has been renamed `Array.sliceCopy`
* `Array.slice_start` has been renamed `Array.sliceFrom`
* `Array.lastIndexOf` has been renamed `Array.lastIndexOfFrom`
* `Array.lastIndexOf_start` has been renamed `Array.lastIndexOf`
* `String.concat` has been renamed `String.concatMany`
* A new non-spliced function has taken the place of the old `String.concat`
=> Additions to js_string and js_array

jscomp/bin/bsb.ml, jscomp/bsb/bsb_ninja.ml
Chose blue for "Building" because it's non-alerting, dim (aka faded) for path because if there's an error, the error message contains the path anyway
=> Color ninja output

jscomp/others/js_obj.ml, jscomp/test/js_obj_test.js, jscomp/test/js_obj_test.ml
Just a suggestion. Although I see from #444 that this has been judged not very useful, I keep having to write `[%bs.raw "{}"]`, and would rather not.
Here's some instances of it being used "in the wild":
* https://github.com/reasonml/rehydrate/blob/master/src/reactRe.re#L488
* https://github.com/bloomberg/bucklescript/blob/master/jscomp/test/flow_parser_reg_test.ml#L13406
=> Added Js_obj.empty + test

jscomp/others/Makefile, jscomp/others/js_global.ml, jscomp/runtime/js.ml, jscomp/test/Makefile, jscomp/test/js_global_test.js, jscomp/test/js_global_test.ml, lib/js/js_global.js
There's lots of open questions about how to handle all the different global scopes and the complex APIs they open up, but this seems like a fairly safe beginning. But even this isn't open and shut, as I discovered `atob` and `btoa` aren't supported on node, and likely won't be.
=> Adds Js.Global with a few safe basics

jscomp/runtime/caml_int64.ml
Fixes #1088 by leveraging float multiplication.
=> Fix `to_float` so it can be compiled on 32-bit systems.

jscomp/others/js_json.ml, jscomp/others/js_json.mli, jscomp/test/.depend, jscomp/test/js_json_test.js, jscomp/test/js_json_test.ml
Partially because it'd be nice to have JSON.stringify, partially because we haven't figured out a newcomer-friendly way of parsing & stringifying JSON data (including ocaml data structures) yet.
=> Add unsafe JSON calls

jscomp/others/Makefile, jscomp/others/js_cast.ml, jscomp/others/js_cast.mli, jscomp/test/Makefile, jscomp/test/js_cast_test.js, jscomp/test/js_cast_test.ml, lib/js/js_cast.js
Add Js_cast module to safely cast between OCaml types which shares the same runtime representation.
=> Add js cast

jscomp/bin/bsb.ml, jscomp/bsb/bsb_main.ml
👋 
Thanks for the `GOOD FIRST TASK` label 👍 
`bsb` will now print the usage text and exit when given an anonymous arg.
=> Show usage info when `bsb` is given unknown args

jscomp/others/js_json.ml, jscomp/others/js_json.mli, jscomp/test/js_json_test.js, jscomp/test/js_json_test.ml, lib/js/js_json.js, package.json
In order to make it easier to read the a JSON object, this PR provides `*OfJson functions` for all JSON types. 
Note this is currently limited to `string` just to discuss the API before I got and make all the other types.
=> Add Js_json.*OfJson functions

jscomp/Makefile, jscomp/all.depend, jscomp/bin/bsdep.d, jscomp/bin/bsdep.ml, jscomp/bin/bsppx.d, jscomp/bin/bsppx.ml, jscomp/bin/whole_compiler.d, jscomp/bin/whole_compiler.ml, jscomp/common/bs_warnings.ml, jscomp/common/lam_methname.ml, jscomp/core/lam.ml, jscomp/core/lam_compile_external_call.ml, jscomp/install-bsc.sh, jscomp/syntax/ast_attributes.ml, jscomp/syntax/ast_core_type.ml, jscomp/syntax/ast_derive.ml, jscomp/syntax/ast_external_attributes.ml, jscomp/syntax/bs_syntaxerr.ml, jscomp/test/.depend, jscomp/test/Makefile, jscomp/test/bb.js, jscomp/test/bb.ml
Fix #1418 
Note this commit start to migrate from `Location.raise_errof` from the standard way of error reporting (see Bs_syntaxerr module) which supports syntax coloring etc
The change is incomplete since we have too many `Location.raise_errorf`
=> standard colorful error format reporting

jscomp/all.depend, jscomp/others/.depend, jscomp/others/Makefile, jscomp/others/dom.mli
The rationale for standardizing this is to ease interop between different implementations, and to be able to deal with these types without having to pull in huge dependencies that otherwise won't be used.
This is very far from complete, but it's a good subset to start with. It's also not settled that this is the best way to do subtyping, but most users will only be concerned with the concrete types (e.g. `element`, not `element_like 'a`) and shouldn't be affected by implementation changes outside of having to recompile.
=> Adds Js_dom module with dom types from reason-js

jscomp/bin/whole_compiler.ml, jscomp/core/design.md, jscomp/core/js_dump.ml, jscomp/test/.depend, jscomp/test/Makefile, jscomp/test/export_keyword.js, jscomp/test/export_keyword.ml, jscomp/test/key_word_property.js, jscomp/test/key_word_property.ml, jscomp/test/key_word_property2.js, jscomp/test/key_word_property2.ml
=> allow keyword in properties

jscomp/bin/bsb.ml, jscomp/bsb/bsb_pkg.ml
Simple typo I found in output when a dependency was missing.
=> Fix typo of 'pakcage' to 'package'

docs/docson/build-schema.json
- The schema currently shows, for `public` field of `sourceItem`, "one of
constant any array", which didn't make sense. Removing the description
(it's already described in the description of `public`).
- Adding type `object` to `group` field of `sourceItem` also kills
awkward "one of string any".
=> [Docs] Remove accidental "any" generated by the schema

scripts/buildocaml.sh
We discussed this a little bit in Discord, but this should perform an update instead of clone if the `ocaml_src` directory already exists.
Sorry about the whitespace noise in the diff.
=> Fix building OCaml from source when postinstall happens more than once

jscomp/others/js_re.mli
Simple typo I found in Js.Re documentation.
=> Fix typo of '=>' to '->' at Js.Re documentation

scripts/install.js
Make on BSDs is BSD Make. The Makefile for this project uses GnuMake
syntax on BSDs this is installed as a separate package as gmake.
This fixes #1499
=> Installation on BSDs need to use gmake.

scripts/buildocaml.sh
This commit also gets rid of `$(pwd)` subshell invocation. Instead `$PWD` is used which buys some milliseconds.
=> Fix handing spaces in buildocaml.sh

site/docsource/OCaml-call-JS.adoc
Signed-Off-By: William Cybriwsky <william.cybriwsky@gmail.com>
=> Fix two small typos in OCaml-call-JS.adoc

docs/docson/build-schema.json, jscomp/bin/bsb.ml, jscomp/bin/bsb_helper.ml, jscomp/bin/bsdep.ml, jscomp/bin/bspp.ml, jscomp/bin/whole_compiler.ml, jscomp/bsb/bsb_build_schemas.ml, jscomp/bsb/bsb_build_ui.ml, jscomp/bsb/bsb_build_ui.mli, jscomp/bsb/bsb_ninja.ml, jscomp/bsb/bsb_ninja.mli, jscomp/common/binary_cache.mli
A sample usage would be 
```js
{ ... ,
"rules" :
[ { "name" :   "ocamllex":  "command" : "ocamllex.opt $in $out"}], 
... 
"dev-generators" : [
{ 
"rule" : "ocamllex",
"in" :  "test.mll"
"out" : "test.ml" // consider different directories in the future
]
}
```
cc @mransan , does it cover your use case of protobuf?
=> wip: bsb generator/customize rule support

jscomp/others/js_json.mli
The deprecation message of `Json.Js.parse` contains odoc markup.
```
File "/work/__tests__/json_test.ml", line 53, characters 67-80:
Warning 3: deprecated: Js.Json.parse
Use {!Js.Json.parseExn} instead
```
I remove this, because this is plain text area.
=> Strip odoc markup from deprecation message

jscomp/syntax/ast_external_attributes.ml, jscomp/syntax/bs_syntaxerr.ml, jscomp/syntax/bs_syntaxerr.mli
Fix #1577
Instead of "Conflict attribute", provide more detailed messages such as:
"Error: conflicting FFI attributes found: you used an FFI attribute that cannot be used with [@@bs.module]."
Note @bobzhang : Are the error messages I wrote accurate? There are some cases for which I was really not sure.
=>  #1577 friendlier conflicting ffi attribute errors

docs/Manual.html, site/docsource/Dev-mode-How-to.adoc, site/docsource/Installation.adoc
Clarify instructions for building docs.
Add step to `cd jscomp` before calling `make` when building bucklescript from source.
=> Update minimal installation, docs contribution docs

jscomp/bin/bsb.ml, jscomp/bsb/bsb_gen.ml, jscomp/bsb/bsb_init.ml, jscomp/bsb/bsb_templates.ml
Fixes #1605.
This is not sufficient to get the generated npm package to work. npm packages [cannot have spaces](https://docs.npmjs.com/getting-started/using-a-package.json#requirements) in their name, so a separate PR should address this issue.
=> Quote output to ninja build

jscomp/others/js_option.ml, jscomp/others/js_option.mli, jscomp/test/Makefile, jscomp/test/js_option_test.js, jscomp/test/js_option_test.ml, lib/js/js_option.js
I have added what I consider basic functions that should be in every standard library for options. I also created tests for all functions as we didn't have any for these.
I tried running the doc generating script here, but it changes a lot more files than what I was expecting, so I'm leaving this out for now. Let me know how to proceed in this case.
=> Add more functions and tests to Js.Option

jscomp/bin/bsb_watcher.js
On BSD and other system the filename is not passed.
We assume that it is a valid event and will kick off a build.
Fixes #1676
=> validEvent returns true if no filename specified.

jscomp/bsb/templates/basic/.vscode/tasks.json
With this property set to true, the little "build in progress" icon that appears to the left of the "problems" icons in the lower left never stops spinning. What it's supposed to do is only spin while the watch tool is busy (the speed of `bsb` makes it hard to spot, which is a good thing!).
I'm not sure whether vscode is trying to support multiple start/end patterns, but it definitely goes into the wrong state when set to true but the tool still outputs the begin pattern.
=> activeOnStart should be false for the vscode watch task

jscomp/bsb/templates/react/.gitignore, jscomp/bsb/templates/react/README.md, jscomp/bsb/templates/react/bsconfig.json, jscomp/bsb/templates/react/package.json, jscomp/bsb/templates/react/src/interop/README.md, jscomp/bsb/templates/react/src/interop/index.html, jscomp/bsb/templates/react/src/interop/interopRoot.js, jscomp/bsb/templates/react/src/interop/myBanner.js, jscomp/bsb/templates/react/src/interop/myBannerRe.re, jscomp/bsb/templates/react/src/interop/pageReason.re, jscomp/bsb/templates/react/src/simple/index.html, jscomp/bsb/templates/react/src/simple/page.re, jscomp/bsb/templates/react/src/simple/simpleRoot.re, jscomp/bsb/templates/react/webpack.config.js
This is basically copied over from https://github.com/chenglou/reason-react-example
I didn't regenerate things with ocp-ocamlres.
Note that if you test this as-is, it'll fail because reason-react>=0.1.4 (as specified by package.json) isn't released yet (waiting for the bs release). You'd have to manually change it to `https://github.com/SanderSpies/react-on-reason.git`.
Test: see the readme
=> ReasonReact template

README.md
This patch converts all 'bloomberg' URLs and badges to 'bucklescript'.
=> Update URLs and badges for new organization name

jscomp/bin/reactjs_ppx.ml, jscomp/bin/reactjs_ppx_2.ml, jscomp/bin/refmt_main.ml
From https://github.com/facebook/reason/commit/183fed4decbaf954b469a40044ac85e56ccde37b
At this point, the ppxes:
- Fixes #1721
- Recursively transforms non-children props' jsx
- Correctly transforms explicit optional `ref` and `key`.
Test:
- Scaffold a project through `bsb -theme -init react .`
- Try #1721's snippet in a file (e.g. simpleRoot.re)
- Try
```reason
module Foo = {let make ::bar children => Obj.magic 1};
<Foo bar=(fun () => <div />) />
```
and see no error
- Try
```
<Foo key=?(Some "1") bar=(fun () => <div />) />
```
=> Sync in new refmt & jsx ppx from 183fed4

jscomp/Makefile
Signed-Off-By: António Nuno Monteiro <anmonteiro@gmail.com>
Ran into an error while running `jscomp/js.sh`. Adding the explicit path to `bspack.exe` fixes it without having to muck with adding `jscomp/bin` to the PATH.
=> Correct path to bspack.exe in `bin/js_compiler.ml` Makefile target

jscomp/Makefile, jscomp/all.depend, jscomp/bsb/bsb_main.ml, jscomp/bsb/bsb_query.ml, jscomp/bsb/bsb_query.mli
Sample output:
```
bsb -query sources
```
```
reason-react-example>bsb -query sources
BSB check build spec : Bsb forced rebuild
Package bs-platform -> /Users/hongbozhang/git/reason-react-example/node_modules/bs-platform
Package reason-react -> /Users/hongbozhang/git/reason-react-example/node_modules/reason-react
Package reason-js -> /Users/hongbozhang/git/reason-react-example/node_modules/reason-js
QUERY-INFO-BEGIN(sources)
[ { "dir" : "src" , "sources" : [] } , { "dir" : "src/todomvc" , "sources" : [ "App" , "TodoItem" , "TodoFooter" ] } , { \
"dir" : "src/simple" , "sources" : [ "Page" , "SimpleRoot" ] } , { "dir" : "src/logo" , "sources" : [ "Logo" , "LogoRoot"\
, "Constants" , "LifecycleTester" ] } , { "dir" : "src/interop" , "sources" : [ "PageReason" ] } ]
QUERY-INFO-END
```
=> add query info support

scripts/install.js
since bs-platform will move the provided ninja bin, any subsequent runs
of `node postinall` will rebuild ninja from source. this is quite
annoying during development. this commit will check the ninja_bin_output
location to see if there is a compatible binary there before rebuilding
=> check for compiled/moved ninja before recompiling

bin/bsrefmt
Currently it doesn't work because it looks for a bsrefmt.exe. This correct the name
cc @glennsl
=> Expose bsrefmt correctly

docs/docson/build-schema.json, jscomp/bsb/bsb_exception.ml, jscomp/bsb/bsb_package_specs.ml, jscomp/ext/ext_position.ml
The detection was broken; 2 `in-source: false` would still error saying that both configs are in-source
=> [bsb] Fix package-specs in-source detection & provide better errors

Changes.md, docs/Manual.html, docs/blog/index.html, docs/index.html, jscomp/bin/all_ounit_tests.i.ml, jscomp/bin/all_ounit_tests.ml, jscomp/bin/bsdep.ml, jscomp/bin/bsppx.ml, jscomp/bin/whole_compiler.ml, jscomp/core/js_of_lam_option.ml, jscomp/core/js_of_lam_option.mli, jscomp/core/js_of_lam_variant.ml, jscomp/core/js_of_lam_variant.mli, jscomp/core/lam_compile_external_call.ml, jscomp/ounit_tests/ounit_ffi_error_debug_test.ml, jscomp/runtime/js_primitive.ml, jscomp/runtime/js_primitive.mli, jscomp/syntax/ast_arg.ml, jscomp/syntax/ast_arg.mli, jscomp/syntax/ast_attributes.ml, jscomp/syntax/ast_attributes.mli, jscomp/syntax/ast_external_attributes.ml, jscomp/syntax/bs_syntaxerr.ml, jscomp/syntax/bs_syntaxerr.mli, jscomp/test/Makefile, jscomp/test/bs_unwrap_test.js, jscomp/test/bs_unwrap_test.ml, lib/js/js_primitive.js, site/docsource/OCaml-call-JS.adoc, site/docsource/build.sh
Closes #1736 
---
This introduces a `[@bs.unwrap]` attribute as described in #1736 which can be added to an argument to an external, if that argument has an inline anonymous variant as its type, and will have the effect of the boxed value being "unwrapped" from the tagged tuple that bucklescript usually creates for variants at codegen callsites.
For example, this ocaml:
```ocaml
external log :
(
[ `String of string
| `Options of < foo : int > Js.t
] [@bs.unwrap]
)
-> unit = "console.log" [@@bs.val]
let _ = log (`String "foo")
let _ = log (`Options [%bs.obj { foo = 1 }])
```
will compile to this js:
```js
console.log("foo");
console.log({
foo: 1
});
```
One intention is that we can guarantee that if the variant is constructed inline at the callsite, as in ``log (`String "foo")``, then the …
=> Introduce [@bs.unwrap] for inline variant as external arg

.gitmodules
This was causing a few git fetch warnings. We're not using it anywhere
anymore right?
=> Remove submodule config

jscomp/Makefile, jscomp/ext/ext_color.ml, jscomp/ext/ext_color.mli, jscomp/ext/ext_string.mli, jscomp/super_errors/super_location.ml, jscomp/super_errors/super_misc.ml, jscomp/super_errors/super_misc.mli, jscomp/super_errors/super_typecore.ml, jscomp/super_errors/super_warnings.ml
This makes it so that turning on `-bs-better-error` shows errors inline, a big request from the community.
It gracefully degrades to the normal reporting.
=> Display error location inline

jscomp/all.depend, jscomp/bin/bsb.ml, jscomp/bin/bsb_helper.ml, jscomp/bsb/bsb_ninja_file_groups.ml, jscomp/bsb/bsb_ninja_file_groups.mli, jscomp/bsb/bsb_ninja_gen.ml, jscomp/bsb/bsb_ninja_gen.mli, jscomp/bsb/bsb_ninja_global_vars.ml, jscomp/bsb/bsb_ninja_regen.ml, jscomp/bsb/bsb_parse_sources.ml, jscomp/bsb/bsb_parse_sources.mli, jscomp/bsb/bsb_pkg_create.ml, jscomp/bsb/bsb_pkg_map_gen.ml, jscomp/bsb/bsb_pkg_map_gen.mli, jscomp/bsb/bsb_rule.ml, jscomp/bsb/bsb_rule.mli
- We create binary ast for package map, the major benefit is  not for perf  but to express some invariants
- build namespace should be in parallel with build ast so that such time 
is almost free (in config stage), 
since it is compiled in the config stage so it is not 
needed to be specified as dependency later
- we should check that no `pkg-name.ml` exists either
- Which directory we  should put our `pkg-name.ml`
- We need figure out a proper place to be -I ed
- ninja has a special treatment for depfile 
{[
expected depfile to mention, got ..
]}
- make sure merlin can handle it (-open in .merlin)
- make sure install correct (install public modules + namespace map)
- generated Js code for global bindings look reasonable
```ocaml
X.length
```
```
var X$Pkg = require('pkg/lib/js/x-pkg.js') …
```
=> namespace part3 (WIP)

jscomp/Makefile, jscomp/core/js_main.ml, jscomp/reason_outcome_printer/README.md, jscomp/reason_outcome_printer/reason_outcome_printer_main.ml, jscomp/reason_outcome_printer/tweaked_reason_oprint.ml
Port of #1870, with only the changes relevant to the outcome printer
pars.
=> Report error in Reason syntax (take 2)

jscomp/others/js_vector.ml, jscomp/others/js_vector.mli, lib/js/js_vector.js
Replaces `Js.Array.append`, fixes #1884
=> Add Js.Vector.append

jscomp/runtime/js.ml, jscomp/runtime/js.mli
Reverts BuckleScript/bucklescript#1904
=> Revert "Change Js.toOpt to Js.toOption"

jscomp/super_errors/super_misc.ml
I accidentally used the last line's last highlighted char index as the
boundary for the first line's last highlighted char index. First line
should highlight all the way til the end. Also renamed things to make
this clear in the future.
=> Fix super errors line highlighting bug

docs/Manual.html, site/docsource/Dev-mode-How-to.adoc, site/docsource/Exception-handling.adoc, site/docsource/Get_started.adoc, site/docsource/OCaml-call-JS.adoc, site/docsource/Runtime-representation.adoc, site/docsource/js-lib.adoc
Signed-Off-By: Antonio N. Monteiro <anmonteiro@gmail.com>
=> Add links to the manual, future-proof others

jscomp/Makefile, jscomp/super_errors/README.md, jscomp/super_errors/super_location.ml, jscomp/super_errors/super_misc.ml, jscomp/super_errors/super_misc.mli, jscomp/super_errors/super_typecore.ml, jscomp/super_errors/super_typetexp.ml, jscomp/super_errors/super_warnings.ml
Depends on #1919
Now that we're using a compiler patch for coloring, we can kill the old custom color logic I needed Took the occasion to clean up some comment and a deprecation warning
=> [Super errors] Revert the colors hack

vendor/ocaml/parsing/location.mli
See https://github.com/BuckleScript/bucklescript/pull/1916#discussion_r134701551
=> [Super errors] Expose hook for error msgs formatting

jscomp/super_errors/super_location.ml, jscomp/super_errors/super_typecore.ml, jscomp/super_errors/super_typetexp.ml
Final part of #1919
Before:
After:
=> [Super errors] display type unification more clearly

jscomp/super_errors/super_typecore.ml, jscomp/super_errors/super_typetexp.ml
=> [Super errors] Use better unification printing

site/docsource/js-lib.adoc
See the following sections for examples:
- https://bucklescript.github.io/bucklescript/Manual.html#_stable_ish_submodules
- https://bucklescript.github.io/bucklescript/Manual.html#_experimental_incomplete_submodules
- https://bucklescript.github.io/bucklescript/Manual.html#_very_experimental_internal_submodules
- https://bucklescript.github.io/bucklescript/Manual.html#_node_module
These links are located within `site/docsource/js-lib.adoc`, which I've updated to be relative to the current folder.
Have tested locally by running `site/docsource/build.sh` and browsing `docs/Manual.html`.
=> Broken links in JS Modules documentation

jscomp/core/js_dump_program.ml
I chose to say "optimized away" because removed might be confusing and
leads folks to think they didn't wire things up correctly.
=> Small message tweak for empty output files

jscomp/super_errors/super_location.ml, jscomp/super_errors/super_misc.ml
And they're correctly normalized!
Formats:
```
path/to/file.re
path/to/file.re 10:20
path/to/file.re 10:20-30
path/to/file.re 10:20-15:5
```
Replaces #2023
=> [Super errors] display line and column

jscomp/super_errors/super_typetexp.ml
The message splits the value and the module wrapper. This way it doesn't say "Unbound value Foo.Bar.baz" and the newcomer doesn't get confused which part is unbound.
=> [Super errors] Better unbound value msg

jscomp/runtime/js_typed_array.ml, jscomp/test/js_typed_array_test.js, jscomp/test/js_typed_array_test.ml
I can't test it, but it is simply a copy of the slice function with the name changed.
Technically both parameters are optional and one could add a `subarrayFrom`
Fixes #2020
=> Add subarray

jscomp/bin/bsb.ml, jscomp/bin/whole_compiler.ml, jscomp/bsb/bsb_ninja_file_groups.ml, jscomp/core/js_main.ml, jscomp/core/ocaml_parse.ml, jscomp/core/ocaml_parse.mli, jscomp/reason_outcome_printer/tweaked_reason_oprint.ml
```
jscomp/bin/bsc.exe  jscomp/others/js_list.cmi
```
```
type 'a t = 'a list
val length : 'a t -> int
val cons : 'a -> 'a t -> 'a t
val isEmpty : 'a t -> bool
val hd : 'a t -> 'a option
val tl : 'a t -> 'a t option
val nth : 'a t -> int -> 'a option
val revAppend : 'a t -> 'a t -> 'a t
val rev : 'a t -> 'a t
val mapRev : ('a -> 'b [@bs]) -> 'a t -> 'b t
val map : ('a -> 'b [@bs]) -> 'a t -> 'b t
val iter : ('a -> unit [@bs]) -> 'a t -> unit
val iteri : (int -> 'a -> unit [@bs]) -> 'a t -> unit
val foldLeft : ('a -> 'b -> 'a [@bs]) -> 'a -> 'b list -> 'a
val foldRight : ('a -> 'b -> 'b [@bs]) -> 'a list -> 'b -> 'b
val flatten : 'a t t -> 'a t
val filter : ('a -> bool [@bs]) -> 'a t -> 'a t
val filterMap : ('a -> 'b option [@bs]) -> 'a t -> 'b t
val countBy : ('a -> bool [@bs]) -> 'a list …
```
=> dump mli/rei from cmi , fix Js.Internal leaking in error message

scripts/install.js
This is a possible solution for #2086.
I only catch this one command, but maybe the other commands can fail as well, but I don't know what possible reasons are for failure of these other commands.
=> catch the error of the buildocaml script and print it for more information

bin/bsb
fix #2093 
besides colorful output, we also fixed a bug to detect staled .bsb.lock
once the `bsb -w` is killed, but `.bsb.lock` is not cleaned properly, we got a staled lockfile.
This is fixed by testing the existence of such pid, but the question remains: why VSCode terminate process does not allow bsb to quit gracefully?
TODO: how can we make `ninja:error` output captured by VSCODE
=> colorize ninja error output

jscomp/syntax/ast_external_attributes.ml
We need two escaped `@` here. Otherwise it shows up as `[@bs.splice]`.
Also fixes a typo.
=> Fix bs.splice error message

jscomp/bin/bsb.ml, jscomp/bsb/bsb_bsdeps.mli, jscomp/bsb/bsb_main.ml, jscomp/common/js_config.mli, jscomp/others/bs.ml, jscomp/others/js_dict.mli, jscomp/others/js_promise.ml, jscomp/others/node.ml, jscomp/runtime/js.mli
This fixes some misspellings and grammar issues noticed while browsing the documentation and looking at the help text for the `bsb` executable.
=> Editing for doc comments and some help text

jscomp/bin/bsb.ml, jscomp/bsb/bsb_merlin_gen.ml, jscomp/bsb/bsb_warning.ml, jscomp/bsb/bsb_warning.mli, jscomp/build_tests/namespace/input.js
make warning number additive to default instead of reset (cc @bsansouci )
Note you can already reset by setting 'a', so additive makes more sense
```
"warnings" : 
{ "number" : "a+3-2" }
```
=> make wanring number additive to default instead of reset

Changes.md
- Fixes all the typos
- Consistent issue listing
- Formatting
This is carried over from the changes section in the docs, which was
getting stale. I'm unifying these in the same place.
=> [Docs] Add old entries to changes

jscomp/core/js_cmj_datasets.mli, jscomp/core/js_cmj_load.ml, jscomp/core/jsoo_main.ml, jscomp/jscmj_main.ml
Add `load_module` to `ocaml` object:
ocaml.load_module cmi_path cmi_content cmj_name cmj_content
where `cmi_path` is the `.cmi` path in the (JSOO) pseudo file-system, `cmi_content` is the binary serialization of the `.cmi` file, `cmj_name` is the `.cmj` filename, and `cmj_content` is the binary serialization of the `.cmj` file. File contents should be serialized like [this](https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/lib/js_output.ml#L279).
Example:
ocaml.load_module("/cmis/reactDOMRe.cmi", "Caml1999I017\x84\x95..., "reactDOMRe.cmj", "BUCKLE20170907\x84\x95...);
Signed-off-by: Alessandro Strada <alessandro.strada@gmail.com>
=> Allow loading compiled modules via JS API

jscomp/runtime/caml_obj.ml
This follows the ocaml implementation.
See https://github.com/BuckleScript/bucklescript/issues/2142
=> Special case polymorphic compare for physically equal value.

site/docsource/OCaml-call-JS.adoc
Looks like it's used now, based on details in `Unicode support with string interpolation` section.
=> Remove phrase "j is unused so far"

jscomp/super_errors/super_typecore.ml
Hi, thanks for the work all of you have put into this project 🙂
I saw that the error messages pointed to the wrong documentation url for reason-react children and tracked them here. I don't know if this solves it as I have little knowledge of how all of this fits together, but hope it helps.
=> Update links to reason-react children docs

jscomp/bsb/templates/basic-reason/bsconfig.json, jscomp/bsb/templates/basic-reason/src/demo.re, jscomp/bsb/templates/react/bsconfig.json, jscomp/bsb/templates/react/src/index.re, jscomp/bsb/templates/react/src/page.re
Projects generated with `bsb -init my-first-app -theme basic-reason` aren't generating compilable code right now.  This fixes it for `basic-reason` and `react`.
There will probably be failing tests since I was unable to get the project to actually build or run unit tests in my Linux VM.  I will address them if a CI can report the specific failures on this PR.
=> Reason templates should use new syntax.

jscomp/others/js_json.mli
Just tested by pasting into Try Reason.
=> Correct examples of Js.Json.parseExn usage

jscomp/bsb/bsb_config_parse.ml
Needs a new line, otherwise it looks like this:
```
Warn: refmt version missed, it is recommended to set it explicitly since we may change the default in the futureFile "bsconfig.json", line 3:
Error: JSX version 3...
```
Thanks for putting the warning too.
=> Fix refmt version message warning

bin/bsb
That thing where instead of outputting a build command and its results onto hundreds of lines, ninja overrides the existing line in the terminal. Not sure why this still worked on mac without problem.
=> Make watcher mode in linux accept ninja progress animation

jscomp/Makefile, jscomp/README.md, jscomp/core/jsoo_main.ml, jscomp/repl.js
* Fix Makefile
* Update jsoo_main to use js_of_ocaml 3.0 new api
Signed-off-by: Alessandro Strada <alessandro.strada@gmail.com>
=> Use js_of_ocaml 3.0 to compile BuckleScript

scripts/install.js
Tiny contribution to fix a typo in an error message.
Introduced in https://github.com/BuckleScript/bucklescript/pull/2089.
=> scripts/install.js: Fix typo in missing compiler error message

jscomp/build_tests/super_errors/index.js, jscomp/super_errors/README.md, jscomp/super_errors/super_location.ml, jscomp/super_errors/super_main.ml, jscomp/super_errors/super_typecore.ml, jscomp/super_errors/super_typetexp.ml
This reverts the color logic part of e114d2c786b7c22626a6a1f28732b6c529d1df91.
I've forgotten why the colors logic were changed.
The related tests (which aren't triggered yet still) aren't fixed yet;
will do it in a separate diff.
=> [Super errors] Fix terminal output colors & update docs

lib/bsb
This really fixes #2226. It seems my first fix didn't really work (I've must have missed something with my first tests because I thought it did...)
Researched a bit more and tested better and this fix works (does the same as webpack-dev-server: https://github.com/webpack/webpack-dev-server/blob/0a8f8965fba4a46a862497f6e7d1ad9377040a15/bin/webpack-dev-server.js#L262). 
@jackalcooper maybe you can test this as well, because you have the same issue. If you just replace my fixed file into a project where you have the problem in the folder `node_modules/.bin` then it should work.
=> now really close when stdin stops

jscomp/bsb/templates/react/bsconfig.json
Not sure if we should turn it on by default everywhere. At least in
ReasonReact this is frequent enough to warrant this.
=> Turn partial application warning into error for bsb react template

jscomp/super_errors/super_warnings.ml
https://mobile.twitter.com/splodingsocks/status/939001746445123585 looks great but the code is in reason 3 and the error message shows reason 2 syntax.
=> Reason 3 syntax in this error

jscomp/syntax/external_ffi_types.ml
Though I'm not sure how to trigger this warning anymore. Would be good
to have a repro
=> Better errors for when there's a compiler version mismatch

jscomp/core/js_dump_import_export.ml
It causes a lot of spurious changed lines in diffs.
=> Stop tab-aligning imports and exports

jscomp/bsb/templates/react/bsconfig.json
This pull-request changes is just a small style change on `bsconfig.json` for the React theme. Every attribute was using `:·` and the `react-jsx` attribute had an extra space before, being `·:·`.
=> Fix trailing space on react-jsx

jscomp/others/js_string.ml
The order of the function arguments is potentially confusing, so
document it.
=> Js.String.replace: add doc comment

README.md
Bloomberg's url isn't working without `www.`
=> fix: Bloomberg url

jscomp/bsb/templates/react/webpack.config.js
Currently if you import a file that uses code splitting with [Dynamic Imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports) (e.g. `import("./path/to/file")`):
**dynamicImports.js**
```js
module.exports = import("./file1");
```
**Index.re**
```reason
[@bs.module] external dynamicComponents : Js.Promise.t(ReasonReact.reactClass) : "./dynamicImports"
```
it will look for it in the `src` directory (`src/0.index.js`) which causes it to fail when loading the chunk. Adding `publicPath` to the webpack config will let it resolve the file properly to `build/0.index.js`.
=> Add publicPath to webpack config

scripts/config.js
As pointed out in #2340 the else clause in `config.js` prevents building on FreeBSD. With the changes in this PR the build proceeds (even though there are no prebuilt components) and successfully completes.
=> Prevent config.js throwing error on FreeBSD

jscomp/super_errors/super_typecore.ml
The following repro:
```
/lib/bsc.exe -bs-super-errors -bs-eval 'let add = ((fun x  -> fun y  -> x + y)[@bs ]) let x = ((add 3)[@bs ])'
```
Now gives:
```
Found uncurried application [@bs] with arity 2, where arity 1 was expected.
This has type:
(int -> int -> int [@bs]) (defined as (int -> int -> int [@bs]))
But somewhere wanted:
('a -> 'b [@bs]) (defined as ('a -> 'b [@bs]))
These two variant types have no intersection
```
=> [SuperErrors] Check arity mismatch for uncurried [@bs] application.

jscomp/README.md
I still don't understand what `(cd vendor/ocaml && make world)` is about. I've already run `make.world.opt` and `make install` from going through the "Setup" section. And why is this and the `node repl.js`, the command that actually does most of the work, in parentheses? The only thing that comes to mind is that it means they're optional, but that makes absolutely zero sense.
I also think the move to js_of_ocaml 3.0 broke webpack compatibility. There's now a bunch of "Critical dependency: the request of a dependency is an expression" warnings from webpack, and it fails in the browser with the error `Error: Cannot find module "."`. Still trying to figure this one out.
cc @astrada 
Edit: Forgot to mention, `BS_RELEASE_BUILD=true` is required to generate amdjs modules. Should maybe explain …
=> fix build instructions

jscomp/others/js_global.ml, scripts/doc_gen.js
cc @glennsl 
if you have `opam switch buckle-master`, make docs in directory `jscomp` will generate the API docs. Note ocamldoc is quite tricky, I did some tweaks to make the html look better
=> tweak docs

jscomp/runtime/js_null.ml, jscomp/runtime/js_null.mli, jscomp/test/js_null.js, jscomp/test/js_null_test.js, jscomp/test/js_null_test.ml
=> Undo removal of Js.Null.to_opt

jscomp/README.md
These commands seems to have worked for me when making my changes.
=> Update jscomp/README.md with correct make commands

jscomp/core/js_dump_program.ml
ES6 modules are always strict so `'use strict';` unnecessary when using that as output. I'm not sure if this is a real problem as it will probably be removed by uglify or similar but that depends on if it is smart enough I guess.
http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code
> Module code is always strict mode code.
I'm kind of new to this (coming here via ReasonML) so any pointers on how to do this better are appreciated.
=> Only use 'use strict'; in amdjs and commonjs

jscomp/super_errors/super_typetexp.ml
=> [Super errors] Improve constructor and record messages

jscomp/super_errors/super_typetexp.ml
Fixes https://github.com/reasonml-community/error-message-improvement/issues/49
=> [Super errors] Better msg for Str

jscomp/others/belt_HashSet.ml, jscomp/others/belt_MutableSet.ml, jscomp/others/belt_MutableSet.mli, jscomp/others/belt_MutableSetInt.ml, jscomp/others/belt_MutableSetInt.mli, jscomp/others/belt_MutableSetString.ml, jscomp/others/belt_MutableSetString.mli, jscomp/others/belt_Set.ml, jscomp/others/belt_Set.mli, jscomp/others/belt_SetDict.mli, jscomp/others/belt_SetInt.ml, jscomp/others/belt_SetInt.mli, jscomp/others/belt_SetString.ml, jscomp/others/belt_SetString.mli, jscomp/others/belt_internalAVLset.ml, jscomp/others/belt_internalAVLset.mli, jscomp/others/belt_internalSetInt.ml, jscomp/others/belt_internalSetString.ml, jscomp/others/internal_set.cppo.ml, jscomp/others/set.cppo.ml, jscomp/others/set.cppo.mli, jscomp/others/setm.cppo.ml, jscomp/others/setm.cppo.mli
Second diff of #2536, pulled out.
> For set, understandably it's the "key" that's hashed and compared, but everyone I've talked to think of a set item in terms of "value" instead.
=> Change set terminology of elt to value

jscomp/super_errors/super_typecore.ml
Fixes https://github.com/reasonml-community/error-message-improvement/issues/45
=> [Super errors] Tweak missing argument msg

jscomp/super_errors/super_typecore.ml
See for example https://github.com/BuckleScript/bucklescript/pull/2548#issuecomment-368851245
So `option('a)` is the same as `option('b)`, `array(string)` is the same
as `array(string)`, but `list('a)` isn't the same as `list(string)`.
Along with #2548, this fixes
https://github.com/reasonml-community/error-message-improvement/issues/10
I believe
=> [Super errors] Tweak collect_missing_arguments equality check

jscomp/super_errors/super_typecore.ml, jscomp/super_errors/super_typemod.ml
Fixes https://github.com/reasonml-community/error-message-improvement/issues/51
=> [Super errors] Tweak the wording and formatting of some msgs

jscomp/super_errors/super_typecore.ml
Continuation of #2548
Mini usability testing result out. Apparently the previous message was too confusing, so I'm adding back the fallback type clash msg.
Additionally, I'm now using `Ctype.matches`, which considers `option('a)` and `option(string)` as equal. This, along with the original code in #2548, fixes https://github.com/reasonml-community/error-message-improvement/issues/14
But since this produces false positives "missing parameters" msg for such code below:
```reason
let a: int => float => option(int) = (a) => Some("");
```
Where `option(int)` matches `option('a)` inferred from `Some("")`, I've also tweaked the msg to indicate that we're _guessing_ that it _might_ be because of missing parameters (but that we're not sure). The fallback type clash msg gives us leeway to guess.
cc …
=> [Super errors] Better missing param msg

jscomp/others/belt_Id.ml, jscomp/others/belt_Id.mli
It's a single arg, so reduces the burden of using that pattern a little.
I'll update the docs after this
=> [Belt] Make comparable label-less

jscomp/others/belt_Map.mli, jscomp/others/belt_MapInt.mli, jscomp/others/belt_MapString.mli, jscomp/others/map.cppo.mli
Makes things a bit more consistent. @bobzhang so the set API uses
`('value, 'id) t` but map here mostly uses `('k, 'v, 'id) t` to stay
more concise, since `('key, 'value, 'id) t` in every signature might be
a bit verbose. Or is it? If it's not, I'd gladly do `('key, 'v, 'id) t`
or `('key, 'value, 'id) t`.
=> [Belt] Use 'v instead of 'a for interface signature

jscomp/bsb/templates/react/README.md, jscomp/bsb/templates/react/bsconfig.json, jscomp/bsb/templates/react/package.json, jscomp/bsb/templates/react/webpack.config.js
=> Added production ready settings for react theme

jscomp/runtime/js_undefined.mli
=> Fix typo in `Js.Undefined.to_opt` deprecation message.

jscomp/others/belt_Id.ml, jscomp/others/belt_Id.mli, lib/js/belt_Id.js
This allows the creation of custom Set/Map through these functor directly rather than passing by a first-class module. Slightly more verbose, but much easier for newcomers.
If the diff makes sense, I'll expose MakeHashable too.
=> Expose Id.MakeComparable/ComparableU/Hashable/HashableU

jscomp/others/belt_Id.ml, jscomp/others/belt_Id.mli, jscomp/test/bs_hashtbl_string_test.ml, jscomp/test/bs_map_set_dict_test.ml, jscomp/test/bs_poly_map_test.ml, jscomp/test/bs_poly_mutable_map_test.ml, jscomp/test/bs_poly_mutable_set_test.ml, jscomp/test/bs_poly_set_test.ml
See #2565 which removed it. #2589 deprecates comparable, so we can just
put the label back to avoid unnecessary churn the next release
https://github.com/BuckleScript/bucklescript/pull/2602/files?w=1
=> [Belt] Put comparable ~cmp label back

jscomp/super_errors/super_reason_react.ml, jscomp/super_errors/super_reason_react.mli, jscomp/super_errors/super_typecore.ml
The "state escape scope" one.
This one shouldn't catch any false positives, so we can safely remove
the original type clash error.
Also, we only detected state escaping scope, not that it's actually
related to ReasonReact.componentSpec. So every state escape scope error
ended up giving a ReasonReact error correction tip. This is fixed now.
Sorry about that.
=> [Super errors] Make the second worst ReasonReact error a bit shorter

docs/api/Belt.html
Hi there! I found a few small typos in the documentation for the Belt module overview. I read through the contribution guidelines, but if I missed anything, I'd be glad to know.
=> Fix typos in Belt Module overview

jscomp/others/belt.ml
=> [Docs] Fix typos

jscomp/bsb/templates/react/README.md, jscomp/bsb/templates/react/bsconfig.json
See https://github.com/BuckleScript/bucklescript/pull/2587#discussion_r173338421
=> [Bsb] Revert the React template from es6 to commonjs

jscomp/others/belt.ml, jscomp/others/belt_Map.mli, jscomp/others/belt_MutableMap.mli, jscomp/others/belt_MutableSet.mli, jscomp/others/belt_Set.mli
https://github.com/BuckleScript/bucklescript/pull/2618/files?w=1
This is a first round of cleanup. It fixes typos, removes redundant (and
sometimes wrong) examples and rewords a few things. This reduces the
verbosity of pages like Set and Map, where lots of helpers repeated the
creation of e.g. IntCmp, which becomes verbose after a few times.
Later I'll be properly sectionning each page too, just like how stdlib
docs have section in List for e.g. "list scanning", "iterators", etc.
=> [Docs][Belt] Cleanup; remove references to comparableU

jscomp/syntax/ast_exp_apply.ml, jscomp/test/.depend, jscomp/test/Makefile, jscomp/test/bs_list_test.js, jscomp/test/bs_list_test.ml, jscomp/test/pipe_syntax.js, jscomp/test/pipe_syntax.ml, lib/bsdep.ml, lib/bsppx.ml
Note we only implement part of the proposal(#2342) in this PR:
```ocaml
x |. f --> f x 
x |. f a0 a1 --> f x a0 a1 
x |. f ~h:a0 a1 -> f x ~h:a0 a1 
```
Currently, the [@bs] will result in an unused attribute in such cases:
```ocaml
x |. f [@bs]
x |. f a0 a1 [@bs]
```
To keep things simple, we simply warn when in  `x |. f  [@attrs]`, attirs is not empty, otherwise 
- if we carry such attrs while not process it, (a warning produced but not idempotent)
- process again --> complicated not obvious benefit?
=> tentative pipe syntax #2342

jscomp/super_errors/super_typecore.ml, jscomp/super_errors/super_warnings.ml
See the updated error/warning msgs
=> [Super errors] Specialize error msgs for Reason syntax when needed

jscomp/others/Makefile, jscomp/others/belt.ml, jscomp/others/belt_Option.ml, jscomp/others/belt_Option.mli, lib/js/belt.js, lib/js/belt_Option.js
This adds the following utility functions for the option data type to belt.
```ocaml
val getExn : 'a option -> 'a
val mapWithDefaultU : 'a option -> 'b -> ('a -> 'b [@bs]) -> 'b
val mapWithDefault : 'a option -> 'b -> ('a -> 'b) -> 'b
val mapU : 'a option -> ('a -> 'b [@bs]) -> 'b option
val map : 'a option -> ('a -> 'b) -> 'b option
val flatMapU : 'a option -> ('a -> 'b option [@bs]) -> 'b option
val flatMap : 'a option -> ('a -> 'b option) -> 'b option
val getWithDefault : 'a option -> 'a -> 'a
val isSome : 'a option -> bool
val isNone : 'a option -> bool
val eqU : 'a option -> 'b option -> ('a -> 'b -> bool [@bs]) -> bool
val eq : 'a option -> 'b option -> ('a -> 'b -> bool) -> bool
val cmpU : 'a option -> 'b option -> ('a -> 'b -> int [@bs]) -> int
val cmp : 'a option -> 'b option -> …
```
=> Add option module to Belt

jscomp/others/.depend, jscomp/outcome_printer/outcome_printer_ns.ml, jscomp/repl.js
Adding `Belt_Option` to some files as calling `make` in `master` was failing locally.
There are a few more files besides these that are missing `Belt_Option`, but I'm unsure as they seem auto generated:
- `scripts/win_build.bat`
- `jscomp/core/js_cmi_datasets.ml`
- `jscomp/core/js_cmj_datasets.ml`
=> Adding belt_Option to some files

jscomp/outcome_printer/reason_syntax_util.ml, jscomp/outcome_printer/reason_syntax_util.mli
Addresses https://github.com/BuckleScript/bucklescript/pull/2636#issuecomment-373896302
=> [Reason] Check in interface file for outcome printer f1d22a691a74a6dfd939b1e1e00c46d9ec89d082

jscomp/Makefile, jscomp/all.depend, jscomp/syntax/ast_attributes.ml, jscomp/syntax/ast_derive_abstract.ml, jscomp/syntax/external_ffi_types.ml, jscomp/syntax/external_ffi_types.mli, jscomp/syntax/external_process.ml, jscomp/test/gpr_2614_test.js, jscomp/test/gpr_2614_test.ml, lib/bsdep.ml, lib/bsppx.ml
fix #2583,
part One of #2614
```
type t = {
mutable hi : int
[@bs.as "Content-Type"];
mutable low : int
[@bs.as "l"];
mutable x : int;
[@bs.as "open"]
} [@@bs.deriving abstract]
let v = t ~hi:3 ~low:2 ~x:2
let (a,b,c) = (v |. hi, v |. low, v |. x)
let ff () =
v |. hiSet 3;
v |. lowSet 2
```
generated code:
```js
var v = {
"Content-Type": 3,
l: 2,
open: 2
};
var a = v["Content-Type"];
var b = v.l;
var c = v.open;
function ff() {
v["Content-Type"] = 3;
v.l = 2;
return /* () */0;
}
```
=> allow customize label name

CONTRIBUTING.md
Changes the `make -C` command to use the full relative path from the project root to the test directory.
=> [contributing] fix `make -C` command for tests

jscomp/repl.js
cc @astrada @bobzhang
I get the following error at runtime if I don't: `"caml_weak_create not implemented"` (wrapped in some jsoo exception data structure)
=> [Repl] Add +weak.js back into exports.js

jscomp/others/.depend, jscomp/others/belt_List.ml, jscomp/others/belt_List.mli, jscomp/test/bs_list_test.js, jscomp/test/bs_list_test.ml, lib/js/belt_List.js
Implements Belt.List.sort as specified in the issue.
Adds a couple of simple tests and an example.
Fixes #2586.
=> [Belt] Add List.sort

lib/bsb
This fixes the regression in #2651 by only enabling ending when stdin is closed on non win32 platforms.
=> exit on stdin on non win32 platforms

jscomp/runtime/caml_obj.ml, jscomp/test/caml_compare_test.js, jscomp/test/caml_compare_test.ml, jscomp/test/record_with_test.ml, lib/js/caml_obj.js
Extend polymorphic compare to support objects created as e.g. `[%bs.obj {x=1; y=2}]`.
The comparison of `{x:1, y:2}` and `{x:3, y:4}` is defined logically as if the objects were lists of pairs: the first keys are compared, then the first values, then the second keys, then the second values, etc.
In particular, the order of keys matters, and `{x:1, y:2}` is different from `{y:2, x:1}`.
TODO: equality and hash.
Objects, when viewed as blocks, have size 0 and no tag.
Here an object `o` is recognized by checking that `o.constructor === Object`.
Then, the keys and values can be extracted.
The compare function keeps the same structure, with one extra while loop, and does not change unless objects are encountered. Presumably `Object.keys(o)` performs some allocation.
=> Extend polymorphic compare to support objects.

jscomp/core/js_exp_make.ml, jscomp/core/lam_dispatch_primitive.ml, jscomp/test/js_bool_test.js, jscomp/test/js_bool_test.ml
cc @cristianoc fix bool comparison, added tests
=> fix bool comparison

jscomp/common/bs_warnings.ml, jscomp/common/bs_warnings.mli, jscomp/syntax/external_process.ml
The warning "You are passing a OCaml bool type into JS, probably you want to pass Js.boolean" can be deleted now that Js.boolean is the same as bool.
=> Delete warning “You are passing a OCaml bool type into JS”.

jscomp/core/lam.ml, jscomp/core/lam.mli, jscomp/core/lam_analysis.ml, jscomp/core/lam_compile_primitive.ml, jscomp/core/lam_pass_eliminate_ref.ml, jscomp/core/lam_print.ml, jscomp/test/bigarray_test.js, jscomp/test/complex_test.js, jscomp/test/flow_parser_reg_test.js, jscomp/test/mario_game.js, jscomp/test/ocaml_proto_test.js, jscomp/test/ocaml_re_test.js, jscomp/test/ocaml_typedtree_test.js, jscomp/test/record_with_test.js, jscomp/test/test_primitive.js, jscomp/test/test_runtime_encoding.js, jscomp/test/tfloat_record_test.js, jscomp/test/update_record_test.js, lib/js/complex.js, vendor/ocaml/bytecomp/translcore.ml
This diff would make sure us to own the path of trans_record so that it doesn't not turn a record into float array etc, so that debug mode would be robust
(see this diff https://github.com/BuckleScript/bucklescript/pull/2709/commits/d2124fbc28a94c9eb9130202915659e67f496573 cc @cristianoc )
=> take ownership of transl_record (for debug mode)

jscomp/Makefile, jscomp/core/jsoo_main.ml
RFC. Feedback welcome. cc @bobzhang
Huge quality improvement for the online experience. This activates
color (needed, otherwise it's a wall of white text). I use a small lib
to parse the raw ANSI color escape chars into html styles. It'd not look
good in the BS playground currently.
This doesn't activate Reason syntax for outcome printer, since it's
compiling ocaml.
=> [Playground] activate super-errors

jscomp/bsb/bsb_theme_init.ml
https://github.com/BuckleScript/bucklescript/pull/2715/files?w=1
=> [Bsb] Fix error msg grammar & color

jscomp/super_errors/super_location.ml
See updated comment.
Test plan: this path is never reached for normal files. Try this in e.g. the playground where file is actually "". See no more double location reporting.
=> [Super errors] No need for fallback location printing

jscomp/others/js_string.ml
Comments and examples are in the same style as used in `Belt_Array.ml` (and others).
You may want to get rid of the editorial comment in line 157.
=> Add documentation to js_string.ml 2.2.3

jscomp/Makefile, jscomp/bin/js_compiler.d, jscomp/bin/reactjs_jsx_ppx_v2.bspp.ml, jscomp/bsb/bsb_warning.ml, jscomp/bsb/bsb_warning.mli, jscomp/core/jsoo_main.ml
- Make warnings use super-errors too
- Add default warnings set from bsb (cc @astrada, no more ReasonReact warning 40 that you have to grep out anymore!)
- Report errors into stderr (aka console.error)
=> [Playground][JSX PPX] Tweaks to warnings & errors

jscomp/others/belt_Array.mli, jscomp/others/js_string.ml
Was not able to come up with good examples for `makeUninitialized` as I do not entirely understand the type system.
=> [Docs] Add examples for Belt.Array

jscomp/others/node_buffer.ml
This [@bs.scope] was an accidental copy paste when originally submitted. The resulting output was `Buffer.fromString(...).Buffer.toString()`
=> Fix Buffer.toString function

jscomp/others/belt_MapDict.mli, jscomp/others/belt_MapInt.ml, jscomp/others/belt_MapInt.mli, jscomp/others/belt_MapString.ml, jscomp/others/belt_MapString.mli, jscomp/others/belt_MutableMap.ml, jscomp/others/belt_SetDict.mli, jscomp/others/belt_SetInt.mli, jscomp/others/belt_SetString.mli, jscomp/others/map.cppo.ml, jscomp/others/map.cppo.mli, jscomp/others/set.cppo.mli, lib/js/belt_MapInt.js, lib/js/belt_MapString.js, lib/js/belt_MutableMap.js
More consistency in the generated .mli for specialized Set and String, and the corresponding Dict, for maps and sets.
Renamed leftover mergeArray which should be mergeMany.
=> [Belt] More consistency in mli for Maps and Sets.

lib/bsb
'since just got started' or 'since just starting'
Signed off by: Jim Tittsler <jimt@onjapan.net>
=> Fix startup message typo.

jscomp/others/belt_List.mli, jscomp/others/belt_MapDict.mli, jscomp/others/belt_MapInt.mli, jscomp/others/belt_MapString.mli, jscomp/others/belt_MutableMapInt.mli, jscomp/others/belt_MutableMapString.mli, jscomp/others/map.cppo.mli, jscomp/others/mapm.cppo.mli
Minor fixes to ocamldocs:
- `Belt.List.add` adds to the beginning of the list
- Some maps docs were referencing `add` instead of `set`
=> Small documentation fixes

jscomp/runtime/caml_obj.ml, jscomp/test/caml_compare_test.js, jscomp/test/caml_compare_test.ml, lib/js/caml_obj.js
Polymorphic compare could crash when the second argument is null, as it would try to read the tag of null.
Added test where previously it would crash.
=> Fix polymorphic compare on nullables.

jscomp/others/js_console.ml
There are already Js.log, log2, log3, log4 and logMany.
However, the Js.Console namespace was missing similar bindings for log/info/warn/error. I added those.
=> Improved Js.Console.log/info/warn/error bindings with different numbers of parameters

scripts/build_util.js
Add callback parameter for fs.rename() to build after Node.js v10.0.0.
=> Fix fs.rename after Node.js v10.0.0

jscomp/others/belt_Array.ml, jscomp/others/belt_Array.mli, jscomp/test/bs_array_test.js, jscomp/test/bs_array_test.ml, lib/js/belt_Array.js
This intends to fix #2753.
I've tried do to an implementation of `Array.partition` using the same style as the existing file (with unsafe set/get and refs). I tried multiple solutions for implementing `partition`, trying to make it efficient in space and time (insert tardis joke), but I didn't see a way of reducing it.
I've seen some other implementations as well, and they all do it in like 3-4 loops. So as far as I can think, this is as good as it gets? If anyone has any ideas, please let me know and I'll try to fix them.
Also please let me know if there is anything I can change with this PR.
=> Add Belt_Array.partition

jscomp/others/belt_Array.mli
There's a minor typo in the description of Array.partition. This PR correct `vause` to `cause`. Maybe the sentence should be rewritten, or is it descriptive enough?
=> Fix minor typo in Array.partition docs

jscomp/install-bsb.sh, jscomp/install-bsc.sh
Global node_modules aren't always in the same place.  By using `npm prefix -g`, you can find out exactly where they are.
=> Use `npm prefix -g` command to figure out where node_modules exist

Makefile, jscomp/bsb/bsb_config_parse.ml, jscomp/bsb/bsb_pkg.ml, jscomp/bsb/bsb_theme_init.ml, lib/bsb.ml
```
Your running bsb (/Users/hongbozhang/git/ocamlscript/lib) instance has a different version from our 
resolved bs-platform(/Users/hongbozhang/git/xx/node_modules/bs-platform): 1.4.1 vs 3.2.0
```
=> prepare consistency check for running bsb and its underlying bs-platform

jscomp/bsb/bsb_templates.ml, jscomp/bsb/templates/react-lite/bsconfig.json, jscomp/core/js_exp_make.ml
Note the optimization like this
```
x <> None
```
it needs to be undone or depends
but the name `intcomp` is really misleading
Note the case  `intcomp` in combination of nullary constructor is (marked with simplify_constant_constructor)
```
%notequal
%equal
%bs_equal_nullable
%bs_equal_undefined
%bs_equal_null
```
For those primitives above, once one operand is immediate, we can do an address comparison
=> [part one] unbox option

jscomp/core/lam.ml, jscomp/test/.depend, jscomp/test/Makefile, jscomp/test/option_repr_test.js, jscomp/test/option_repr_test.ml, vendor/ocaml/bytecomp/lambda.ml, vendor/ocaml/bytecomp/lambda.mli, vendor/ocaml/bytecomp/matching.ml, vendor/ocaml/bytecomp/translcore.ml, vendor/ocaml/typing/datarepr.ml, vendor/ocaml/typing/datarepr.mli, vendor/ocaml/typing/predef.ml, vendor/ocaml/typing/predef.mli
Note we need handle cases like
```ocaml
match Js.Undefined.toOption x with 
| Some "xx" -> 0 
| Some _  -> 1
| None -> 0
```
In this case, string option destructuring is a no-op, but it can not be cancelled with boxing which means regression.
- we keep Psome_unnest only erase it later
- we promote `#undefined_to_opt` to `#undefined_to_unnest_opt` (may apply to null, nullable too)
TODO:
The if_then_else should be adapted:
```js
var s = $star$opt ? $startop : false
```
The code above is no longer correct
it should be adapted to code as below:
```js
var s = $star$opt === undefined? $startop : false
```
or
```js
var s = typeof $star$opt === "undefined" ? $star$opt : false 
```
=> keep type information for specialization

jscomp/core/js_packages_info.ml
It's possible to get commonjs:C:\msys32\... and then this dies. This adds support for having colons after the initial one.
=> Fix bug in windows where path has colon in command line arg

jscomp/others/js_null_undefined.ml, jscomp/others/js_null_undefined.mli, jscomp/runtime/js.ml, jscomp/runtime/js.mli
The former might accidentally be understood as "isn't null".
=> Rename Js.Nullable.test to Js.Nullable.isNullable

jscomp/runtime/caml_obj.ml, jscomp/runtime/js_primitive.ml, jscomp/test/caml_compare_test.js, jscomp/test/caml_compare_test.ml, jscomp/test/option_repr_test.js, jscomp/test/option_repr_test.ml, lib/js/caml_obj.js, lib/js/js_primitive.js
by introducing a tag 256 to makes it easier to fix polymoprhic comparison semantics
conclusion: `None, Some None, Some (Some (None)) ...` such group is strictly smaller than value outside of this group. In that case we need check comparison between `Some None` and `(Some null)`
todo: caml_equal
=> fix polymoprhic comparison semantics

jscomp/bsb/templates/react-lite/index.html
This to make sure it works on a case-sensitive filesystem (aka linux)
=> Fix react-lite template script path

jscomp/bsb/bsb_build_util.ml, jscomp/bsb/bsb_build_util.mli, jscomp/bsb/bsb_merlin_gen.ml, jscomp/bsb/bsb_ninja_gen.ml, lib/bsb.ml
This fixes #1704 by running `Filename.quote` on each entry in the `ppx-flags` array.
Since the fix is applied to `Bsb_build_util.flag_concat`, it should also fix potential issues with include paths containing spaces. I couldn't find any existing tests or any hints as to how this could be tested, so I would appreciate some ideas or pointers.
It's unfortunately a breaking change since people who today have entered e.g. `ppx-flags: ["graphql_ppx/ppx\\ -ast-out"]` will get doubly escaped backslashes.
=> Quote each entry in ppx-flags in bsconfig.json

jscomp/bsb/bsb_config_parse.ml, jscomp/bsb/bsb_default.ml, jscomp/bsb/bsb_log.ml, jscomp/bsb/bsb_log.mli, jscomp/bsb/bsb_main.ml, jscomp/core/js_main.ml, jscomp/test/bigarray_test.js, lib/bsb, lib/bsb.ml
Note the fix is not ideal.
In a clean slate, to get colorless output,
people need run `bsb -clean-world` first to remove those colors, and `bsb -no-color --`, the `--` is needed to trigger the build
cc @Khady
=> tentative fix for #2983

lib/bsb, lib/minisocket.js
Remove deprecated API, defensive, tentative fix of #2974
cc @chenglou can you confirm this also fixes your issue?
=> Address #2973

jscomp/bsb/templates/react-lite/loader.js
The correct package name for `@astrada/bs-css-core/lib/js/src/Css.js` is `@astrada/bs-css-core` but `getPackageName` was returning `@astrada` and the package was failing to load.
I'd also like to say a big thank you for writing this and including it. I've always hated using bundlers in development mode. This loader is a much better development experience 👍
=> Support npm namespaced packages in the loader

jscomp/bsb/templates/react/package.json
If you run `npm run webpack` with the `react` template, it throws an error:
`TypeError: Cannot read property 'properties' of undefined`
`describe: optionsSchema.definitions.output.properties.path.description`
A recent update went out with breaking changes, `webpack-cli` needs to be upgraded to `3.1.1` to fix the issue. 
See related discussion here: [#8082](https://github.com/webpack/webpack/issues/8082)
This PR simply applies the needed `webpack-cli` update. I tested it out, the script works as expected again.
=> Upgrade `webpack-cli` to fix broken `npm run webpack`

CONTRIBUTING.md
I ran through the bucklescript setup with opam 2. Seemed wise to update this document.
- Changed opam reference to v2
- `opam switch 4.02.3+buckle-master` to `opam switch create 4.02.3+buckle-master`
- Added a line to confirm which opam version is running and used opam eval earlier
- Minor spelling fixes
Signed-Off-By: Tim Burgess <timburgess@mac.com>
=> Update CONTRIBUTING to opam 2. Spelling fixes.

jscomp/bsb/templates/react/README.md, jscomp/bsb/templates/react/package.json, jscomp/bsb/templates/react/src/index.html, jscomp/bsb/templates/react/webpack.config.js
This adds a dev server via [webpack-dev-server](https://github.com/webpack/webpack-dev-server) to the Reason React template (`npm run server`). This enables hot reloading and routing (not just hash changes, but the History API as well). While the server option is added, the simpler server-less development can still be used. The other benefit from moving is that all of the build assets needed to run in a production environment (mainly the addition of `index.html`, which is now copied over) are contained within the `/build` folder.
Obviously this adds a few development dependencies (webpack-dev-server and [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin)), but I think providing this as an option is helpful, especially for people that make use of routing libraries …
=> Add development server (optional) to Reason React template

jscomp/others/belt_List.ml, jscomp/others/belt_List.mli, jscomp/test/bs_list_test.ml
Hi, I found this pretty confusing since the native `List` OCaml does contain a `filter` method, I guess every js dev would expect `Belt.List` to have exactly that naming as well.
This also came up during @ryyppy workshop in Alicante and I noticed some people were confused as well.
For now can we consider to have an alias to that fns? @IwanKaramazow also mentioned to me something about a deprecation flag in OCaml but I have literally no idea how to do that 😄
=> [Belt] Add List.filter/WithIndex with deprecation warning and point to List.keep/WithIndex

jscomp/all.depend, jscomp/syntax/ast_core_type.ml, jscomp/syntax/ast_literal.ml, jscomp/syntax/ast_literal.mli, jscomp/syntax/ast_util.ml, lib/bsdep.ml, lib/bsppx.ml, vendor/ocaml/bytecomp/translcore.ml
TODO: checkout why ast_util module using (*predef*, None/Some) won’t work
Done
=> fix *predef* Some

jscomp/bsb/templates/react/webpack.config.js
Fix the `server` script to run webpack-dev-server properly.
Previously, running `webpack-dev-server` would only work if you were also running the `wepback` script in another terminal tab.
After this change, simply running `yarn server` should be enough to get it working!
I ran `pack-templates.sh` to update the `bsb_templates.ml` file and it moved quite a bit of stuff around. Not sure why it did that, maybe `ocp-ocamlres` is not deterministic? I verified my changes are also in there, though.
1. Make sure there's no `build/` folder
2. Run `yarn/npm server`
4. Open `localhost:8000`
4. You should see the example components render as expected!
5. Make sure `yarn/npm webpack` is still working as expected
6. Make sure `yarn/npm webpack:production` is still working as expected
=> Fix webpack-dev-server script in `react` template

docs/api/Js.String.html, docs/api/Js.html, docs/api/index_modules.html
I noticed a few spots in the docs referring to arrays instead of strings.
=> Fix typos in docs referring to array instead of string

jscomp/others/js_typed_array2.cppo.ml, jscomp/others/js_typed_array2.ml
#3297 only took care of the cppo generation part like js_typed_array. This actually makes the semantic changes.
=> Actually remove bs.send.pipe from js_typed_array2

scripts/ninja.js
Previously, it's eagerly evaluated, which makes `getVersionString()` return the wrong thing because `useEnv` isn't set to true at that point yet when you do `ninja.js -env`
=> Fix cppo ocaml environment version generation

jscomp/super_errors/super_typecore.ml, vendor/ocaml/typing/typecore.ml, vendor/ocaml/typing/typecore.mli
This exposes the first `report_error` binding from the vendored `typecore.ml` (the binding is shadowed afterward). This allows us to avoid copy pasting the whole error pattern matching logic, which differs enough between compiler versions to be annoying to cppo.
I have a similar `typecore.ml` patch for the 4.06 compiler
=> [Super errors] Simplify super_typecore logic

vendor/ocaml/typing/typecore.ml, vendor/ocaml/typing/typecore.mli
I'm not sure why this is here, but the changes already got in, in
164758af4802ca6624dc3648d46b32f559cdfe69. And I think this commit didn't
get applied in an idempotent way?
Now we ended up with two `#if` lol
=> Revert "[compiler] export unwrapped report_error"

vendor/ocaml/typing/typecore.mli
9c4e02ed8021c796db307681a32f87a785d6f0b5 is a revert of 164758af4802ca6624dc3648d46b32f559cdfe69. But I noticed just now that typecore.mli correctly added the #if only once (contrary to typecore.ml). So I'm adding the #if back into the interface file.
=> [Super errors] Put the exposed #if back into typecore.mli

jscomp/super_errors/super_pparse.ml
This is actually so that local and CI can more easily have the same error message, because the command and the temp directories shown in it cause snapshot tests to fail. This is cleaner anyway.
=> [Super errors] Tweak reason syntax error msg

lib/bsb
Without a screen refresh, watch mode fills the terminal with a scroll of build errors and warnings. It is not easy to see where the most recent build started; scanning upwards for ">>>> Start compiling" is cognitively taxing. So now we clear the screen each time watch mode decides to rebuild. Thanks @varunpatro for working with me on this. This pull request is a one-line change, but it took a while to get here!
=> in watch mode, clear the screen upon rebuilding

CONTRIBUTING.md
This provides additional explanation on how to setup submodules. I assume that on clean clones this just works, but if not then maybe it makes sense to add it to the node script or as it's own step.
Addresses #3443
=> add submodule explaination to CONTRIBUTING.md

jscomp/bsb/bsb_config_parse.ml, lib/4.02.3/bsb.ml, lib/4.02.3/reactjs_jsx_ppx_v2.ml, lib/4.02.3/reactjs_jsx_ppx_v3.ml, lib/4.02.3/unstable/bsb_native.ml, lib/4.06.1/reactjs_jsx_ppx_v2.ml, lib/4.06.1/reactjs_jsx_ppx_v3.ml, lib/body.ninja, lib/reactjs_jsx_ppx_v3.ml, scripts/prepublish.js
See reasonml/reason-react#351 for corresponding React changes.
This (re)introduces jsx version 3 and allows people to default their entire project to the new version through a ppx. When using version 3, jsx compiles into something very similar to JS - React.createElement(component, props, ...children). This gets us a 0-cost, 0-runtime binding for React.
Tested in a local repo with all combinations of (None, Some 2, Some 3) in bsconfig.json and in bs.config attribute.
=> Add new React function component jsx ppx

lib/4.06.1/reactjs_jsx_ppx_v2.ml, lib/4.06.1/reactjs_jsx_ppx_v3.ml
A lot of this wrapping was necessary to handle the specific way 4.02 ast treated optional args. 4.06 ast is much more sane so this shouldn't be needed. This should fully fix #3460
=> Remove extra option wrapping that 4.06 doesn't require

lib/4.02.3/reactjs_jsx_ppx_v2.ml, lib/4.02.3/reactjs_jsx_ppx_v3.ml, lib/4.06.1/reactjs_jsx_ppx_v2.ml, lib/4.06.1/reactjs_jsx_ppx_v3.ml
Before we were ignoring all default arguments because they aren't considered optional arguments. Don't even need to run this check really.
=> [react jsx ppx] treat default arguments correctly

jscomp/bsb/templates/react-hooks/.gitignore
I'm new to Reason+Bucklescript so I'm not sure if this is everything that's needed for a good `.gitignore` template. Happy to address any feedback you may have!
Thanks!
Closes https://github.com/BuckleScript/bucklescript/issues/3490
=> Add .gitignore to reason hooks template

jscomp/syntax/reactjs_jsx_ppx.cppo.ml, lib/4.02.3/bsdep.ml, lib/4.02.3/bsppx.ml
This reverts commit 07799b70012ebfa288f796c81c8a57ac6d153ccd.
Didn't actually help with #3519 - only in a weird edge case that's not actually possible to hit. I continued to take off layers of the output until i could identify what I believe is an issue with bs.obj. But a repro in the issue.
=> Revert "use predef option for interface externals"

jscomp/bsb/templates/react-hooks/src/index.html, jscomp/bsb/templates/react-hooks/webpack.config.js
with this config you can open up any route directly `localhost:3000/foo/bar` in the browser
without it you would get a not found
=> fix webpack file serving for direct route access

jscomp/bsb/bsb_merlin_gen.ml
This pr contains the change discussed in https://github.com/BuckleScript/bucklescript/issues/3588.
Had some roadblocks in testing, sending pr to get further on the issue.
I did change to double quotes in the .merlin file manually on my mac, the merlin extension in vscode had no problems after.
I haven't gotten merlin functioning on windows, but at least in the windows case, this does solve the problem with reason-language-server. 
I don't have access to linux, assume it to be similar to mac.
=> Double quote -ppx argument to solve windows issue (#3588)

jscomp/bsb/bsb_ninja_file_groups.ml, jscomp/bsb/bsb_ninja_rule.ml, jscomp/bsb/bsb_ninja_rule.mli, lib/4.02.3/bsb.ml, lib/4.02.3/unstable/bsb_native.ml
The cost of adding a new rule is minimal.
Try to avoid shadows if it is not necessary.
FYI: existing shadows:
- postbuild
- bsb_dir_group
- bsc_extra_includes
- bs_package_includes (seems not used at all)
- bs_package_specs (should be removed)
=> specialize rules for building reason files

jscomp/main/native_ppx_main.ml, jscomp/syntax/ast_attributes.ml, jscomp/syntax/ast_attributes.mli, jscomp/syntax/ast_compatible.ml, jscomp/syntax/ast_compatible.mli, jscomp/syntax/ast_exp_apply.ml, jscomp/syntax/ast_tdcls.ml, jscomp/syntax/native_ast_derive_abstract.ml
This adds support for `|.`, `bs.deriving` (and the `light` version) and `@bs` uncurried calls (which we simply filter out and do nothing about, so that belt compiles without any changes to its ppxes).
I merged all the changes into the ppx code directly. Most of it is simply hiding features away when compiling to native (like `bs.obj` for example). The's a bit that's different for `bs.deriving`, because in JS we can simply make the constructor an external function that returns an `bs.obj` under the hood. We don't have `bs.obj` in native, so we use a record and generate a constructor for the record. We also can't erase the record type at the same level: we have to generate a signature literal for the module inside the implementation file, so that even inside your own code you cannot "know" …
=> Belt bsppx

.gitignore, scripts/buildocaml.js, scripts/install.js, scripts/prebuilt.js
Currently, we get an error when running `yarn`:
```shell-session
$ yarn
yarn install v1.16.0
[1/4] Resolving packages...
success Already up-to-date.
$ node scripts/install.js
/path/to/bucklescript/scripts/buildocaml.js:32
throw new Error("version file not found");
^
Error: version file not found
at ......
```
Newbie, like me, cannot understand what to do.
So this pr is the improvement to show tender message:
```shell-session
$ yarn
yarn install v1.16.0
[1/4] Resolving packages...
success Already up-to-date.
$ node scripts/install.js
cannot find '/path/to/ocaml/VERSION'
cannot find '/path/to/bucklescript/OCAML_VERSION'
You should create OCAML_VERSION or ocaml/VERSION file to specify OCaml version like '4.02.3+buckle-master'
For example, run `opam switch show > OCAML_VERSION` …
```
=> improve OCaml version file error

jscomp/syntax/reactjs_jsx_ppx.cppo.ml, jscomp/test/build.ninja, jscomp/test/gpr_3519_jsx_test.ml, lib/4.06.1/bsdep.ml, lib/4.06.1/bsppx.ml
This adds a fix for 4.06 compilation of @react.component tags which would provide inconsistent return types. Also adds a test to prevent this functionality from breaking in 4.06 or 02 going forward.
Fixes 3519 round 2.
Main change is in the second commit. The first commit is a set of unrelated changes that came up when I built 4.06. Happy to delete that commit entirely if it makes things easier.
=> Jsx fix 3519

jscomp/syntax/reactjs_jsx_ppx.cppo.ml
It seems that the usage of the same identifier as the prop in the `match` statement used for props with default values makes the compiler ignore the unused variable warnings.
This change fixes it by using a different identifier (`$value`), which is intentionally invalid so it doesn't clash with any user generated ids.
cc @rickyvetter
=> React PPX: Show warning 26 on unused props with default value

lib/bsb
Hi everyone,
I was having some issues with some of our npm scripts where I was constantly getting termination errors when running a command like `bsb -make-world -w`. It turns out that the *bsb* script returns `2` after it's started in watch mode and it receives an external interrupt like `Ctrl+C` to terminate. 
This should't be the correct behavior since any script that terminates gracefully should have a exit code of `0`.
This PR fixes that behavior, and now it should be possible to build scripts that rely on logic like `bsb -make-world -w && do_something_after_clean_exit || do_something_on_error`.
The changes are quite simple, all the OS signal handlers (*SIGINT*, *SIGUSR*, etc) now simply call a function that exits the process (basically it's just a wrapper around `process.exit(0)`). …
=> Exit code from bsb in watch mode should be 0 instead of 2

jscomp/build_tests/case3/.gitignore, jscomp/build_tests/case3/input.js, jscomp/build_tests/case3/src/hello.re, jscomp/build_tests/hyphen2/input.js, jscomp/common/bs_warnings.ml, jscomp/common/js_config.ml, jscomp/common/js_config.mli, jscomp/core/bs_conditional_initial.ml, jscomp/core/js_cmj_load.ml, jscomp/core/js_implementation.ml, jscomp/core/js_implementation.mli, jscomp/core/js_pass_debug.ml, jscomp/core/lam_compile_main.ml, jscomp/core/lam_compile_main.mli, jscomp/core/lam_util.ml, jscomp/core/ocaml_options.ml, jscomp/core/ocaml_parse.ml, jscomp/depends/binary_ast.ml, jscomp/depends/binary_ast.mli, jscomp/main/js_main.ml, jscomp/syntax/ast_external_process.ml, jscomp/syntax/ast_reason_pp.ml, jscomp/test/build.ninja, jscomp/test/gentTypeReTest.js, jscomp/test/gentTypeReTest.re, lib/4.02.3/bsdep.ml, lib/4.02.3/bsppx.ml, lib/4.02.3/unstable/all_ounit_tests.ml, lib/4.02.3/unstable/bspack.ml, lib/4.02.3/unstable/native_ppx.ml
cc @cristianoc in case you came across a regression after this release
Note after integration of reason instead of using pp, we should update the sourcefile accordingly to avoid the temporary name used
=> fix regression of genType.import & add backtrace support in compiler debug mode

jscomp/test/recursive_module.js, jscomp/test/recursive_module.ml
cc @cristianoc in the test case, in old encoding that field name is a comment which is not relevant, but it will be important with your patch
=> Add a test case for external with val signature

jscomp/others/belt_Array.mli
This makes it easier to read if you pipe it through refmt:
```
let arr = [|"ant", "bee", "cat", "dog", "elk"|];
Belt.Array.truncateToLengthUnsafe(arr, 3);
arr == [|"ant", "bee", "cat"|];
```
=> simplify truncateToLengthUnsafe example

scripts/buildocaml.js
There were changes I had missed when rebasing my last PR. This should make it possible to build with `esy` again.
=> Fix buildocaml when using esy

esy.json, jscomp/bsb/bsb_pkg.ml, lib/4.02.3/bsb.ml, lib/4.06.1/bsb.ml
This patch is basically taken from this commit https://github.com/esy-ocaml/bucklescript/commit/2b4bc2a07b3b9ee24bc1f5d877ab98f6446ab4e4
This allows us to find bs-platform via a env variable. Users can also supply paths to dependencies in a monorepo style by setting `package_name__install` to the path.
When this is merged we need 2 things:
1. A possibility to write outside of our dependencies sources as `esy` doesn't allow us to modify the soruces except for .merlin files.
2. A way to find sources that do not supply the environment variable mentioned above. We might want to solve this problem by reading the file `_esy/default/installation.json` as that will include all sources.
=> Esy monorepo support

scripts/install.js
Fixes #3843 by using nodejs fs.copyFileSync to copy pre-built compilers instead of using ninja.exe. Since ninja.exe is classed as trojan by many anti-virus software.
=> Fixes #3843

jscomp/bsb_helper/bsb_helper_depfile_gen.ml, jscomp/bsb_helper/bsb_helper_depfile_gen.mli, jscomp/bsb_helper/bsb_helper_extract.ml, jscomp/bsb_helper/bsb_helper_linker.ml, jscomp/bsb_helper/bsb_helper_linker.mli, jscomp/bsb_helper/bsb_helper_packer.ml, jscomp/bsb_helper/bsb_helper_packer.mli, jscomp/core/js_name_of_module_id.ml, jscomp/core/lam_compile_main.ml, jscomp/main/bsb_helper_main.ml, jscomp/syntax/ast_tdcls.ml
This should set us up better for #3762 :)
This shouldn't affect bsb / bsc, everything's compiled away.
The important changes are the ones to the bsb_helper_* which I took from that other PR. Those are just fixes I've accumulated for a while on my other branch. The rest is updating the stuff that's compiled away when BS_NATIVE=false, which was breaking.
=> Fix existing code compiled away with BS_NATIVE

jscomp/others/belt_Option.ml, jscomp/others/belt_Option.mli, lib/js/belt_Option.js
A very simple extension of the `Belt.Option` module. I use this `apply` method a lot in some codebases. When an option is `Some` its content is called as the parameter of a given function. 
I think it is very useful, as there are often functions like React's (reducer) `dispatch` function, or even just a logging statement, which all return `unit`.
[Reason Try Example](https://reasonml.github.io/en/try?rrjsx=true&reason=LYewJgrgNgpgBAFwJ4Ad4HkUIJYgHZwC8cA3gFBxywJwCGKKUSAqgFxwAUIWueHA5LQCUAGk4A6OIKFEAfHAh5sCGYXmLlAbgpUYNeoyTsuPfAOFjBchUpXWNCbQF9tZUJFhxMOfO2+8iUh1qOgYmZkCTBDEAM1VZHUoAZwB3ZQBjAAtObjtySkoAHzgAZRBgGA4AD3i4GI5JGsS4YoA5fHg1TiFmlzJgvVDDSNzY2oNwqLEGuBrrepqhZ1d-fHEJpA4yio4AIgRM7DwAc13RWesAKSTxKBBj6qElslW8dbDN9rwYMSqrm7uD0W2iAA)
=> Add Belt.Option.forEach

jscomp/test/flattern_order_test.ml, jscomp/test/fun_pattern_match.ml, jscomp/test/global_module_alias_test.ml, jscomp/test/js_re_test.ml, jscomp/test/recursive_module.ml
- See if we could optimize away `Sys.backend_type = Other “BS”`
- (XX: S ) -> include XX is coerced twice
=> Take notes of changes between 4.02 and 4.06

jscomp/runtime/caml_int64.mli, jscomp/stdlib-406/release.ninja, jscomp/test/int64_test.js, jscomp/test/int64_test.ml, scripts/prebuilt.js
=> Fix int64 test spec

jscomp/core/js_dump.ml, jscomp/test/class_type_ffi_test.js, jscomp/test/mario_game.js, lib/js/caml_float.js, lib/js/caml_int64.js
The benefit is not worth the complexity, we can add it in other layer if needed
- spot `++i,  —i , i += xx , i -= xx` pattern
- spot pattern `a[I] = a [I] +- j` pattern (this is preserved, since it does add some better perf)
=> Remove some transformations in printer

jscomp/main/js_main.ml, lib/4.06.1/bsdep.ml, lib/4.06.1/bspp.ml, lib/4.06.1/bsppx.ml, lib/4.06.1/unstable/bspack.ml, lib/4.06.1/unstable/native_ppx.ml
This makes the output more readable for debugging
=> Add -bs-noloc option (when using -dparsetree, -dtypedtree)

jscomp/core/lam_compile_primitive.ml, jscomp/core/lam_convert.ml, jscomp/core/lam_primitive.ml, jscomp/core/lam_primitive.mli, jscomp/core/lam_print.ml, jscomp/runtime/caml_obj.ml, jscomp/test/flow_parser_reg_test.js, jscomp/test/large_record_duplication_test.js, jscomp/test/ocaml_typedtree_test.js, jscomp/test/update_record_test.js, jscomp/test/update_record_test.ml, lib/js/caml_obj.js
cc @cristianoc 
Note Pduprecord is rarely called (only for very large record), so the performance tuning can be delayed.
If we can use modern JS syntax, it could be translated into below in the future
```js
{ ...obj, field1 :val1, field2 : val2}
```
=> Remove size field which is never used

4061.json, jscomp/snapshot.ninja, scripts/ninja.js
Sets a `native_ocaml_path` that can point either to the esy installed `ocaml` or the one from git submodules depending on if we're have the `ESY` environment variable.
The resolution should be changed when bucklescript/ocaml#38 lands.
=> Use folders from esy ocaml for snapshots

jscomp/bsb/templates/react-hooks/README.md, jscomp/bsb/templates/react-hooks/index.html, jscomp/bsb/templates/react-hooks/package.json
When running the server with the `--spa` flag every file path where no file can be found automatically will fall back to serving the index.html. This option allows you to implement routing for Single Page Applications.
=> fix SPA mode regression for hooks template

lib/js/caml_chrome_debugger.js
Fixes #3838 
**Problem**
Origninally the `variantCustomFormatter` in `canl_chrome_debugger` just mapped over the objects in the variant and called `showObject` resulting in no spacing between them which made debugging harder because if the two objects where `1` and `2` they would appear as `12`. 
**Solution**
Mapping over the data and placing `span` elements between each call to `showObject` in order to provide some spacing. The `12px` was used as this is the same as `olStyles` left padding. 
Example Reason Code: 
```reason
[%%debugger.chrome]
type y = A(int, int, int, int);
type x = B(int, int, y, y);
type reco = {
x: int,
y: int,
z: x
};
let record = {
x: 3,
y: 2,
z: B(0, 0, A(1, 2, 3, 4), A(1, 2, 3, 4))
};
Js.log(record);
```
Output:
=> Add spacing to variant formatter

jscomp/bsb/templates/react-hooks/watcher.js
One line fix to default `LAST_SUCCESS_BUILD_STAMP` correctly
=> Properly default localstorage get

jscomp/others/belt_Result.ml, jscomp/others/belt_Result.mli, jscomp/stdlib-406/pervasives.ml, jscomp/stdlib-406/pervasives.mli, jscomp/test/belt_result_alias_test.js, jscomp/test/belt_result_alias_test.ml, jscomp/test/build.ninja, jscomp/test/ocaml_parsetree_test.js, jscomp/test/ocaml_typedtree_test.js
This fixes #3952 
I added a test file to verify it works the way I expect it to work.
Note that my last commit added changes to the build artifacts of `jscomp/test/ocaml_parsetree_test.js` and `jscomp/test/ocaml_typedtree.js`.
=> Alias result type

jscomp/core/lam.ml, jscomp/core/lam_compile_util.ml, jscomp/core/lam_constant_convert.ml, jscomp/core/lam_pointer_info.ml, jscomp/core/lam_pointer_info.mli, jscomp/runtime/release.ninja, jscomp/test/build.ninja, jscomp/test/class3_test.js, jscomp/test/class4_test.js, jscomp/test/class5_test.js, jscomp/test/class6_test.js, jscomp/test/class7_test.js, jscomp/test/class8_test.js, jscomp/test/class_fib_open_recursion_test.js, jscomp/test/flow_parser_reg_test.js, jscomp/test/gpr_1539_test.js, jscomp/test/gpr_3931_test.js, jscomp/test/rec_module_test.js, jscomp/test/record_name_test.js, jscomp/test/record_name_test.ml, jscomp/test/recursive_module.js, jscomp/test/recursive_module_test.js, jscomp/test/recursive_unbound_module_test.js, jscomp/test/singular_unit_test.js, jscomp/test/singular_unit_test.ml, lib/4.06.1/bsdep.ml, lib/4.06.1/bsppx.ml, lib/4.06.1/unstable/native_ppx.ml
1. is_type_number has to be adjusted in several ways
for singleton variant -- its type is now undefined
for non-singleton variant -- it has to still be number
2. Change Lam_compile_const.Const_pointer compilation
3. Check Pisint
=> prepare for singleton variant -> undefined

jscomp/syntax/ast_external_process.ml
This is in light of general bs.val external names needing to be named
now. This message makes it less confusing while refactoring both bs.val
and bs.get/set externals
=> Tweak grammar

bspack.json
This PR adds a esy sandbox for bspack.
To use it locally you can run `esy @bspack x bspack.exe`.
But the most important thing is probably to make it usable from other projects more easily. This can be done as follows: `"bspack": "bucklescript/bucklescript:bspack.json"` and then `bspack.exe` should be available in build scripts.
=> Add esy sandbox for bspack

jscomp/bsb/README.md, jscomp/bsb/bsb_templates.ml, jscomp/bsb/templates/react-starter/.gitignore, jscomp/bsb/templates/react-starter/README.md, jscomp/bsb/templates/react-starter/bsconfig.json, jscomp/bsb/templates/react-starter/package.json, jscomp/bsb/templates/react-starter/src/App.re, jscomp/bsb/templates/react-starter/src/Index.re, jscomp/bsb/templates/react-starter/src/index.css, jscomp/bsb/templates/react-starter/src/index.html, jscomp/bsb/templates/react-starter/webpack.config.js
This PR adds a new minimal `react-starter` template with `webpack` configuration, discussed in #4000 .
I have also added some docs on how to add/edit templates and test them locally, since it might help someone else doing it later.
Let me know if there is anything I can improve!
=> React starter template

CONTRIBUTING.md, scripts/repl.js
Fixes #4023.
- Adds note to mention `ocamlfind` needs to be installed to prevent `runtime.js` missing errors
- Removes `+weak.js`, as it seems to be included by default now
- Adds `lib/4.06.1/unstable` to list of deps to remove a warning `Some OCaml interface files were not found: Js_refmt_compiler`.
- ~Re-adds cmi files that were commented~ Edit: this still breaks in 3.5.1 so commented them back again 😅
=> Playground: Update repl.js and docs to support jsoo 3.5.1

lib/bsb
Some editors are using temporary files to store edits. This results in two sync change events: change + rename and two sync builds. Using setImmediate will ensure that only one build done.
=> Use setImmediate for rebuilding in on_change callback

jscomp/common/js_config.ml, jscomp/common/js_config.mli, jscomp/core/js_implementation.ml, jscomp/main/js_main.ml
Hey @bobzhang , finally finding time to work on this I made this PR following your comment 
https://github.com/BuckleScript/bucklescript/pull/3762#discussion_r339384108
This is very useful for bsb-native so that parsing happens only once by bsc :D
=> Add -bs-simple-binary-ast

lib/bsb
When developing across multiple devices, it's useful to have live-reloading across the network. 
This PR enables specifying a custom hostname like for example `0.0.0.0`.
So the new `-ws` part of bsb will work with the followings:
- `bsb -make-world -w -ws _`
- `bsb -make-world -w -ws 0.0.0.0:9999`
- `bsb -make-world -w -ws 5000`
=> Allow defining a custom hostname for the websocket

jscomp/bsb/bsb_config_types.ml, jscomp/bsb/bsb_default.ml, jscomp/bsb/bsb_default.mli, jscomp/bsb/bsb_global_paths.ml, jscomp/bsb/bsb_global_paths.mli, jscomp/bsb/bsb_log.mli
This is another PR that should help #3762
=> Small changes to internals of bsb for native compilation

jscomp/others/node_process.ml, jscomp/others/node_process.mli
Hi,
I've just noticed that the `exit` function in Node process returns `unit`.
Since this function terminates the process, I would expect that `'a` is more appropriate here.
What do you think?
Sander
=> Make node process exit return 'a instead of unit

jscomp/bsb/templates/react-hooks/index.html
Using relative path for watcher.js in SPA mode cause wrong fall back when you have more than one level path (example: http://localhost:8000/my_path/bar)
=> fix SPA mode watcher path in react-hooks template

jscomp/syntax/reactjs_jsx_ppx.cppo.ml, lib/4.06.1/bsb.ml, lib/4.06.1/bsdep.ml, lib/4.06.1/unstable/bsb_native.ml
There are two sets of tools that need locations in OCaml world - the compiler, and editor tooling like Merlin, rls, etc. The first handles error reporting and it's important that all gen'd locations that can error point to handwritten nodes in order to give useful error locations. The later handles type at pos, click to def, etc and requires that all locations form a neat tree that can be traversed and has no cycles or shared locations. Until now we have focused entirely on good error locations for the compiler and ignored the usability of merlin in component ranges.
These two requirements are not compatible and as the gen'd tree is huge using merlins provided tools to provide "alternative" locations is really difficult. Additionally the state of meta-tooling for understanding how all of …
=> Change ReactJS PPX to avoid modifying locations of existing code

jscomp/syntax/reactjs_jsx_ppx.cppo.ml
=> [rrppx] Add error when using non-optional type to define an optional arg

jscomp/bsb/templates/basic-reason/README.md
This PR makes a few minor changes to the `README.md` in the basic reason template to:
- include commands for both `npm` and `yarn`
- include keyboard shortcuts for both Windows and Mac
=> docs: update README in basic reason template

jscomp/bsb/templates/basic-reason/README.md
Saw this tweet and looks like I found a little bug
https://twitter.com/jsjoeio/status/1224124605784305665
`yarn` does `yarn install` by default, not `start`
=> Fix yarn start command

jscomp/bsb/bsb_config_types.ml, jscomp/bsb/bsb_global_backend.ml, jscomp/bsb/bsb_global_backend.mli, jscomp/bsb/bsb_merlin_gen.ml, jscomp/bsb/bsb_ninja_gen.ml, jscomp/bsb/bsb_ninja_regen.ml, jscomp/bsb/bsb_parse_sources.ml, jscomp/bsb/bsb_world.ml, jscomp/main/bsb_main.ml
This adds bsb_global_backend, useful for native compilation. This shouldn't change any behavior and should be fairly fast thanks to `Lazy`. This will allow us to have the JS artifacts stay in `lib/bs` and then have the native artifacts in `lib/native` and bytecode in `lib/bytecode`.
You should merge #4086 first.
=> Add a lazy bsb_global_backend and use it everywhere

jscomp/core/classify_function.ml, jscomp/core/js_dump.ml, jscomp/core/js_raw_info.ml, jscomp/core/lam_analysis.ml, jscomp/test/raw_pure_test.js, jscomp/test/raw_pure_test.ml, lib/4.06.1/unstable/native_ppx.ml
cc @Coobaha 
Note this is not recommended to attach comments to function in general, it's fragile and subject to change
=> An escape hatch for eslint style switches

scripts/doc_gen.js
Should have been fixed with https://github.com/BuckleScript/bucklescript/commit/024695f6e799f7d88ad0bd7a354d7dd5e1d486ae
=> FIX DOCS CI, change binary layout

esy.json
024695f6e799f7d88ad0bd7a354d7dd5e1d486ae and a couple subsequent changes moved around the binaries so they were no longer visible in esy builds (which automatically exposes /bin and /lib but nothing else). This makes sure they are available.
=> add new binary locations to esy manifest

jscomp/runtime/release.ninja, jscomp/syntax/reactjs_jsx_ppx.cppo.ml
There was a regression introduced in f8dc8d54022132d711191c4c12b78bb519af8b33. After this, `forwardRef` would only work if refs variable name was exactly `ref`. Additionally, since we were generating code that assumed `ref` and `ref` is almost always a function in scope it would cause very confusing error messages when a different variable was used.
This allows you to use any name you'd like.
Fixes #4174
=> allow forward ref with any name

jscomp/runtime/caml_obj.ml, lib/es6/caml_obj.js, lib/js/caml_obj.js
There are a number of older libraries and polyfills that adjust the prototype of `Array` with fields that are enumerable and can for...in this iteration. While it is typically very rare in modern codebases, it has remained something that we guard against inside of Facebook.
Example of code that this is intended to protect against:
```
Array.prototype.find = "myFindPolyfill"; 
var array = ['a', 'b', 'c'];
for (var i in array) { console.log(array[i]); }
```
I chose Array.isArray and a standard for loop because there is precedent for both of these in this file.
=> change for_in impl for arrays

jscomp/bsb/bsb_ninja_regen.ml, lib/4.06.1/unstable/bsb_native.ml
We used positional args to start, but it's getting significantly more complicated now so adding named args seems like a good idea.
=> Switch to using arg names for calling bsb-native

.github/workflows/playground.yml, scripts/repl.js
Adds a new workflow that produces an artifact with `exports.js` in it, as well as stdlib folder.
Some notes:
- It only runs when pushing new tags as I guess there's no point to run it on every push / pr
- It doesn't publish to npm, but it should be quite straightforward to do so:
```
- name: publish
run: npm publish
working-directory: ./playground
env:
NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
```
- Includes a small smoke test to make sure bundle works ok
- `avsm/setup-ocaml` doesn't support caching yet, but the workflow stores whole `.opam` folder and this reduces time by half (from ~20min to ~8min).
- Windows build fails for some reason I haven't been able to figure out yet, so it's been left out temporarily
Example run can be seen in …
=> [Playground] Add new workflow to build an npm-ready package

jscomp/runtime/caml_chrome_debugger.ml, lib/es6/caml_chrome_debugger.js, lib/js/caml_chrome_debugger.js
Hey,
I changed how the runtime on the debug mode was adding the customFormatter in order to not override other formatters.
The only difference is this diff, the rest is JS formatting, let me know if you prefer to keep the old one and I can revert it and keep the PR "clean"
```diff
if (typeof window === "undefined"){
-    global.devtoolsFormatters = [formatter]
+    global.devtoolsFormatters = global.devtoolsFormatters || [];
+    global.devtoolsFormatters.push(Formatter);
} else {
-    window.devtoolsFormatters = [formatter]
+    window.devtoolsFormatters = window.devtoolsFormatters || [];
+    window.devtoolsFormatters.push(Formatter);
}
```
=> [-bs-g] Avoid override other formatters

scripts/repl.js
we check in a bytecode version of jsoo.bc and call `ocamlrun jsoo.bc`, no external deps, lighting build on the ci
=> building playground on the fly

scripts/repl.js
small patch that allows to pass a flag to repl.js. In development mode, the resulting bundle contains all original function names: `node scripts/repl.js -development`.
=> repl.js: add development mode

jscomp/core/config_util.ml, jscomp/main/jsoo_main.ml
This patch is the result of an exploration to bring back the `load_modules` API, which was recently disabled.
The proposed approach is to double down on the usage of js_of_ocaml pseudo file system to load these modules. As can be seen, the implementation of `load_modules` API for the playground is really simple, just a couple of calls to `Js.create_file` to load both cmi and cmj files into jsoo pseudo file system.
- Because we rely on js_of_ocaml on both "sides" —to consume the modules in the browser, and also to generate them as can be seen in section below— , it is highly unlikely this approach will break, as that would mean js_of_ocaml pseudo file system would be broken.
- Using jsoo pseudo-file system removes the need to update references to compiler functions like …
=> Playground: Bring back load_modules API

jscomp/main/jsoo_main.ml, jscomp/refmt/jsoo_refmt_main.ml
Adds `"/static"` to directory in `jsoo_refmt_main` (like `jsoo_main`).
Removes `load_modules` as it's not needed anymore. Using `js_of_ocaml.bc build-fs` creates a JS file that will add a file to jsoo pseudo file system directly when loaded, removing the need for providing an API hook on the compiler.
cc @ryyppy
=> [playground] fix jsoo_refmt_main, remove load_modules as not necessary

jscomp/bsb/bsb_parse_sources.ml
happy to also just do the minimal work of adding the missing space in e.g.:
```
IGNORED "Components" in public is ignored since it is notan existing module
```
=> Better error message for non-existing module in `sources[n].public`

jscomp/runtime/caml_obj.ml, jscomp/runtime/caml_option.ml, jscomp/runtime/caml_option.mli, jscomp/runtime/release.ninja, lib/es6/caml_obj.js, lib/es6/caml_option.js, lib/js/caml_obj.js, lib/js/caml_option.js
Note the main blocking issue that None is not encoded as null is due to bs.obj
for optional fields, if it is None, we don't set it, which matches the semantics of undefined closely. if we compile it to null, we have to set such field as null even if it does not exist
cc @cristianoc
=> fix #4413 -- make Some (None) not depending on physical equivalence

jscomp/core/cmd_ppx_apply.ml, jscomp/syntax/ast_reason_pp.ml
- generate meaningful names for ppx temp files
- only clean up those temp files when all commands succeed, this is important for diagnosing when some commands fail
=> improve ppx driver

jscomp/syntax/bs_ast_invariant.ml, lib/4.06.1/unstable/native_ppx.ml
We allow Some/None/[] to be redefined.
But there's really no use case to allow true/false to be redefined.
fix #4477
=> sanity check not allowing true/false redefined

jscomp/runtime/release.ninja, jscomp/syntax/reactjs_jsx_ppx.cppo.ml
Fixes #4465. Basically allows unlabelled arguments in the situation where you wrap with a forwardRef type call. Additionally adds support for type annotations and custom error case for using non-type annotation arguments to avoid the generic parser error.
=> [reactjs] add support for ref argument inside of React.forwardRef type applications (#4465)

jscomp/test/build.ninja, jscomp/test/hash_collision.js, jscomp/test/hash_collision.ml, jscomp/test/poly_variant_test.ml
TODO: merlin needs be adjusted
=> disable hash collison test for polyvar

scripts/buildocaml.js, scripts/config.js
ocaml's Makefile is a GNU Makefile. FreeBSD's make is not GNU make, it's
bsd make. To execute GNU Makefile on FreeBSD one must use gmake.
It seems gmake was introduced at some point, but then got disabled for some reason.
=> Fix building ocaml on FreeBSD

jscomp/main/js_main.ml
This is user-facing, so it'd be nice if it wasn't a random abbreviation
that only saves 3 letters at the expense of confusion
=> fmt -> format

jscomp/others/release.ninja
It is still needed as per
https://github.com/BuckleScript/bucklescript/pull/4573/files#diff-e0da68698bb17be133a452a8b717c0e6R43
=> Add back dependency module

jscomp/syntax/ast_exp_apply.ml, jscomp/syntax/bs_syntaxerr.ml, jscomp/syntax/bs_syntaxerr.mli, lib/4.06.1/unstable/native_ppx.ml
The ocaml syntax tree is very liberal, so that people could write this
```ocaml
let fn x =
((##) x ~hi)  ~lo:1 ~hi:2
```
ideally, people should write `x##hi ~lo:1 ~hi:2`
=> clean up the confusing error message over uncurry label

jscomp/core/js_dump.ml, jscomp/core/js_dump_import_export.ml, jscomp/core/js_dump_import_export.mli, jscomp/core/js_dump_program.ml, jscomp/core/js_exp_make.ml, jscomp/core/js_exp_make.mli, jscomp/core/js_name_of_module_id.ml, jscomp/core/js_op.ml, jscomp/core/js_op_util.ml, jscomp/core/lam_compile_env.ml, jscomp/core/lam_compile_env.mli, jscomp/core/lam_compile_external_call.ml, jscomp/core/lam_module_ident.ml, jscomp/core/lam_module_ident.mli, jscomp/test/key_word_property.js, jscomp/test/key_word_property.ml
Finally, we got proper default import support for es6 addressing #4566 
The implementation is quite good, we get some consistency between commonjs and es6.
```ocaml
external f :  ...  = "default" [@@bs.module "xx"]
``` 
in commonjs, it will be translated as 
```js
var f = require("xx").default
```
in es6, it will be translated as 
```js
import f from "xx"
```
Note there's a semantics mismatch between commonjs and es6 about default import, this is the closest we can get based on my research
=> es6 default import support

jscomp/super_errors/super_location.ml
Fixes #4651
This potentially breaks some ad-hoc editor plugins
Also, since the reporting of the syntax goes through a different path, I'll have to make the change on the syntax side and sync it back here (cc @IwanKaramazow)
=> [Super errors] Comform to a reporting format that's recognized by editors

jscomp/super_errors/super_location.ml
The `:` won't appear for files without location
Before:
After:
No `:`
=> [Super errors] Better version of #4654

jscomp/build_tests/super_errors/expected/collections.re.expected, jscomp/build_tests/super_errors/expected/highlighting1.re.expected, jscomp/build_tests/super_errors/expected/highlighting2.re.expected, jscomp/build_tests/super_errors/expected/highlighting3.re.expected, jscomp/build_tests/super_errors/expected/highlighting5.re.expected, jscomp/build_tests/super_errors/expected/primitives1.re.expected, jscomp/build_tests/super_errors/expected/primitives11.re.expected, jscomp/build_tests/super_errors/expected/primitives2.re.expected, jscomp/build_tests/super_errors/expected/primitives6.re.expected, jscomp/build_tests/super_errors/expected/primitives7.re.expected, jscomp/build_tests/super_errors/expected/primitives9.re.expected, jscomp/build_tests/super_errors/expected/syntaxErrors4.re.expected, jscomp/build_tests/super_errors/expected/type1.re.expected, jscomp/build_tests/super_errors/expected/warnings1.re.expected, jscomp/build_tests/super_errors/expected/warnings2.re.expected, jscomp/build_tests/super_errors/fixtures/primitives11.re, jscomp/super_errors/super_location.ml, jscomp/super_errors/super_typecore.ml
More compact layout helps with editor plugins' diagnostics display.
=> [Super errors] Tweak type mismatch to be more compact

scripts/buildocaml.js
See here: https://discuss.ocaml.org/t/ocaml-4-07-1-fails-to-build-with-apple-xcode-12/6441/19
tldr one of XCode's gcc's warning turned into an error, which made the build configuration go wrong.
The solution is either this diff, which silences that error, or use ocaml 4.08's newer `configure` which is apparently more resilient.
=> Fix broken ocaml build on macOS

jscomp/bsb/bsb_ninja_file_groups.ml, jscomp/bsb/bsb_ninja_rule.ml, jscomp/bsb/bsb_ninja_rule.mli, lib/4.06.1/bsb.ml
seems 
```
-bs-package-name graph -bs-ns Graph
```
The first part is not needed for cmi, the latter is still needed for cmi
```
rule cmji
command = $bsc $g_pkg_flg $g_lib_incls $warnings $bsc_flags -o $out $in
dyndep = $in_e.d
restat = 1
```
we should expand g_pkg_flg locally to make use of $in_d which means rules has to take advantage of package info earlier
=> (part 1) no package flags when building cmi files

jscomp/bsb/bsb_build_schemas.ml, jscomp/bsb/bsb_config.ml, jscomp/bsb/bsb_ninja_gen.ml, jscomp/bsb/bsb_ninja_global_vars.ml, jscomp/bsb/bsb_ninja_rule.ml, jscomp/bsb/bsb_ninja_rule.mli, lib/4.06.1/bsb.ml
variables in rule are expensive, they are looked up per each build target, when it's easy to have it calcuated without bloating the file size, we should the pre-computation.
Also for the variable interpolation, it should be put in the tail position based on the mutable string appending
=> get rid of variable interoplation, precompute everything

jscomp/super_errors/super_location.ml
38cbd10 was a diff that was sandwiched between 5ac77cc and b5e045d. The
latter reverted the former but forgot my initial diff which contained a
fix. This fixes it. Now the warning report is displaying correctly
again.
Before:
After:
=> [Super errors] Fix a bad revert

CONTRIBUTING.md, jscomp/build_tests/super_errors/README.md
It seems that a repeated `BS_TRAVIS_CI=1 npm install -g .` doesn't
actually trigger a newer bsb/bsc build & install anymore. Wipe the
previous one as a fix. Not sure this is the right workflow.
=> Tweak CONTRIBUTING for the local workflow

.gitmodules
Unlike SSH, HTTPS allows for anonymous fetching, such as on a build server.
=> Use HTTPS to fetch ninja git submodule

jscomp/bsb/bsb_build_util.ml, jscomp/bsb/bsb_build_util.mli, jscomp/bsb/bsb_exception.ml, jscomp/bsb/bsb_ninja_targets.mli, jscomp/bsb/bsb_world.ml, jscomp/build_tests/jsxv/input.js, lib/4.06.1/bsb.ml
It's common some projects inited from template use the old name which is not consistent with package.josn
=> consistent check for name field in bsconfig.json

scripts/buildocaml.js
As discussed here: https://github.com/ocaml/ocaml/issues/9144, and here: https://github.com/ocaml/opam-repository/pull/16583.
I hope this won't break the build process.
=> Fix broken ocaml build when compiled with gcc 10

jscomp/bsb/bsb_ninja_gen.ml, jscomp/core/bs_conditional_initial.ml, lib/4.06.1/bsb.ml, scripts/ninja.js
- Previously, in the dev mode, it does not load cmi/cmj by default since there's a bootstrap issue, 
you need build those binary artifacts first before embedding it, this cause the slightly different behavior
between the compiler built in dev mode and release mode, this commit make them behave almost 
the same by adding the include path in dev mode, so that those binary artifacts are loaded during the runtime
The consequence is that to test the compiler, we don't need go into a release mode, you can test the new behavior very fast
- add `rescript = 1` in ninja file so that the build engine could do some specialization
=> make the dev version of bsc.exe behave the same as release version of bsc

jscomp/bsb/bsb_config.ml, jscomp/bsb/bsb_ninja_gen.ml, jscomp/bsb/bsb_ninja_global_vars.ml, jscomp/bsb/bsb_ninja_rule.ml, jscomp/core/config_util.ml, jscomp/core/config_util.mli, jscomp/core/js_implementation.ml, jscomp/core/js_implementation.mli, jscomp/main/js_main.ml, jscomp/others/release.ninja, jscomp/runtime/release.ninja, jscomp/stdlib-406/release.ninja, jscomp/syntax/ast_exp_extension.ml, jscomp/test/bs_hashtbl_string_test.js, jscomp/test/bs_rbset_int_bench.js, jscomp/test/bs_set_bench.js, jscomp/test/bs_sort_test.js, jscomp/test/imm_map_bench.js, lib/4.06.1/bsb.ml, lib/4.06.1/bsb.ml.d, lib/4.06.1/unstable/js_compiler.ml.d, lib/4.06.1/unstable/js_refmt_compiler.ml.d, scripts/buckle_lto.js, scripts/ninja.js
Mixing absolute path with relative paths cause some headache: https://github.com/ninja-build/ninja/issues/1251
Using relative paths is not friendly to tooling in particular, location of files.
This patch will make good of both, it takes relative path as input but expand to absolute path in the beginning and store it into binary ast, all processing thereafter only see absolute paths.
It should not break anything since this expansion is done immediately cc @cristianoc
=> relative paths reloaded

Changes.md
Instead of:
```
#4825 fix a typo in the wanring `%@string` -> `@string`
```
Use:
```
#4825 fix a typo in the warning `%@string` -> `@string`
```
=> Fixed typo in Changes.md

jscomp/bsb/bsb_ninja_gen.ml, lib/4.06.1/bsb.ml
This commit could cut some unneeded rebuild for `-make-world`. So for a package chain A -> B -> C
If we change A, however, its public essential files, cmi and cmj does not change, it will not trigger rebuild for B and C.
This works well when you write interface file for package A so its public interface is small.
=> experimental changes so that only cmi/j changes will trigger a rebuild

jscomp/test/complex_if_test.js, jscomp/test/ext_bytes_test.js, jscomp/test/ext_string_test.js, jscomp/test/flow_parser_reg_test.js, jscomp/test/gpr_3877_test.js, jscomp/test/gpr_3877_test.ml, jscomp/test/mario_game.js, jscomp/test/ocaml_parsetree_test.js, jscomp/test/ocaml_re_test.js, jscomp/test/ocaml_typedtree_test.js, jscomp/test/parser_api.js, jscomp/test/qcc.js, jscomp/test/sexpm.js, jscomp/test/test_bug.js, jscomp/test/tscanf_test.js, lib/es6/bytes.js, lib/es6/caml_format.js, lib/es6/camlinternalFormat.js, lib/es6/genlex.js, lib/es6/scanf.js, lib/es6/string.js, lib/js/bytes.js, lib/js/caml_format.js, lib/js/camlinternalFormat.js, lib/js/genlex.js, lib/js/scanf.js, lib/js/string.js
Note the original pattern match compiler will offset the object for the convenience of the compiler, see the pic below
This actually caused a bug in the comment for variants in #4871 
The major part of this diff  is modifications to upstream to not do such offset in the pattern match compilation.
It also leads to much more readable code in various output
cc @cristianoc
=> integrate better pattern match code generation

jscomp/syntax/ast_utf8_string.ml, jscomp/syntax/ast_utf8_string_interp.ml, jscomp/test/chn_test.js, lib/4.06.1/unstable/all_ounit_tests.ml
Invariant: we always print Unicode inside ""
=> fix #4896 `'` not needed be escaped when printed inside double quotes

scripts/config.js, scripts/install.js
With this PR I'm able to compile by running first `ulimit -d 4000000`.  
```
ulimit -d 4000000
git submodule update --init
node scripts/buildocaml.js
npm install   # Also works CXX=c++ yarn install
./scripts/ninja.js config./scripts/ninja.js build
```
I ported on the following platform:
OS: OpenBSD/adJ 6.7
node: 12.16.1
(although not used by rescript-lang, this platform includes ocaml 4.09.0)
I didn't include the generated `openbsd/ninja.exe` with this PR, however I included it in the branch `openbsd-bin6.7` of my fork  <https://github.com/vtamara/rescript-compiler/tree/openbsd-bin6.7>
¿Should I do the pull request including `openbsd/ninja.exe`?
=> Porting to OpenBSD/adJ

jscomp/core/j.ml, jscomp/core/js_dump.ml, jscomp/core/js_fold.ml, jscomp/core/js_map.ml, jscomp/core/js_of_lam_variant.ml, jscomp/core/js_stmt_make.ml, jscomp/core/js_stmt_make.mli, jscomp/core/lam_compile.ml
- prepare to get rid of dev dependencies on camlp4
- once we own the code generator, it means we can generate more optimized code and more utilities
=> no higher order types in js ir for easier code generation

jscomp/others/js_exn.ml, jscomp/others/js_exn.mli
I am trying to express an idiomatic `Promise.catch` approach, which usually receives an error like this:
```
type t<+'a> = Js.Promise.t<'a>
type error = Js.Promise.error
@bs.send
external catch: (t<'a>, @bs.uncurry (error => 'b)) => t<'b> = "catch"
```
Now, `error`'s value is determined by following scenarios (in a scope of a `Promise.then`):
- 1) `raise(MyOwnError)`
- 2) `Promise.reject(MyOwnError)`
- 3) `Js.Exn.raiseError`
- 4) `someJsFunctionThatThrowsError()`
- 5) `someJsFnThatThrowsNonError()`
Case 1) and 2) are fine, because they are already making sure that our `error` is pattern matchable.
Generally I would have liked to just type the catch value to be of `type exn` and just use the explicit exception patterns and a default case for the other values, like this:
```rescript
@val …
```
=> Add Js_exn.anyToExnInternal function

jscomp/core/js_analyzer.ml, jscomp/core/js_fold_basic.ml, jscomp/core/js_pass_flatten_and_mark_dead.ml, jscomp/core/js_pass_get_used.ml, jscomp/core/js_record_iter.ml, jscomp/core/js_record_map.ml, ocaml-tree/record_iter.js, ocaml-tree/record_map.js, ocaml-tree/wasm.js, scripts/ninja.js
address the comments in the review #4916.
Something we can improve further:
- no need to monkey patch `expression_desc`, `statement_desc`
we can create each functions and fix it in the code generation
=> continue simplify visitor

docs/docson/build-schema.json, jscomp/bsb/bsb_build_schemas.ml, jscomp/bsb/bsb_config_parse.ml, jscomp/bsb/bsb_config_types.ml, jscomp/bsb/bsb_merlin_gen.ml, jscomp/bsb/bsb_ninja_gen.ml, jscomp/bsb/bsb_ninja_rule.ml, jscomp/bsb/bsb_package_specs.ml, jscomp/bsb/bsb_package_specs.mli, jscomp/bsb/bsb_pkg.mli, jscomp/bsb/bsb_pkg_types.ml, jscomp/common/js_config.ml, jscomp/common/js_config.mli, jscomp/core/js_name_of_module_id.ml, jscomp/core/js_packages_info.ml, jscomp/main/js_main.ml, lib/4.06.1/bsb.ml, lib/4.06.1/unstable/all_ounit_tests.ml, lib/4.06.1/unstable/bspack.ml
- disable the  checking between the compiler and stdlib versions,
it is a bit complicated when we can change the runtime, settle later
The setup would be additions in `bsconfig.json`:
```
"external-stdlib" : "@rescript/std"
```
=> part 2: support `external-stdlib` config

jscomp/build_tests/super_errors/expected/arity_mismatch.re.expected, jscomp/build_tests/super_errors/expected/arity_mismatch2.re.expected, jscomp/super_errors/super_typecore.ml
Fixes #4939
The previous message was also wrong (?). The types were flipped; if the
function expected 1 and got 2, it'd say "this function has arity2 but
was expected arity1".
=> [Super errors] better arity mismatch error for uncurried function

jscomp/build_tests/super_errors/expected/arity_mismatch.re.expected, jscomp/build_tests/super_errors/expected/arity_mismatch2.re.expected, jscomp/build_tests/super_errors/expected/arity_mismatch3.re.expected, jscomp/super_errors/super_typecore.ml
Depends on #4940
Before 😅:
After:
=> [Super errors] Fixes another uncurried arity mismatch report

jscomp/frontend/ast_exp_apply.ml, jscomp/test/hash_sugar_desugar.js, jscomp/test/hash_sugar_desugar.ml, jscomp/test/hash_sugar_desugar.mli
After this diff, the `##` can be replace with `#` everywhere.
The only usage place for `##` is for method call to capture `this` semantics:
```
obj##method a b 
```
=> simplify x##property#= 3 into x#property#= 3

jscomp/build_tests/super_errors/expected/highlighting5.re.expected, jscomp/super_errors/super_code_frame.ml
Fixes part of https://github.com/rescript-lang/rescript-vscode/issues/86
Previous to #5013 we couldn't fix this issue because we used Format to break lines for us. Now that we're controlling this manually, we can draw the gutter for those lines.
=> [Super errors] Add the missing gutter when a line overflows to the next

jscomp/main/js_main.ml
Low level CLI support for in place formatting
```
bsc -o output -format input
```
Note we will provide high level commands for daily usage
=> in place format support

CONTRIBUTING.md, jscomp/main/js_main.ml
Fixes #5034
This intentionally went in in #5024, but the extra debugging stack trace made some bsc/bsb diagnostics harder to read when working on the repo. So it's turned off again now. I've added a line in CONTRIBUTING.md on reactivating it, because it's a nice utility.
=> Turn off debug mode type error stack trace again

jscomp/others/js_string.ml, jscomp/others/js_string2.ml, jscomp/test/js_string_test.ml
Javscript String.prototype.match function can return `undefined` for optional capture groups that are not found, which breaks the type annotations since this is not added as a `Js.nullable`, it's not possible to deal with those undefined values since it can't be passed to `Js.Nullable.isNullable`.
Fixes #5066.
I used the following code to test this.
```ocaml
let m = Js.String.match_ [%re "/hello (world)?/"] "hello word";;
let n =
match m with
| Some(n) -> Js.Array.filter (fun a -> not (Js.Nullable.isNullable a)) n
| None -> [||];;
Js.log n;;
```
=> Fix Js.String.match_ return type

jscomp/main/rescript_main.ml, lib/4.06.1/rescript.ml, rescript, scripts/rescript_arg.js, scripts/rescript_convert.js, scripts/rescript_format.js
- Consistent usage and options doc format
- 80 col everywhere
- Same spacing everywhere, no double newline at the end
- Convenience shortcut documented the same way everywhere
- Fix typos & capitalizations
- Fix old/wrong documentations
Before:
After:
=> Clean up new CLI's help pages

rescript
=> `rescript`: mention the `init` subcommand in usage

scripts/ciTest.js
In recent Node.js versions, an uncaught exception becomes an UnhandledPromiseRejection and that makes the actual error hard/impossible to find:
https://app.circleci.com/pipelines/github/rescript-lang/rescript-compiler/3637/workflows/928d0272-43fe-4ac6-b981-114bdf3c5355/jobs/3759
=> scripts/ciTest.js: catch exceptions from main

scripts/rescript_format.js
- `rescript format -stdin`: clean up created temp file when we're done
- `rescript format file.{ml,mli,re,rei}`: don't add an extra newline at the end
- `rescript format`: only write valid code to `stdout`; errors go to `stderr`
- `rescript format`: non-zero exit code when subprocess fails
Fixes #5131
=> rescript format bugfixes

jscomp/test/build.ninja, jscomp/test/gpr_4280_test.ml, jscomp/test/hash_sugar_desugar.ml, jscomp/test/hello_res.res, jscomp/test/obj_magic_test.ml, jscomp/test/option_encoding_test.ml, jscomp/test/rec_module_opt.ml, jscomp/test/recursive_react_component.re, jscomp/test/res_debug.res, jscomp/test/unit_undefined_test.ml, scripts/ninja.js
- format
- make build scripts more robust
- fix build scripts
- make the default output less noisy
- snapshot
It used to work since we run the default mode which contains all targets
=> fix build script: rebuild tests when compiler changed

jscomp/ml/typecore.ml, jscomp/test/a_recursive_type.js, jscomp/test/a_recursive_type.ml
- remove array_kind in recursive values
- add some tests with comments
- snapshot
Note in theory, we could relax array usage (not Use.inspect) to allow more recursive values, but we hit a hidden bug here, so we are conservative in such rules. See the added test examples
=> completely remove array_kind

jscomp/ml/typetexp.ml
@wokalski opened an issue #5201 for a simpler error message for type arity mismatch case. I spent a little time working on it as a good first issue. 
Taking a page out of Elm's book, I thought it would be nice to explicitly suggest a solution to the user here. Here's what it ends up looking like: 
```
// Sample file:
type t = int
let make = (~param: t<int>) => param + 1
```
which produces this error message: 
```
We've found a bug for you!
./test.res:3:21-26
1 │ type t = int
2 │ 
3 │ let make = (~param: t<int>) => param + 1
4 │ 
The type t is not generic so expects no arguments,
but is here applied to 1 argument(s).
You wrote `t<>`. Have you tried removing the angular brackets
and writing `t` instead? 
```
I don't quite understand what `stl` does, but I know it contains the actual …
=> Add better error message for arity mismatch

jscomp/ml/btype.ml, jscomp/ml/btype.mli, jscomp/ml/typecore.ml
- add type annotations
- remove redundant begin end
- localize exceptions
- label more_sargs
- more_sargs has to be empty
- shuffle the workflow
- shuffle
- refactor extract_label
- add label
- ty_old is indeed updated but never used
- factor out ignore
- tweak
- move omitted updates upwards
- tweak
- shuffle
- snapshot
=> simplify the typing of application

jscomp/core/lam_convert.ml, jscomp/core/lam_print.ml, jscomp/ml/lambda.ml, jscomp/ml/lambda.mli, jscomp/ml/printlambda.ml, jscomp/ml/translcore.ml, jscomp/ml/translcore.mli, jscomp/ml/translmod.ml, jscomp/test/flow_parser_reg_test.js
- remove one level indirection
- simplify, remove dead code
- remove used primitives
- shuffle the order
- remove Psetglobal
- remove unused primitive_declaration
- snapshot js
- snapshot
=> remove unused code

jscomp/ml/includemod.ml
- turn pair_components into tailcall (credits to opr #10590)
- snapshot
=> tailcall conversion

.circleci/config.yml
Reverts rescript-lang/rescript-compiler#5182
check the speed difference.
The current status:
10m 16s / 13h ago
cc @Minnozz 
without the cache, it is 8m 53s, the majority of the CI time is spent in `git checout ` and building the ocaml compiler
=> Revert "circleci: enable .git directory caching"

scripts/ninja.js
This fixes #5337.
Test plan:
- `./scripts/ninja.js clean`
- `./scripts/ninja.js config`
- `./scripts/ninja.js build`
See that the build completes without any errors.
=> Fix issue with mll tests in ninja.js

jscomp/runtime/caml_obj.ml, jscomp/test/caml_compare_test.js, jscomp/test/caml_compare_test.ml, lib/es6/caml_obj.js, lib/js/caml_obj.js
Resolves https://github.com/rescript-lang/rescript-compiler/issues/5357
This is my first contribution to the project so apologies if I've checked in the wrong files or there is some other changes that need to be made. Let me know and I'll adjust the PR accordingly.
=> Use Object.prototype.hasOwnProperty.call(a, b) instead of a.hasOwnProperty(b)

CONTRIBUTING.md, dune, dune-project, jscomp/dune, scripts/ninja.js
This is one way to get standard ocaml editor integration work out of the box in vscode.
At dev time one would do `dune build` to set up the necessary files for the editor. And repeat on file changes.
Notice this does not replace the ordinary build, which does much more than build bsc.exe.
=> Add dune build for editor integration.

.github/workflows/ci.yml, package.json, scripts/buildocaml.js, scripts/ciTest.js, scripts/install.js, scripts/ninjaFactory.js, scripts/prebuilt.js
This is based on #5372 from @cristianoc.
I spent a lot of time trying to get the build and tests to run on macOS, Linux and Windows and only partially succeeded.
I am using the `ocaml/setup-ocaml@v2` action to provide the latest OCaml version 4.14.0 for the build.
Status:
* macOS: build and all tests are working 🎉
* Linux: build is working, and all tests except for the ones run by the `-bsb` option to `ciTest.js` are working, so I disabled this option for now. (The problem with this option is that `npm link rescript` fails for some reason.)
* Windows: If I disable `NINJA_FORCE_REBUILD`, then I can get the Windows build to work sometimes, but most of the time it fails with `Unbound module Obj` when compiling `stdlib-406/printexc.ml`. I was not able to find the reason and have therefore …
=> Add Github actions workflow to run build and tests on multiple platforms

jscomp/runtime/curry.ml
The dependency on `Caml_array` is not picked up because of `let%private` and a clean build fails from time to time.
=> Fix build dependency issue with curry.ml

.github/workflows/ci.yml, jscomp/test/a_filename_test.js, jscomp/test/a_filename_test.ml, scripts/ciTest.js
This PR adds the CI build for Windows.
* ~~For building ninja from source, the configure script was looking for the MSVC compiler which is not present on the Github action runners. However, MinGW is there by default, so I changed the install script to use the `mingw` platform for Windows instead.~~ Using the vendored ninja binaries now.
* There was an issue with `stdlib-406/printexc.ml` not compiling because it contained a template string which causes an indirect reference to `Obj.magic` via some AST transformation, and `obj.ml` is not necessarily built before `printexc.ml`. ~~As a quick/easy fix, I changed the template string to string concatenations.~~ Fixed in #5388.
* Only a subset of the tests is working for Windows now, so I disabled the rest. One problem here are the filename tests …
=> Github actions: Windows

.github/workflows/ci.yml, .github/workflows/get_artifact_info.js
This PR adds artifact upload for all platforms.
For each platform, a zip file is created with the contents of that platform's bin directory:
* bsb_helper.exe
* bsc.exe
* ninja.COPYING
* ninja.exe
* refmt.exe
* rescript.exe
See e.g. https://github.com/rescript-lang/rescript-compiler/actions/runs/2379805466.
Based on this, we can add further automation later, e.g. to automatically publish tag builds to npm including the binaries for all platforms.
=> Upload artifacts

jscomp/frontend/ast_utf8_string.ml, jscomp/ounit_tests/ounit_unicode_tests.ml
Fixes https://github.com/rescript-lang/syntax/issues/473
The [ecmascript spec](https://tc39.es/ecma262/#prod-CharacterEscapeSequence) states that both `SingleEscapeCharacter` and `NonEscapeCharacter` are valid escape sequences.
Previously escape sequences containing a `NonEscapeCharacter`, any regular char like `a` in`\a`, would throw the "Invalid escape code" error.
ReScript strings should have the same semantics as JS.
See [webkit](https://github.com/WebKit/WebKit/blob/263cfc964b750589b0c64a7c2d8fbcdbb6e05440/Source/JavaScriptCore/parser/Lexer.cpp#L849-L856) which implements the spec.
* Safari:
* Chrome:
=> Transform "NonEscapeCharacter" in Ast_utf8_string correct.

jscomp/others/belt_Option.ml, jscomp/others/belt_Option.mli
We find ourselves doing the following kind of thing quite often:
```rescript
let opt = switch option {
| Some(_) as some => some
| None => alternativeOption
}
let value = opt->Option.getWithDefault("string")
```
Option types in other languages already support using alternative options in the standard lib:
- [Scala – `orElse`](https://www.baeldung.com/scala/option-type#3-option-default-values)
- [F# – `orElse`](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-optionmodule.html#orElse)
- [Rust – `or`](https://doc.rust-lang.org/std/option/enum.Option.html#method.or)
In terms of naming, I followed the convention from Scala: [`getOrElse` is to `orElse`](https://www.baeldung.com/scala/option-type#3-option-default-values) as `Belt.Option.getWithDefault` is to …
=> Add new function to Option: orElse

jscomp/others/belt_Result.mli
I can sync more modules. I only need an approve that I’m going the right direction
=> Sync docs for belt_Result.mli

jscomp/others/belt_MutableSetInt.mli, jscomp/others/belt_MutableSetString.mli, jscomp/others/belt_Set.mli, jscomp/others/belt_SetDict.mli, jscomp/others/belt_SetInt.mli, jscomp/others/belt_SetString.mli
Please let me know if I am on the right track. I am basically replacing the comments with the raw comments from rescript-lang.
=> Sync docs for belt_Set.mli

jscomp/others/belt_MutableSet.mli, jscomp/others/belt_MutableSetInt.mli, jscomp/others/belt_MutableSetString.mli, jscomp/others/belt_Set.mli, jscomp/others/belt_SetDict.mli, jscomp/others/belt_SetInt.mli, jscomp/others/belt_SetString.mli
I continued with the set of `Set`-related header files:
- corrected some English wording across the `Set` header files
- finished `belt_MutableSet.mli` including making a couple of signatures consistent by replacing `'k` with `'value`
- also noticed that `belt_SetInt.mli` was completed in a prior PR but not checked off
cc @ryyppy
=> Sync docs for belt_MutableSet.mli

.github/workflows/ci.yml
As suggested by @cristianoc, let's always show the full diff (no `--stat`).
=> git diff without --stat

jscomp/others/js_re.ml
The case where MDX is arguably inferior to the comments. Please, review the content removed:
- Intro
- Some MDN links
=> Sync docs for js_re.ml

Changes.md, jscomp/ml/typecore.ml, jscomp/test/res_debug.js, jscomp/test/res_debug.res
This gives pattern matching that mimics expression constructor, where the variable by default is not optional.
The generated code seems fine, thought the checks for exhaustiveness are not kicking in.
See https://github.com/rescript-lang/rescript-compiler/issues/5452
=> Pattern matching for @nullable records.

scripts/prebuilt.js
Now I can run it without errors by invoking `node ./scripts/prebuilt.js -use-env-compiler`.
Not sure how much of it is still needed though if we already have the output of the CI build for the three platforms.
=> Get prebuilt.js to run again

.gitignore, CONTRIBUTING.md
Some minor changes:
- add `_opam` folder to gitignore, to support opam local switch development
- reference latest version of OCaml compiler in docs
- add note that `./scripts/ninja.js config` is required even in dune workflow, as I got stuck on that part (thanks @cknitt for the help!)
happy to break pr down in case it's problematic to have them together.
=> Update contributing + gitignore

jscomp/build_tests/super_errors/expected/warnings4.res.expected, jscomp/build_tests/super_errors/expected/warnings5.res.expected, jscomp/build_tests/super_errors/fixtures/warnings5.res, jscomp/ext/warnings.ml, jscomp/ml/parmatch.ml, lib/4.06.1/unstable/all_ounit_tests.ml
This changes more pattern matching related warnings/errors from OCam to ReScript syntax:
- Non closed record pattern warning ("please add ", _" to your pattern)
- Record syntax
- Variants with payloads
- Arrays
=> convert more warnings in OCaml syntax to ReScript syntax

jscomp/build_tests/case3/input.js, jscomp/build_tests/custom_namespace/input.js, jscomp/build_tests/exports/input.js, jscomp/build_tests/hyphen2/input.js, jscomp/build_tests/install/input.js, jscomp/build_tests/namespace/input.js, jscomp/build_tests/nested/input.js, jscomp/build_tests/nnest/input.js, jscomp/build_tests/ns/input.js, jscomp/build_tests/priv/input.js, jscomp/build_tests/react_ppx/input.js, jscomp/build_tests/rerror/input.js, jscomp/build_tests/scoped_ppx/input.js, jscomp/build_tests/white space/input.js, scripts/ciTest.js
https://github.com/rescript-lang/rescript-compiler/pull/5471#discussion_r906863174
=> citest: add callback

jscomp/ml/printtyp.ml, jscomp/ml/typecore.ml, jscomp/ml/typedecl.ml, jscomp/test/record_regression.res, jscomp/test/res_debug.res, lib/4.06.1/unstable/js_playground_compiler.ml.d, lib/4.06.1/whole_compiler.ml.d
See https://github.com/rescript-lang/syntax/pull/588
=> Prepare support for `ns.optional`.

package-lock.json, scripts/rescript_format.js
And use more restrictive permissions.
We should not accidentally overwrite a random file.
See discussion in https://github.com/rescript-lang/rescript-compiler/pull/5194/commits/86a5568ad2fb408f9bda324300fdc878e2319e39#r654858470
=> rescript format -stdin: check if tmpfile exists

Changes.md
Fixes https://github.com/rescript-lang/rescript-compiler/issues/5524
=> Document no escape needed for regexps.

.github/workflows/ci.yml
This is because of e.g. Debian 10 not having glibc 2.29, see the discussion in https://github.com/rescript-lang/rescript-vscode/issues/216.
=> Use ubuntu-18.04 in CI

.github/workflows/ci.yml, packages/test/test_freebsd.sh
This PR adds a job for testing installation from source on FreeBSD via https://github.com/cross-platform-actions/action to CI.yml.
In total (spinning up the VM, installing required packages and installing the ReScript npm package with postinstall from source) takes around 11 minutes.
As this would slow down CI quite a bit, I have kept it commented out.
It can be enabled in a PR anytime one wants to test if installing from source on an exotic platform still works.
=> Add installation test on FreeBSD to CI script (disabled by default)

CHANGELOG.md, jscomp/frontend/ppx_entry.ml, lib/4.06.1/unstable/js_compiler.ml.d, lib/4.06.1/unstable/js_playground_compiler.ml.d, lib/4.06.1/whole_compiler.ml.d
- Initial support for JSX V4, still work in progress.
- :boom: when V4 is activated, at most one component is allowed for each module.
=> Sync latest syntax.

CREDITS.md, README.md
Rewrote the README to give more information about the ReScript language itself and moved project history and acknowledgements into CREDITS.md.
(Took the structure from the React Native README and most of the content from the https://rescript-lang.org/ front page.)
=> New README

jscomp/frontend/ast_exp_apply.ml, jscomp/test/res_debug.js, jscomp/test/res_debug.res
This PR is the following PR to #5581 and fixes same issue in the single arity function.
=> Fix issues where pipe "->" processing eats up attributes in 1 arity function

jscomp/core/js_of_lam_string.ml, jscomp/test/test_bytes.js, lib/es6/char.js, lib/js/char.js
PR #5580 didn't use the correct reference; my initial suggestion was to use `unsafe_to_string` but that's just the same as `to_string` now.
Fixes #5573
=> Further fix for %bytes_to_string

CHANGELOG.md, rescript
I tried a few different ways to fix this, but in the end just moving the watch mode exit handlers out to run all the time was the best approach.
Fixes #5590.
=> Fix build lock not releasing

CHANGELOG.md
Per https://github.com/rescript-lang/rescript-compiler/issues/5603#issuecomment-1221571185,
resolves !5403
@cristianoc should this go into `master` or here?
=> Remove @optional mention in CHANGELOG.md

CHANGELOG.md, rescript
This PR resolves an issue where `fs.openSync` is throwing a permission error on windows, preventing any building from happening.
View the linked issues for more information, attached is a screenshot of the lock file performing it's duty
Fixes #5620 
Fixes #5617
=> Close the lock file after opening

.github/workflows/ci.yml
Simplify ci.yml, setup-ocaml fork is no longer needed.
=> setup-ocaml 2.0.6 supports macOS ARM now
