- README.md
- jscomp/Makefile
- jscomp/Makefile.shared
- jscomp/bin/compiler.ml
- jscomp/build.sh
- jscomp/compiler.mllib
- jscomp/runtime/.depend
- jscomp/runtime/Makefile
- jscomp/stdlib/.depend
- jscomp/stdlib/Compflags
- jscomp/stdlib/Makefile.shared
- jscomp/test/.depend
- jscomp/test/Compflags
- jscomp/test/Makefile
need to check the build system as well
> now we have our own compiler driver

- jscomp/Makefile
- jscomp/bin/compiler.ml
- jscomp/release.sh
- jscomp/tools/ocaml_pack.ml
- jscomp/tools/ocaml_pack_main.ml
- jscomp/tools/pack.sh
1. add a timestamp 2.snapshot the new release 3. add a release script
> automate release

- jscomp/runtime/caml_format.js
- jscomp/runtime/caml_format.ml
- jscomp/runtime/caml_format.mli
- jscomp/test/caml_format_test.js
- jscomp/test/caml_format_test.ml
Full coverage for `caml_string`, now it's prepared for caml_int64_format support in ocaml
Be careful..
```ocaml
Exception: Failure "int_of_string". 
```
> replace all format utils with ocaml now

- jscomp/ext_string.ml
- jscomp/js_analyzer.ml
- jscomp/js_exp_make.ml
- jscomp/js_fun_env.ml
- jscomp/js_pass_debug.ml
- jscomp/lam_current_unit.ml
- jscomp/lam_dispatch_primitive.ml
- jscomp/lam_methname.ml
- jscomp/lam_pass_remove_alias.ml
- jscomp/lam_util.ml
- jscomp/runtime/caml_bigarray.ml
- jscomp/runtime/caml_float.ml
- jscomp/runtime/caml_format.js
- jscomp/runtime/caml_format.ml
- jscomp/runtime/caml_format.mli
- jscomp/runtime/caml_obj.ml
- jscomp/stdlib/scanf.js
- jscomp/test/caml_format_test.js
- jscomp/test/caml_format_test.ml
- jscomp/test/lam_methname.js
also a bug fix for misuse `!=` instead of `<>`
> support int64_of_string

- jscomp/runtime/caml_io.js
- jscomp/runtime/caml_io.ml
> fix std exit

- jscomp/index.html
- jscomp/js_config.ml
- jscomp/js_dump.ml
- jscomp/lam_dispatch_primitive.ml
- jscomp/lib/js.ml
- jscomp/runtime/.depend
- jscomp/runtime/caml_md5.js
- jscomp/runtime/caml_md5.ml
- jscomp/runtime/caml_md5.mli
- jscomp/runtime/md5.js
- jscomp/runtime/runtime.mllib
- jscomp/stdlib/digest.js
- jscomp/test/.depend
- jscomp/test/digest_test.js
- jscomp/test/digest_test.ml
- jscomp/test/string_get_set_test.js
- jscomp/test/string_get_set_test.ml
- jscomp/test/test.mllib
> add md5 support in pure ocaml

- jscomp/js_main.ml
- jscomp/jsoo_driver.ml
- jscomp/runtime/Makefile
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/fail_comp.js
- jscomp/test/fail_comp.ml
- jscomp/test/test.mllib
> [fix] always turn on -safe-string

- jscomp/lam_compile_group.ml
- jscomp/test/stack_comp_test.ml
> [fix] disable labmda output -- should on only when debug mode

- jscomp/js_config.ml
- jscomp/js_exp_make.ml
- jscomp/js_stmt_make.ml
- jscomp/lam_compile_group.ml
- jscomp/runtime/caml_hash.js
- jscomp/runtime/caml_hash.ml
- jscomp/stdlib/obj.js
- jscomp/stdlib/parsing.js
- jscomp/test/.depend
- jscomp/test/test.mllib
- jscomp/test/undef_regression_test.js
- jscomp/test/undef_regression_test.ml
> [fix] Fix wrong optimization on undef

- jscomp/jsoo_driver.ml
> [fix] playground syntax extension support

- jscomp/lam_compile_external_call.ml
- jscomp/lib/bench.ml
- jscomp/test/demo_page.js
- jscomp/test/demo_page.ml
- jscomp/test/test_react.js
- jscomp/test/test_react.ml
- jscomp/test/test_scope.js
- jscomp/test/test_scope.ml
> [fix] disabled `bs.scope`

- jscomp/ext_filename.ml
- jscomp/ext_filename.mli
- jscomp/ext_pervasives.ml
- jscomp/ext_pervasives.mli
- jscomp/js_config.ml
- jscomp/js_config.mli
- jscomp/js_main.ml
- jscomp/lam_dispatch_primitive.ml
- jscomp/runtime/.runtimedepend
- jscomp/runtime/caml_basic.js
- jscomp/runtime/caml_basic.ml
- jscomp/runtime/caml_basic.mli
- jscomp/runtime/caml_sys.js
- jscomp/runtime/caml_sys.ml
- jscomp/runtime/caml_sys.mli
- jscomp/runtime/runtime.mllib
- jscomp/test/.depend
- jscomp/test/ext_filename.js
- jscomp/test/ext_pervasives.js
- jscomp/test/ext_pervasives.ml
- jscomp/test/ext_pervasives.mli
- jscomp/test/test.mllib
> support `-npm-package` and provide some utilities to handle `option` and `list` on js side

- jscomp/js_exp_make.ml
- jscomp/js_exp_make.mli
- jscomp/lam_compile_external_call.ml
- jscomp/test/.depend
- jscomp/test/http_types.ml
- jscomp/test/test.mllib
- jscomp/test/test_http_server.ml
- jscomp/test/test_http_server.mli
- lib/js/test/http_types.js
- lib/js/test/test_http_server.js
the server is running! see test_http_server.ml (js) for generated code
> [feature] finally a working http server using nodejs!!

- README.md
> [Readme] Update bsc command

- jscomp/js_exp_make.mli
- jscomp/lam_dispatch_primitive.ml
- jscomp/runtime/js.ml
- jscomp/test/.depend
- jscomp/test/test.mllib
- jscomp/test/test_unsafe_cmp.ml
- lib/js/test/test_unsafe_cmp.js
> [feature] expose unsafe generic js comparison in Js lib

- jscomp/lam_compile.ml
- jscomp/syntax/ppx_entry.ml
- jscomp/test/.depend
- jscomp/test/demo.ml
- jscomp/test/method_chain.ml
- jscomp/test/test.mllib
- jscomp/test/test_unsafe_obj_ffi_ppx.ml
- lib/js/test/chain_code_test.js
- lib/js/test/method_chain.js
- lib/js/test/promise.js
> Method chaining feature #463

- docs/Extensions.md
- jscomp/ext/ext_pervasives.ml
- jscomp/ext/ext_pervasives.mli
- jscomp/stdlib/pervasives.ml
- jscomp/stdlib/pervasives.mli
- jscomp/syntax/ast_util.ml
- jscomp/syntax/ast_util.mli
- jscomp/syntax/ppx_entry.ml
- jscomp/syntax/syntax.mllib
- jscomp/test/.depend
- jscomp/test/obj_type_test.ml
- jscomp/test/ppx_apply_test.ml
- jscomp/test/test.mllib
- lib/js/test/ext_pervasives.js
- lib/js/test/obj_type_test.js
first step: refactoring ppx before changing existing syntax
> finalizing FFI syntax - step one

- docs/Compiler-options.md
- docs/Compiler-overview.md
- docs/Create-a-simple-example-with-NPM.md
- docs/Dev-mode-How-to.md
- docs/Extensions.md
- docs/FAQ.md
- docs/Help-move-runtime-functions-from-OCaml-to-Javascript.md
- docs/How-to-adapt-your-build-system.md
- docs/Installation.md
- docs/JS-call-OCaml.md
- docs/JavaScript-target-versions.md
- docs/NPM-Support.md
- docs/OCaml-call-JS.md
- docs/Playground.md
- docs/Roadmap.md
- docs/Runtime-representation.md
- docs/SUMMARY.md
- docs/Semantic-differences-from-other-backends.md
- docs/Unsupported-IO-primitives.md
This started as only spelling/punctuation changes, but ended up including some small grammar readability suggestions as well. Please tell me if there is a way you would prefer to consider these diffs.
Signed-Off-By: Jim Tittsler <jimt@onjapan.net>
> Fix docs spelling/punctuation.

- jscomp/js_of_lam_variant.ml
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/bs_rest_test.js
- jscomp/test/bs_rest_test.ml
- jscomp/test/poly_variant_test.js
- jscomp/test/poly_variant_test.ml
- jscomp/test/poly_variant_test.mli
> Rest calling convention

- jscomp/bs_loc.ml
- jscomp/bs_loc.mli
- jscomp/core.mllib
- jscomp/lam_compile_external_call.ml
- jscomp/lam_external_def.ml
- jscomp/runtime/bs_string.ml
- jscomp/test/ffi_test.ml
Squashed commits:
[754a833] move labels up
[14eff28] provide better error messages
[c205aad] fix a typo
[b44994d] always pass a location -- can be Location.none
[63c922b] remove unused qualifiers, i.e, bs.scope
[41c919f] WIP
[1bb3ca3] clean up ffi interface
> seems ready to serialize for native string

- jscomp/syntax/ast_external_attributes.ml
- jscomp/syntax/ast_payload.ml
- jscomp/syntax/ast_payload.mli
- jscomp/test/demo.ml
- jscomp/test/demo_binding.ml
- jscomp/test/http_types.ml
- jscomp/test/js_val.ml
see test/http_types.ml for example
@freebroccolo
> address #569, unify bs.val_of_module with bs.module

- js-demo/edit.js
- js-demo/index.html
- js-demo/theme.css
- Add navbar and examples
- Changed styling
> Upgrade Playground

- jscomp/runtime/Makefile
- jscomp/stdlib/Makefile.shared
- jscomp/test/Makefile
since we would not change the package name anyway
> fix environment variables

- jscomp/common/bs_exception.ml
"Pacage" -> "Package" in error message.
> Fixes typo

- jscomp/bin/bs_ppx.ml
- jscomp/bin/compiler.ml
- jscomp/syntax/ast_util.ml
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/ppx_this_obj_field.js
- jscomp/test/ppx_this_obj_field.ml
see test/ppx_this_obj_field.ml 
seems that we can support `private method` too
> support object field fix #694

- docs/blog/index.html
- site/docsource/blog/index.adoc
> redirect to TechAtBloomberg

- docs/Manual.html
- jscomp/bin/compiler.ml
- jscomp/lam_compile_group.ml
- lib/js/sys.js
- site/docsource/Semantic-differences-from-other-backends.adoc
> fix max string(array) length

- package.json
cc @chenglou @jordwalke @bobzhang
> Make bucklescript binaries discoverable by dependencyEnv

- jscomp/bin/bsdep.ml
- jscomp/bin/bspp.ml
- jscomp/bin/whole_compiler.ml
- jscomp/others/Makefile
- jscomp/runtime/Makefile
- scripts/config.js
> fix osx failure

- jscomp/others/.depend
- jscomp/others/Makefile
- jscomp/others/node.ml
- jscomp/others/node_child_process.ml
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/installation_test.js
- jscomp/test/installation_test.ml
- lib/js/node.js
- lib/js/node_child_process.js
1, this test should prevent silly configure error
2. array.includes not available in node v4
> add bsc.exe installation check to prevent regression

- docs/Manual.html
> Corrected flag heading.

- README.md
> update license to LGPL with linking exception per #5

- jscomp/bin/bsb.ml
- jscomp/bin/bsdep.ml
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.ml
- jscomp/bsb/bs_build_util.ml
- jscomp/bsb/bs_build_util.mli
- jscomp/bsb/bsb_main.ml
- jscomp/ext/ext_filename.ml
- jscomp/ext/ext_filename.mli
- jscomp/test/.depend
- jscomp/test/a_filename_test.js
- jscomp/test/a_filename_test.ml
- jscomp/test/ext_filename.js
normalize configuration path, fix #886 in a more elegant way
> add a slow normalize path

- jscomp/bin/whole_compiler.ml
- jscomp/core/ocaml_batch_compile.ml
TODO: we need formalize the ppx order, whether apply built in ppx first or external ppx first, fix #891
> apply ppx rewriter for -bs-eval

- jscomp/Makefile
- jscomp/bin/bsb.ml
- jscomp/bsb/bsb_gen.ml
- jscomp/bsb/bsb_ninja.ml
Test: try bsb.exe, make sure the generated build.ninja's typo got corrected.
> [bsb] Correct bs_packaeg_includes spelling

- .gitignore
- .vscode/tasks.json
- jscomp/bin/whole_compiler.ml
- jscomp/bsb/bsb.adoc
- jscomp/core/js_program_loader.ml
- jscomp/core/lam_compile_group.ml
@chenglou 
would you confirm that this would fix the issue
> tentative fix for #913

- jscomp/.merlin
- jscomp/Makefile
- jscomp/all.depend
- jscomp/bin/all_ounit_tests.d
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsb.d
- jscomp/bin/bsb.ml
- jscomp/bsb/bsb_dep_infos.ml
- jscomp/bsb/bsb_main.ml
- jscomp/bsb/bsb_ninja.ml
- jscomp/ext/ext_array.ml
- jscomp/ext/resize_array.ml
- jscomp/ext/resize_array.mli
- jscomp/ext/string_vec.ml
- jscomp/ounit_tests/ounit_array_tests.ml
- jscomp/ounit_tests/ounit_tests_main.ml
- jscomp/test/ext_array.js
now `bsb.exe -help` works
common patterns:
```
bsb.exe
bsb.exe -regen --
bsb.exe -regen 
```
Options nice to add 
```
bsb.exe -run src/xx/a.ml  -- # only build its dependency and run directly
bsb.exe -init -- # for the first time generate `bsconfig.json`
```
> address #929, work in progress

- jscomp/Makefile
- jscomp/others/.depend
- jscomp/others/Makefile
- jscomp/others/js_boolean.ml
- jscomp/others/js_boolean.mli
- jscomp/runtime/Makefile
- jscomp/runtime/js.ml
I couldn't make it build & refer to Js_boolean for some reason. Maybe the code's actually wrong here or maybe it's make.
> Add module Js_boolean for boolean-specific logic

- jscomp/Makefile
- jscomp/all.depend
- jscomp/bench/map_test.js
- jscomp/bench/set_test.js
- jscomp/bin/all_ounit_tests.d
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsb.d
- jscomp/bin/bsb.ml
- jscomp/bin/whole_compiler.d
- jscomp/bin/whole_compiler.ml
- jscomp/ext/bal_set_common.ml
- jscomp/ext/bal_tree.ml
- jscomp/ext/bal_tree.mli
- jscomp/ext/ext_array.ml
- jscomp/ext/ext_array.mli
- jscomp/ext/ext_int.ml
- jscomp/ext/ident_set.ml
- jscomp/ext/resize_array.ml
- jscomp/ext/resize_array.mli
- jscomp/ext/string_set.ml
- jscomp/ounit_tests/ounit_bal_tree_tests.ml
- jscomp/ounit_tests/ounit_vec_test.ml
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/bal_set_common.js
- jscomp/test/bal_set_common.ml
- jscomp/test/bal_tree.js
- jscomp/test/ext_array.js
- jscomp/test/string_set.js
2. refactoring vector to make it easy to specialize in the future
> 1. fix a bug in vector reverse

- docs/docson/build-schema.json
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsb.ml
- jscomp/bsb/bsb_build_ui.ml
- jscomp/bsb/bsb_json.ml
- jscomp/bsb/bsb_json.mli
- jscomp/bsb/bsb_json.mll
now 
```js
"dir" : "src" // "files" field are optional, if not specified, all files are considered as source code
```
> files field are optional, if not specified, all files are considerred to be sources

- docs/Manual.html
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/test_cpp.js
- jscomp/test/test_cpp.ml
- package.json
- site/docsource/Get_started.adoc
- site/docsource/Manual.adoc
update the docs (cc @dorafmon)
> Fix #988 about the docs

- jscomp/bin/bsb.ml
- jscomp/bsb/bsb_main.ml
`FLG -ppx` works as of merlin 2.5.1
https://github.com/bloomberg/bucklescript/pull/994/files?w=1
Signed-Off-By: Cheng Lou <chenglou92@gmail.com>
> bsb merlin generation: use `FLG -ppx` instead of `PPX`

- jscomp/Makefile
- jscomp/all.depend
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/whole_compiler.d
- jscomp/bin/whole_compiler.ml
- jscomp/build.sh
- jscomp/core/lam_dce.ml
- jscomp/core/lam_pass_collect.ml
- jscomp/core/lam_stats.ml
- jscomp/core/lam_stats.mli
- jscomp/ext/hash_set.cppo.ml
- jscomp/ext/ident_hash_set.ml
- jscomp/ext/ident_hash_set.mli
- jscomp/ext/int_hash_set.ml
Note that however fancy build system we use here, it does not affect end user experience thanks to bspack
> manageable specialized data structures

- docs/Manual.html
- jscomp/.ocamlinit
- jscomp/Makefile
- jscomp/all.depend
- jscomp/bin/all_ounit_tests.d
- jscomp/bin/all_ounit_tests.i.ml
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsb.ml
- jscomp/bin/whole_compiler.ml
- jscomp/ext/ext_topsort.ml
- jscomp/ext/ext_topsort.mli
- jscomp/ext/int_vec.ml
- jscomp/ext/resize_array.ml
- jscomp/ext/set_gen.ml
- jscomp/ext/set_int.mli
- jscomp/ext/vec.cppo.ml
- jscomp/ext/vec_gen.ml
- jscomp/ounit_tests/ounit_tests_main.ml
- jscomp/ounit_tests/ounit_topsort_tests.ml
- jscomp/ounit_tests/ounit_vec_test.ml
TODO: merge after we test layered dfs
> more efficient int vector/ efficient partition support

- jscomp/Makefile
- jscomp/all.depend
- jscomp/bin/all_ounit_tests.i.ml
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsb.d
- jscomp/bin/bsb.ml
- jscomp/bin/bsb_helper.ml
- jscomp/bin/bsdep.ml
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.ml
- jscomp/bsb/bsb_build_ui.ml
- jscomp/bsb/bsb_build_util.ml
- jscomp/bsb/bsb_build_util.mli
- jscomp/bsb/bsb_default.ml
- jscomp/bsb/bsb_dep_infos.ml
- jscomp/bsb/bsb_main.ml
- jscomp/bsb/bsb_unix.ml
- jscomp/bsb/bsb_unix.mli
- jscomp/ext/ext_filename.ml
- jscomp/ext/ext_filename.mli
- jscomp/ext/ext_string.ml
- jscomp/ext/ext_string.mli
- jscomp/test/ext_filename.js
- jscomp/test/ext_string.js
provide two new options `-make-world` and `-clean-world`
typical use cases:
```
bsb -clean-world
bsb -make-world -w 
```
build all dependencies and itself entering the watch mode
> build all dependencies

- jscomp/.ocamlinit
- jscomp/Makefile
- jscomp/all.depend
- jscomp/bin/all_ounit_tests.d
- jscomp/bin/all_ounit_tests.i.ml
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/whole_compiler.d
- jscomp/bin/whole_compiler.ml
- jscomp/bsb/bsb.adoc
- jscomp/core/lam.ml
- jscomp/core/lam.mli
- jscomp/core/lam_compile.ml
- jscomp/ext/int_vec_util.ml
- jscomp/ext/int_vec_util.mli
- jscomp/ounit_tests/ounit_int_vec_tests.ml
- jscomp/ounit_tests/ounit_tests_main.ml
- jscomp/test/arith_lexer.js
- jscomp/test/flattern_order_test.js
- jscomp/test/flow_parser_reg_test.js
- jscomp/test/number_lexer.js
- jscomp/test/ocaml_proto_test.js
- jscomp/test/rec_value_test.js
- jscomp/test/simple_lexer_test.js
- jscomp/test/stream_parser_test.js
- lib/js/camlinternalFormat.js
TODO: better free_variables analysis, handling such case without dynamic update:
```ocaml
type t = { get : unit -> int ; set : int -> unit }
let rec obj = { get = (fun _ -> !v) ; set = {fun i -> v := i}}
```
> scc when compiling recursive bindings -- this might be the best gateway place

- jscomp/bin/bsb.ml
- jscomp/bin/bsdep.ml
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.ml
- jscomp/bsb/bsb_dep_infos.ml
- jscomp/bsb/bsb_ninja.ml
- jscomp/bsb/bsb_ninja.mli
- jscomp/core/js_main.ml
- jscomp/core/jsoo_main.ml
- jscomp/test/hello_reason.re
test case: https://github.com/yawaramin/bs-mli-repro
> wip:fix for build

- jscomp/bin/bsb_watcher.js
Fixes #1077 
https://github.com/bloomberg/bucklescript/pull/1078/files?w=1
> Make bsb -w stream better

- jscomp/bin/bsb.ml
- jscomp/bsb/bsb_default.ml
- jscomp/bsb/bsb_ninja.ml
> merlin_gen_by_default, install sources

- jscomp/bin/bsb.ml
- jscomp/bsb/bsb_main.ml
Fixes #1117
https://github.com/bloomberg/bucklescript/pull/1118/files?w=1
> Fix bsb -w silently failing

- docs/Manual.html
- site/docsource/Build-system-support.adoc
- site/docsource/Compiler-options.adoc
see #1108 
@OvermindDL1 would you have a look to see if it addresses most of your concerns?
> more docs about bsb

- docs/Manual.html
- jscomp/bin/all_ounit_tests.i.ml
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/whole_compiler.ml
- jscomp/core/lam_compile_external_call.ml
- jscomp/ounit_tests/ounit_cmd_tests.ml
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/gpr_1170.js
- jscomp/test/gpr_1170.ml
> fix combination of bs.set bs.as

- jscomp/all.depend
- jscomp/bin/all_ounit_tests.i.ml
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsb.ml
- jscomp/bin/bsdep.ml
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.ml
- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_default.ml
- jscomp/bsb/bsb_gen.ml
- jscomp/ext/ext_list.ml
- jscomp/ext/ext_list.mli
- jscomp/ounit_tests/ounit_list_test.ml
- jscomp/test/.depend
- jscomp/test/ext_list.js
> fix external paths merlin issue

- jscomp/test/js_array_test.js
- jscomp/test/js_array_test.ml
- jscomp/test/js_re_test.js
- jscomp/test/js_re_test.ml
- jscomp/test/js_string_test.js
- jscomp/test/js_string_test.ml
js_array_test, js_string_test, js_re_test
Should work now that Travis has been upgraded to Node v6.
> Re-enabled es2015 tests

- lib/es6/js_date.js
- lib/js/js.js
- lib/js/js_date.js
A couple of missing files it seems should have been checked in with #1223
> Missing files from js_date PR

- jscomp/runtime/caml_float.ml
- jscomp/runtime/caml_int64.ml
- jscomp/runtime/typed_array.ml
- jscomp/test/Makefile
- jscomp/test/typed_array_test.js
- jscomp/test/typed_array_test.ml
- lib/es6/caml_float.js
- lib/es6/typed_array.js
- lib/js/caml_float.js
- lib/js/typed_array.js
I'm not terribly familiar with the type system yet, so please excuse and inform me of any abuse.
> Completed typed_array and added tests

- jscomp/bin/bsb.ml
- jscomp/bsb/bsb_dep_infos.ml
Kept thinking "File not found" is an error.
cc @bsansouci
> Tweak the wording of bsb_dep_infos

- jscomp/others/js_null_undefined.ml
- jscomp/others/js_null_undefined.mli
- jscomp/test/Makefile
- jscomp/test/js_null_test.js
- jscomp/test/js_null_test.ml
- jscomp/test/js_null_undefined_test.js
- jscomp/test/js_null_undefined_test.ml
- jscomp/test/js_undefined_test.js
- jscomp/test/js_undefined_test.ml
- jscomp/test/mock_mt.js
- jscomp/test/mock_mt.ml
- jscomp/test/mt.js
- jscomp/test/mt.ml
- jscomp/test/mt.mli
Also added tests for js_null_undefined, js_null and js_undefined
Fixes #1235
> Added null and undefined to js_null_undefined

- jscomp/bin/bsb.ml
- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_config_types.ml
- jscomp/bsb/bsb_gen.ml
> Check for missing package name in bsb

- jscomp/bin/whole_compiler.ml
- jscomp/core/js_implementation.ml
- jscomp/others/Makefile
- jscomp/others/js_null_undefined.ml
- jscomp/runtime/Makefile
- jscomp/runtime/caml_int64.ml
- jscomp/test/Makefile
- jscomp/test/mock_mt.js
- jscomp/test/mock_mt.ml
previously `-warn-error` does not have effect, this PR will bring it back..
> [fix] add missed fatal error checking

- jscomp/bin/bsdep.ml
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.ml
- jscomp/syntax/ast_external_attributes.ml
- jscomp/test/return_check.js
- jscomp/test/return_check.ml
> 1. more exhaustive checking thanks to warning +9 2. allow [@@bs.return null_to_opt]

- jscomp/runtime/js.mli
- lib/es6/arg.js
- lib/es6/caml_int64.js
- lib/es6/caml_parser.js
- lib/es6/camlinternalFormat.js
- lib/es6/curry.js
- lib/es6/format.js
- lib/es6/hashtbl.js
- lib/es6/js_global.js
- lib/es6/scanf.js
- lib/es6/sort.js
- lib/js/js.js
> Added Global in js.mli too. Added updated es6 output

- jscomp/others/js_string.ml
cc @glennsl , what do you think
> return string primitive instead of string object

- docs/js-demo/examples/left_pad.ml
Just playing around in the BuckleScript js-demo, thinking the left_pad demo should maybe actually create the function similar to other left_pads. This will also show how currying can be used.
> Changes left pad example to create left_pad fun

- jscomp/others/js_re.mli
> [Docs] Fix Js_re example

- docs/api_static/script.js
- docs/api_static/style.css
- odoc_gen/generator.ml
- Adds anchor links to each item, so they can be easily copied and referred to elsewhere
- Adds sidebar with module index, so modules can be navigated between directly
> [API docs] Usability improvements

- jscomp/runtime/js.mli
Forgot to put it in the mli in #1390
> Add promise to js.mli

- jscomp/others/js_json.ml
- jscomp/others/js_json.mli
- jscomp/test/js_json_test.js
- jscomp/test/js_json_test.ml
- lib/js/js_json.js
Signed-Off-By Maxime Ransan <maxime.ransan@gmail.com>
> Rename '*OfJSON' functions to 'decode*'

- docs/docson/build-schema.json
- Put the important items first.
- Corrected typos & phrasing, made things more consistent (e.g. not
implemented, not needed, default).
- Documented a few new things along the way.
> Revamp bsb schema

- scripts/install.js
Broken by c1715f5678d1bdbf61918ad84c73ba945fba3315
> Fix install

- jscomp/Makefile
- jscomp/all.depend
- jscomp/bin/whole_compiler.d
- jscomp/bin/whole_compiler.ml
- jscomp/core/lam.ml
- jscomp/core/lam.mli
- jscomp/core/lam_analysis.ml
- jscomp/core/lam_beta_reduce.ml
- jscomp/core/lam_beta_reduce.mli
- jscomp/core/lam_bounded_vars.ml
- jscomp/core/lam_bounded_vars.mli
- jscomp/core/lam_compile_group.ml
- jscomp/core/lam_compile_primitive.ml
- jscomp/core/lam_pass_exits.ml
- jscomp/core/lam_pass_remove_alias.ml
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/bdd.js
- jscomp/test/ffi_arity_test.js
- jscomp/test/flow_parser_reg_test.js
- jscomp/test/gpr_1072.js
- jscomp/test/gpr_1072.ml
- jscomp/test/gpr_1438.js
- jscomp/test/gpr_1438.ml
- jscomp/test/libqueue_test.js
- jscomp/test/qcc.js
- jscomp/test/stack_comp_test.js
- jscomp/test/tuple_alloc.js
- lib/js/arg.js
- lib/js/genlex.js
slightly better than #1437 
also fix #1080
> tentative fix of #1437

- jscomp/all.depend
- jscomp/bin/bsdep.ml
- jscomp/bin/bspp.ml
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.ml
- jscomp/syntax/ast_derive_dyn.ml
- jscomp/syntax/ast_external_attributes.ml
- jscomp/syntax/bs_syntaxerr.ml
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/module_alias.js
- jscomp/test/module_alias.ml
- jscomp/test/unicode_type_error.js
- jscomp/test/unicode_type_error.ml
> make ppx error message also color ful

- scripts/install.js
This has been tested on centos 6/7
> Use prebuilt linux ninja for x64

- docs/docson/build-schema.json
Signed-Off-By: António Nuno Monteiro <anmonteiro@gmail.com>
> glboal -> global in build-schema

- jscomp/Makefile
- jscomp/all.depend
- jscomp/runtime/Makefile
- jscomp/test/literals.js
cc @bsansouci 
needs to add new files to Makefile and run make depend for dev build
> fix bsb dev build error

- jscomp/others/.depend
- jscomp/others/Makefile
- jscomp/others/js_promise.ml
- jscomp/runtime/js.ml
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/exn_error_pattern.js
- jscomp/test/exn_error_pattern.ml
- jscomp/test/js_promise_basic_test.js
- jscomp/test/js_promise_basic_test.ml
- lib/js/js_promise.js
> provide promise bindings

- jscomp/bin/bsb.ml
- jscomp/bsb/bsb_config_parse.ml
Don't resovle dev package when [no_dev]
> fix bs-dev-dependencies

- jscomp/Makefile
- jscomp/all.depend
- jscomp/bin/all_ounit_tests.d
- jscomp/bin/all_ounit_tests.i.ml
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsdep.d
- jscomp/bin/bsdep.ml
- jscomp/bin/bsppx.d
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.d
- jscomp/bin/whole_compiler.ml
- jscomp/ounit_tests/ounit_tests_main.ml
- jscomp/ounit_tests/ounit_unicode_tests.ml
- jscomp/syntax/ast_utf8_string.ml
- jscomp/syntax/ast_utf8_string.mli
- jscomp/syntax/ppx_entry.ml
cc @dorafmon FYI 
I happen to have some time this weekend, so I will add string interpolation
This commit did some clean up for existing interface
> Start string interpolation

- jscomp/bsb/bsb_build_util.ml
> [Docs] Fix small comment error

- docs/Manual.html
- jscomp/Makefile
- jscomp/all.depend
- jscomp/bin/all_ounit_tests.d
- jscomp/bin/all_ounit_tests.i.ml
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsb.ml
- jscomp/bin/bsdep.d
- jscomp/bin/bsdep.ml
- jscomp/bin/bsppx.d
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.d
- jscomp/bin/whole_compiler.ml
- jscomp/ounit_tests/ounit_unicode_tests.ml
- jscomp/syntax/ast_utf8_string.ml
- jscomp/syntax/ast_utf8_string_interp.ml
- jscomp/syntax/ast_utf8_string_interp.mli
- jscomp/syntax/ppx_entry.ml
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/string_interp_test.js
- jscomp/test/string_interp_test.ml
- site/docsource/OCaml-call-JS.adoc
cc @dorafmon , in case you are interested in implementation
> string interpolation

- docs/Manual.html
Ran into some trouble with this recently
> Update bs-platform version in example package.json

- Changes
- docs/Manual.html
- jscomp/bin/all_ounit_tests.i.ml
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsdep.ml
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.ml
- jscomp/core/lam_compile_external_call.ml
- jscomp/others/js_math.ml
- jscomp/ounit_tests/ounit_cmd_tests.ml
- jscomp/syntax/ast_external_attributes.ml
- jscomp/syntax/ast_ffi_types.ml
- jscomp/syntax/ast_ffi_types.mli
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/bs_qualified.js
- jscomp/test/bs_qualified.ml
- jscomp/test/test_react_case.ml
- jscomp/test/webpack_config.js
- jscomp/test/webpack_config.ml
- site/docsource/OCaml-call-JS.adoc
fix #1561
TODO: spit out a warning when "xx.yy" happens in `bs.val`
> address #1561

- Changes
- jscomp/bin/bsdep.ml
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.ml
- jscomp/core/lam_compile_external_call.ml
- jscomp/syntax/ast_external_attributes.ml
- jscomp/syntax/ast_ffi_types.ml
- jscomp/syntax/ast_ffi_types.mli
- jscomp/test/bs_qualified.js
- jscomp/test/bs_qualified.ml
- jscomp/test/ocaml_parsetree_test.js
- jscomp/test/ocaml_parsetree_test.ml
- jscomp/test/ocaml_typedtree_test.js
- jscomp/test/ocaml_typedtree_test.ml
fix #1612 
In general `x.scope0.scope1....scoepN.bla`
> support bs.scope in bs.send/bs.send.pipe/bs.set/bs.get/bs.get_index/bs.set_index

- jscomp/others/js_dict.ml
- jscomp/others/js_dict.mli
- jscomp/test/js_dict_test.js
- jscomp/test/js_dict_test.ml
- lib/js/js_dict.js
This PR extracts the changes made from @glennsl in #1445 for `Js_dict`.
**Todo:**
> Improve Js_dict

- Changes
I updates the Changes file to reflect #1604 (and fixed a typo).
> Add changes entry for #1604

- jscomp/bin/bsb.ml
- jscomp/bsb/bsb_init.ml
- jscomp/bsb/bsb_main.ml
- jscomp/bsb/bsb_templates.ml
- jscomp/bsb/templates/basic/.gitignore
> special handing "bsb -init ."

- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsb.ml
- jscomp/bin/bsdep.ml
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.ml
- jscomp/bsb/bsb_build_schemas.ml
- jscomp/ext/ext_json.ml
- jscomp/ext/ext_json_parse.ml
- jscomp/ext/ext_json_parse.mll
- jscomp/ext/ext_json_types.ml
- jscomp/ounit_tests/ounit_json_tests.ml
TODO: revert special handling of mll files
> Part II: support generators

- docs/docson/build-schema.json
- jscomp/all.depend
- jscomp/bin/all_ounit_tests.d
- jscomp/bin/all_ounit_tests.i.ml
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsb.ml
- jscomp/bin/bsb_helper.ml
- jscomp/bin/bsdep.ml
- jscomp/bin/bsppx.ml
- jscomp/bin/whole_compiler.ml
- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_config_types.ml
- jscomp/bsb/bsb_gen.ml
- jscomp/ext/literals.ml
- jscomp/ext/literals.mli
- jscomp/test/literals.js
so that 
```
"reason" : { "react-jsx" : 1/2/true/false }
```
> integrate jsx option into bsconfig

- docs/blog/index.html
- docs/index.html
- site/docsource/Build-system-support.adoc
- site/docsource/Differences-from-js_of_ocaml.adoc
- site/docsource/Exception-handling.adoc
- site/docsource/FAQ.adoc
- site/docsource/Get_started.adoc
- site/docsource/Manual.adoc
- site/docsource/OCaml-call-JS.adoc
- site/docsource/Why-bucklescript-matters-for-Javascript-platform.adoc
- site/docsource/js-lib.adoc
Passed the docs through some spell checker =D
> [Docs] Fix typos

- Changes.md
- jscomp/all.depend
- jscomp/bin/whole_compiler.ml
- jscomp/core/lam_compile.ml
- jscomp/core/lam_compile_external_obj.ml
- jscomp/core/lam_compile_external_obj.mli
- jscomp/core/lam_compile_primitive.ml
- jscomp/runtime/js.ml
- jscomp/runtime/js.mli
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/gpr_1409_test.js
- jscomp/test/gpr_1409_test.ml
- jscomp/test/test_obj_simple_ffi.js
> fix #1409, fix #1734

- jscomp/bin/whole_compiler.ml
- jscomp/core/lam_compile_external_obj.ml
- jscomp/test/gpr_1409_test.js
- jscomp/test/gpr_1409_test.ml
- jscomp/test/test_obj_simple_ffi.js
> fix optional unbox

- Changes.md
- jscomp/bin/whole_compiler.ml
- jscomp/core/lam.ml
- jscomp/core/lam_compile_group.ml
- jscomp/test/.depend
- jscomp/test/Makefile
- jscomp/test/flow_parser_reg_test.js
- jscomp/test/gpr_1409_test.js
- jscomp/test/rec_fun_test.js
- jscomp/test/rec_fun_test.ml
- jscomp/test/tscanf_test.js
> tentative fix for markup html

- jscomp/bsb/templates/react/package.json
- jscomp/bsb/templates/react/src/interop/pageReason.re
- jscomp/bsb/templates/react/src/simple/page.re
New change from reason-react 0.2.0
> New reason-react boilerplate

- jscomp/release.sh
Signed-Off-By: António N. Monteiro <anmonteiro@gmail.com>
> DEUBG -> DEBUG in jscomp/release.sh

- jscomp/README.md
- jscomp/js.sh
A couple of things tripped me up when trying to run `js.sh`.
Signed-Off-By: Jared Forsyth <jared@jaredforsyth.com>
> Add some checks and documentation to js.sh and the Readme

- jscomp/all.depend
- jscomp/bin/whole_compiler.ml
- jscomp/core/cmjdump_main.ml
- jscomp/core/js_cmj_format.ml
- jscomp/core/js_cmj_format.mli
- jscomp/core/lam_compile.ml
- jscomp/core/lam_compile_env.ml
- jscomp/core/lam_compile_env.mli
- jscomp/core/lam_pass_collect.mli
- jscomp/core/lam_stats_export.ml
- jscomp/core/lam_stats_util.ml
cc @copy
WIP: some interaction with  submodule coercion
1. Make sure the analyzer could take advantage of more serialized information
2. (todo): make sure the stored information is sound
> improve submodule-cross module arity analysis

- jscomp/all.depend
- jscomp/bin/whole_compiler.ml
- jscomp/core/lam_stats_export.ml
- jscomp/core/lam_stats_export.mli
- jscomp/test/inner_call.js
- jscomp/test/scanf_io.js
- jscomp/test/scanf_reference_error_regression_test.js
- jscomp/test/submodule_call.js
- jscomp/test/tscanf_test.js
- lib/js/filename.js
- lib/js/hashtbl.js
This PR completes the submodule arity infer
> improve submodule arity inference finished

- docs/js-demo/init.js
> fix examples menu

- .npmignore
Note we have to put both npmignore files together
> fix npm ignore issue

- site/docsource/OCaml-call-JS.adoc
Signed-Off-By: Royall Spence <royall@royall.us>
> Fix small typo

- site/docsource/Manual.adoc
I guess you will have to regenerate your site though.
> Fixed the URL of JS demo

- jscomp/all.depend
- jscomp/bin/whole_compiler.d
- jscomp/bin/whole_compiler.ml
Gonna be testing the recent commits internally!
> Check in artifacts from #1857

- jscomp/runtime/js.ml
- jscomp/runtime/js.mli
Signed-Off-By: António Nuno Monteiro <anmonteiro@gmail.com>
> Add `Js.logN` that splices its argument

- jscomp/all.depend
- jscomp/bin/all_ounit_tests.ml
- jscomp/bin/bsb.ml
- jscomp/bin/whole_compiler.ml
- jscomp/bsb/bsb_templates.ml
- jscomp/core/js_dump.ml
- jscomp/ext/ext_ident.ml
- jscomp/ext/ext_pp_scope.ml
- jscomp/ext/ext_pp_scope.mli
so that we print
```
var List$Pkg = require('./xx/list.js')
```
instead of 
```
var List$negPkg = require('./xx/list.js')
```
> clean up pp_scope, prepare better printing module names

- jscomp/all.depend
- jscomp/bin/bsb.ml
- jscomp/bin/whole_compiler.d
- jscomp/bin/whole_compiler.ml
- jscomp/bsb/bsb_templates.ml
- jscomp/bsb/templates/generator/bsconfig.json
- jscomp/bsb/templates/generator/src/test.cpp.ml
gcc is really not portable with regard to preprocessing
> fix ci issue

- jscomp/others/js_array.ml
> Deprecate Js.Array.append

- docs/Manual.html
This isn't released yet and tripped someone up. We can let this be overridden after the next release.
> [Docs] Restore nullable docs to before

- jscomp/runtime/js.ml
- jscomp/runtime/js.mli
Per offline discussion. For consistency we'll use `to[ModuleName]`.
> Change Js.toOpt to Js.toOption

- jscomp/super_errors/super_misc.ml
2e99e607cc26db2ca601dbab55902a1206070590 fixed one case but broke another. I'm turning this into a variant instead of commenting & forgetting to match a condition
> [Super errors] Fix file printing

- jscomp/Makefile
- jscomp/super_errors/README.md
- jscomp/super_errors/super_location.ml
- jscomp/super_errors/super_main.ml
- jscomp/super_errors/super_reason_react.ml
- jscomp/super_errors/super_reason_react.mli
- jscomp/super_errors/super_typecore.ml
- jscomp/super_errors/super_typemod.ml
This fixes the 3 most common RR problems
> [Super errors] Custom msgs for ReasonReact pitfalls

- jscomp/repl.js
Went through the entire stdlib and tested which ones were missing. Hopefully not many left!
> Add more missing playground modules

- docs/Manual.html
- site/docsource/OCaml-call-JS.adoc
Was reading through the FFI support and found a few places to improve.
> Improvements to the BuckleScript manual

- jscomp/reason_outcome_printer/tweaked_reason_oprint.ml
This mirrors https://github.com/facebook/reason/commit/01da2b0a278b754ff1753bedb09687ba967fa422
Should make the file easier to maintain in the medium-term
> [Reason oprint] Better header comment

- jscomp/super_errors/README.md
- jscomp/super_errors/super_location.ml
- jscomp/super_errors/super_misc.ml
> [Super errors] Fix a corner-case highlighting problem

- jscomp/Makefile
- jscomp/super_errors/super_env.ml
- jscomp/super_errors/super_location.ml
- jscomp/super_errors/super_main.ml
Fixes https://github.com/reasonml-community/error-message-improvement/issues/12
> [Super errors] Fixes wrong file name error message

- jscomp/Makefile
- jscomp/super_errors/super_location.ml
- jscomp/super_errors/super_main.ml
- jscomp/super_errors/super_pparse.ml
> Removes the lengthy "maybe this is a syntax error" message

- jscomp/super_errors/super_typetexp.ml
Fixes https://github.com/reasonml-community/error-message-improvement/issues/11
> Better unbound modules error

- site/docsource/OCaml-call-JS.adoc
Signed-off-by: Diego Marquina <d@mardie.net>
> Fixed some documentation typos

- jscomp/super_errors/super_location.ml
- jscomp/super_errors/super_misc.ml
https://github.com/BuckleScript/bucklescript/pull/2033/files?w=1
> [Super errors] Trim output when too many lines

- jscomp/test/.depend
- jscomp/test/js_promise_basic_test.js
- jscomp/test/js_promise_basic_test.ml
- jscomp/test/mt.js
- jscomp/test/mt.ml
- jscomp/test/mt.mli
For the record:
```
utf8_decode_test.ml
✓ File "utf8_decode_test.ml", line 125, characters 5-12 id 1
2165 passing (541ms)
```
lgtm
```
2167 passing (503ms)
```
> poor man test for promise

- jscomp/reason_outcome_printer/tweaked_reason_oprint.ml
The tag `[@bs]` should come after the parentheses, not before.
This also cleans up some bits so that the syncing can be a bit easier; see https://github.com/facebook/reason/pull/1484
> Fix reason outcome printer for bs tags

- jscomp/stdlib/buffer.ml
- jscomp/stdlib/camlinternalFormat.ml
- jscomp/stdlib/camlinternalOO.ml
- jscomp/stdlib/gc.ml
- jscomp/stdlib/hashtbl.ml
- jscomp/stdlib/lexing.ml
- jscomp/stdlib/nativeint.ml
- jscomp/stdlib/weak.ml
- lib/js/buffer.js
- lib/js/camlinternalFormat.js
- lib/js/camlinternalOO.js
- lib/js/gc.js
- lib/js/genlex.js
- lib/js/hashtbl.js
- lib/js/lexing.js
- lib/js/moreLabels.js
- lib/js/nativeint.js
- lib/js/weak.js
hi @ryanartecona  I made some work to patch stdlib so that only Arg, Unix depend on Sys module this means you have more freedom to work on Sys module to make it work better on Node while not affecting front-end developers
> less inter-dependency on Sys module

- jscomp/others/js_re.mli
- jscomp/test/js_re_test.js
- jscomp/test/js_re_test.ml
Fixes #2124.
@glennsl Please feel free to point out any ways to make this better, as i'm very new to OCaml and Bucklescript :) Thanks!
> Return `string option array` from Js_re.matches

- jscomp/bsb/bsb_theme_init.ml
> Tweak invalid package name message

- jscomp/bin/bsdep.ml
- jscomp/bin/bspp.ml
- jscomp/bin/bsppx.ml
- jscomp/core/js_packages_state.ml
> no deps on package map

- jscomp/bin/bsdep.ml
- jscomp/bin/bspp.ml
- jscomp/bin/bsppx.ml
- jscomp/super_errors/super_warnings.ml
> clean up super_warning, it is also future proof when add more warning number

- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/ext/ext_json.ml
- jscomp/ext/ext_json.mli
This works in conjunction with #2188
> [Reason] Config for the new syntax

- jscomp/outcome_printer/tweaked_reason_oprint.ml
Addresses https://github.com/BuckleScript/bucklescript/pull/2188/files/427909424f6baa3a89d32d27b14c1b6319bf0a64#r147300572
> [Reason] Fix outcome printer regression

- site/docsource/Build-system-support.adoc
Signed off by: Jim Tittsler <jimt@onjapan.net>
> Fix doc typos.

- docs/Manual.html
- jscomp/Makefile.shared
- jscomp/bin/Makefile
- jscomp/bin/bsb.ml
cc @jmorrell #2079 
TODO: test on windows
> [part 1] bsc compiler relocatable

- jscomp/others/js_re.mli
> add @deprecated to Js.Re.matches doc comment

- bin/bsb
> fixes #2226

- jscomp/bsb/templates/node/README.md
> npm start script does the watching.

- docs/Manual.html
- site/docsource/Installation.adoc
- site/docsource/Manual.adoc
> new installation docs

- jscomp/super_errors/super_warnings.ml
The whole sentenced sounded better
> [Super errors] Revert back to the old deprecated message

- jscomp/others/js_global.ml
- jscomp/test/js_global_test.js
- jscomp/test/js_global_test.ml
These are all part of ECMA-262
Also moved doc comments postfix
> add Js_global.(encode|decode)URI(Component)?

- jscomp/bsb/templates/basic-reason/README.md
> Fixed a wrong sub command

- jscomp/others/bs_Array.ml
- jscomp/others/bs_Array.mli
- jscomp/others/bs_Cmp.ml
- jscomp/others/bs_Cmp.mli
- jscomp/others/bs_HashMap.ml
- jscomp/others/bs_HashMap.mli
- jscomp/test/bs_hashtbl_string_test.js
- jscomp/test/bs_hashtbl_string_test.ml
- lib/js/bs_Array.js
- lib/js/bs_HashMap.js
> part3: make resize tail recursive

- jscomp/others/js_math.ml
Correct comments for `min_x` functions on Math-module
Signed-Off-By: Christian Lentfort <christian@lentfort.com>
> Correct comments

- jscomp/repl.js
> disable jsoo share feature for repl build

- jscomp/others/belt_HashMap.ml
- jscomp/others/belt_Map.ml
- jscomp/others/belt_MutableMap.ml
- jscomp/others/belt_MutableMapInt.ml
- jscomp/others/belt_MutableMapString.ml
- jscomp/others/mapm.cppo.ml
> [Belt] Change map terminology from elt to key

- jscomp/super_errors/super_reason_react.ml
- jscomp/super_errors/super_reason_react.mli
- jscomp/super_errors/super_typecore.ml
Fixes https://github.com/reasonml-community/error-message-improvement/issues/29
> [Super errors] Tweak message for trying to create a reactElement without JSX

- jscomp/super_errors/super_warnings.ml
Fixes https://github.com/reasonml-community/error-message-improvement/issues/3
> [Super errors] Better warning msg

- docs/api/Belt.Map.html
- docs/api/Belt.Set.html
- docs/api/Belt_Map.html
- docs/api/Belt_Set.html
- jscomp/others/belt_Map.mli
- jscomp/others/belt_Set.mli
> [Docs] Correctly IntCmp.comparable to Belt.Id.comparable

- jscomp/super_errors/super_reason_react.ml
- jscomp/super_errors/super_reason_react.mli
- jscomp/super_errors/super_typemod.ml
Specialize the message for each case.
Fixes https://github.com/reasonml-community/error-message-improvement/issues/55
> [Super errors] Improve the worst ReasonReact error

- jscomp/bin/reactjs_jsx_ppx_v2.bspp.ml
- jscomp/repl.js
Follow-up of #2683
Tested on Reason playground
cc @bobzhang @astrada
> Make JSX PPX also support unicode

- vendor/ocaml/.travis.yml
- vendor/ocaml/testsuite/tests/typing-gadts/pr5332.ml.reference
- vendor/ocaml/testsuite/tests/typing-gadts/pr5989.ml.reference
- vendor/ocaml/testsuite/tests/typing-gadts/pr5997.ml.reference
- vendor/ocaml/testsuite/tests/typing-gadts/pr6241.ml.principal.reference
- vendor/ocaml/testsuite/tests/typing-gadts/pr6241.ml.reference
> [compiler] fix ocaml ci (committed by @cristiano)

- jscomp/others/belt_Option.mli
Added descriptions for all functions and examples for some.
> Added documentation to Belt.Option in branch 2.2.3

- jscomp/others/belt_Option.mli
Added some blank lines as well as putting some items into a `{ul}` to make the HTML output more readable (everything was on one line before).
> Add  {ul} to make output look better

- jscomp/others/js_console.ml
Fixes #2673.
@bobzhang I'm not sure how to update the docs. happy to do it if you point me in the right direction, unless that's done only before any release?
> Add console.error and console.trace

- jscomp/others/js_json.ml
- jscomp/others/js_json.mli
> Add stringifyWithSpace to Js_json

- jscomp/bsb/bsb_ninja_gen.ml
- lib/bsb.ml
> fix raised by @bsansouci

- jscomp/others/belt_Option.mli
This should have only one file in it; the pull request with the extraneous files can be closed if this one is OK.
> Add documentation to Belt.Option.

- jscomp/others/belt_Debug.ml
> Prettier debugger output

- jscomp/all.depend
- jscomp/core/js_dump.ml
- jscomp/runtime/block.ml
- jscomp/runtime/block.mli
- lib/js/block.js
> fix variant instrumentation in debug mode

- jscomp/README.md
I ran into some issues while trying to rebuild the bucklescript playground and I believe these changes will better guide people that want to build it in the future.
> Improve the playground documentation based on recent experience

- jscomp/others/belt_Array.ml
- jscomp/others/belt_Array.mli
- jscomp/test/bs_array_test.js
- jscomp/test/bs_array_test.ml
- lib/js/belt_Array.js
Closes #2867
(I got tons of files updated but only pushed what I feel relevant - tell me if that's ok)
> Belt.Array.sliceToEnd

- jscomp/Makefile
- jscomp/all.depend
- jscomp/core/js_dump.ml
- jscomp/core/js_exp_make.ml
- jscomp/core/js_fold_basic.ml
- jscomp/core/js_long.ml
- jscomp/core/js_of_lam_block.ml
- jscomp/core/js_of_lam_block.mli
- jscomp/core/js_of_lam_option.ml
- jscomp/core/js_of_lam_variant.ml
- jscomp/core/js_op.ml
- jscomp/core/lam.ml
- jscomp/core/lam.mli
- jscomp/core/lam_analysis.ml
- jscomp/core/lam_compile_const.ml
- jscomp/core/lam_compile_primitive.ml
- jscomp/core/lam_compile_util.ml
- jscomp/core/lam_compile_util.mli
- jscomp/core/lam_print.ml
- jscomp/core/lam_tag_info.ml
- jscomp/test/test_zero_nullable.js
- lib/bsdep.ml
- lib/bsppx.ml
- lib/whole_compiler.d
Note Const_block is missed, we need remove Blk_some in downstream
> [part 6] turn on optional block path

- jscomp/others/belt_Array.ml
- jscomp/others/belt_Array.mli
- lib/js/belt_Array.js
Fixes part of #2517
https://github.com/BuckleScript/bucklescript/pull/2926/files?w=1
Is this the way to go? If it is, I'll also add it for List
> [Belt] Add Array.keepWithIndex

- jscomp/others/belt_Map.ml
- jscomp/others/belt_Map.mli
- jscomp/others/belt_MapDict.ml
- jscomp/others/belt_MapDict.mli
- jscomp/others/belt_MapInt.ml
- jscomp/others/belt_MapInt.mli
- jscomp/others/belt_MapString.ml
- jscomp/others/belt_MapString.mli
- jscomp/others/belt_internalAVLtree.ml
- jscomp/others/belt_internalAVLtree.mli
- lib/js/belt_Map.js
- lib/js/belt_MapDict.js
- lib/js/belt_MapInt.js
- lib/js/belt_MapString.js
- lib/js/belt_internalAVLtree.js
> Add Belt.Map.findFirstBy

- jscomp/all.depend
- jscomp/bsb/bsb_build_util.ml
- jscomp/bsb/bsb_build_util.mli
- jscomp/bsb/bsb_main.ml
- jscomp/bsb/bsb_theme_init.ml
- jscomp/bsb/bsb_world.ml
- lib/bsb.ml
when file or dir already exists it will continue initialization with some needed checks
fix #2945 #2500
> make bsb -init more forgiving

- lib/bsb
note the ninja verbose output is out of our control (fix #2743)
> more quiet by default

- jscomp/super_errors/super_reason_react.ml
- jscomp/super_errors/super_reason_react.mli
- jscomp/super_errors/super_typecore.ml
Solved by #2969. Specifically, by https://github.com/facebook/reason/pull/2091
> [Super errors] Remove one obsolete error

- jscomp/super_errors/super_typecore.ml
> [Super errors] Fix syntax error from #2970

- jscomp/bsb/bsb_config_parse.ml
> fix message when bs-platform version mismatch

- jscomp/others/belt_List.ml
- jscomp/others/belt_List.mli
- jscomp/test/bs_list_test.ml
> [Belt] Add reduceWithIndex

- jscomp/others/belt_Debug.ml
> fix #3047 - handle null values correctly in the devtools custom formatter

- jscomp/others/belt_List.ml
- jscomp/others/belt_List.mli
- jscomp/test/bs_list_test.ml
- lib/js/belt_List.js
Fixes #2517. This is a continuation of #2926 which added this function for Array.
> [Belt] Add List.keepWithIndex

- jscomp/others/belt_Result.mli
Have added this documentation but not generated the result yet.
> Add documentation to Belt.Result mli file.

- jscomp/others/belt_Array.ml
- jscomp/others/belt_Array.mli
- jscomp/test/bs_array_test.ml
I forgot to add the method also for `Array`s 🙃 
Fixes #3032 (again 😂)
> [Belt] Add reduceWithIndex for Arrays

- jscomp/core/js_dump.ml
- jscomp/core/js_exp_make.ml
- jscomp/core/js_fold_basic.ml
- jscomp/core/js_of_lam_block.ml
- jscomp/core/js_of_lam_float_record.ml
- jscomp/core/js_of_lam_record.ml
- jscomp/core/lam_compile_util.ml
- jscomp/core/lam_constant.ml
- jscomp/core/lam_convert.ml
- jscomp/core/lam_tag_info.ml
TODO: more tests, e.g, mutable set, duplication of record etc
> support for inline records

- jscomp/runtime/.depend
- jscomp/runtime/Makefile
- jscomp/runtime/bs_stdlib_mini.mli
- jscomp/runtime/caml_obj.ml
- jscomp/test/.depend
- jscomp/test/406_primitive_test.js
TODO: provide a customized GC module
> make runtime self contained, not relying on stdlib interface

- Makefile
- jscomp/Makefile
- jscomp/others/Makefile
- jscomp/others/belt_Array.ml
- jscomp/others/belt_MutableSet.ml
- jscomp/others/belt_MutableSetInt.ml
- jscomp/others/belt_MutableSetString.ml
- jscomp/others/belt_internalAVLset.ml
- jscomp/others/belt_internalAVLtree.ml
- jscomp/others/js_math.ml
- jscomp/others/setm.cppo.ml
- jscomp/runtime/bs_stdlib_mini.mli
- jscomp/stdlib/Makefile.shared
Now: runtime -> others -> stdlib
> remove the cycle between stdlib and runtime

- jscomp/runtime/caml_module.ml
- jscomp/stdlib-402/camlinternalMod.ml
- jscomp/test/int_hashtbl_test.js
- vendor/ocaml/bytecomp/translcore.ml
- vendor/ocaml/typing/typecore.ml
cc @OvermindDL1 this diff should generate better code when you use first class modules
> [compiler] uncury more when using first class module as function

- jscomp/compiler.ninja
- jscomp/others/build.ninja
- jscomp/others/release.ninja
- jscomp/runtime/build.ninja
- jscomp/runtime/release.ninja
- jscomp/stdlib-402/build.ninja
- jscomp/stdlib-402/release.ninja
- jscomp/test/build.ninja
- scripts/ninja.js
I need to submit a change to ninja.js later and didn't want the clutter
> [Build] Clean up whitespaces

- jscomp/others/build.ninja
- jscomp/others/js_re.mli
- jscomp/others/js_re2.mli
- jscomp/others/release.ninja
- jscomp/runtime/js.ml
- jscomp/syntax/ast_literal.ml
- jscomp/test/js_re_test.ml
- lib/bsdep.ml
- lib/bsppx.ml
- lib/js/js.js
https://github.com/BuckleScript/bucklescript/pull/3298/files?w=1
A few more and then we'll be done!
> Js.Re -> Js.Re2

- jscomp/others/js_dict.mli
Everything is in the title! :)
> Fix minor mistake in Js.Dict.values doc

- jscomp/bin/bspack.ml
- jscomp/main/js_main.ml
- lib/bsdep.ml
- lib/bspp.ml
- lib/bsppx.ml
- vendor/ocaml/typing/cmt_format.ml
- vendor/ocaml/utils/clflags.ml
- vendor/ocaml/utils/clflags.mli
> [part one] add -bs-gentype

- jscomp/super_errors/super_typemod.ml
- vendor/ocaml/typing/typemod.ml
- vendor/ocaml/typing/typemod.mli
> [Super errors] Clean up super_typemod.ml

- jscomp/super_errors/super_typetexp.ml
Unlike the previous PRs, typetexp.ml doesn't wrap and shadow the `report_error` binding we needed. We don't have to patch the compilers in this case.
> [Super errors] Clean up super_typetexp

- jscomp/super_errors/super_location.ml
Super_location was the only one left. The upstream display logic changed a little.
Tested on file with 1 warning, 2 warnings, 1 warning + 1 warning configured as error, that + another error, etc. All seems to work again.
> [Super errors] Finish upgrading

- jscomp/runtime/curry.ml
- jscomp/test/ffi_arity_test.ml
- lib/js/curry.js
- scripts/curry_gen.ml
> arity forigving

- jscomp/outcome_printer/reason_syntax_util.ml
- jscomp/outcome_printer/reason_syntax_util.mli
- jscomp/outcome_printer/tweaked_reason_oprint.cppo.ml
Small difference this time: the new synced in files use cppo now
> Sync in refmt 681c491ba760cdf3b49f92297c3dab1703682808

- jscomp/outcome_printer/reason_syntax_util.cppo.ml
- jscomp/outcome_printer/tweaked_reason_oprint.cppo.ml
> Upstream reason@3c6a9ca981f8c4902cc48c2ac9fb4d2bdb25f79a 4.02

- lib/4.02.3/bsb.ml
- lib/4.02.3/unstable/bsb_native.ml
- lib/4.06.1/bsb.ml
- lib/4.06.1/unstable/bsb_native.ml
A couple of these got added without getting built into the actual ml files.
> Building the bsb.ml files

- jscomp/syntax/reactjs_jsx_ppx.cppo.ml
- lib/4.02.3/bsdep.ml
- lib/4.02.3/bsppx.ml
> use predef option for interface externals

- jscomp/bsb/templates/react-hooks/src/Component1.re
> remove outdated example documentation on how hooks event handlers work

- docs/Manual.html
- docs/blog/index.html
Reverts BuckleScript/bucklescript#3584
Keep it until we feel confident all important stuff are indeed ported
> Revert "Remove old docs"

- scripts/ninja.js
also fix #3545
- ocaml point to local version (in case ocaml in not in PATH)
- detect camlp4, if not found, give a warning, keep going
> more defensive dev build

- jscomp/build_tests/react_ppx/bsconfig.json
- jscomp/build_tests/react_ppx/src/gpr_3695_test.re
- jscomp/syntax/reactjs_jsx_ppx.cppo.ml
- lib/4.02.3/bsdep.ml
- lib/4.02.3/bsppx.ml
Fixes #3695 
This change should only be applied with the new ast.
> make optional type changes conditional on compiler version

- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_rule.ml
- jscomp/bsb/bsb_ninja_rule.mli
- jscomp/core/ocaml_parse.ml
- jscomp/core/ocaml_parse.mli
- jscomp/depends/ast_extract.ml
- jscomp/ext/ext_filename.ml
- jscomp/ext/ext_filename.mli
- jscomp/main/js_main.ml
- lib/4.02.3/bsb.ml
- lib/4.02.3/bsb_helper.ml
- lib/4.02.3/bsdep.ml
- lib/4.02.3/bsppx.ml
- lib/4.02.3/unstable/all_ounit_tests.ml
- lib/4.02.3/unstable/bsb_native.ml
- lib/4.02.3/unstable/bspack.ml
- lib/4.02.3/unstable/native_ppx.ml
so it is only a dev dependency if only applied to dev directories
> no -impl/-intf needed for re/rei files

- docs/api/Belt.Array.html
- docs/api/Belt_Array.html
- docs/api/Belt_internalMapInt.A.html
- docs/api/Belt_internalMapString.A.html
- docs/api/Belt_internalSetInt.A.html
- docs/api/Belt_internalSetString.A.html
- docs/api/index_values.html
- jscomp/others/belt_Array.mli
Probably a typo spread across docs :D
> Docs: Rename getUnasfe to getUnsafe

- jscomp/ext/ext_ident.ml
- lib/4.02.3/unstable/all_ounit_tests.ml
Hey, first PR so let me know if I did anything wrong. This should fix #3807. Assuming I did the right thing, it seemed pretty easy to get things building following the instructions in CONTRIBUTING.
- I didn't see anywhere to add tests for how specific special characters get compiled, but if I should add tests, just let me know
- I checked in the generated changes in `./lib/`... I assume that's normal
I'm not quite sure how to confirm that the change does the right thing, but it seems pretty straightforward.
> Add question mark and ampersand to special chars

- jscomp/others/belt_Array.mli
> fix partition example

- Changes.md
- lib/4.02.3/bsdep.ml
- lib/4.02.3/bsppx.ml
- lib/4.02.3/unstable/all_ounit_tests.ml
- lib/4.02.3/unstable/bspack.ml
- lib/4.02.3/unstable/native_ppx.ml
- scripts/buildocaml.js
> update changes, fix release issues

- CONTRIBUTING.md
> Update contribution guide line && remove staled docs

- scripts/buildocaml.js
> tweak changes to buildocaml.js to make esy patch obvious

- jscomp/core/js_block_runtime.ml
- jscomp/core/js_dump.ml
- jscomp/core/js_dump_lit.ml
- jscomp/others/belt_Debug.mli
- jscomp/runtime/block.ml
- jscomp/runtime/block.mli
- jscomp/runtime/caml_chrome_debugger.ml
- jscomp/runtime/caml_chrome_debugger.mli
- lib/js/block.js
- lib/js/caml_chrome_debugger.js
> Upgrade debug mode to adapt the changes of local module representation

- jscomp/test/build.ninja
- jscomp/test/queue_402.js
- jscomp/test/queue_402.ml
- jscomp/test/queue_test.js
- jscomp/test/queue_test.ml
- jscomp/test/recursive_records_test.js
- jscomp/test/recursive_records_test.ml
cc @cristianoc 
add tests for recursive values over inline records/records/variants
> tests for queue 402 using recursive let and 406 inline records

- jscomp/runtime/bs_stdlib_mini.mli
- lib/js/belt_MapDict.js
- lib/js/belt_MapInt.js
- lib/js/belt_MapString.js
- lib/js/belt_MutableSet.js
- lib/js/belt_MutableSetInt.js
- lib/js/belt_MutableSetString.js
- lib/js/belt_SetDict.js
- lib/js/belt_SetInt.js
- lib/js/belt_SetString.js
- lib/js/belt_internalAVLset.js
- lib/js/belt_internalAVLtree.js
- lib/js/belt_internalMapInt.js
- lib/js/belt_internalMapString.js
- lib/js/caml_chrome_debugger.js
- lib/js/caml_exceptions.js
- lib/js/caml_obj.js
> Update bs_stdlib_mini for ref

- jscomp/core/lam_compile.ml
- jscomp/test/queue_402.js
- jscomp/test/recursive_records_test.js
- jscomp/test/recursive_records_test.ml
> finish caml_update_dummy prepartion

- jscomp/core/lam_eta_conversion.ml
- jscomp/test/build.ninja
- jscomp/test/gpr_3931_test.js
- jscomp/test/gpr_3931_test.ml
- jscomp/test/ocaml_typedtree_test.js
Note recursive module field access is lazily resolved
> tentative fix for #3931

- jscomp/build_tests/super_errors/expected/syntaxErrors1.re.expected
- jscomp/build_tests/super_errors/expected/syntaxErrors2.re.expected
- jscomp/build_tests/super_errors/expected/syntaxErrors3.re.expected
- jscomp/build_tests/super_errors/expected/syntaxErrors5.re.expected
This PR adds refmt 3.5.3 with reerror to Bucklescript
> Sync refmt 3.5.3

- jscomp/runtime/caml_chrome_debugger.ml
- lib/js/caml_chrome_debugger.js
cc @cristianoc 
seems my mistake in reviewing #3944 
the changes should be done in source code (.ml) instead of generated js file
Also removed some staled functions in this PR
> make changes in ml file instead

- jscomp/bsb/data_format.md
> docs about format of lib/bs/.bsbuild

- jscomp/syntax/native_ast_derive_abstract.ml
Just making a small PR following https://github.com/BuckleScript/bucklescript/pull/3762#discussion_r339385448 :D
> Fix native ast_deriving for 4.06

- jscomp/syntax/ast_exp_apply.ml
- jscomp/test/pipe_syntax.js
- jscomp/test/pipe_syntax.ml
- lib/4.06.1/bsdep.ml
- lib/4.06.1/bsppx.ml
- lib/4.06.1/unstable/native_ppx.ml
fixes https://github.com/BuckleScript/bucklescript/issues/3951
> Fix pipe first poly variant

- jscomp/ounit_tests/ounit_cmd_tests.ml
- jscomp/test/build.ninja
- jscomp/test/unboxed_attribute_test.js
- jscomp/test/unboxed_attribute_test.ml
- jscomp/test/unboxed_use_case.js
- jscomp/test/unboxed_use_case.ml
- jscomp/test/unboxed_use_case.mli
- lib/4.06.1/bsdep.ml
- lib/4.06.1/bsppx.ml
- lib/4.06.1/unstable/all_ounit_tests.ml
- lib/4.06.1/unstable/bspack.ml
- lib/4.06.1/unstable/native_ppx.ml
Todo: more tests for failing cases (recursive values)
> add unboxed support

- jscomp/test/string_set.ml
- scripts/ninja.js
- scripts/tasks.js
when start a task in vscode
we can type config/r/clean to do config build/rebuild/cleanbuild without restart
> improve dev workflow so that no restart needed in most time

- Changes.md
Forgot to update the Changes.md file (think it's quite useful to see when Reason got upgraded to a specific version)
> Update changes file

- .gitignore
- lib/bstracing
> support bstracing -C dir

- .vscode/tasks.json
- jscomp/runtime/js.ml
- jscomp/syntax/ast_util.ml
- jscomp/test/flow_parser_reg_test.js
- jscomp/test/ocaml_parsetree_test.js
- jscomp/test/ocaml_typedtree_test.js
- lib/4.06.1/bsdep.ml
- lib/4.06.1/unstable/native_ppx.ml
- lib/js/belt_internalBuckets.js
- lib/js/belt_internalSetBuckets.js
- scripts/checkUnused.js
> poor man global dead code analyzer

- jscomp/core/lam_analysis.ml
- jscomp/core/lam_compile.ml
- jscomp/core/lam_compile_primitive.ml
- jscomp/core/lam_convert.ml
- jscomp/core/lam_primitive.ml
- jscomp/core/lam_primitive.mli
- jscomp/core/lam_print.ml
- jscomp/test/build.ninja
- jscomp/test/unsafe_full_apply_primitive.js
- jscomp/test/unsafe_full_apply_primitive.ml
Note to support labels in uncurried function, we have to delay it untill application happens in the type checking level
TODO: implement current uncurry/method application on top of it
> introduce an internal unsafe primitive Pfull_apply

- jscomp/bsb/templates/react-hooks/watcher.js
- jscomp/bsb/templates/tea/watcher.js
> Grab the hostname from window.location when connecting to websocket

- Changes.md
- jscomp/build_tests/react_ppx/src/recursive_component_test.re
- jscomp/syntax/reactjs_jsx_ppx.cppo.ml
- lib/4.06.1/bsdep.ml
@bloodyowl noticed this issue. Would be great to get confirmation that it resolves for you!
> handle recursive components with ppx change

- jscomp/others/node_buffer.ml
Hi!
I think it would make sense to also expose `toString` with encodings.
What do you think?
Best
Sander
> Add Node.Buffer.toStringWithEncoding

- esy.json
- esy.lock/.gitattributes
- esy.lock/index.json
References a commit from 4.06.1+BS
> Update esy manifest

- bsb
Before:
Error: could not acquire lockfile/Users/.../.../.bsb.lock
After:
Error: could not acquire lockfile /Users/.../.../.bsb.lock
> add a space after "acquire lockfile" stderr message

- jscomp/bsb/bsb_global_backend.ml
- jscomp/bsb/bsb_global_backend.mli
- lib/4.06.1/bsb.ml
- lib/4.06.1/unstable/bsb_native.ml
> remove some unused code for bsb non native

- jscomp/build_tests/super_errors/input.js
- jscomp/super_errors/README.md
- jscomp/super_errors/super_typecore.ml
The test runners for super errors seem to be broken now. But we can fix
those later.
Tested on a demo.
> [Super errors] Embellish one new error

- jscomp/runtime/caml_obj.ml
- lib/es6/caml_obj.js
- lib/js/caml_obj.js
Reverts BuckleScript/bucklescript#4276
> Revert "change for_in impl for arrays"

- Changes.md
I figured having the original issue linked to the unit/undefined change would help anyone looking to understand more about the justifications for it 🤔
> Tweak to Changes.md

- jscomp/syntax/reactjs_jsx_ppx.cppo.ml
Reanalyze found some issues with this ppx and being able to map to the correct make function. Used it to better point to the location of the final make binding.
> force binding location on the actual make binding

- jscomp/syntax/reactjs_jsx_ppx.cppo.ml
The bs.config in react-ppx handling seems to be not correct (see #4357)
Instead of fixing it, I am thinking remove it seems to be better.
The handling was introduced to switch to jsx v2 for some legacy files in file level, now we have a more systematic file level handling, for example:
```reasonml
[@bs.config { flags : [| "-bs-jsx", "2"|] }]
```
This makes the old ad-hoc flags `[@bs.config { jsx : 2}]` not needed. This is a breaking change for people rely on the legacy jsx v2, the transition is easy, I think such breaking change is fine for version bs-platform@8 
cc @rickyvetter
> remove bs.config handling in react-jsx-ppx

- jscomp/core/js_dump.ml
- jscomp/core/js_dump_property.ml
- jscomp/ext/ext_array.ml
- jscomp/ext/ext_array.mli
- jscomp/runtime/caml_int64.ml
- jscomp/test/build.ninja
- jscomp/test/gpr_1943_test.js
- jscomp/test/gpr_1946_test.js
- jscomp/test/gpr_1946_test.ml
- lib/4.06.1/bsb.ml
- lib/4.06.1/unstable/all_ounit_tests.ml
- lib/4.06.1/unstable/bsb_native.ml
- lib/4.06.1/unstable/bspack.ml
- lib/4.06.1/unstable/native_ppx.ml
- lib/es6/caml_int64.js
- lib/js/caml_int64.js
when we found cases like
```ocaml
type t =   {  hi : nativeint ; [@bs.as "0"] lo : nativeint ; [@bs.as "1" ]  }
```
we turn it into an array instead, since it is clear that the user wants an array
> turn array like records into array when needed

- jscomp/runtime/caml_lexer.ml
- lib/es6/caml_lexer.js
- lib/js/caml_lexer.js
> clean up lexing runtime, stay close to lexing.c

- jscomp/super_errors/super_typetexp.ml
Primarily, use the actual field or constructor names for more clarity.
Also tweak the wording of the message slightly.
EDIT: sorry, I realize this has an error. I'll polish it up later today.
> Tweak error message for not found record fields/constructors

- jscomp/core/js_dump.ml
- jscomp/core/js_pass_flatten.ml
- jscomp/test/gpr_3980_test.js
- jscomp/test/gpr_4491_test.js
cc @TheSpyder 
after fixing the printer bug, optimize unneeded allocation
> optmize cases in #4491

- jscomp/common/js_config.ml
- jscomp/common/js_config.mli
- jscomp/main/js_main.ml
- jscomp/super_errors/super_typetexp.ml
- lib/4.06.1/unstable/all_ounit_tests.ml
- lib/4.06.1/unstable/bspack.ml
- lib/4.06.1/unstable/native_ppx.ml
- for res users, since the default is now non recursive, tweaked the error message as below
- some refactoring to remove the boilerplate for spellchecking
cc @chenglou 
Feel free to tweak the error message here
https://github.com/BuckleScript/bucklescript/pull/4512/files#diff-6f0ab65499e63495729ad3873a549372R41
> hint people that they may forget rec after type for res users

- jscomp/main/js_main.ml
- jscomp/test/rec_value_test.js
- jscomp/test/rec_value_test.ml
- scripts/buckle_lto.js
when we remove some seldomly used flags
be careful the compatibility with merlin
> continue cleaning up bsc flags

- jscomp/super_errors/super_warnings.ml
> [Super errors] Tweak warning indentation

- jscomp/syntax/ast_external_process.ml
- jscomp/syntax/classify_function.ml
- jscomp/test/external_ppx.js
- jscomp/test/external_ppx.ml
- jscomp/test/limits_test.js
- jscomp/test/prepend_data_ffi.ml
- lib/4.06.1/unstable/native_ppx.ml
The fix in version 8.2 brings unnecessary breakage.
The general idea is that we can not infer the type of  constant payload in bs.as, let's just not make it appear in object typing, this works due to static subtyping.
```ocaml
external ff : 
hi:int -> 
lo:(_ [@bs.as 3]) -> 
lo2:(_ [@bs.as {json|{hi:3 }|json}]) ->
_ = "" [@@bs.obj]
let u = ff ~hi:2     
```
This will work, but the inferred type is `< hi : int > Js.t`, instead of  `< hi:int, lo:int , lo2: ?type> Js.t`
> fix combination of bs.obj with bs.as

- jscomp/syntax/bs_builtin_ppx.ml
- jscomp/test/build.ninja
- jscomp/test/debug_tmp.ml
- jscomp/test/flow_parser_reg_test.js
- jscomp/test/ocaml_typedtree_test.js
- jscomp/test/type_disambiguate.js
- jscomp/test/type_disambiguate.ml
address #4612 
```ocaml
module N = struct
type t = {
a : int; 
b : int;
c : int
}
end 
let f (e : N.t) = 
let {a;b;c} = e in 
a + b +c   
```
without this patch, this will compile with an error `unbound field a`
> better data flow inference for pattern let {a,b,c} = ..

- jscomp/super_errors/super_typecore.ml
> [Super errors] New simple conversion suggestions

- scripts/ciTest.js
> add ci test for playground, it should fail

- jscomp/main/bsb_main.ml
- jscomp/stubs/ext_basic_hash_stubs.c
- lib/4.06.1/bsb.ml
> prevent multiple bsb instances running in the same directory

- jscomp/bsb/templates/basic/.gitignore
- jscomp/bsb/templates/generator/.gitignore
- jscomp/bsb/templates/node/.gitignore
> Ignore node_modules in templates generator

- jscomp/bsb/bsb_templates.ml
- jscomp/bsb/templates/react-starter/package.json
* Upgrade react related libraries and reason-react to the lastest major version.
* Upgrade webpack related libraries to the latest minor version.
* Update the loader to the latest version.
> Upgrade react-starter template

- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_config_types.ml
- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_file_groups.mli
- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/bsb/bsb_unix.ml
- jscomp/bsb/bsb_world.ml
- jscomp/bsb/bsb_world.mli
- jscomp/main/bsb_main.ml
- lib/4.06.1/bsb.ml
- lib/4.06.1/bsb.ml.d
Changes:
- Installation is fast & correct 
- No need scan the dependency directory when it is not needed, --> fast -make-world
TODO:
- windows support
> change the installation from hash_set into Queue, prepare install.ninja

- jscomp/bsb/bsb_build_util.ml
- jscomp/bsb/bsb_build_util.mli
- jscomp/bsb/bsb_clean.ml
- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_world.ml
- jscomp/main/bsb_main.ml
- lib/4.06.1/bsb.ml
address comments from https://forum.rescript-lang.org/t/call-for-testing-bs-platform-8-3-3-dev-1-better-make-world-performance/616/4?u=hongbo
> proper error message when bsconfig is missing

- jscomp/bsb/bsb_config_parse.ml
- lib/4.06.1/bsb.ml
cc @rickyvetter 
to set RES_SKIP_STDLIB_CHECK
> add an option to skip STDLIB_CHECK to work around node_modules restriction

- jscomp/others/js_re.ml
See https://github.com/rescript-lang/rescript-editor-support/issues/17
> Fix typo in docs

- jscomp/bsb/bsb_build_util.ml
- jscomp/bsb/bsb_build_util.mli
- jscomp/bsb/bsb_clean.ml
- jscomp/bsb/bsb_world.ml
- lib/4.06.1/bsb.ml
- scripts/pack.js
> toplevel pinned dependencies should trigger the build of dev dependencies

- jscomp/bsb_helper/bsb_helper_depfile_gen.ml
- lib/4.06.1/bsb_helper.ml
> clean up bsb_helper

- CONTRIBUTING.md
Update document CONTRIBUTING.md section Test
> fix issue #4880

- jscomp/bsb/bsb_templates.ml
- jscomp/bsb/templates/basic/bsconfig.json
- jscomp/bsb/templates/basic/src/demo.ml
- jscomp/bsb/templates/basic/src/demo.res
- jscomp/test/build.ninja
- jscomp/test/es6_export.js
- jscomp/test/es6_export.mjs
- jscomp/test/es6_export.ml
- jscomp/test/es6_import.js
- jscomp/test/es6_import.mjs
- jscomp/test/es6_import.ml
- lib/4.06.1/bsb.ml
- Note $$default is used for communication between rescript files. default was created to make js interop happier
> add a test case to test both nodejs and es6 format; themes default to rescript syntax

- jscomp/common/js_config.ml
- jscomp/common/js_config.mli
- jscomp/core/js_implementation.ml
- jscomp/main/js_main.ml
- jscomp/test/build.ninja
- jscomp/test/hello_res.js
- jscomp/test/hello_res.res
- jscomp/test/hello_res.resi
- lib/4.06.1/unstable/bspack.ml
- scripts/ninja.js
1. add `-as-pp` flag to work with native tools
2. add support for rescript syntax in jscomp/test
> [internal] add support for rescript syntax testing, add -as-pp for native, fix #4977

- bsb
> Don't trigger a rebuild if mjs file changes

- jscomp/build_tests/super_errors/expected/collections.re.expected
- jscomp/build_tests/super_errors/expected/highlighting2.re.expected
- jscomp/build_tests/super_errors/expected/highlighting3.re.expected
- jscomp/build_tests/super_errors/expected/highlighting5.re.expected
- jscomp/build_tests/super_errors/expected/highlighting6.re.expected
- jscomp/build_tests/super_errors/expected/modules1.re.expected
- jscomp/build_tests/super_errors/expected/modules3.re.expected
- jscomp/build_tests/super_errors/expected/moreArguments1.re.expected
- jscomp/build_tests/super_errors/expected/moreArguments2.re.expected
- jscomp/build_tests/super_errors/expected/moreArguments3.re.expected
- jscomp/build_tests/super_errors/expected/moreArguments4.re.expected
- jscomp/build_tests/super_errors/expected/primitives1.re.expected
- jscomp/build_tests/super_errors/expected/primitives10.re.expected
- jscomp/build_tests/super_errors/expected/primitives2.re.expected
- jscomp/build_tests/super_errors/expected/primitives3.re.expected
- jscomp/build_tests/super_errors/expected/primitives4.re.expected
- jscomp/build_tests/super_errors/expected/primitives5.re.expected
- jscomp/build_tests/super_errors/expected/primitives6.re.expected
- jscomp/build_tests/super_errors/expected/primitives7.re.expected
- jscomp/build_tests/super_errors/expected/primitives8.re.expected
- jscomp/build_tests/super_errors/expected/primitives9.re.expected
- jscomp/build_tests/super_errors/expected/type1.re.expected
- jscomp/build_tests/super_errors/expected/warnings3.re.expected
- jscomp/super_errors/super_code_frame.ml
This is technically a small bug from way back. The recent refactor #5013 allowed us to fix this.
> [Super errors] Add the last line of a file to the code frame

- jscomp/super_errors/super_code_frame.ml
- jscomp/super_errors/super_location.ml
> [Super errors] Various cleanups

- rescript
This PR needs extensive testing.
It tries to best to handle event spamming and duplicated events, event watcher is unreliable and platform-dependent.
It allows  multiple watchers and short lived builds work concurrently.
- question: for one short build, should we fail directly or retry ?
> allow multiple rescript build

- jscomp/main/rescript_main.ml
- lib/4.06.1/rescript.ml
Haven't added it to the main rescript help page.
Follow-up to #5135
> Tweak `init` docs for rescript CLI

- jscomp/others/belt_Array.ml
- jscomp/others/belt_Array.mli
- lib/js/belt_Array.js
This seems like an obvious omission (I went to use it and was surprised when the compiler told me it didn't exist).
Let me know if I've missed something, done something incorrectly, or if there's a better way to do this - I'm not that familiar with OCaml.
> Add flatMap to Belt.Array

- rescript
- scripts/rescript_arg.js
- scripts/rescript_dump.js
```
rescript dump src/hello.cmi
```
will try to build it and dump to readable output, currently only for cmi, in the future, we can add more
> add dump subcommand

- .circleci/config.yml
This should speed up the CI jobs.
https://circleci.com/docs/2.0/caching/#source-caching
> circleci: enable .git directory caching

- rescript
- scripts/rescript_convert.js
- scripts/rescript_dump.js
- scripts/rescript_format.js
Hopefully clears up some confusion.
> Rename bsb_exe variable to rescript_exe where it points to rescript.exe

- jscomp/core/lam_convert.ml
- jscomp/core/lam_pass_alpha_conversion.ml
- jscomp/super_errors/super_code_frame.ml
- avoid open Lexing
- tweak names
- remove one usage of Pjs_fn_make
- snapshot
> refactor: clean up one usage of Pjs_fn_make

- jscomp/core/lam_convert.ml
- jscomp/ml/lambda.ml
- jscomp/ml/lambda.mli
- jscomp/ml/printlambda.ml
- jscomp/ml/translcore.ml
- jscomp/ml/translmod.ml
- jscomp/test/mutable_uncurry_test.js
- jscomp/test/mutable_uncurry_test.ml
- remove dead code for untuplify
- remove unused argument for transl_function
- remove function_kind which does not make sense
- remove dead code
- add nested test case
- remove event_after
- snapshot
> clean up: remove unused code

- jscomp/ml/typecore.ml
- branching Pexp_record
- tweak
- tweak
- tweak
- mv check_duplicates upwards
- snapshot
> branch record type checking

- jscomp/core/lam_convert.ml
- jscomp/ml/lambda.ml
- jscomp/ml/lambda.mli
- jscomp/ml/printlambda.ml
> remove unneeded bookkeeping 

- jscomp/core/js_of_lam_block.ml
- jscomp/core/lam_compat.ml
- jscomp/core/lam_compat.mli
- jscomp/core/lam_convert.ml
- jscomp/ml/lambda.ml
- jscomp/ml/lambda.mli
- jscomp/ml/printlambda.ml
- jscomp/ml/translcore.ml
- remove unused code Fld_set_na, nice refactor
- snapshot
> cleanup: Fld_set_na is not needed any more

- jscomp/core/lam_convert.ml
- jscomp/ml/lambda.ml
- jscomp/ml/lambda.mli
- jscomp/ml/matching.ml
- jscomp/ml/printlambda.ml
- jscomp/ml/translcore.ml
- jscomp/ml/typeopt.ml
- jscomp/ml/typeopt.mli
- type specialize
- no not need array_kind
- remove Typeopt.array_pattern_kind
- remove Typeopt.array_kind
- snapshot
> not bookkeeping array_kind

- jscomp/core/lam_constant_convert.ml
- jscomp/ml/lambda.ml
- jscomp/ml/lambda.mli
- jscomp/ml/printlambda.ml
- jscomp/ml/translcore.ml
- specialize false/true
- snapshot
> specialize true/false

- jscomp/ml/typecore.ml
- refactor
- refactor
- snapshot
> clean up type checking of record duplicates

- jscomp/core/lam_analysis.ml
- jscomp/core/lam_compile_primitive.ml
- jscomp/core/lam_convert.ml
- jscomp/core/lam_primitive.ml
- jscomp/core/lam_primitive.mli
- jscomp/core/lam_print.ml
- jscomp/ml/includecore.ml
- jscomp/ml/matching.ml
- jscomp/ml/printlambda.ml
- jscomp/ml/printtyped.ml
- jscomp/ml/translcore.ml
- jscomp/ml/typecore.ml
- jscomp/ml/types.ml
- jscomp/ml/types.mli
- rename Record_float into object
- adapt Record_obj for recursive values
- adapt Pmakeblock -- for record creation it should has such information
- snapshot
> add record_obj

- jscomp/core/lam_constant_convert.ml
- jscomp/core/lam_convert.ml
- jscomp/core/record_attributes_check.ml
- jscomp/ml/lambda.ml
- jscomp/ml/lambda.mli
- jscomp/ml/matching.ml
- jscomp/ml/printlambda.ml
- jscomp/ml/translcore.ml
- jscomp/ml/translmod.ml
- Add a comment
- re-org lambda meta data info for Pmakeblock
- snapshot
> re-org block metadata

- jscomp/core/js_dump.ml
- jscomp/core/js_exp_make.ml
- jscomp/core/js_of_lam_block.ml
- jscomp/core/js_of_lam_variant.ml
- jscomp/core/js_pass_flatten_and_mark_dead.ml
- jscomp/core/lam_compile.ml
- jscomp/core/lam_compile_primitive.ml
- jscomp/core/lam_compile_util.ml
- jscomp/core/lam_constant_convert.ml
- jscomp/core/lam_convert.ml
- jscomp/core/lam_tag_info.ml
- jscomp/core/record_attributes_check.ml
- jscomp/ext/ext_array.ml
- jscomp/ml/lambda.ml
- jscomp/ml/lambda.mli
- jscomp/ml/printlambda.ml
- jscomp/ml/translcore.ml
- clean up
- pass lambda tag_info as is
Enough tag info so that record carries meta data for code generation (Record_obj)
> pass tag info as is

- jscomp/ml/oprint.ml
- jscomp/ml/outcometree.mli
- jscomp/ml/printtyp.ml
- jscomp/ml/typecore.ml
- jscomp/ml/typecore.mli
- jscomp/ml/typedecl.ml
- recognize Record_object attribute
- add outcometree support for ml syntax
- prepare turn on
- snapshot
TODO: 
- outcometree printer for res
- code generation
> prepare to turn on @obj record

- jscomp/ext/map_gen.ml
- jscomp/ext/set_gen.ml
- lib/4.06.1/rescript.ml
- lib/4.06.1/unstable/all_ounit_tests.ml
- lib/4.06.1/unstable/bspack.ml
- recognize Record_object attribute
- add outcometree support for ml syntax
- prepare turn on
- snapshot
- micro-optimize Set_gen
- micro-optmize
- snapshot
> micro-optimize trees

- jscomp/bsb/bsb_merlin_gen.ml
- jscomp/core/js_dump.ml
- jscomp/core/lam_print.ml
- jscomp/ext/ext_list.ml
- jscomp/ext/ext_list.mli
- jscomp/main/bspack_main.ml
- jscomp/main/cmij_main.ml
- jscomp/ml/ast_helper.ml
- jscomp/ml/ast_mapper.ml
- jscomp/ml/ctype.ml
- jscomp/ml/docstrings.ml
- jscomp/ml/env.ml
- jscomp/ml/matching.ml
- jscomp/ml/parmatch.ml
- jscomp/ml/printtyp.ml
- jscomp/ml/subst.ml
- jscomp/ml/translcore.ml
- jscomp/ml/translmod.ml
- jscomp/ml/typecore.ml
- jscomp/ml/typedecl.ml
- jscomp/ml/typemod.ml
- jscomp/outcome_printer/reason_syntax_util.cppo.ml
- format
- format
- add a better List.filter
- format
- format
- format
- add .ocamlformat marker
- avoid an allocation in filter
- format
- snapshot
> micro-optimization & experiment ocamlformat

- jscomp/ext/warnings.ml
- jscomp/ext/warnings.mli
- jscomp/ml/translcore.ml
- jscomp/ml/typecore.ml
- jscomp/ml/typecore.mli
- lib/4.06.1/unstable/all_ounit_tests.ml
- lib/4.06.1/unstable/bspack.ml
- remove some dead code
- remove dead code
- turn Labels_omitted from warning into Error
- snapshot
> simplify type checking for applications

- jscomp/ml/typecore.ml
- extract some common functions
- remove dead code
- snapshot
> remove dead code

- rescript
Signed-Off-By: Bence Fábián <begnoc@gmail.com>
> Fix indexing of websocket param

- jscomp/core/bs_conditional_initial.ml
- jscomp/ext/warnings.ml
- jscomp/frontend/typemod_hide.ml
- jscomp/ml/translmod.ml
- jscomp/ml/typedtree.mli
- jscomp/ml/typemod.ml
- jscomp/ml/typemod.mli
- lib/4.06.1/unstable/all_ounit_tests.ml
- lib/4.06.1/unstable/bspack.ml
- tweak: no poly compare
- remove an indirection of rescript-hide
- remove unused signature
- snapshot
> prepare work for private attributes

- jscomp/ml/ctype.ml
- jscomp/ml/ctype.mli
- jscomp/ml/typeclass.ml
- jscomp/ml/typecore.ml
- remove comments
- simplify type_let
- The guard is applied to the whole or pattern
> simplify the typing for let

- jscomp/test/res_debug.js
- jscomp/test/res_debug.res
- lib/4.06.1/whole_compiler.ml.d
- upgrade submodule
- add a test case
- snapshot
cc @IwanKaramazow 
TODO: fix the char comment
> upgrade syntax submodule

- jscomp/core/bs_conditional_initial.ml
- jscomp/main/jsoo_main.ml
- scripts/repl.js
- format
- No color for playground
- tweak build scripts
> tweak build scripts

- jscomp/ml/ctype.ml
- jscomp/ml/longident.ml
- jscomp/ml/longident.mli
- jscomp/ml/translmod.ml
- jscomp/ml/types.ml
- jscomp/ml/types.mli
- lib/4.06.1/unstable/all_ounit_tests.ml
- lib/4.06.1/unstable/bspack.ml
- scripts/local_br_clean.sh
- add a script
- add two missed comparison functions
- tweak
- use same_arg_label
- use same_record_representation
- specialize
- simplify
- simplify
- snapshot
> type checking perf improvement

- jscomp/core/js_output.ml
- jscomp/core/lam_compile.ml
- jscomp/core/lam_compile_context.ml
- jscomp/core/lam_compile_context.mli
- jscomp/ml/matching.ml
- jscomp/ml/switch.ml
- no polymorphic compare
- remove #if true
- format
- format
- format
- format
- snapshot
> better performance tweaks and format

- jscomp/core/bs_conditional_initial.ml
- jscomp/ml/transl_recmodule.ml
- jscomp/ml/transl_recmodule.mli
- jscomp/ml/translmod.ml
- jscomp/ml/translmod.mli
- lib/4.06.1/unstable/js_compiler.ml.d
- lib/4.06.1/whole_compiler.ml.d
- spin off recursive module compilation
- snapshot
> spin off recursive module translation

- jscomp/test/js_promise_basic_test.js
- jscomp/test/js_promise_basic_test.ml
> fix promise test

- package-lock.json
- package.json
Node v16 comes with npm 8 that is based on the new v2 lockfile format.
> Update package-lock to new v2 lockfile format

- .github/workflows/ci.yml
Starting the work by getting the build process to run on the new M1 runner 🚀
> Add M1 Builds

- scripts/ninja.js
I encountered the build error due to the latest change in module structure of syntax. This PR fixes the build error including the modules in `syntax/cli`
> Sync syntax submodule to current master.

- jscomp/others/belt_Map.mli
- jscomp/others/belt_MapDict.mli
- jscomp/others/belt_MapInt.mli
- jscomp/others/belt_MapString.mli
- jscomp/others/belt_MutableMap.mli
- jscomp/others/belt_MutableMapInt.mli
- jscomp/others/belt_MutableMapString.mli
> Sync docs for Belt Map, Map.Dict, Map.Int, Map.String, MutableMap, MutableMap.Int, MutableMap.String

- jscomp/build_tests/bs_dependencies_node_path_override/testcase.js
- scripts/ciTest.js
> Clean test case.

- scripts/bin_path.js
- scripts/ninja.js
- scripts/ninjaFactory.js
- scripts/prebuilt.js
https://github.com/rescript-lang/rescript-compiler/pull/5471#issuecomment-1166601567
> Fix win build

- Changes.md
- jscomp/bsb/bsb_clean.mli
- jscomp/core/lam_pass_collect.ml
- lib/4.06.1/rescript.ml
- rescript
Follow-up to https://github.com/rescript-lang/ninja/pull/3 😉
> staled -> stale

- jscomp/core/j.ml
- jscomp/core/js_analyzer.ml
- jscomp/core/js_dump.ml
- jscomp/core/js_exp_make.ml
- jscomp/core/js_exp_make.mli
- jscomp/core/js_fold.ml
- jscomp/core/js_pass_flatten_and_mark_dead.ml
- jscomp/core/js_pass_scope.ml
- jscomp/core/js_record_fold.ml
- jscomp/core/js_record_iter.ml
- jscomp/core/js_record_map.ml
- jscomp/core/js_stmt_make.ml
- jscomp/core/lam_compile_const.ml
- jscomp/test/chn_test.js
Some more cleanup likely needed in future.
Towards: https://github.com/rescript-lang/rescript-compiler/issues/5489
> Refactor: remove Unicode as it's a duplicate of Str.

- scripts/buildocaml.js
> Vendor OCaml 4.14.0 sources

- lib/4.06.1/unstable/js_playground_compiler.ml.d
- lib/4.06.1/whole_compiler.ml.d
3e8bafb596097ab303bb9641ba804c74a48d068e
> Last syntax sync before 10.0 alpha release.

- Makefile
just type make, make clean, make test
no need to remember the internal commands
> Add makefile to drive the most common commands.

- CHANGELOG.md
> Consolidate changelog into a single 10.0.

- .github/workflows/ci.yml
See https://github.com/actions/runner-images/issues/6002.
> Use the ubuntu-20.04 runner as 18.04 is deprecated

- CHANGELOG.md
- lib/4.06.1/unstable/js_compiler.ml.d
- lib/4.06.1/unstable/js_playground_compiler.ml.d
- lib/4.06.1/whole_compiler.ml.d
> sync latest syntax

- scripts/buildNinjaBinary.js
> Fix ninja build error with python3

- jscomp/others/jsxDOMStyle.ml
As requested in https://github.com/rescript-lang/rescript-react/issues/42
> JsxDOMStyle.t: add backgroundFilter prop

- scripts/ninja.js
> Remove doc_gen leftovers

- LICENSE
- README.md
- res_syntax/LICENSE
* Add information about different license (MIT) for syntax to README
* Add "Authors of ReScript"
> Update license information

- res_syntax/README.md
I left the part about syncing of super_errors as is, we need to clean this up separately later.
> Update syntax README

- res_syntax/Makefile
- res_syntax/src/res_ast_conversion.ml
- res_syntax/src/res_ast_conversion.mli
- res_syntax/src/res_core.ml
- res_syntax/src/res_parsetree_viewer.ml
- res_syntax/src/res_printer.ml
- res_syntax/src/res_scanner.ml
- res_syntax/src/res_scanner.mli
Reanalyze was deactivated when vendoring the syntax repo: the `.cmt` files are now in the root `_build` folder.
> Syntax: reactivate reanalyze

- lib/4.06.1/unstable/js_compiler.ml.d
- lib/4.06.1/unstable/js_playground_compiler.ml.d
- lib/4.06.1/whole_compiler.ml.d
- res_syntax/src/res_core.ml
- res_syntax/src/res_parser.ml
- res_syntax/src/res_parser.mli
- res_syntax/src/res_parsetree_viewer.ml
- res_syntax/src/res_printer.ml
- res_syntax/src/res_uncurried.ml
Should make it easy to experiment with a mode where everything is parsed to uncurried.
> Refactor uncurried in parsing/printing.

- .github/workflows/ci.yml
- CHANGELOG.md
See the discussion in #5834 and #5868.
> Revert to ubuntu 18.04 in CI

- CHANGELOG.md
> Update changelog in 10.1

- Makefile
- jscomp/frontend/dune
Should be `test_syntax.sh` like for `make test-syntax`.
Also fix format check
> Fix wrong test script run in Makefile

- jscomp/others/jsxDOMStyle.res
- https://github.com/rescript-lang/rescript-react/pull/86
> Add the gap property to jsxDOMStyle

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
Seems like this is useful to have in the issue template :)
> docs: Adds instructions to CONTRIBUTING for issue reproduction

- CHANGELOG.md
- jscomp/core/lam_eta_conversion.ml
- jscomp/test/async_inline.js
- jscomp/test/async_inline.res
Port of PR https://github.com/rescript-lang/rescript-compiler/pull/6010 to compiler version 10.1
> Fix:  Inline auto curried async functions produce invalid javascript

- CHANGELOG.md
- jscomp/frontend/ast_async.ml
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6013
> Fix location issue for the treatment of `async` functions

- jscomp/frontend/ast_core_type.ml
- jscomp/frontend/ast_uncurry_gen.ml
- jscomp/test/UncurriedExternals.js
- jscomp/test/attr_test.js
- jscomp/test/bs_auto_uncurry.js
- jscomp/test/bs_auto_uncurry.ml
- jscomp/test/bs_auto_uncurry_test.js
- jscomp/test/event_ffi.js
- jscomp/test/ffi_arity_test.js
- jscomp/test/flow_parser_reg_test.js
- jscomp/test/gpr_3492_test.js
- jscomp/test/mt.js
- jscomp/test/mt.ml
- jscomp/test/mt.mli
- jscomp/test/ocaml_re_test.js
- jscomp/test/pipe_send_readline.js
- jscomp/test/ppx_apply_test.js
- jscomp/test/raw_output_test.js
- jscomp/test/reasonReactRouter.js
- jscomp/test/tramp_fib.js
- jscomp/test/unit_undefined_test.js
- jscomp/test/unit_undefined_test.ml
- lib/es6/camlinternalLazy.js
- lib/js/camlinternalLazy.js
Uncurried arity 0 does not exist in .res.
It was only used in certain internal .ml files.
> Spring cleaning: remove uncurried arity 0.

- jscomp/test/demo_int_map.js
- jscomp/test/int_map.js
- jscomp/test/map_find_test.js
- jscomp/test/map_test.js
- jscomp/test/ocaml_re_test.js
- jscomp/test/offset.js
- jscomp/test/rec_module_test.js
- jscomp/test/test_for_map.js
- jscomp/test/test_int_map_find.js
- jscomp/test/test_string_map.js
- jscomp/test/ticker.js
- jscomp/test/topsort_test.js
Ran `make` and `make artifacts`. These seem to have been forgotten in some recent PR merge. Looks correct?
> update generated files

- CHANGELOG.md
I've finally managed to migrate to rescript v11 using the build from master, so there shouldn't be any more blocking issues.
> Update changelog (prepare for rc 3 release)

- CHANGELOG.md
- rescript
> Fix watch exiting on error

- .github/workflows/ci.yml
website_update_playground.sh was missing as there was no checkout step in publish.
> Fix publish

- docs/docson/build-schema.json
Intentionally PR to master, because that's where the build schema is drawn from.
> Adapt build schema to new generic JSX transform

- CHANGELOG.md
- jscomp/syntax/src/jsx_common.ml
- jscomp/syntax/tests/ppx/react/expected/newtype.res.txt
- jscomp/syntax/tests/ppx/react/newtype.res
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6625
> Fix local type variables breaking react components in uncurried mode

- scripts/makeArtifactList.js
Fixed this error from CI and local
> Fix the makeArtifactList script to be less sensitive to NPM version

- .github/workflows/ci.yml
- Makefile
- scripts/copyExes.js
- scripts/moveArtifacts.sh
Simplified and even more speedup!
> CI: do not wait for rewatch build before starting compiler build

- jscomp/test/belt_list_ntest.js
- jscomp/test/bigint_test.js
- jscomp/test/bs_set_int_test.js
- jscomp/test/chn_test.js
- jscomp/test/earger_curry_test.js
- jscomp/test/float_test.js
- jscomp/test/gpr_1667_test.js
- jscomp/test/gpr_5218_test.js
- jscomp/test/int32_test.js
- jscomp/test/int64_mul_div_test.js
- jscomp/test/int64_test.js
- jscomp/test/js_json_test.js
- jscomp/test/js_string_test.js
- jscomp/test/lazy_test.js
- jscomp/test/ocaml_re_test.js
- jscomp/test/poly_variant_test.js
- jscomp/test/queue_test.js
- jscomp/test/random_test.js
- jscomp/test/record_debug_test.js
- jscomp/test/tramp_fib.js
Leftover from previous PR, most likely #6983.
> Commit JS output changes

- runtime/Stdlib_Bool.resi
A small part of https://github.com/rescript-lang/rescript/issues/7546.
Does this need a changelog entry?
> Add docstrings for StdLib_Bool

- rewatch/src/build/parse.rs
Upstreams https://github.com/rescript-lang/rewatch/pull/166.
Closes #7563
> Rewatch: fix non-unicode stderr

- rewatch/src/build/deps.rs
Upstreams https://github.com/rescript-lang/rewatch/pull/165
> Rewatch: don't add deps to modules that are in packages that are not a dependency

- CHANGELOG.md
- rewatch/src/build.rs
> Show deprecation warnings for local deps only
