rescript-lang/rescript

CHANGELOG.md
commit: ac56ff7e00bcfde6e7830a05b3f65a7e9723a9d4
Fixes https://github.com/rescript-lang/rescript-compiler/issues/5654
=> Sync syntax to latest master.

CHANGELOG.md
Fixes https://github.com/rescript-lang/rescript-compiler/issues/5635
=> Sync latest syntax master, with fix for location in JSX V4.

jscomp/ml/typecore.ml
Fix an issue where a wrong error (empty record not annotated) was issues when  `{}` has type a record without optional fields.
Improve error message when mandatory fields are missing, suggesting it could be a component.
=> Improve error message for missing props.

scripts/install.js
After #5673, we are using `python3` to build ninja in local dev (from the ninja subfolder in the repo), but not in npm package postinstall (from `vendor/ninja.tar.gz`).
We should use `python3` in this case, too. For consistency and because many newer systems only have `python3` in the path, not `python`.
=> Use python3 for building ninja in all cases

CHANGELOG.md, docs/docson/build-schema.json, jscomp/bsb/bsb_package_specs.ml, jscomp/ext/ext_js_suffix.ml, jscomp/ext/literals.ml, lib/4.06.1/bsb_helper.ml, lib/4.06.1/rescript.ml, lib/4.06.1/unstable/all_ounit_tests.ml
- `.bs.mjs`, `.bs.cjs` to fill the gap between `.bs.js` and `.mjs`
- ~~`.res.js`, `.res.mjs`, `.res.cjs` to assist BS → ReScript rebranding~~
=> Add extra variants for suffixes in bsconfig.json

jscomp/others/jsxDOM.ml
* Add missing DOM props from rescript-react issues and PRs
* Add fix from #5702
=> Add some missing DOM props

.github/workflows/ci.yml, .github/workflows/get_artifact_info.js, .github/workflows/get_package_info.js
Got rid of all warnings coming from our scripts.
The few remaining ones are coming from Github's download artifact action and need to be fixed there.
=> CI: replace deprecated set-output command with GITHUB_ENV

CHANGELOG.md, jscomp/core/lam_compile_main.ml, jscomp/core/lam_compile_main.pp.ml
=> Fix .bs.js timestamp being reset to 1970-01-01 when there are warnings

CHANGELOG.md, jscomp/ml/typecore.ml
Reverts rescript-lang/rescript-compiler#5744
The fix is hard to reason about, I have a cleaner fix coming
The root cause is that when we try to give a counter example for pattern match, it generates int instead of char
=> Revert "Fix issue where exhaustiveness check for pattern matching char was no…"

jscomp/gentype_tests/typescript-react-example/package-lock.json, jscomp/gentype_tests/typescript-react-example/src/JSXV4.gen.tsx
=> Update genType snapshot tests.

CHANGELOG.md, scripts/rescript_arg.js, scripts/rescript_format.js
Fixes #4780.
This PR also fixes a few bugs:
- the last line of `rescript format` usage was not being displayed
- there was a mix of sync and async functions with side effects which led to conditions (hasError) not waiting for the variable to be indeed properly set
=> Check formatting

res_syntax/cli/JSXV4.md
Bring this last change done after importing the syntax repo: https://github.com/rescript-lang/syntax/pull/719
=> Update JSX V4 docs.

CHANGELOG.md, res_syntax/CHANGELOG.md, res_syntax/src/res_core.ml, res_syntax/src/res_parsetree_viewer.ml, res_syntax/src/res_printer.ml, res_syntax/tests/parsing/grammar/expressions/expected/arrow.res.txt, res_syntax/tests/ppx/react/expected/fileLevelConfig.res.txt, res_syntax/tests/ppx/react/expected/forwardRef.res.txt, res_syntax/tests/ppx/react/expected/innerModule.res.txt, res_syntax/tests/ppx/react/expected/topLevel.res.txt, res_syntax/tests/printer/expr/asyncAwait.res, res_syntax/tests/printer/expr/expected/asyncAwait.res.txt
Moved https://github.com/rescript-lang/syntax/pull/683
Regarding issue https://github.com/rescript-lang/rescript-compiler/issues/5735
=> Simplify parsing and printing attributes of function and arguments

CHANGELOG.md, res_syntax/src/res_core.ml, res_syntax/tests/parsing/grammar/expressions/expected/uncurried.res.txt, res_syntax/tests/printer/expr/asyncAwait.res, res_syntax/tests/printer/expr/expected/asyncAwait.res.txt
Interpret the arity of uncurried functions explicitly so this is a unary function:
```
(. x) => y => x+y
```
The parser adds braces to the body to make this explicit.
This is a breaking change, but only for code that is not formatted. And solves the lack of idempotency in https://github.com/rescript-lang/rescript-compiler/pull/5794
=> Interpret arity of uncurried explicitly.

CHANGELOG.md, res_syntax/src/res_core.ml, res_syntax/src/res_printer.ml, res_syntax/tests/printer/expr/ToUncurried.res, res_syntax/tests/printer/expr/expected/ToUncurried.res.txt
Add `@@toUncurried` to the file and reformat. The file will turn into uncurried syntax.
=> Support automatic conversion to uncurried syntax via @@toUncurried and reformat

CHANGELOG.md, res_syntax/cli/reactjs_jsx_v4.ml, res_syntax/tests/ppx/react/expected/v4.res.txt, res_syntax/tests/ppx/react/v4.res
=> JSX V4: allow uncurried `make` function and treat it as usual

CHANGELOG.md, res_syntax/cli/reactjs_jsx_v4.ml, res_syntax/tests/ppx/react/expected/forwardRef.res.txt, res_syntax/tests/ppx/react/forwardRef.res
=> Fix uncurried forwardRef component

CHANGELOG.md, res_syntax/cli/reactjs_jsx_v4.ml, res_syntax/tests/ppx/react/expected/v4.res.txt, res_syntax/tests/ppx/react/v4.res
=> Fix the external uncurried make function support for JSX V4

res_syntax/README.md, res_syntax/cli/dune, res_syntax/cli/res_cli.ml, res_syntax/scripts/bootstrap.sh, res_syntax/scripts/test.sh
Currently, both the compiler and the syntax have an executable named "rescript".
This will lead to a conflict when we merge everything into a single dune project.
Therefore, rename the "rescript" executable in the syntax repo to "res_parser".
=> Rename syntax cli from "rescript" to "res_parser"

CHANGELOG.md, jscomp/frontend/ast_core_type.ml, jscomp/frontend/ast_external_process.ml, jscomp/ml/typedecl.ml, jscomp/test/UncurriedExternals.js, jscomp/test/UncurriedExternals.res, jscomp/test/bs_rest_test.js
Preserve arity during type checking, and reconstruct it during external attributes processing in the front-end.
=> Uncurried support for externals part 2

CHANGELOG.md, res_syntax/src/res_parens.ml, res_syntax/src/res_parsetree_viewer.ml, res_syntax/src/res_parsetree_viewer.mli, res_syntax/src/res_printer.ml, res_syntax/tests/printer/expr/UncurriedByDefault.res, res_syntax/tests/printer/expr/expected/UncurriedByDefault.res.txt, res_syntax/tests/printer/expr/expected/callback.res.txt
They did not print the same way as curried ones.
=> Fix issue in printing uncurried callbacks.

CHANGELOG.md, res_syntax/src/res_core.ml, res_syntax/tests/parsing/grammar/expressions/UncurriedByDefault.res, res_syntax/tests/parsing/grammar/expressions/expected/UncurriedByDefault.res.txt, res_syntax/tests/parsing/grammar/expressions/expected/uncurried.res.txt, res_syntax/tests/printer/expr/UncurriedByDefault.res, res_syntax/tests/printer/expr/expected/UncurriedByDefault.res.txt
In `@foo (. x) => 3` the attribute `@foo` went outside `Js.Fn.I1 ` instead of the function contained inside.
=> Fix formatting uncurried functions with attributes.

CHANGELOG.md, jscomp/frontend/ast_attributes.ml, jscomp/frontend/ast_attributes.mli, jscomp/frontend/ast_exp_apply.ml, jscomp/frontend/ast_uncurry_apply.ml, jscomp/frontend/ast_uncurry_apply.mli, jscomp/test/UncurriedExternals.js, jscomp/test/UncurriedExternals.res, jscomp/test/reactTestUtils.js, jscomp/test/uncurried_cast.js, res_syntax/src/res_core.ml, res_syntax/src/res_parsetree_viewer.ml, res_syntax/src/res_parsetree_viewer.mli, res_syntax/src/res_printer.ml, res_syntax/tests/parsing/grammar/expressions/UncurriedByDefault.res, res_syntax/tests/parsing/grammar/expressions/expected/UncurriedByDefault.res.txt, res_syntax/tests/parsing/grammar/expressions/expected/apply.res.txt, res_syntax/tests/parsing/grammar/expressions/expected/argument.res.txt, res_syntax/tests/parsing/grammar/expressions/expected/arrow.res.txt, res_syntax/tests/parsing/grammar/expressions/expected/async.res.txt, res_syntax/tests/parsing/grammar/expressions/expected/binary.res.txt, res_syntax/tests/parsing/grammar/expressions/expected/uncurried.res.txt, res_syntax/tests/parsing/grammar/typexpr/expected/uncurried.res.txt, res_syntax/tests/parsing/infiniteLoops/expected/equalAfterBinaryExpr.res.txt, res_syntax/tests/parsing/recovery/expression/expected/infinite.res.txt, res_syntax/tests/printer/expr/expected/UncurriedByDefault.res.txt
- Don't emit arity 0 for uncurried functions and types
- Get around the front-end's special treatment of application with `()` as zero-arity application, by using  annotation `@res.uapp` for uncurried applications and have the compiler front-end treat it specially.
- Don't distinguish between types `(. ) => int` and `(. unit) => int` or in uncurried notation, between `() => int` and `unit=>int`.
- Don't distinguish between `foo(.)` and `foo(. e)`, both unary applications
- Don't distinguish between `(. ) => 3` and `(. x) => x+1` both unary function definitions
This brings the uncurried subset of the language closer to the curried one.
=> Parser/Printer: unify uncurried functions of arity 0, and of arity 1 taking unit.

CHANGELOG.md, jscomp/frontend/ast_core_type_class_type.ml, jscomp/frontend/bs_builtin_ppx.ml, jscomp/test/UncurriedExternals.js, jscomp/test/UncurriedExternals.res
Both in types in externals and in function definitions, the `@this` annotation now ignores uncurried types. In any case, the processing replaces the type (and the function definition) with some internal representation of method types (and of methods).
This is so when switching to uncurried mode, the code does not need changing.
=> Add support for uncurried @this

.github/workflows/ci.yml
When a commit is pushed to a branch and CI starts a build for it, auto-cancel the previous build for that branch.
=> CI: auto-cancel previous build when new one is started

jscomp/frontend/ast_exp_apply.ml, jscomp/frontend/ast_uncurry_apply.ml, jscomp/frontend/ast_uncurry_apply.mli
This is an extra check that existing uncurried tests still work. Later, they can be converted to .res.
=> Make legacy uncurried apply for .ml use new uncurried application.

.github/workflows/ci.yml
To prevent red builds on the master branch, only cancel previous builds for pull requests.
=> Cancel previous builds for pull requests only

CHANGELOG.md, jscomp/core/lam_pass_remove_alias.ml, jscomp/test/arity_deopt.js, jscomp/test/async_inline.js, jscomp/test/async_inline.res, jscomp/test/attr_test.js, jscomp/test/bs_rest_test.js, jscomp/test/internal_unused_test.js, jscomp/test/ppx_apply_test.js, jscomp/test/uncurried_cast.js, jscomp/test/uncurried_pipe.js, jscomp/test/uncurry_glob_test.js, jscomp/test/uncurry_test.js
Inlining is generally safe, but if one treats uncurried application just like curried one, calls to the Curry runtime might be generated. This PR only acts when the inlining is actually triggered.
=> Inline uncurried application when it is safe

CHANGELOG.md, jscomp/ml/typecore.ml, jscomp/test/UncurriedExternals.js, jscomp/test/bs_splice_partial.js
Primitives are treated specially in the type checker, so that when fully applied, no function is generated. With uncurried application, primitives are wrapped with eta expansion before being used, because the encoding via `Js.Internal.opaqueFullApply` disables the special treatment by the type checker. This PR treats uncurried application of primitives like curried application, to help `Lam` compilation produce better code instead of leaving eta-expanded functions in the output.
=> Treat uncurried application of primitives like curried application

CHANGELOG.md, jscomp/build_tests/super_errors/expected/fieldNotOptional.res.expected, jscomp/build_tests/super_errors/fixtures/fieldNotOptional.res, jscomp/ml/typecore.ml, jscomp/ml/typecore.mli
=> Print error message when `?` is used for non-optional fields.

scripts/copyExes.js
Windows CI was failing if there was a change to the syntax repo as `copyExe.js` is invoked again by `make test-syntax` in that case.
=> Fix Windows CI

CHANGELOG.md, res_syntax/src/reactjs_jsx_v4.ml, res_syntax/tests/ppx/react/aliasProps.res, res_syntax/tests/ppx/react/expected/aliasProps.res.txt
=> Fix build error where aliasing argument to `_` in make function with jsx v4

jscomp/ext/ext_basic_hash_stubs.c
See https://github.com/ocaml/ocaml/pull/11255.
=> Fix a warning when compiling the C stubs with OCaml 5

CHANGELOG.md, res_syntax/src/res_core.ml, res_syntax/tests/ppx/react/expected/spreadProps.res.txt, res_syntax/tests/ppx/react/spreadProps.res
This PR fixes https://github.com/rescript-lang/rescript-compiler/issues/5882
=> Fix parsing not atomic expression in spread props of JSX

jscomp/ml/typecore.ml, jscomp/super_errors/super_typecore.ml
This is not an error anymore since the introduction of partial application in https://github.com/rescript-lang/rescript-compiler/pull/5805
See: https://github.com/rescript-lang/rescript-compiler/issues/5888
=> Remove errors for curried application of uncurried functions.

jscomp/build_tests/super_errors/expected/uncurried_expected.res.expected, jscomp/build_tests/super_errors/fixtures/uncurried_expected.res, jscomp/ml/typecore.ml, jscomp/super_errors/super_typecore.ml
See https://github.com/rescript-lang/rescript-compiler/issues/5888
=> Restore error where uncurried type is expected.

CHANGELOG.md, jscomp/build_tests/super_errors/expected/non_function_uncurried_apply.res.expected, jscomp/build_tests/super_errors/fixtures/non_function_uncurried_apply.res, jscomp/ml/ast_uncurried.ml, jscomp/ml/typecore.ml
This is an old standing issue still present.
When something which is not a function is applied in an uncurried way, the error message leaks the internal representation of uncurried types.
See https://github.com/rescript-lang/rescript-compiler/issues/5888
=> Uncurried internal representation escapes in error message.

CHANGELOG.md, jscomp/frontend/ast_core_type.ml, jscomp/frontend/ast_external_process.ml, jscomp/test/UncurriedExternals.js, jscomp/test/UncurriedExternals.res
So existing externals can be used without change in uncurried mode, without giving an error. That said, the `@uncurry` annotation becomes redundant in those cases.
=> Support `@uncurry` externals with uncurried types.

CHANGELOG.md, jscomp/ml/typecore.ml, jscomp/test/record_regression.js, jscomp/test/record_regression.res
=> Support {} for empty inlined record literals and types

CHANGELOG.md, res_syntax/src/reactjs_jsx_v4.ml, res_syntax/tests/ppx/react/expected/mangleKeyword.res.txt, res_syntax/tests/ppx/react/mangleKeyword.res
This PR fixes dropping the attributes from the arguments and core_type in the make function or make primitive in JSX v4.
It can fix issue #5904 either.
=> Fix dropping attributes of props in JSX v4

jscomp/others/jsxDOM.res
Changes from https://github.com/reasonml/reason-react/pull/603
See https://html.spec.whatwg.org/multipage/links.html#link-type-preload for when this can be used. For example:
```html
<link rel="preload" as="style" href="..." />
```
=> Added `as` property to DOM props

res_syntax/src/reactjs_jsx_ppx.ml
Fixes https://github.com/rescript-lang/rescript-compiler/issues/5927 for the master branch.
=> Fix jsx mode being ignored when set via @@jsxConfig

scripts/rescript_dump.js, scripts/rescript_postinstall.js
Simplify the postinstall script and provide better error messages.
Do not explicitly limit supported operating systems here. The user will get a corresponding error message anyway when no binary is found for the platform. Also this prepares us for supporting user-provided binaries for exotic platforms.
=> Clean up postinstall script

bsc, scripts/bin_path.js
If we want to include binaries for additional platforms/architectures in the npm package (Linux arm64 would be the next candidate), we need to think about the bin path / directory name for those.
Currently we are supporting the following architectures:
* x64: darwin, linux, windows
* arm64: darwin
and we have some special logic in place to use "darwinarm64" for darwin on arm64.
To generalize while keeping compatible with the existing naming, we can use the following rule:
* For architecture x64, the directory name is just the platform name.
* For all other architectures, it is platform name + architecture name.
=> Prepare bin_path logic for more platforms/architectures

scripts/test_syntax.sh
Github Actions is starting to use macOS 12 for `macos-latest` by default, see https://github.com/actions/runner-images/issues/6384.
However, macOS 12 does not have the `realpath` utility. This was causing builds to fail. This PR adds a workaround for that.
=> Fix CI-build on macos-latest

CHANGELOG.md, jscomp/build_tests/super_errors/expected/await.res.expected, jscomp/build_tests/super_errors/fixtures/await.res, jscomp/frontend/bs_builtin_ppx.ml, jscomp/test/async_await.js, jscomp/test/async_await.res
Fixes https://github.com/rescript-lang/rescript-compiler/issues/5925
`await` can appear anywhere unless it's under a non-async function.
=> Add support for toplevel await.

CHANGELOG.md, jscomp/ml/typecore.ml, jscomp/test/uncurried_default.args.js, jscomp/test/uncurried_default.args.res
Functions with optional named arguments normally require a final unit (or some other unnamed argument) to specify the end of supplied arguments: https://rescript-lang.org/docs/manual/latest/function#optional-labeled-arguments
With uncurried functions, the number of arguments is fixed, and there is no such ambiguity.
This PR supports the use of optional named arguments without a final unit.
For example:
```res
let foo = (. ~x=3, ~y) => x+y
```
can now be applied omitting `x` as
```res
let n = foo(. ~y=11)
```
There's one special case where all arguments are optional:
```res
let allOpt = (. ~x=3, ~y=4) => x+y
```
this can be applied without arguments as follows
```res
let z = allOpt(. )
```
Note that this application `foo(. )` normally supplies a single argument of type `unit`. However, the …
=> Support optional named arguments without a final unit in uncurried functions.

jscomp/ml/typedecl.ml, res_syntax/src/reactjs_jsx_v4.ml, res_syntax/tests/ppx/react/expected/aliasProps.res.txt, res_syntax/tests/ppx/react/expected/commentAtTop.res.txt, res_syntax/tests/ppx/react/expected/externalWithCustomName.res.txt, res_syntax/tests/ppx/react/expected/fileLevelConfig.res.txt, res_syntax/tests/ppx/react/expected/interface.res.txt, res_syntax/tests/ppx/react/expected/interface.resi.txt, res_syntax/tests/ppx/react/expected/interfaceWithRef.res.txt, res_syntax/tests/ppx/react/expected/interfaceWithRef.resi.txt, res_syntax/tests/ppx/react/expected/mangleKeyword.res.txt, res_syntax/tests/ppx/react/expected/newtype.res.txt, res_syntax/tests/ppx/react/expected/optimizeAutomaticMode.res.txt, res_syntax/tests/ppx/react/expected/removedKeyProp.res.txt, res_syntax/tests/ppx/react/expected/topLevel.res.txt, res_syntax/tests/ppx/react/expected/typeConstraint.res.txt, res_syntax/tests/ppx/react/expected/v4.res.txt
This PR fixes the #5936. Now it shows the error with loc.
The message is not a bit kind yet, but the typechecker would not distinguish whether it is a type parameter of props type or not.
=> Add loc to each props in JSX4

CHANGELOG.md, res_syntax/src/reactjs_jsx_v4.ml, res_syntax/tests/ppx/react/expected/forwardRef.res.txt
This PR fixes https://github.com/rescript-lang/rescript-compiler/issues/5957. The only case of the lowercase & classic mode keeps the loc and others are missing. This PR add the missing the loc of JSX call expression into all cases.
=> Add the missing loc of jsx call expression

.github/workflows/ci.yml, CHANGELOG.md
Changelog entry belongs to 10.1.2, not 10.1.1.
Merging this into a new branch 10.1.2_release as work has already continued on 10.1_release.
=> Update/fix changelog for 10.1.2

CHANGELOG.md, res_syntax/src/reactjs_jsx_v4.ml, res_syntax/tests/ppx/react/expected/uncurriedProps.res.txt, res_syntax/tests/ppx/react/uncurriedProps.res
This PR fixes #5969 
This change keeps the attributes of the argument in the make function and removes the unnecessary optional attr from the core_type as the type parameter. So it prevents that uncurried functions were incorrectly converting the type of a prop given as a default value. The test has no diff with this PR, because the current master branch doesn't have an issue with it due to works regarding the uncurried as default
=> JSX4: Fix missing attributes from props type

CHANGELOG.md, jscomp/ml/translcore.ml, jscomp/test/async_inline.js, jscomp/test/async_inline.res
Nested curried functions are combined into one, and the async inner function is not generated. This PR Avoids combining nested functions when they are async.
Fixes https://github.com/rescript-lang/rescript-compiler/issues/5980
=> Fix issue with nested async functions

CHANGELOG.md, jscomp/frontend/bs_builtin_ppx.ml, jscomp/napkin/CHANGELOG.md
This is a port of the compiler part of https://github.com/rescript-lang/rescript-compiler/pull/5982 to 10.1.
=> Fix issue with async context and locally abstract types

CHANGELOG.md, jscomp/frontend/bs_builtin_ppx.ml, res_syntax/src/res_parsetree_viewer.ml, res_syntax/tests/printer/expr/asyncAwait.res, res_syntax/tests/printer/expr/expected/asyncAwait.res.txt, res_syntax/tests/printer/expr/expected/newtype.res.txt
To fix the printer, the async internal representation via an attribute needs to be preserved on functions starting with a locally abstract type. For this reason, annotations cannot be placed individually on the first locally abstract type, if that's how the function starts. Some printer tests of functions starting with an abstract type have changed because of this.
Fixes https://github.com/rescript-lang/rescript-compiler/issues/5974
=> Fix issue with async and locally abstract types

CHANGELOG.md, jscomp/core/lam_eta_conversion.ml, jscomp/test/async_inline.js, jscomp/test/async_inline.res
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6007
=> Fix:  Inline auto curried async functions produce invalid javascript

CHANGELOG.md, jscomp/frontend/ast_async.ml
Fixes https://github.com/rescript-lang/rescript-vscode/issues/698
=> Fix location issue for the treatment of `async` functions

CHANGELOG.md, res_syntax/src/res_comments_table.ml, res_syntax/src/res_printer.ml, res_syntax/tests/printer/expr/expected/switch.res.txt, res_syntax/tests/printer/expr/switch.res
Formatter adds a blank line after braced `case`, which seems to be a regression introduced in v10
```res
switch foo {                             
| 1 => {
Js.log(1)
Js.log(2)
} 
| 2 => Js.log(3)
}
```
=> Fix formatting of `switch` expressions that contain brace `cases` inside

CHANGELOG.md, jscomp/gentype/Annotation.ml
Port of https://github.com/rescript-lang/rescript-compiler/pull/5903 to v10.1
=> GenType: check annotations also in module types.

CHANGELOG.md, res_syntax/src/reactjs_jsx_ppx.ml, res_syntax/src/reactjs_jsx_v3.ml, res_syntax/src/reactjs_jsx_v4.ml, res_syntax/tests/ppx/react/expected/aliasProps.res.txt, res_syntax/tests/ppx/react/expected/commentAtTop.res.txt, res_syntax/tests/ppx/react/expected/defaultValueProp.res.txt, res_syntax/tests/ppx/react/expected/fileLevelConfig.res.txt, res_syntax/tests/ppx/react/expected/firstClassModules.res.txt, res_syntax/tests/ppx/react/expected/forwardRef.res.txt, res_syntax/tests/ppx/react/expected/interface.res.txt, res_syntax/tests/ppx/react/expected/interfaceWithRef.res.txt, res_syntax/tests/ppx/react/expected/mangleKeyword.res.txt, res_syntax/tests/ppx/react/expected/nested.res.txt, res_syntax/tests/ppx/react/expected/newtype.res.txt, res_syntax/tests/ppx/react/expected/noPropsWithKey.res.txt, res_syntax/tests/ppx/react/expected/optimizeAutomaticMode.res.txt, res_syntax/tests/ppx/react/expected/removedKeyProp.res.txt, res_syntax/tests/ppx/react/expected/sharedProps.res.txt, res_syntax/tests/ppx/react/expected/topLevel.res.txt, res_syntax/tests/ppx/react/expected/typeConstraint.res.txt, res_syntax/tests/ppx/react/expected/uncurriedProps.res.txt, res_syntax/tests/ppx/react/expected/v4.res.txt, res_syntax/tests/ppx/react/nested.res
Fixes https://github.com/rescript-lang/rescript-compiler/issues/5975
The issue is due to a combination of:
1) when a component let make = body is transformed, first the body is transformed, then when transformStructureItem4 is called, the body is transformed again
2) @react.component is left after the PPX transformation
Because of this, in the case of nested components, the transformed inner components is transformed again by transformStructureItem4, but it should not as it's been desugared already.
It would be enough to change either one, to avoid the error with nested components, but this PR handles both aspects.
=> Fix issue with JSX V4 when components are nested

.github/workflows/ci.yml
[setup-ocaml 2.0.11](https://github.com/ocaml/setup-ocaml/releases/tag/v2.0.11) contains the following change:
> Don't install Cygwin's git or mercurial packages (reduces cache by ~90MB).
(see also https://github.com/ocaml/setup-ocaml/pull/648)
In our CI script, we are setting up the git config as follows for Windows:
```
git config --global core.autocrlf false
git config --global core.eol lf
```
With the Git Windows client (already installed in the runner image) used instead of Cygwin's git, this causes the following error when running `git diff` later on in the CI process:
```
Run git diff --exit-code lib/js lib/es6
fatal: bad boolean config value 'false
' for 'core.autocrlf'
```
I am therefore pinning the setup-ocaml version to 2.0.10 for now.
=> Downgrade setup-ocaml to fix Windows CI issue

jscomp/test/float_test.js, jscomp/test/float_test.ml
=> test(float): more test cases for generic and non-generic comparisons

CHANGELOG.md, docs/JSXV4.md, jscomp/test/alias_default_value_test.js, jscomp/test/alias_default_value_test.res, res_syntax/src/reactjs_jsx_v4.ml, res_syntax/tests/ppx/react/aliasProps.res, res_syntax/tests/ppx/react/expected/aliasProps.res.txt, res_syntax/tests/ppx/react/expected/defaultValueProp.res.txt, res_syntax/tests/ppx/react/expected/firstClassModules.res.txt, res_syntax/tests/ppx/react/expected/newtype.res.txt, res_syntax/tests/ppx/react/expected/uncurriedProps.res.txt, res_syntax/tests/ppx/react/newtype.res
This
```res
@react.component
let foo = (~x, ~y=3+x, ?z) => ...
```
was generating
```res
({props: props<_, _, _>) => {
let x = props.x
let y = switch props.y {
| None => 3 + x
| Some(y) => y
}
let z = props.z
...
```
now it generates instead
```res
({x, ?y, ?z}: props<_, _, _>) => {
let x = x
let y = switch y {
| None => 3 + x
| Some(y) => y
}
let z = z
...
```
the different in generated code is that bindings such as `let x = props.x` are not present in the `js` output.
=> Improve code generated for default arguments in JSX V4

.github/workflows/ci.yml
This reverts commit e9b20aeae707b57f7ca5d9f3b351cc18990ce2e3.
We want to be on the latest setup-ocaml version, as the new [ocaml-setup 2.0.12](https://github.com/ocaml/setup-ocaml/releases/tag/v2.0.12) now also uses the official OPAM mingw repo instead of the deprecated and outdated fork fdopen/opam-repository-mingw.
=> Use latest setup-ocaml again as Windows git config issue is fixed

CHANGELOG.md, jscomp/build_tests/super_errors/expected/jinterp.res.expected, jscomp/build_tests/super_errors/fixtures/jinterp.res, jscomp/frontend/ast_utf8_string_interp.ml, jscomp/stdlib-406/arg.ml, jscomp/stdlib-406/printexc.ml, lib/4.06.1/unstable/all_ounit_tests.ml
Deprecate unsafe ``` j`$(a)$(b)` ``` interpolation
=> Deprecate unsafe "j" string interpolation

jscomp/bsc/rescript_compiler_main.ml, jscomp/ml/clflags.ml, jscomp/ml/clflags.mli, res_syntax/src/res_driver.ml, res_syntax/src/res_driver.mli, res_syntax/src/res_multi_printer.ml, res_syntax/src/res_multi_printer.mli
For debugging purposes, don't stop the compiler after parse errors are encountered. This lets you take a look at the parse tree produced after parse errors, or format in the presence of errors.
=> Add internal bsc option `ignore-parse-errors`

CHANGELOG.md, jscomp/build_tests/super_errors/expected/unicode_location.res.expected, jscomp/build_tests/super_errors/fixtures/unicode_location.res, res_syntax/src/res_core.ml, res_syntax/src/res_parser.ml, res_syntax/src/res_scanner.ml, res_syntax/src/res_scanner.mli
When some unicode characters are present on a line, the existing encoding of positions, based on number of bytes since line start, is incorrect. This can be seen in e.g. error messages picked up in the editor (or on the command-line).
This PR takes unicode into account. Even though the ocaml locations are byte-based, one can trick the system by encoding as `pos_cnum`:
```  (number of bytes from file start to line start) + (number of utf16 code units since line start) ```
Since the compiler's printer performs a subtraction, the utf16 character position is shown. Notice that editors, vscode in particular, show you something in "Col", but its internal commands expect correct utf16 character which is different.
=> Make internal encoding of locations aware of unicode

.github/workflows/ci.yml
It seems the compiler binaries (other than the statically linked Linux binary) were built with the "dev" profile, i.e. without the `-O3 -unbox-closures` flags.
=> Build compiler binaries with release profile

jscomp/bsb_exe/dune, jscomp/bsb_helper_exe/dune, jscomp/dune, jscomp/jsoo/dune, jscomp/ounit_tests/dune, res_syntax/benchmarks/dune, res_syntax/cli/dune, res_syntax/testrunner/dune
Enable building the playground compiler using
```sh
dune build --profile browser
```
When trying to use it following the instructions in https://github.com/rescript-lang/rescript-compiler/blob/master/CONTRIBUTING.md#playground-js-bundle-api, it currently gives `The module or file Pervasives can't be found.` This is because of the missing cmij cache, will address that in a separate PR at a later time.
=> jsoo build with "dune build --profile browser"

CHANGELOG.md, res_syntax/src/res_core.ml, res_syntax/tests/printer/expr/Uncurried.res, res_syntax/tests/printer/expr/expected/Uncurried.res.txt
Desugar the semantics of `|>` in uncurried mode so existing curried code still compiles. But the code will stop using `|>` after formatting.
For example: `3 |> add3(1,2)` would not compile when `add3` has 3 arguments. But after desugaring, the third argument is added.
=> Add support for `|>` in uncurried mode by desugaring it

CHANGELOG.md, jscomp/ml/ctype.ml, jscomp/test/UncurriedAlways.js, jscomp/test/UncurriedAlways.res
Subtyping from uncurried to curried functions was not working when the expected curried function was under a type definition. This would give type errors on components that take a component type as prop.
=> Make subtyping in uncurried mode work past type definitions.

CHANGELOG.md, jscomp/ml/ctype.ml, jscomp/stdlib-406/pervasivesU.res, jscomp/stdlib-406/pervasivesU.resi, jscomp/test/UncurriedAlways.js, jscomp/test/UncurriedAlways.res, lib/es6/pervasivesU.js, lib/js/pervasivesU.js, res_syntax/src/reactjs_jsx_v3.ml, res_syntax/src/reactjs_jsx_v4.ml
This change does not seem strictly necessary, and it's a bit invasive. E.g. the editor integration needs to be adapted.
But eventually, we'll want this in, as otherwise e.g. hover on the `make` would show a curried function.
=> Make components actually uncurried functions in uncurried mode.

CHANGELOG.md, jscomp/core/js_exp_make.ml, jscomp/test/caml_format_test.js, jscomp/test/ext_filename_test.js, jscomp/test/int64_mul_div_test.js, jscomp/test/mario_game.js, jscomp/test/template.js, lib/es6/arg.js, lib/js/arg.js
Now that `j` interpolation is gone, string append can be optimized in the back-end.
Fixes https://github.com/rescript-lang/rescript-compiler/issues/5521
=> Improve code generated for template literals.

.github/workflows/ci.yml, package.json, packages/artifacts.txt, scripts/moveArtifacts.sh
This PR adds building Linux arm64 binaries to the CI process. Like the Linux x64 binaries, these are statically linked and therefore need to be built in an Alpine-based Docker container. For this, I extended the Docker image used for CI (https://github.com/rescript-lang/docker-rescript-ci-build) to be multi-platform (x64 + arm64).
As GitHub Actions currently does not provide an ARM-based Linux runner and running in QEMU is too slow, the Linux arm64 builds are performed on a [BuildJet](https://buildjet.com/for-github-actions) ARM 2 vCPU runner. The costs for that runner are covered  by the ReScript Association as set up by @ryyppy.
This extends the list of supported platforms for which pre-built binaries are included in the `rescript` npm package to
* macOS x64
* macOS arm64
* Linux x64 …
=> CI: build statically linked Linux arm64 binaries

CHANGELOG.md, jscomp/core/js_exp_make.ml, jscomp/core/js_stmt_make.ml, jscomp/frontend/ast_attributes.ml, jscomp/frontend/ast_payload.ml, jscomp/frontend/ast_payload.mli, jscomp/gentype/Annotation.ml, jscomp/gentype/GenTypeCommon.ml, jscomp/gentype/TranslateCoreType.ml, jscomp/gentype/TranslateTypeDeclarations.ml, jscomp/gentype_tests/typescript-react-example/src/MoreVariants.gen.tsx, jscomp/gentype_tests/typescript-react-example/src/Variants.gen.tsx, jscomp/ml/lambda.ml, jscomp/ml/lambda.mli, jscomp/test/variantsMatching.gen.tsx, jscomp/test/variantsMatching.js, jscomp/test/variantsMatching.res
This needs to be in sync with the compiler's runtime representation annotations.
=> GenType: handle @as(_) in variant declarations.

.github/workflows/ci.yml, package.json, packages/artifacts.txt, scripts/makeArtifactList.js, scripts/moveArtifacts.sh
Currently, our macos-arm Github actions runner is down, preventing builds from completing.
Therefore, deactivate the macos-arm platform until the runner is back up.
=> Deactivate macos-arm builds for now

.github/workflows/ci.yml, package.json, packages/artifacts.txt, scripts/bin_path.js, scripts/makeArtifactList.js, scripts/moveArtifacts.sh
macos-arm build were deactivated temporarily because our self-hosted Github actions runner was out of order.
We now have a new one, so we can reenable macos-arm builds.
=> CI: reactivate macos-arm builds

jscomp/core/js_exp_make.ml, jscomp/core/js_exp_make.mli, jscomp/core/lam_compile.ml, jscomp/test/UntaggedVariants.js
See https://github.com/rescript-lang/rescript-compiler/pull/6103#issuecomment-1501357056
=> Untagged variants: use Array.isArray

jscomp/core/js_exp_make.ml, jscomp/test/UntaggedVariants.js, jscomp/test/UntaggedVariants.res
There are cases where literals can overlap with blocks.
e.g. string literals with type string, or null with type object
Fixes: https://github.com/rescript-lang/rescript-compiler/issues/6123
=> Untagged variants: fix pm with overlap.

CHANGELOG.md, res_syntax/src/res_parens.ml, res_syntax/tests/printer/expr/UncurriedByDefault.res, res_syntax/tests/printer/expr/expected/UncurriedByDefault.res.txt
See https://github.com/rescript-lang/rescript-compiler/issues/6141
=> Fix formatting of uncurried function with constraint on return type.

res_syntax/src/res_parsetree_viewer.ml, res_syntax/tests/printer/expr/UncurriedByDefault.res, res_syntax/tests/printer/expr/expected/UncurriedByDefault.res.txt
Fix https://github.com/rescript-lang/rescript-compiler/pull/6148
=> Fix PR 6148

CHANGELOG.md, jscomp/ml/typedecl.ml, jscomp/test/DotDotDot.js, jscomp/test/DotDotDot.res
This does 2 things:
1. Fixes an issue where the fields being optional wasn't propagated through the new record type spread functionality. Before this, any optional field from a record that was then spread onto another record would no longer be optional.
2. Adds a commented out test for a case where the parser breaks as we're spreading a single type only, with no additional fields, as in copying the record to a new identical record. I _think_ that's supposed to work?
=> Record definition spread issues

CHANGELOG.md, jscomp/build_tests/super_errors/expected/record_type_spreads.res.expected, jscomp/build_tests/super_errors/fixtures/record_type_spreads.res, jscomp/ml/typedecl.ml
Closes https://github.com/rescript-lang/rescript-compiler/issues/6150
=> Fix record type spread loc

CHANGELOG.md, jscomp/ml/ctype.ml
This commit adds the necessary checks to ensure compatibility between the "as" attributes of corresponding fields when determining subtype relationships between record types. The code now verifies that the string payloads of the "as" attributes in matching fields are equal. If they are not equal, the subtype relationship is considered invalid. This change improves the accuracy and robustness of the subtype checking mechanism when dealing with record types that utilize custom "as" attributes.
See https://github.com/rescript-lang/rescript-compiler/issues/6158
=> Fixed subtype checking for record types with "@as" attributes

jscomp/ml/ast_uncurried.ml, res_syntax/tests/printer/expr/Uncurried.res, res_syntax/tests/printer/expr/expected/Uncurried.res.txt
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6094
=> Fix issue with formatting comment on labelled argument in uncurried mode

CHANGELOG.md, res_syntax/src/res_core.ml, res_syntax/src/res_grammar.ml, res_syntax/src/res_parsetree_viewer.ml, res_syntax/src/res_parsetree_viewer.mli, res_syntax/src/res_printer.ml, res_syntax/tests/printer/expr/UncurriedByDefault.res, res_syntax/tests/printer/expr/expected/UncurriedByDefault.res.txt
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6165
This PR introduces a new surface syntax for partial application of uncurried functions in ReScript. The syntax allows developers to partially apply uncurried functions more easily and concisely using the ... token in argument lists. The implementation includes changes to the parser, grammar, and printer to handle the new syntax properly.
```res
@@uncurried
let add = (a, b, c) => a + b + c
let ptl1 = add(1, ...)
let result = ptl1(2, 3) // result will be 6
```
This example demonstrates the new syntax for partial application of the uncurried add function.
=> Add surface syntax for partial application of uncurried functions

CHANGELOG.md, package.json, scripts/rescript_format.js
=> Make "rescript format" work with node 10 again and set "engines" field

jscomp/frontend/bs_builtin_ppx.ml, jscomp/test/Import.js, jscomp/test/Import.res, res_syntax/src/res_core.ml, res_syntax/src/res_grammar.ml, res_syntax/src/res_printer.ml, res_syntax/tests/parsing/grammar/expressions/await.res, res_syntax/tests/parsing/grammar/expressions/expected/await.res.txt
```rescript
// for value
let forEach = await @a @b Js.Import(Belt.List.forEach)
// for module
module M = await @a @b Belt.List
```
=> Add syntax surface, module type name and tests for dynamic import

CHANGELOG.md, jscomp/ml/ast_uncurried.ml, jscomp/ml/translcore.ml, jscomp/ml/typecore.ml, jscomp/test/UncurriedAlways.js, jscomp/test/UncurriedAlways.res
Partial application for uncurried functions used normal application. There's an issue with the code generated in the presence of labeled arguments, as the function generated is curried.
This PR changes the translation from typed ast to lambda for the uncurried partial application case, by writing a single function with all the leftover arguments. So it correctly represents an uncurried function.
Fixex https://github.com/rescript-lang/rescript-compiler/issues/6164
=> Fix partial application for uncurried functions with labeled args

jscomp/core/j.ml, jscomp/core/js_dump.ml, jscomp/core/js_exp_make.ml, jscomp/core/js_exp_make.mli, jscomp/core/js_stmt_make.ml, jscomp/core/js_stmt_make.mli, jscomp/core/lam_compile.ml, jscomp/core/lam_compile_const.ml, jscomp/core/lam_constant_convert.ml, jscomp/core/lam_print.ml, jscomp/frontend/lam_constant.ml, jscomp/frontend/lam_constant.mli, jscomp/ml/ast_untagged_variants.ml
This is a cleanup of the type definitions and code for untagged variants.
No semantic change.
=> Refactor untagged logic

CHANGELOG.md, jscomp/others/js.ml, jscomp/others/js_json.ml, jscomp/others/js_json.mli, jscomp/others/js_null.ml, jscomp/others/js_null.mli, jscomp/others/js_null_undefined.ml, jscomp/others/js_null_undefined.mli, jscomp/others/release.ninja, jscomp/runtime/js.ml, jscomp/test/custom_error_test.js, jscomp/test/js_json_test.js
This changes 3 type definitions in the stdlib:
1. `Js.Json.t` is now an untagged variant representing valid JSON
2. `Js.nullable` is now an untagged variant representing `Value('a) | Null | Undefined`
3. `Js.null` is now an untagged variant representing `Value('a) | Null`
I'm trying to do as little as possible here, and the rest will be done in `Core`. But, in order to be able to make using these types smooth, I'd like the source definitions to be in here so it can be reused everywhere.
I've opted to only do `nullable` in the global `Js` scope of all of the nullable types (`null`, `undefined` etc). I'm very much open to feedback here, but my reasoning is that that's the most important one, and having multiple definitions with `Value`/`Null`/`Undefined` constructors is going to create a …
=> Unboxed variants stdlib types

CHANGELOG.md, jscomp/ml/ast_untagged_variants.ml, jscomp/ml/matching.ml, jscomp/ml/translcore.ml, jscomp/ml/typeopt.ml, jscomp/ml/typeopt.mli, jscomp/test/UntaggedVariants.js, jscomp/test/UntaggedVariants.res
The compiler's logic for unboxing options assumes that variant types cannot hold the `undefined` value.
This PR updates the logic taking into account the custom representation and untagged.
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6222
=> Fix option unboxing logic in the presence of untagged variants

.github/stale.yml
This repo has stalebot configured to mark issues older than 720 days as stale and then close them after 7 days of inactivity.
However, there is a long list of exempt labels defined that causes obsolete issues from as early as 2016 to still remain open.
This PR removes that exempt labels list.
=> Remove stalebot exemptions

CHANGELOG.md, jscomp/syntax/src/res_printer.ml, jscomp/syntax/tests/printer/modExpr/expected/structure.res.txt, jscomp/syntax/tests/printer/modExpr/structure.res
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6212
=> Fix printing of local module with type.

CHANGELOG.md, jscomp/bsc/rescript_compiler_main.ml
Fixes #6242 
Related #6199 
This PR revives the compiler's `-bs-super-errors` flag and deprecates it. Actually, it can be called a deprecation of the flag because super_errors is removed but merged into normal errors. This allows you to avoid build errors if your dependent packages still use that flag.
=> Deprecate -bs-super-errors flag for backward compat

CHANGELOG.md, docs/JSXV4.md, jscomp/syntax/src/reactjs_jsx_v4.ml, jscomp/syntax/tests/ppx/react/expected/fragment.res.txt, jscomp/syntax/tests/ppx/react/expected/noPropsWithKey.res.txt, jscomp/syntax/tests/ppx/react/expected/removedKeyProp.res.txt, jscomp/syntax/tests/ppx/react/fragment.res, packages/artifacts.txt
Fixes #6234 
This PR modifies the JSX4 implementation to accommodate the change of React fragment's `'children` type to `React.element` https://github.com/rescript-lang/rescript-react/pull/94. The main changes are as follows:
* JSX4 classic
1. Using `React*` instead of `ReactDOM*`
2. Adding an empty record as a prop for `React.createElementVariadic`
```res
let _ = React.createElementVariadic(
React.fragment,
{}, // along with type change of React.fragment
[ReactDOM.createDOMElementVariadic("div", []), ReactDOM.createDOMElementVariadic("div", [])],
)
```
3. ~Adding `React.array` for children of fragment~
* JSX4 automatic:
1. Adding a missing `React.array` for children of fragment
~Side change: `make test-syntax` wouldn't build the compiler, so I've changed it to build compiler first and …
=> React fragment's children type change and JSX4 adaptation

.github/workflows/ci.yml, jscomp/core/js_name_of_module_id.ml, jscomp/ml/cmt_format.ml
This fixes some warnings for the playground compiler build and adds it to CI to prevent breakage of the playground build in the future.
It does not automatically run the upload to the CDN yet. (Still to be discussed under what conditions this should be run.)
=> Build playground compiler in CI

.github/workflows/ci.yml, CONTRIBUTING.md
CI will now also be triggered when tags of the form "v*" are pushed, and the playground bundle will automatically be uploaded for such tag builds.
This means that future version tags will have to be e.g. "v11.0.0-beta.1" instead of just "11.0.0-beta.1". This is so that we can still create other tags without causing playground compiler uploads.
The process is not tested yet, I will only be able to test it when creating the next beta release.
=> Automatically upload playground compiler to CDN on version tag builds

CHANGELOG.md, jscomp/syntax/src/res_outcome_printer.ml
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6263
```res
We've found a bug for you!
tst.res:4:13-22
2 │ 
3 │ let foo = (x: array<_>) => ()
4 │ let x = foo(a => a + 1)
5 │ 
This has type: _ => _
Somewhere wanted: array<'b>
```
=> Fix issue where uncurried type internals leak in type error.

CHANGELOG.md, jscomp/core/js_exp_make.ml, jscomp/frontend/ast_core_type.ml, jscomp/frontend/ast_external_process.ml, jscomp/gentype/EmitType.ml, jscomp/gentype_tests/typescript-react-example/bsconfig.json, jscomp/gentype_tests/typescript-react-example/package-lock.json, jscomp/gentype_tests/typescript-react-example/src/Unboxed.gen.tsx, jscomp/gentype_tests/typescript-react-example/src/Unboxed.res, jscomp/ml/ast_uncurried.ml, jscomp/ml/ast_untagged_variants.ml, jscomp/syntax/src/react_jsx_common.ml, jscomp/syntax/src/res_parens.ml, jscomp/syntax/src/res_printer.ml, jscomp/test/UntaggedVariants.js, jscomp/test/UntaggedVariants.res
This was done at speed: need to double check that there are no corner cases missing.
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6278
TODO:
=> Add support for functions in untagged variants.

CHANGELOG.md, jscomp/build_tests/super_errors/expected/RecordInclusion.res.expected, jscomp/build_tests/super_errors/fixtures/RecordInclusion.res, jscomp/ml/includecore.ml
Speed up record inclusion check.
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6284
Record inclusion check (between implementation and interface) is quadratic.
Example:
```res
module M : {
type t<'a, 'b, 'c> = {x:int, y:list<('a, 'b)>, z:int}
} = {
type t<'a, 'b, 'c> = {x:int, y:list<('a, 'c)>, z:int}
}
```
The existing algorithm tries to instantiate type parameters. It only reports an error if there is an inconsistency. This requires solving type equations involving many types at once.
To give an accurate error message, the first problematic field is reported (in this case `y`). So the type equations are checked again and again with size 1, 2, ...n where n is the number of fields. (Plus the type parameters).
This is quadratic and is problematic for records of ~1K …
=> Speed up record inclusion check.

CHANGELOG.md, jscomp/ml/ast_untagged_variants.ml
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6140
=> Untagged variants: consider regexp as an object type.

CHANGELOG.md, jscomp/core/js_exp_make.ml, jscomp/test/UntaggedVariants.js, jscomp/test/UntaggedVariants.res
From https://github.com/rescript-lang/rescript-compiler/issues/6108
=> Example of complex pattern for untagged variant.

jscomp/syntax/src/res_printer.ml, jscomp/syntax/tests/printer/expr/UncurriedByDefault.res, jscomp/syntax/tests/printer/expr/expected/UncurriedByDefault.res.txt
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6299
@cristianoc I'm not very familiar with the parser/printer, so I'm unsure whether this is a good/acceptable approach to solve the problem. Would appreciate some feedback on that.
=> ensure trailing comma is never printed after ... for partial application

CHANGELOG.md, jscomp/build_tests/super_errors/expected/variant_to_variant_coercion.res.expected, jscomp/build_tests/super_errors/expected/variant_to_variant_coercion_as.res.expected, jscomp/build_tests/super_errors/expected/variant_to_variant_coercion_tag.res.expected, jscomp/build_tests/super_errors/expected/variant_to_variant_coercion_unboxed.res.expected, jscomp/build_tests/super_errors/fixtures/variant_to_variant_coercion.res, jscomp/build_tests/super_errors/fixtures/variant_to_variant_coercion_as.res, jscomp/build_tests/super_errors/fixtures/variant_to_variant_coercion_tag.res, jscomp/build_tests/super_errors/fixtures/variant_to_variant_coercion_unboxed.res, jscomp/core/matching_polyfill.ml, jscomp/ml/ast_uncurried.ml, jscomp/ml/ast_uncurried_utils.ml, jscomp/ml/ast_untagged_variants.ml, jscomp/ml/ctype.ml, jscomp/ml/record_coercion.ml, jscomp/ml/variant_coercion.ml, jscomp/test/VariantCoercion.js, jscomp/test/VariantCoercion.res
Allow coercing between variants which have the same exact constructors. We need to ensure that the runtime representation exactly matches as we coerce. The following restrictions are therefore in place:
* Both variants must have the same configuration for @unboxed and @tag
* Each constructor pair must have the same configuration of @as
=> Exploring variant-to-variant coercion

CHANGELOG.md, jscomp/others/js_json.res, jscomp/others/js_json.resi, jscomp/test/js_json_test.res, lib/es6/js_json.js, lib/js/js_json.js
This PR fixes an issue with existing Js.Json.kind types shadowing the variant constructor of Js.Json.t types.
=> Fix shadowing Js.Json.t with type kind

jscomp/syntax/src/res_printer.ml, jscomp/syntax/tests/printer/expr/expected/templateLiteral.res.txt, jscomp/syntax/tests/printer/expr/templateLiteral.res
=> Fix printing of type constraints in template literal substitutions

CHANGELOG.md, jscomp/syntax/src/res_outcome_printer.ml, jscomp/syntax/src/res_printer.ml, jscomp/syntax/tests/oprint/expected/oprint.resi.txt, jscomp/syntax/tests/oprint/oprint.res
=> Fix outcome printing of uncurried higher order function types

CHANGELOG.md, jscomp/core/js_dump.ml, jscomp/core/js_dump_import_export.ml, jscomp/core/js_dump_import_export.mli, jscomp/test/default_export_test.js, jscomp/test/es6_export.js, jscomp/test/es6_export.mjs, jscomp/test/es6_import.js, jscomp/test/es6_import.mjs, jscomp/test/escape_esmodule.js, jscomp/test/key_word_property.js, lib/es6/js_option.js, lib/js/js_option.js
Closes https://github.com/rescript-lang/rescript-compiler/issues/4906#issuecomment-1637042291.
* The compiler exports any invalid identifier as `$$<identifierName>`. For example, `let else = "hello"` is valid ReScript, but not valid JS because else is a keyword. Therefore, you couldn't export `else` from a JS file, even if it's valid ReScript. So, the compiler prepends `$$` to any identifier it thinks might be invalid. And via that, it also exports the identifier as `$$<identifierName>`. The alternative would be to not export those identifiers at all, which doesn't really make sense.
* However, `default` is a special case that might just be possible to support, because we're always adding a dedicated default export whenever we see `default`. So, even if `$$default` isn't exported anymore, …
=> Don't export $$default

CHANGELOG.md, jscomp/build_tests/super_errors/expected/component_missing_prop.res.expected, jscomp/build_tests/super_errors/expected/variant_spread_inline_records.res.expected, jscomp/build_tests/super_errors/fixtures/component_missing_prop.res, jscomp/ml/typecore.ml, jscomp/ml/typecore.mli
Whenever there's a missing property in a record, we optimistically tell the user this might be a component. While that is great, we're _always_ printing it for any record. 
This diff applies a simple heuristic ("is the record called props?") when deciding to print the message about this being a component or not.
=> Conditionally print message about record possibly being component

CHANGELOG.md, jscomp/build_tests/super_errors/expected/component_missing_prop_test.res.expected, jscomp/build_tests/super_errors/expected/wrong_name_component_prop.res.expected, jscomp/build_tests/super_errors/expected/wrong_name_record_field.res.expected, jscomp/build_tests/super_errors/fixtures/component_missing_prop_test.res, jscomp/build_tests/super_errors/fixtures/wrong_name_component_prop.res, jscomp/build_tests/super_errors/fixtures/wrong_name_record_field.res, jscomp/ml/typecore.ml
This flips the order of the error message parts for the "wrong name" error message. This is to make things clearer. Instead of starting with the _definition_ of the thing we're looking for, we start with what's wrong, and _then_ print the definition. 
This makes things clearer in general, but it especially improves the situation for React components with a large amount of props, or with props with types that are verbose.
React component before:
```
This record expression is expected to have type
Component.props<
string,
string,
string,
string,
string,
string,
string,
string,
string,
>
The field nonExistant does not belong to type Component.props
```
After:
```
The field nonExistant does not belong to type Component.props
This record expression is expected to have type
Component.props< …
```
=> Flip order of error message for wrong name

CHANGELOG.md, jscomp/build_tests/super_errors/expected/polyvariant_name_formatting.res.expected, jscomp/build_tests/super_errors/fixtures/polyvariant_name_formatting.res, jscomp/core/bs_conditional_initial.ml, jscomp/gentype/EmitType.ml, jscomp/ml/ctype.ml, jscomp/ml/printtyp.ml, jscomp/ml/printtyp.mli, jscomp/ml/typetexp.ml, jscomp/syntax/src/res_printer.ml, jscomp/syntax/src/res_printer.mli
Fixes a few places where polyvariant names were still printed in OCaml syntax.
=> print polyvar tag names in ReScript syntax

CHANGELOG.md, jscomp/syntax/src/res_outcome_printer.ml
The outcome printer was deciding whether something is uncurried or not in its own way. Probably just an oversight when centralizing how uncurried config is resolved. I changed it to resolve the uncurried config the same way as the rest of the code does.
This might fix a few issues we've had with formatting being with dots even when it shouldn't be. Hopefully.
=> Fix outcome printer in uncurried mode

jscomp/ml/printtyp.ml
Backport from the editor tooling. Skips printing `PervasivesU` just like `Pervasives` is skipped.
=> strip PervasivesU the same way Pervasives is stripped from paths

jscomp/build_tests/weird_names_not_found_bug/bsconfig.json
There were two conflicting PRs:
https://github.com/rescript-lang/rescript-compiler/pull/6366
https://github.com/rescript-lang/rescript-compiler/pull/6367
=> Fix master tests

CHANGELOG.md, jscomp/syntax/src/reactjs_jsx_v4.ml, jscomp/syntax/tests/ppx/react/defaultValueProp.res, jscomp/syntax/tests/ppx/react/expected/aliasProps.res.txt, jscomp/syntax/tests/ppx/react/expected/defaultValueProp.res.txt, jscomp/syntax/tests/ppx/react/expected/uncurriedProps.res.txt, jscomp/test/alias_default_value_test.js
Fixes #6374 #6375 
* build error when the prop has default value with same name
```res
module C2 = {
let a = "foo"
@react.component
let make = (~a=a) => React.string(a) // build error
}
```
* build error when prop has default value and type annotation
```res
module C3 = {
@react.component
let make = (~disabled as everythingDisabled: bool=false) => {
React.string(everythingDisabled ? "true" : "false")
}
}
```
=> Fix JSX V4 build error when component props have the default value with same name

CHANGELOG.md, jscomp/ext/js_reserved_map.ml
https://bun.sh/ adds `Bun` as global object. This reserves that names to that modules cannot accidentally clash.
=> add Bun as reserved name

jscomp/ml/ast_untagged_variants.ml
This can be cleaned up now that we expand the types.
=> clean up type lookup in instanceof untagged variants

jscomp/gentype_tests/typescript-react-example/package-lock.json, package-lock.json, package.json
Also, pin dev dependencies versions, so they are not updated by themselves.
=> Remove unused rollup from dependencies

rescript
I want to do a few fixes in the file, so I've decided to start with a lil clean up.
++ Display build time in the non-TTY mode
=> Bin clean up

CHANGELOG.md, jscomp/gentype/TranslateStructure.ml, jscomp/syntax/src/res_printer.ml, jscomp/syntax/tests/printer/expr/expected/callback.res.txt, jscomp/syntax/tests/printer/expr/expected/smartPipe.res.txt, jscomp/syntax/tests/printer/expr/smartPipe.res
This PR is an alternative to #6387
Fixes #6380
=> Smart linebreak printer for pipe chains

CHANGELOG.md, jscomp/bsb_exe/rescript_main.ml, rescript
Fixed dependencies reinitialization on every save in watch mode.
Before:
After:
Also:
- Actualized help for commands
- Started showing the compile time for `rescript build` command without watch mode
- Pass through the `-verbose` flag to builds in watch mode
What I want to do next:
- Fix the build needed condition.
- Resolve the problems with duplicated builds (existed before the changes)
- Enable watch mode for pinned dependencies 🤔
- Update documentation
=> ReScript cli clean up + watcher fix

CHANGELOG.md, jscomp/frontend/ast_external_process.ml, jscomp/gentype/TranslateStructure.ml, jscomp/syntax/tests/ppx/react/expected/mangleKeyword.res.txt, jscomp/syntax/tests/ppx/react/mangleKeyword.res, jscomp/test/external_ppx.js, jscomp/test/external_ppx.res
After we removed field mangling, it happened that it was not possible to migrate to rescript@11 because rescript-relay relied on it to support queriend data having names as reserved keywords. So, as an alternative solution for the field mangling, I think we should allow creating field aliases in the obj ppx, as it works in other places.
@zth Will you be able to update rescript-relay to use `@as` instead of prefixing reserved keywords with underscore? Or should I do this? It's currently the only blocker for us to start using rescript@11 at Carla.
=> Add @as support for obj ppx

CHANGELOG.md, jscomp/build_tests/super_errors/expected/math_operator_string.res.expected, jscomp/build_tests/super_errors/fixtures/math_operator_string.res, jscomp/ml/error_message_utils.ml
=> Improve error message when concatenating strings

CHANGELOG.md, jscomp/others/js_json.res, jscomp/others/js_json.resi
Follow up to https://github.com/rescript-lang/rescript-compiler/pull/6368
cc @DZakh
=> make Js.Json.t use Boolean(bool) instead of explicit true/false

CHANGELOG.md, jscomp/frontend/bs_builtin_ppx.ml
This PR fixes not allowing to using the dynamic import of module in the normal function that is not async function.
```res
// should not compiled
let f0 = () => {
module O = await Belt.Option
O.forEach
}
// Ok
let f1 = async () => {
module O = await Belt.Option
O.forEach
}
```
Plus, This PR fixes build error using the dynamic import of module in uncurried mode:
```res
// should be fine in uncurried mode
let f1 = async () => {
module O = await Belt.Option
O.forEach
}
```
=> Fix allowing using dyanmic import of module instead of async function

CHANGELOG.md, jscomp/build_tests/super_errors/expected/variant_coercion_string_to_variant_no_payload.res.expected, jscomp/build_tests/super_errors/fixtures/variant_coercion_string_to_variant_no_payload.res, jscomp/ml/ctype.ml, jscomp/ml/variant_coercion.ml, jscomp/test/VariantCoercion.js, jscomp/test/VariantCoercion.res
Adds support for a very specific (but useful) coercion - from `string` to an unboxed (elgible) variant:
```rescript
@unboxed
type x = One | Two | Other(string)
let x = "Hello"
let y = (x :> x)
let f = switch y {
| One => "hollo"
| _ => "bollo"
}
```
This works because the variant is unboxed, and because there's a "catch all" unboxed `string` constructor in the variant, that will catch any provided string that doesn't map to `One` or `Two`.
Criteria for this coercion to work:
- Variant must be unboxed
- All variant construtors must be coercable to string (criterion for this is covered elsewhere)
- There must be a constructor case with a string payload. This acts as a "catch all" (because it's unboxed) and is what makes the variant cover all possible cases of `string`
=> Support coercing string to elgible untagged variants

CHANGELOG.md, jscomp/syntax/src/reactjs_jsx_v4.ml
This PR fixes JSX v4 in the build error of the discouraged forward ref usage, e.g. https://rescript-lang.org/docs/react/latest/forwarding-refs#discouraged-reactforwardref
=> Fix forwardRef in uncurried mode

CHANGELOG.md, jscomp/jsoo/jsoo_playground_main.ml, playground/playground_test.js
This one is a prerequisite for the v11 docs so that we do not need to have `open RescriptCore` in every example.
See also: https://github.com/rescript-association/rescript-lang.org/issues/718
=> Playground: implicitly opened modules

CHANGELOG.md, jscomp/syntax/src/res_printer.ml, jscomp/syntax/tests/printer/expr/expected/jsx.res.txt, jscomp/syntax/tests/printer/expr/jsx.res
before this fix, 
```res
<\"my-custom-tag" className="hello" />
```
would get reformatted to:
```res
<my-custom-tag className="hello" />
```
which doesn't compile.
=> correctly print exotic JSX names

jscomp/ml/ast_await.ml
So it does not cover the rest on hover.
https://github.com/rescript-lang/rescript-vscode/issues/838
=> Make `unsafe_await` ghost location.

CHANGELOG.md, jscomp/core/record_attributes_check.ml, jscomp/ml/matching.ml, jscomp/ml/matching.mli, jscomp/test/as_inline_record_test.js, jscomp/test/as_inline_record_test.res
Fix for #6438 
PS: First time contributor here. It would be nice to get some guidance on a proper way to contribute this fix properly. (I have read the contributing guidelines).
=> Get field name from attribute when pattern matching

CHANGELOG.md, jscomp/bsb/bsb_arg.ml, jscomp/bsb_exe/rescript_main.ml, jscomp/build_tests/cli_compile_status/input.js, jscomp/build_tests/cli_compile_status/rescript.json, jscomp/build_tests/cli_help/input.js, jscomp/ext/bsc_args.ml, rescript, scripts/rescript_arg.js
Fixes: https://github.com/rescript-lang/rescript-compiler/issues/6435#issuecomment-1758691587 (only the comment)
=> Fix compile status with help command

CHANGELOG.md, jscomp/gentype/GenTypeCommon.ml, jscomp/gentype/TranslateCoreType.ml, jscomp/gentype/TranslateTypeDeclarations.ml, jscomp/gentype/TranslateTypeExprFromTypes.ml, jscomp/gentype_tests/typescript-react-example/package-lock.json, jscomp/gentype_tests/typescript-react-example/src/Unboxed.bs.js, jscomp/gentype_tests/typescript-react-example/src/Unboxed.gen.tsx, jscomp/gentype_tests/typescript-react-example/src/Unboxed.res
There is some special code in the type emitter to take care of poly variants of the form e.g. `#0`, which is represented internally as the string "0". This conflicts with normal variants annotated with `@as("0")` and such.
This PR resolves the case of numeric poly variants early on, and removes the special casing in the code emitter.
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6486
=> GenType: fix issue with @as("0") and other numbers.

CHANGELOG.md, jscomp/syntax/src/res_core.ml, jscomp/syntax/tests/parsing/grammar/expressions/expected/record.res.txt, jscomp/syntax/tests/parsing/grammar/expressions/record.res
This did not parse without a `,` after the field:
```res
type inlineWithAttrs = | A({@as("VALUE") value: string})
```
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6497
=> Fix issue where an inline record with attributes did not parse.

CHANGELOG.md, jscomp/core/lam_pass_alpha_conversion.ml, jscomp/test/UncurriedAlways.js, jscomp/test/UncurriedAlways.res
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6504
Uncurried functions with 1 unit argument are emitted without the parameter. This leaves a possible undefined id in the emitted code if the parameter is a variable. This PR limits the optimization to cases where the parameter is explicitly `()`, as opposed to e.g. a variable whose type is inferred to be unit.
=> Fix issue with uncurried function with 1 arg being a variable

CHANGELOG.md, jscomp/others/belt_Result.res, jscomp/others/belt_Result.resi
As discussed in https://github.com/rescript-lang/rescript-compiler/pull/6450#issuecomment-1843838255
This was a breaking change, there's no harm in restoring the type alias.
=> Restored belt Ok and Error constructors

CHANGELOG.md, jscomp/ml/typedecl.ml, jscomp/test/UntaggedVariants.js, jscomp/test/UntaggedVariants.res
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6519
=> Fix compiler crash with unboxed types with only 1 constructor.

CHANGELOG.md, jscomp/build_tests/cli_help/input.js, packages/artifacts.txt, rescript, scripts/rescript_bsb.js
If `rescript` is called with a flag other than help or version, it'll be treated as `rescript build` command.
So now you can use `rescript -w`.
> I've moved some code to make args parsing code more readable. Besides `var`->`const/let` changes, the code is the same.
=> Treat `rescript` as `rescript build` aka `rescript -w` support 🚀

jscomp/jsoo/jsoo_playground_main.ml
Fixes the issue reported here: https://github.com/rescript-association/rescript-lang.org/issues/716
Applies the same fix as here: https://github.com/rescript-lang/rescript-vscode/pull/851
=> playground: fix bug when printing recursive polyvariant types

jscomp/core/js_implementation.ml, jscomp/core/res_compmisc.ml, jscomp/core/res_compmisc.mli
This is for discussion/a proposal.
We have a situation right now where you can use `-open` in `bsc-flags` to open modules globally. This is quite useful in many cases. However, you're only able to open modules from external dependencies, not modules from your current project, as that would create a circular dependency as it'd also be opened in itself. This PR changes that so that the globally opened module won't be opened in itself.
I'm not sure if this is something we want to allow, nor what the consequences would be. But, it would be useful in many scenarios given that you could put together your own globally available little "stdlib". The usefulness might be a bit negated by the fact that it'd be quite restricted - you couldn't reference other files in your project as _those_ would get …
=> Proposal: allow opening files from the current project globally

CHANGELOG.md, jscomp/ml/ctype.ml, jscomp/ml/variant_coercion.ml, jscomp/test/VariantCoercion.js, jscomp/test/VariantCoercion.res
Generalizes https://github.com/rescript-lang/rescript-compiler/pull/6443 to also allow the same functionality for `int` and `float` as that PR implements for `string`.
=> Coercing int and float unboxed variant catch all cases

packages/playground-bundling/package-lock.json, packages/playground-bundling/package.json
Right now there is no `Array.toSorted` available in the playground for instance, which has been added to rescript-core in version 0.4.0
=> Upgrade playground dependencies

CHANGELOG.md, jscomp/build_tests/super_errors/expected/UntaggedTupleAndArray.res.expected, jscomp/build_tests/super_errors/expected/UntaggedUnknown.res.expected, jscomp/build_tests/super_errors/fixtures/UntaggedTupleAndArray.res, jscomp/build_tests/super_errors/fixtures/UntaggedUnknown.res, jscomp/ml/ast_untagged_variants.ml, jscomp/test/UntaggedVariants.js, jscomp/test/variantsMatching.gen.tsx, jscomp/test/variantsMatching.js, jscomp/test/variantsMatching.res
=> Allow tuples in untagged variants

CHANGELOG.md, jscomp/ml/ctype.ml, jscomp/ml/variant_coercion.ml
Closes https://github.com/rescript-lang/rescript-compiler/issues/6571
=> fixed Not_found exception raised in certain coercion cases

.github/workflows/ci.yml
GitHub-hosted macOS arm action runners are now available, see https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source.
This means that we do not need our custom "macos-arm" runner anymore.
My understanding is that the `macos-13` is Intel-only whereas `macos-14` is ARM-only. And `macos-13` will continue to be available at least for the rest of this year. Later on, in case they go ARM only, we may have to think about what to do with the macOS Intel builds.
=> Use Github-hosted macos arm runner (macos-14)

.github/workflows/ci.yml
Now that we don't need the self-hosted runner anymore, we don't have the problem described in https://github.com/ocaml/setup-ocaml/issues/735 anymore.
=> Reactivate latest setup-ocaml

CHANGELOG.md, jscomp/ml/ast_async.ml, jscomp/test/async_await.js, jscomp/test/async_await.res
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6587
=> Fix issue with async and newtype in uncurried mode.

CHANGELOG.md, jscomp/bsc/rescript_compiler_main.ml, jscomp/syntax/src/jsx_ppx.ml, jscomp/syntax/src/jsx_v4.ml
- Rename the expected module name for lowercase JSX elements to `Elements` from `DOM`. This was just left out, but `Elements` is what's actually documented.
- Set default config params for jsxConfig when using the generic JSX transform.
- Handle potentially namespaced/submodules in the generic module path.
=> Generic JSX transform fixes 

CHANGELOG.md, jscomp/syntax/src/res_core.ml, jscomp/syntax/tests/printer/expr/DocComments.res, jscomp/syntax/tests/printer/expr/expected/DocComments.res.txt
Fix https://github.com/rescript-lang/rescript-compiler/issues/6598
=> Handle doc comment in recursive module

.github/workflows/ci.yml, Makefile, dune-project, jscomp/frontend/bs_ast_mapper.ml, jscomp/syntax/src/jsx_v4.ml, rescript.opam
Build the master branch / v12 with OCaml 5.1.0.
Binaries are a bit bigger than those built with 4.14. And I haven't compared the performance.
Nonetheless, I think it would be good to have this active for v12 development. In case we discover any issues, we can still fall back to 4.14 before the v12 release.
Also, I had to deactivate reanalyze for now as there is no 5.x-compatible version of it on opam yet.
=> Build with OCaml 5.1.0

CHANGELOG.md, jscomp/syntax/src/res_core.ml, jscomp/syntax/src/res_printer.ml, jscomp/syntax/src/res_scanner.ml, jscomp/syntax/tests/parsing/errors/expressions/expected/jsx.res.txt, jscomp/syntax/tests/printer/expr/expected/jsx.res.txt, jscomp/syntax/tests/printer/expr/jsx.res
~remaining:~
~- [ ] hyphens in prop names~
Edit: We don't actually need to allow hyphens in prop names since we can use `@as` for them.
The current situation where scanner.mode is a list is not ideal, you end up pushing multiple times to this list, you never know what's the mode once you popped up, etc. I tried using GADT so you could restrict some functions to a given mode, but it doesn't play well with the rest of the interface (mutable fields everywhere). Meanwhile it could maybe just be replaced with just a value instead of a list. What's is even Diamond mode by the way?
=> allow hyphens in JSX tag names and props

docs/docson/build-schema.json
JSX version is not required to be set anymore given the generic JSX transform.
=> Relax build schema JSX version constraint

.github/workflows/ci.yml, playground/upload_bundle.sh
The script seems to work when run with bash, but not when run with sh.
This is weird, I don't know why it used to work before.
=> Fix playground upload

CHANGELOG.md
I accidentally pushed the actual fix directly to the branch: https://github.com/rescript-lang/rescript-compiler/commit/a82ea96187cf95d51487c99671e7bee65a19377c
This just adds the changelog.
=> No parens around tagged template literals

CHANGELOG.md, jscomp/core/lam_compile_external_call.ml, jscomp/syntax/src/res_core.ml, jscomp/syntax/tests/printer/other/expected/string.res.txt, jscomp/syntax/tests/printer/other/string.res, jscomp/test/build.ninja, jscomp/test/tagged_template_test.js, jscomp/test/tagged_template_test.res
Allow to write this:
```res
let taggedTemplate = Pg.sql`select * from ${table} where id = ${id}`
```
Without this fix, when reexporting tagged template external bindings, it would raise 
```
File "jscomp/core/lam_compile_external_call.ml", line 262, characters 17-23: Assertion failed
```
=> Polish tagged template literals

.github/workflows/ci.yml
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions. Our plan is to transition all actions to run on Node 20 by Spring 2024.
* Alpine build: run individual steps in Docker container (and not the whole job). This allows us to get rid of a workaround and do the checkout on the host instead of in the container, which is required because checkout@v4 doesn't work in Alpine containers anymore.
* Upgrade `actions/checkout`, `actions/setup-node`, `actions/upload-artifact` and `actions/download-artifact` to v4 to fix deprecation warnings. `actions/upload-artifact@v4` also brings significant …
=> Github actions: upgrade some actions to v4 to fix deprecation warnings

.github/workflows/ci.yml, CHANGELOG.md, CONTRIBUTING.md, package-lock.json, package.json
The official maintenance for Node 16 ended last October. Perfect timing
This won't break anything right away, but it should be marked as a breaking change. Then we can make further improvements in the JS part in the future
=> drop Node.js v16 (EoL) support

CHANGELOG.md, jscomp/build_tests/super_errors/expected/warnings4.res.expected, jscomp/build_tests/super_errors/expected/warnings5.res.expected, jscomp/ml/parmatch.ml
In current behavior:
```res
let next = (state, event) => {
// Compiler understand what type you want here, without additional annotations
switch (state, event) {
| (Paused(data), Start | Resume) => Running(data)
| (Running({ count }), Increase) => Running({ count: count + 1 })
| (Running({ count }), Decrease) => Running({ count: count - 1 })
| (Running({ count }), Pause) => Paused({ count: count })
| (_, Reset) => init()
}
}
```
```
You forgot to handle a possible case here, for example: 
(Running({count: _, _}), Start | Resume)
| (Paused(_), Pause | Increase | Decrease)
```
When I want to copy the pattern suggested from this message, copying two lines is not enough. I need to manually insert `|` at front of the pattern.
```diff
You forgot to handle a possible case here, for example: 
- …
```
=> Make the partial match suggestion easier to copy-paste

CHANGELOG.md, jscomp/core/lam_compile.ml, jscomp/test/gpr_1438.js, jscomp/test/gpr_1698_test.js, jscomp/test/mario_game.js, jscomp/test/ocaml_re_test.js, jscomp/test/string_test.js, jscomp/test/typeof_test.js, lib/es6/caml_format.js, lib/es6/genlex.js, lib/js/caml_format.js, lib/js/genlex.js
Hi, I'm new to this project and honestly to ocaml, let me know if the fix seems reasonable and what would be the most appropriate way to propose it (if direct PR is not your style).
I'm looking for forward for comments on this possible approach to solve the issue, the general idea is that the issue is caused by loss of information when translating from typed tree to labmda tree, therefore the easiest way to avoid the issue is to implement an optimization. That said I know that the optimization could be implemented in other places, and at the same time I hope that it's sound.
=> Fix redundant branches in generated switch body, fixes #6671

CHANGELOG.md, jscomp/ml/translcore.ml, jscomp/test/UncurriedAlways.js, jscomp/test/UncurriedAlways.res
Fix the check to determine whether all the arguments were passed to a partial application. The check needs to keep into account the real arguments passed.
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6680
=> Fix issue in partial application when the last named arg is provided.

CHANGELOG.md, jscomp/build_tests/super_errors/expected/UncurriedArgsNotApplied.res.expected, jscomp/build_tests/super_errors/fixtures/UncurriedArgsNotApplied.res, jscomp/frontend/ast_core_type.ml, jscomp/frontend/ast_external_process.ml, jscomp/ml/ast_uncurried.ml, jscomp/ml/error_message_utils.ml, jscomp/ml/predef.ml, jscomp/ml/predef.mli, jscomp/ml/typecore.ml, jscomp/syntax/src/jsx_common.ml, jscomp/syntax/src/res_printer.ml
Closes #6662 
Super errors were not handling uncurried functions properly.
```res
let apply = (fn: (. unit) => option<int>) => fn(. ())
let _ = apply(Some(1))
```
outputted:
```
The constructor Some does not belong to type function$
This variant expression is expected to have type . unit => option<int>
```
whereas it should have outputted
```
This value might need to be wrapped in a function that takes an extra
parameter of type unit
Here's the original error message
This has type: option<'a>
But it's expected to have type: (. unit) => option<int>
```
There were a number of place where uncurried functions were not being handled here and I suspect there's a number of gremlins still around.
=> Fix super error mishandling uncurried function

CHANGELOG.md, jscomp/build_tests/super_errors/expected/DerivingAccessorsRecordParam.res.expected, jscomp/build_tests/super_errors/fixtures/DerivingAccessorsRecordParam.res, jscomp/frontend/ast_derive_projector.ml
Closes #6704 
Previously
```res
@deriving(accessors)
type t = Struct({a: int})
```
would error with:
```
Fatal error: exception File "jscomp/frontend/ast_derive_projector.ml", line 57, characters 42-48: Assertion failed
```
now we get:
```
We've found a bug for you!
/.../fixtures/DerivingAccessorsRecordParam.res:2:10-25
1 │ @deriving(accessors)
2 │ type t = Struct({a: int})
3 │
@deriving(accessors) from a variant record argument is unsupported. Either define the record type separatelyfrom the variant type or use a positional argument.
```
=> Improve error when using '@deriving(accessors)` on a variant with a record arg

CHANGELOG.md, jscomp/build_tests/super_errors/expected/todo_with_no_payload.res.expected, jscomp/build_tests/super_errors/expected/todo_with_payload.res.expected, jscomp/build_tests/super_errors/fixtures/todo_with_no_payload.res, jscomp/build_tests/super_errors/fixtures/todo_with_payload.res, jscomp/ext/warnings.ml, jscomp/ext/warnings.mli, jscomp/frontend/ast_exp_extension.ml
This adds a `%todo` extension, for which the compiler will warn (but not fail) when encountered:
```rescript
let implementMeLater = (): string => %todo("This should return a string eventually.")
let x = implementMeLater()
Js.log(x->Js.String2.includes("x"))
```
Gives:
And compiles to the following JS:
```javascript
// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';
var Js_exn = require("rescript/lib/js/js_exn.js");
function implementMeLater(param) {
return Js_exn.raiseError("tst.res:1:37-42 - Todo: This should return a string eventually.");
}
var x = Js_exn.raiseError("tst.res:1:37-42 - Todo: This should return a string eventually.");
console.log(x.includes("x"));
exports.implementMeLater = implementMeLater;
exports.x = x;
/* x Not a pure module */
```
`%todo` doesn't need to …
=> %todo extension

CHANGELOG.md, jscomp/syntax/src/res_printer.ml, jscomp/syntax/tests/printer/expr/expected/exoticIdent.res.txt, jscomp/syntax/tests/printer/expr/expected/jsx.res.txt, jscomp/syntax/tests/printer/expr/jsx.res
Since the parser already supported hyphens in prop names, I updated the printer to support it too, I guess it's more coherent.
=> Hyphen_jsx_attribute

CHANGELOG.md, jscomp/syntax/src/jsx_v4.ml, jscomp/syntax/tests/ppx/react/expected/forwardRef.res.txt, jscomp/syntax/tests/ppx/react/expected/forwardRef.resi.txt, jscomp/syntax/tests/ppx/react/forwardRef.resi
Fixes #6714 
In the Discouraged ForwardRef use case, if `ref` did not have a type annotation, JSX4 added an incorrect type as an annotation during transformation. While this PR change may cause build errors where the type `'ref` cannot be generalized, I don't think it will be a problem because in most cases the type of `ref` can be inferred from the ForwardRef component implementation. I think adding an incorrect type is a bigger problem.
Original
```res
module ForwardRef = {
@react.component
let make = React.forwardRef(ref => {
React.useImperativeHandle1(
ref,
() =>
Js.Nullable.return({
bla: "bla",
}),
[],
)
React.null
})
}
```
Before this change
```res
module ForwardRef = {
type props<'ref> = {ref?: 'ref}
let make = (_: props<ReactDOM.Ref.currentDomRef>, ref) => { …
```
=> Fix the incorrect type annotation for ref in JSX4

CHANGELOG.md, docs/docson/build-schema.json, jscomp/bsb/bsb_config.ml, jscomp/bsb/bsb_config.mli, jscomp/bsb/bsb_package_specs.ml, jscomp/bsb/bsb_spec_set.ml, jscomp/build_tests/cycle1/rescript.json, jscomp/build_tests/deprecated-package-specs/input.js, jscomp/build_tests/deprecated-package-specs/rescript.json, jscomp/build_tests/deprecated-package-specs/src/Index.res, jscomp/build_tests/in_source/rescript.json, jscomp/core/dune, jscomp/core/js_dump_program.ml, jscomp/core/js_name_of_module_id.ml, jscomp/core/js_packages_info.ml, jscomp/core/js_packages_info.mli, jscomp/core/lam_compile_main.ml, jscomp/core/lam_compile_primitive.ml, jscomp/ext/ext_module_system.ml, jscomp/ext/literals.ml, jscomp/gentype/EmitType.ml, jscomp/gentype/GenTypeConfig.ml, jscomp/gentype_tests/typescript-react-example/rescript.json, jscomp/jsoo/jsoo_playground_main.ml, packages/playground-bundling/rescript.json, packages/playground-bundling/scripts/generate_cmijs.js, packages/test/rescript.json
In v11.x, we only print a deprecation warning for `"es6"` and `"es6"` usage and notice to use `"esmodule"`
In v12
- Remove `"es6"` and "es6-global" completely, and redirect related output paths (`lib/js` to `lib/cjs`, `lib/es6` to `lib/mjs` or we can just merge it into single `lib/js`)
- `"esmodule"`, the standard format will be the default output format.
- Additional option to emit an [importmap](https://github.com/WICG/import-maps) so provide better alternative to the legacy `"es6-global"`
=> Deprecated es6 and es6-global in favor of esmodule

CHANGELOG.md, jscomp/syntax/src/res_printer.ml, jscomp/syntax/tests/printer/expr/expected/exoticIdent.res.txt, jscomp/syntax/tests/printer/expr/expected/jsx.res.txt, jscomp/syntax/tests/printer/expr/jsx.res
This reverts commit 1ec144b4acd8ca54438a946bb6c666159f7afa7e. (#6705).
It created an issue #6723 that will be fixed by improving how we handle modes in the parser. We'll reintroduce #6705 when this lands.
=> Revert escape hyphens in jsx prop names

CHANGELOG.md, jscomp/core/js_dump_import_export.ml, jscomp/test/es6_import.mjs, jscomp/test/gpr_4931_allow.mjs
=> No empty export dump

jscomp/ml/lambda.ml, jscomp/ml/lambda.mli, jscomp/ml/printlambda.ml, jscomp/ml/translattribute.ml, jscomp/ml/translcore.ml, jscomp/ml/translmod.ml
Looking at the difference between `Fun of {...}` in `j.ml` and `type function_attribute` in `lambda.mli`, to see if it's worth using some shared sub-structure, noticed that this is unused.
If a shared sub-structure is used, then `function_attribute` can copied into `Fun of {...}` and replace the 3 fields:
```
return_unit : bool;
async : bool;
directive : string option;
```
=> Cleanup: Remove unused `stub`.

CHANGELOG.md, jscomp/syntax/src/res_parens.ml, jscomp/syntax/tests/printer/expr/expected/smartPipe.res.txt, jscomp/syntax/tests/printer/expr/smartPipe.res
Fix https://github.com/rescript-lang/rescript-compiler/issues/6749
=> Fix parens removed in series of pipes for anonymous uncurried function

jscomp/others/belt_Set.cppo.resi, jscomp/others/belt_SetInt.resi, jscomp/others/belt_SetString.resi
Currently, `make lib` fails for me locally because of a cppo error caused by a change in #6417.
This PR fixes that.
=> Fix belt_Set.cppo.resi

CHANGELOG.md, jscomp/syntax/src/res_core.ml
The location of let bindings did not include annotations attached to the binding (for the first binding in a sequence).
This would show up in actions for dead code elimination in the editor tooling, which would remove everything but the annotation: https://github.com/rescript-lang/rescript-vscode/issues/991
=> Fix location of let bindings with attributes

CHANGELOG.md
Consolidates git history and CHANGELOG.
=> Merge 11.0_release into master

CHANGELOG.md, jscomp/syntax/src/jsx_v4.ml, jscomp/syntax/tests/ppx/react/expected/externalWithCustomName.res.txt, jscomp/syntax/tests/ppx/react/expected/externalWithRef.res.txt, jscomp/syntax/tests/ppx/react/expected/externalWithTypeVariables.res.txt, jscomp/syntax/tests/ppx/react/expected/firstClassModules.res.txt, jscomp/syntax/tests/ppx/react/expected/mangleKeyword.res.txt, jscomp/syntax/tests/ppx/react/expected/noPropsWithKey.res.txt, jscomp/syntax/tests/ppx/react/expected/v4.res.txt, jscomp/syntax/tests/ppx/react/externalWithRef.res
Fixes https://github.com/rescript-lang/rescript-vscode/issues/994
Dead code elimination in the editor tooling complains about props never being read in the `props` type record defined by the V4 ppx. This is because externals don't provide the implementation of the component, and it's in the implementation that props could be read. This PR marks the `props` type definition as `@live` for external components, so the dead code analysis does not complain.
=> PPX v4: mark props type in externals as `@live`.

CHANGELOG.md, jscomp/frontend/bs_ast_invariant.ml
Not sure why I had kept this one deactivated before.
Compiler libs and tests build fine with this, and I also tested successfully with some of my projects.
=> Reactivate unused attribute check for `@int`

.prettierignore, Makefile, scripts/check_format.sh, scripts/ciTest.js, scripts/test_syntax.sh
Always run the ocamlformat check in CI, not just when something has changed in jscomp/syntax.
Fixes #6801
=> Run OCaml format check as part of CI tests

jscomp/common/.ocamlformat, jscomp/common/bs_loc.ml, jscomp/common/bs_loc.mli, jscomp/common/ext_log.ml, jscomp/common/js_config.ml, jscomp/common/js_config.mli, jscomp/common/pattern_printer.ml
There are other directories, too, where `ocamlformat` is still disabled.
Let's start with this one, as it is pretty small.
=> Format jscomp/common

CHANGELOG.md, jscomp/gentype/TranslateTypeExprFromTypes.ml
The type Jsx.element can show user-side in ppx V4 (at least), and affects gentype too. It special-cases `React.element`, and needs to then special-case `Jsx.element` too.
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6807
=> gentype: support Jsx.element in addition to React.element

CHANGELOG.md, jscomp/build_tests/super_errors/expected/UntaggedImplIntf.res.expected, jscomp/build_tests/super_errors/fixtures/UntaggedImplIntf.res, jscomp/ml/includecore.ml, jscomp/ml/oprint.ml, jscomp/ml/outcometree.ml, jscomp/ml/printtyp.ml, jscomp/syntax/src/res_outcome_printer.ml, packages/playground-bundling/package-lock.json, packages/playground-bundling/package.json
- Print `@as(...)` as required for variant cases.
- Print `@unboxed` in the variant type declaration in the outcome printer.
- Fix issue where attributes such as `@unboxed` were printed twice.
- Fix issue where inconsistency in `@unboxed` in variant declarations between implementation and interface was not checked, and the type error was missing.
Test:
```res
module M: {
@unboxed type t = | @as(null) A
} = {
@unboxed type t = | @as(undefined) A
}
```
Triggered in error message:
```res
Type declarations do not match:
@unboxed type t = @as(undefined) A
is not included in
@unboxed type t = @as(null) A
```
=> Print variant runtime repr in error messages, and fix inclusion check.

CHANGELOG.md, jscomp/syntax/src/res_core.ml, jscomp/syntax/tests/parsing/other/expected/stringLiterals.res.txt, jscomp/syntax/tests/parsing/other/stringLiterals.res, jscomp/test/tagged_template_test.js, jscomp/test/tagged_template_test.res
=> support utf8 in tagged templates

packages/playground-bundling/scripts/generate_cmijs.js
`package` is a reserved identifier in JavaScript. should throw SyntaxError in strict mode.
- #6838 Biome can audit this kind of problems
- I'm migrating the codebase to ESM, which is in strict mode by default.
=> internal: avoid JS identifier

package.json
[Corepack](https://nodejs.org/api/corepack.html) is Node.js' canonical tool for managing PM binaries and shims
When a Node.js user with Corepack enabled runs the `npm` command, the `"packageManager"` field is automatically added like this.
It's better to specify the version we want first before getting unnecessary diffs. This has no effect for users who don't use Corepack.
=> Specify `packageManager` for Corepack users

.github/workflows/ci.yml, .github/workflows/get_artifact_dir_name.js, dune-project, ninja/misc/ci.py, ninja/misc/output_test.py, rescript.opam, scripts/buildNinjaBinary.js
Mostly using `actions/cache`
Skip build if there are no changes in rewatch sources and its dependencies.
Pre-install Linux dependencies more efficiently using [cache-apt-pkgs-action](https://github.com/awalsh128/cache-apt-pkgs-action)
Skip OPAM installation as much as possible.
Once it installed, there are three paths can be cached:
- `${{ runner.tool_cache }}/opam/...`: Shared storage for binaries installed by `setup-*` actions. It will contain `opam` executable.
- `~/.opam`: The home directory of OPAM, every modification by OPAM will placed there.
- `_opam`: Local switch
After caching these three, we can restore OPAM installation by adding `PATH` and exporting `opam env`.
It can be cached with other deps
`build-rewatch` on `ubuntu-latest`:
- before: 50s~90s
- after (cached): ~15s …
=> Boost CI speed

rescript
Rescript fails to start at the moment, if launched with specifically Deno on specifically Windows:
```
PS C:\Users\user> deno run -A npm:rescript
error: Uncaught TypeError: Windows only supports ctrl-c (SIGINT) and ctrl-break (SIGBREAK).
at bindSignal (ext:runtime/40_signals.js:14:10)
at Object.addSignalListener (ext:runtime/40_signals.js:54:19)
at Process.on (node:process:349:12)
at Object.<anonymous> (file:///C:/Users/user/rust/rescript-compiler/node_modules/.deno/rescript@11.1.2/node_modules/rescript/rescript:64:9)
at Object.<anonymous> (file:///C:/Users/user/rust/rescript-compiler/node_modules/.deno/rescript@11.1.2/node_modules/rescript/rescript:133:4)
```
The reason is: https://github.com/denoland/deno/issues/9995
I've tested it locally (with some …
=> Fix Deno compatibility issues on Windows

package.json
I switched module exporting to explicit from #6782 without lib paths.
It will possibly break at runtime `ReferenceError`
=> export lib paths

CHANGELOG.md, jscomp/syntax/src/res_core.ml, jscomp/syntax/tests/parsing/grammar/modtype/expected/with.res.txt, jscomp/syntax/tests/parsing/grammar/modtype/with.res
=> fix(syntax): allow private in with constraints

CHANGELOG.md, jscomp/build_tests/super_errors/expected/recursive_type.res.expected, jscomp/build_tests/super_errors/fixtures/recursive_type.res, jscomp/ml/typecore.ml
Fixes https://github.com/rescript-lang/rescript-compiler/issues/6863
=> Fix issue with infinite loops with type errors on recursive types.

CHANGELOG.md, jscomp/syntax/src/res_core.ml, jscomp/test/UncurriedAlways.js, jscomp/test/UncurriedAlways.res
Reverse application`|>` is already formatted away, but this takes care of the issue before formatting.
This is the last instance of `Curry` used at runtime in the compiler code/lib/tests, when built in uncurried mode.
=> Avoid generation of `Curry` with reverse application `|>`.

CHANGELOG.md, jscomp/core/lam_convert.ml, jscomp/ml/lambda.ml, jscomp/ml/lambda.mli, jscomp/ml/printlambda.ml, jscomp/ml/translcore.ml, jscomp/ml/typecore.ml, jscomp/others/js.res, jscomp/runtime/js.res, jscomp/stdlib-406/sys.res, jscomp/stdlib-406/sys.resi, lib/es6/belt_internalBuckets.js, lib/js/belt_internalBuckets.js
This was used for uncurried application, but does not seem to be needed now. And for some esoteric `Sys. opaque_identity` function.
Just one less bit of magic.
=> Remove `%opaque` primitive.

jscomp/core/js_dump_property.ml, jscomp/syntax/tests/oprint/expected/oprint.resi.txt, jscomp/syntax/tests/oprint/oprint.res, jscomp/syntax/tests/printer/expr/exoticIdent.res, jscomp/syntax/tests/printer/expr/expected/exoticIdent.res.txt, jscomp/test/exotic_labels_test.js, jscomp/test/exotic_labels_test.res
Fixed #6882
The ident format has changed in #6777 for exotic uppercase names, but the change is not applied to the backend in the previous PR.
=> Fix uppercase exotic field format

CHANGELOG.md
Reference all related PRs in a single place.
=> Update CHANGELOG for the uppercase exotic ident stuff

package.json, packages/std/package.json
Hoisted up the package's basic information. Arranged them in a meaningful order.
And changed the current maintainer information to @cristianoc 's one
=> Organize `package.json` content

jscomp/gentype_tests/typescript-react-example/src/Hooks.res.js, jscomp/ml/translcore.ml, jscomp/test/ari_regress_test.js, jscomp/test/arity_deopt.js, jscomp/test/event_ffi.js, jscomp/test/random_test.js, jscomp/test/test_demo.js
```res
let h34 = x => x(1,2)(4)
```
should generate
```js
function h34(x) {
return x(1, 2)(4);
}
```
and not this:
```js
function h34(x) {
return x(1, 2, 4);
}
```
=> Fix nested inferred application.

packages/playground-bundling/package-lock.json, packages/playground-bundling/package.json
Upgrade `@rescript/react` dependency in the playground to 0.13.0 (the version without `%external`).
=> Playground: rescript-react 0.13.0

.github/workflows/ci.yml, scripts/moveArtifacts.sh
Simplifies the CI script and speeds up CI by another 1:30.
Checks that the Linux executables are actually statically linked to avoid regressions.
=> CI: build Linux x64 binaries directly on runner (no docker)

CHANGELOG.md, jscomp/others/js.res, jscomp/runtime/js.res
See #6905 and https://forum.rescript-lang.org/t/is-it-good-idea-having-binding-to-js-this/2922
=> Add `Js.globalThis` object binding

.github/workflows/ci.yml, Makefile, scripts/npmPack.js
`npm pack` was run twice. Once with `--dry-run` to check the artifact list, and one more time for the actual package creation.
Doing it only once saves another 12s in CI.
=> CI: don't run npm pack twice

.github/workflows/ci.yml
Currently,
- we are building the compiler in CI with OCaml 5.2.0
- the oldest OCaml version that the compiler still builds with is 4.13.0. (If we wanted to, I think we could extend this further back with very little effort.)
With this PR, CI will check that the compiler still builds with the older versions 5.0.0, 4.14.2 and 4.13.0.
This doesn't cost us additional build time as the compiler builds run in parallel, and the slowest one is macos x64.
=> CI: verify that compiler still builds with older OCaml versions

.github/workflows/ci.yml
Use our own fork of opam-repository containing this fix:
https://github.com/ocaml/opam-repository/pull/26323
This way, we do not need Docker anymore for the Linux arm64 build. So we can treat Linux arm64 exactly the same as the other architectures, get the benefit of the caching implemented by @cometkim, and do not need to create new Docker images for new OCaml versions anymore.
=> Build static Linux arm64 binaries without docker

CHANGELOG.md, jscomp/core/lam.ml, jscomp/core/lam_compile_external_call.ml, jscomp/frontend/ast_external_process.ml, jscomp/frontend/external_arg_spec.ml, jscomp/frontend/external_arg_spec.mli
Fn_uncurry_arity is not constructed anywhere.
After removing it, no_auto_uncurried_arg_types always returns true, so can be removed as well.
=> Remove leftover Fn_uncurry_arity and no_auto_uncurried_arg_types

Makefile, docker/Dockerfile
See #6851 - people were asking for a dev container. 
This adds a `Dockerfile` and a `Makefile` entry for building a container with all the required dependencies installed.
I am not familiar with the [Development Containers](https://containers.dev/) spec as such and leaving that to someone else.
Example usage:
```sh
make dev-container
docker run --rm -it -v `pwd`:/data -w /data rescript-dev-container bash
opam exec -- make
opam exec -- make lib
opam exec -- make test
```
=> Add Dockerfile for development container

CHANGELOG.md, jscomp/syntax/src/res_parsetree_viewer.ml, jscomp/syntax/src/res_parsetree_viewer.mli, jscomp/syntax/src/res_printer.ml, jscomp/syntax/tests/printer/expr/apply.res, jscomp/syntax/tests/printer/expr/expected/apply.res.txt
=> Skip trailing comma in explicit partial application

jscomp/ml/datarepr.ml, jscomp/ml/env.ml, jscomp/ml/matching.ml, jscomp/ml/rec_check.ml, jscomp/ml/translcore.ml, jscomp/ml/typecore.ml, jscomp/ml/typedecl.ml, jscomp/ml/types.ml, jscomp/ml/types.mli
Branched from https://github.com/rescript-lang/rescript-compiler/pull/6942 with the additional removal of the constant flag, which became unneeded
=> Remove constant flag from extension constructor

CHANGELOG.md, jscomp/syntax/src/res_parens.ml, jscomp/syntax/tests/printer/expr/expected/field.res.txt, jscomp/syntax/tests/printer/expr/expected/unary.res.txt, jscomp/syntax/tests/printer/expr/field.res, jscomp/syntax/tests/printer/expr/unary.res
Fix https://github.com/rescript-lang/rescript-compiler/issues/6884
=> Fix incorrect format of function under unary operator

CHANGELOG.md, jscomp/syntax/src/res_parens.ml, jscomp/syntax/src/res_parens.mli, jscomp/syntax/src/res_printer.ml, jscomp/syntax/tests/printer/modExpr/expected/structure.res.txt, jscomp/syntax/tests/printer/modExpr/structure.res
Fix https://github.com/rescript-lang/rescript-compiler/issues/6936
=> Fix module printing

jscomp/ml/ctype.ml, jscomp/ml/env.ml, jscomp/ml/predef.ml, jscomp/ml/subst.ml, jscomp/ml/typedecl.ml, jscomp/ml/types.ml, jscomp/ml/types.mli, jscomp/test/record_extension_test.js, jscomp/test/record_extension_test.res
Adds `ext_is_exception` field to the `extension_constructor` type. It can be used to differentiate between exceptions and normal extension types. Currently used in one place for error message (the place existed before, made it use the `ext_is_exception` instead of figuring out it itself).
I believe the change is the first step to split extension types and exceptions representations.
=> Differentiate exception extensions

CHANGELOG.md, jscomp/runtime/caml_exceptions.res, lib/es6/caml_exceptions.js, lib/es6/caml_js_exceptions.js, lib/js/caml_exceptions.js, lib/js/caml_js_exceptions.js
Also, removed `/1` for `RE_EXN_ID` created the first time
=> Improve extension creation runtime

.github/workflows/ci.yml
Now that my PR https://github.com/ocaml/opam-repository/pull/26323 is merged, we do not need our own fork of the opam repository anymore.
=> No need to use our custom opam fork anymore

CHANGELOG.md, jscomp/build_tests/super_errors/expected/variant_spread_abstract_type.res.expected, jscomp/build_tests/super_errors/expected/variant_spread_extensible_variant.res.expected, jscomp/build_tests/super_errors/fixtures/variant_spread_abstract_type.res, jscomp/build_tests/super_errors/fixtures/variant_spread_extensible_variant.res, jscomp/ml/typedecl.ml, jscomp/ml/variant_type_spread.ml, jscomp/runtime/release.ninja
Disallows anything but regular variants as spreads in other variants. Closes https://github.com/rescript-lang/rescript-compiler/issues/6952.
=> Disallow non-variant spreads in variants

CHANGELOG.md, jscomp/build_tests/super_errors/expected/variant_coercion_open_polyvariant.res.expected, jscomp/build_tests/super_errors/expected/variant_coercion_polyvariant_mismatch_as_attribute.res.expected, jscomp/build_tests/super_errors/expected/variant_coercion_polyvariant_mismatch_as_attribute2.res.expected, jscomp/build_tests/super_errors/expected/variant_coercion_polyvariant_unmatched_cases.res.expected, jscomp/build_tests/super_errors/expected/variant_coercion_polyvariant_with_payload.res.expected, jscomp/build_tests/super_errors/fixtures/variant_coercion_open_polyvariant.res, jscomp/build_tests/super_errors/fixtures/variant_coercion_polyvariant_mismatch_as_attribute.res, jscomp/build_tests/super_errors/fixtures/variant_coercion_polyvariant_mismatch_as_attribute2.res, jscomp/build_tests/super_errors/fixtures/variant_coercion_polyvariant_unmatched_cases.res, jscomp/build_tests/super_errors/fixtures/variant_coercion_polyvariant_with_payload.res, jscomp/ml/ctype.ml, jscomp/ml/variant_coercion.ml, jscomp/test/VariantCoercion.js, jscomp/test/VariantCoercion.res
This makes it possible to coerce from polyvariant to variant when we can guarantee the runtime representations will match.
- Checks that the polyvariant is closed.
- Checks that there's a variant case that would match for each polyvariant label
=> Coerce polyvariant to variant

CHANGELOG.md, jscomp/syntax/src/res_comments_table.ml, jscomp/syntax/src/res_core.ml, jscomp/syntax/src/res_grammar.ml, jscomp/syntax/src/res_parsetree_viewer.ml, jscomp/syntax/src/res_parsetree_viewer.mli, jscomp/syntax/src/res_printer.ml, jscomp/syntax/src/res_scanner.ml, jscomp/syntax/src/res_token.ml, jscomp/syntax/tests/parsing/grammar/expressions/dict.res, jscomp/syntax/tests/parsing/grammar/expressions/expected/dict.res.txt, jscomp/syntax/tests/printer/expr/bsObj.res, jscomp/syntax/tests/printer/expr/dict.res, jscomp/syntax/tests/printer/expr/expected/bsObj.res.txt, jscomp/syntax/tests/printer/expr/expected/dict.res.txt
This PR adds basic support for the `dict{}` literal syntax (https://github.com/rescript-lang/rescript-compiler/issues/6545).
Semantics within the braces are similar to the record with string keys (as dict keys can be any string).
It then turns `dict{"foo": "bar"}` into `Js.Dict.fromArray([("foo", "bar")])`. 
Any `Js.Dict.fromArray` call that contains a literal array of tuples (with no spread) is now printed as `dict{...}`. 
I think this change is safe for the upcoming stdlib change (that'll move `Js.Dict` into `Dict`) as the change will be invisible once using this syntax. If that's something we don't want, we can add an attribute when parsing a `dict{}` expression so that we only print those back and leave `Js.Dict.fromArray` calls.
=> Add dict literal syntax

CHANGELOG.md, jscomp/syntax/src/res_comments_table.ml, jscomp/syntax/tests/printer/comments/expected/expr.res.txt
Fix https://github.com/rescript-lang/rescript-compiler/issues/6890
=> Fix comment removed when function signature has type keyword

.github/workflows/stale.yml
Stale action was running in debug mode first. Activate it now so that it actually marks issues as stale.
Looking at the issues that would have been marked as stale, let's maybe be a bit more conservative now and use 360 days before stale. We can always reduce that value later.
Closes #6977.
=> Activate stale action

CHANGELOG.md, jscomp/syntax/src/res_core.ml, jscomp/syntax/tests/parsing/other/docComments.res, jscomp/syntax/tests/parsing/other/expected/docComments.res.txt, jscomp/syntax/tests/printer/comments/docComments.res, jscomp/syntax/tests/printer/comments/expected/docComments.res.txt
=> Fix parse error on doc comment before "and" in type def

CHANGELOG.md, jscomp/frontend/ast_attributes.ml, jscomp/frontend/ast_attributes.mli, jscomp/frontend/ast_derive_abstract.ml, jscomp/ml/typedecl.ml, jscomp/syntax/tests/parsing/infiniteLoops/expected/nonRecTypes.res.txt, jscomp/syntax/tests/parsing/infiniteLoops/nonRecTypes.res
=> Remove attribute "internal.arity"

CHANGELOG.md, jscomp/others/jsxDOM.res
Adding the `capture` attribute to JsxDOM.res
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture
=> Add missing HTML attribute capture to JsxDOM.res

.github/workflows/stale.yml
The stale action also marks PRs as stale, not just issues.
I was not really able to deactivate that feature (but I think it's ok to have it).
Related configuration (permissions) was missing though, causing errors on action runs.
=> CI: fix stale action config for PRs

CHANGELOG.md, jscomp/syntax/src/res_core.ml, jscomp/syntax/tests/parsing/grammar/expressions/coerce.res, jscomp/syntax/tests/parsing/grammar/expressions/expected/coerce.res.txt
Fix https://github.com/rescript-lang/rescript-compiler/issues/7003. 
It was only handled for the first argument in the tuple. This handles for the rest of the args in the tuple.
=> Fix tuple coercion

CHANGELOG.md, jscomp/build_tests/super_errors/expected/pattern_matching_on_option_but_value_not_option.res.expected, jscomp/build_tests/super_errors/expected/pattern_matching_on_value_but_is_option.res.expected, jscomp/build_tests/super_errors/fixtures/pattern_matching_on_option_but_value_not_option.res, jscomp/build_tests/super_errors/fixtures/pattern_matching_on_value_but_is_option.res, jscomp/ml/error_message_utils.ml, jscomp/ml/printtyp.ml, jscomp/ml/printtyp.mli, jscomp/ml/typecore.ml
This expands error messages when matching on options/non-options or non-options/options to better explain what's going wrong, and how you can solve it.
Part of https://github.com/rescript-lang/rescript-compiler/issues/6975
=> Improve error messages for pattern matching mismatches for options/concrete values

CHANGELOG.md, jscomp/bsb/bsb_jsx.ml
resolved https://github.com/rescript-lang/rescript-compiler/issues/6982
Deprecate JSX 3 from v11
=> Deprecate JSX 3

CHANGELOG.md, jscomp/build_tests/super_errors/expected/function_call_mismatch.res.expected, jscomp/build_tests/super_errors/expected/warnings2.res.expected, jscomp/ml/error_message_utils.ml
Adds some simple context to error messages when `unit` is expected. I _would_ like to also add a contextual message "Did you mean to return this value from the function? Make sure it's the final expression in the function body to return it" but that requires tracking if the error happens inside of a function or not, and that's a lot more work, so skipping for now.
Part of https://github.com/rescript-lang/rescript-compiler/issues/6975
=> Add context to error message when unit is expected

CHANGELOG.md, jscomp/build_tests/super_errors/expected/component_missing_prop_children.res.expected, jscomp/build_tests/super_errors/fixtures/component_missing_prop_children.res, jscomp/ml/error_message_utils.ml
This special cases the error message you get when you pass `children` to a JSX component that does not accept them. The big reason for special casing just this prop is that _passing it_ is already special cased in the syntax (`<div>{React.string("this is children")}</div>`) vs passing a regular prop ( `<div className="this is a regular prop" />`).
I think this makes it clearer, but I'd love to hear some feedback.
Part of https://github.com/rescript-lang/rescript-compiler/issues/6975
=> Special JSX children error message

CHANGELOG.md, jscomp/syntax/src/res_parsetree_viewer.ml, jscomp/syntax/src/res_parsetree_viewer.mli, jscomp/syntax/src/res_printer.ml, jscomp/syntax/tests/printer/typexpr/expected/arrow.res.txt, jscomp/test/reasonReact.res
Fix https://github.com/rescript-lang/rescript-compiler/issues/6638
@cknitt Can you look at the diff output for the test and see whether they are acceptable in terms of formatting changes? They look okay to me. https://github.com/rescript-lang/rescript-compiler/pull/7025/files#diff-2333e082552a974a4c2fc20db5dbd0415ae96a46b675d967a6d9804f7497ad08
I've checked all the attributes we have here (https://rescript-lang.org/syntax-lookup) and there are only a few that is at field level (e.g. `@as`, `@this`, etc).
I had worked on this during the retreat but Max preferred not to hard code attribute value for the check, so this PR try to generalize the check without checking for specific attribute. (Prev PR: https://github.com/rescript-lang/rescript-compiler/pull/6773).
=> Fix @this attribute dropping parens

jscomp/build_tests/super_errors/expected/unbound_record_field.res.expected, jscomp/build_tests/super_errors/fixtures/unbound_record_field.res, jscomp/ml/typetexp.ml
Tweaking the error message for unbound record fields slightly. Interested in feedback on if you think this message is an improvement over the current, which reads roughly like:
```
The record field knownKey can't be found.
If it's defined in another module or file, bring it into scope by:
- Prefixing it with said module name: TheModule.knownKey
- Or specifying its type:
let theValue: TheModule.theType = {knownKey: VALUE}
```
So, just changing the wording slightly.
=> Tweak unbound record field error message

CHANGELOG.md, jscomp/others/js_cast.res, jscomp/others/js_cast.resi
Resolves the deprecation part of 5439
needs to be removed on master as well
=> Deprecate js_cast.res

.github/workflows/ci.yml, CHANGELOG.md, scripts/test.js, tests/build_tests/case/input.js, tests/build_tests/case2/input.js, tests/build_tests/cli_compile_status/input.js, tests/build_tests/cli_help/input.js, tests/build_tests/duplicated_symlinked_packages/input.js, tests/build_tests/post-build/input.js, tests/build_tests/rerror/input.js, tests/build_tests/scoped_ppx/input.js, tests/build_tests/super_errors/input.js, tests/build_tests/unboxed_bool_with_const/input.js, tests/build_tests/unicode/input.js, tests/build_tests/utils.js, tests/build_tests/weird_deps/input.js, tests/build_tests/weird_devdeps/input.js
Gets most of `build_tests` running on Windows.
OUnit tests remain disabled on Windows, we can have a look at those later.
=> Run build_tests on Windows

CHANGELOG.md, cli/rescript_format.js
=> rescript format: process files in batches

Makefile, cli/bsc, cli/rescript, package-lock.json, package.json, packages/artifacts.txt, scripts/buildRuntime.sh, scripts/format.sh, scripts/format_check.sh, tests/build_tests/cli_compile_status/input.js, tests/build_tests/cli_help/input.js, tests/gentype_tests/typescript-react-example/package-lock.json
This cleans up the root folder a bit. `rescript` and `bsc` (the wrapper scripts, not the native exes) are actually part of the cli and should be in the `cli` folder.
=> Move rescript and bsc wrapper scripts into cli folder

CHANGELOG.md, jscomp/core/lam_compile_primitive.ml, jscomp/core/lam_convert.ml, tests/tests/src/bigint_test.js, tests/tests/src/bigint_test.res
This PR fixes the issue where max, min operations generate js ouput incorrectly. It is described in the related issue https://github.com/rescript-lang/rescript-compiler/issues/7062#issuecomment-2395737100
=> Fix js ouput of bigint max, min

CHANGELOG.md, compiler/core/lam_constant_convert.ml, tests/tests/src/VariantCoercion.js, tests/tests/src/VariantCoercion.res
Fix for https://github.com/rescript-lang/rescript-compiler/issues/7036
=> Fix variant coercion with as attribute

.github/workflows/ci.yml, dune-project, rescript.opam, tests/syntax_benchmarks/Benchmark.ml, tests/syntax_benchmarks/dune, tests/syntax_benchmarks/time.c
This PR runs the syntax benchmark in CI and uses https://github.com/benchmark-action/github-action-benchmark to have the github-actions bot create a comment with the benchmark results in future PRs. It will also warn if the results diverge too much from the previous ones (currently 150% is set as the alerting threshold, we can fine tune this later).
It cleans up `Benchmark.ml` and modifies it to output JSON for consumption by github-action-benchmark.
It also fixes two bugs in the benchmark logic:
- Incorrect implementation of `caml_mach_absolute_time` for Linux
- The number of allocations for *one* run was divided by the number of runs, instead of the total number of allocations.
Also note that:
- The comment that the bot left in this PR is outdated. It seems it only comments once on PR …
=> Continuous benchmarking in CI

CHANGELOG.md, compiler/ml/error_message_utils.ml, compiler/ml/typecore.ml, tests/build_tests/super_errors/expected/object_passed_when_record_expected.res.expected, tests/build_tests/super_errors/fixtures/object_passed_when_record_expected.res
This improves the error message when an object is passed where a record is expected. A scenario that happens from time to time when copy pasting JS/TS stuff.
=> Improve error message when an object is passed where a record is expected

.github/workflows/ci.yml
* Reduce alert threshold to 120%
* Remove unneeded permissions
* Remove `summary-always: true`, hoping that that fixes build errors on master.
=> Benchmark cleanup

CHANGELOG.md, compiler/gentype/TranslateTypeExprFromTypes.ml, tests/gentype_tests/typescript-react-example/src/Hooks.gen.tsx, tests/gentype_tests/typescript-react-example/src/OnClick2.gen.tsx
Fixes https://github.com/rescript-lang/rescript-compiler/issues/7106
The Jsx.element type has moved from Pervasives.
=> Fix gentype jsx issue

CHANGELOG.md, compiler/gentype/FindSourceFile.ml, compiler/gentype/FindSourceFile.mli, compiler/gentype/GenTypeConfig.ml, compiler/gentype/GenTypeMain.ml, compiler/gentype/Paths.ml
Like discussed in [rescript-lang/rewatch#102](https://github.com/rescript-lang/rewatch/issues/102) this PR enables gentype to handle passing of absolute file paths.
Instead of manipulating the path to the `.cmt` file it gets the source file path from the `.cmt` file first.
Then constructs the output file paths from there.
=> Handle absolute paths in typegen

lib/es6/Error.js, lib/js/Error.js, runtime/Error.res, runtime/Error.resi, runtime/Float.res, runtime/Float.resi, runtime/Pervasives.res
While working on adding the Core tests to the compiler repo, I discovered and fixed some issues with primitives.
(Mainly the changes from #6984 not being reflected in Core yet.)
=> Fix some primitives usage

CHANGELOG.md, jscomp/gentype/FindSourceFile.ml, jscomp/gentype/FindSourceFile.mli, jscomp/gentype/GenTypeConfig.ml, jscomp/gentype/GenTypeMain.ml, jscomp/gentype/Paths.ml
=> v11 backport of #7104

.github/workflows/ci.yml
In the future, as requested [here](https://github.com/rescript-lang/rescript-compiler/commit/66daccbcef78498257b8176efafc1a9b3c02bb34#commitcomment-148232002), have the bot only comment if there is a >5% difference in benchmark results.
=> Benchmark: report on alert only

CHANGELOG.md, compiler/core/js_dump.ml, compiler/core/js_exp_make.ml, tests/tests/src/UntaggedVariants.mjs, tests/tests/src/core/Core_NullableTests.mjs, tests/tests/src/variantsMatching.mjs
- `x === null || x === undefined` --> `x == null`
- `[(typeof x === "string") && (x === "abc")]` --> `[x === "abc"]`
- `[(typeof x === "number") && (x === 123)]` --> `[x === 123]`
=> small simplifications

CHANGELOG.md, compiler/ml/parmatch.ml, tests/tests/src/DictTests.mjs
Pattern matching of optional fields such as
```res
| {x: 1, y: "hello"}
```
can be specialised as the constants already imply the values cannot be absent.
=> Code gen: improve pattern matching of optional fields.

CHANGELOG.md, compiler/core/js_exp_make.ml, tests/tests/src/core/Core_JsonTests.mjs, tests/tests/src/core/Core_NullableTests.mjs
This handles all the boolean simplifications in https://github.com/rescript-lang/rescript-compiler/issues/7142.
What's left from that issue is conditionals `b ? x : y`, that can be done separately.
=> More boolean simplifications in generated code.

CHANGELOG.md, compiler/syntax/src/res_scanner.ml, tests/syntax_tests/data/parsing/errors/scanner/expected/exponent_notation.res.txt, tests/syntax_tests/data/parsing/errors/scanner/exponent_notation.res
Fix https://github.com/rescript-lang/rescript/issues/6986
=> Fix exponential syntax

CONTRIBUTING.md
`rescript-compiler` has been renamed to `rescript`
=> docs: Update shallow clone URL in CONTRIBUTING.md

analysis/README.md
Ported from https://github.com/rescript-lang/rescript-vscode/pull/1063
=> Add more info about analysis tool

CHANGELOG.md, runtime/JsxDOMStyle.res
`JsxDOMStyle` lacks some properties that already in CSS standards (e.g. `aspectRatio`, `scrollbarWidth`).
The top half are from https://github.com/mdn/data/blob/main/css/properties.json and filtered by:
```javascript
// ignore vendor properties
!key.startsWith("-")
// ignore non-standard properties
&& value.status === "standard"
```
The bottom half are those already in `JsxDOMStyle` but not in current CSS standards.
Here are the script to generate new record fields (https://github.com/stephanoskomnenos/rescript-cssprops/blob/main/scripts/generate.ts).
=> Add all standard CSS properties to `JsxDOMStyle`

CHANGELOG.md, compiler/syntax/src/jsx_v4.ml, tests/build_tests/super_errors/expected/react_component_with_props_external.res.expected, tests/build_tests/super_errors/fixtures/react_component_with_props_external.res
Resolves https://github.com/rescript-lang/rescript/issues/7215
=> Add error using `@react.componentWithProps` with `external`

CHANGELOG.md, compiler/syntax/src/res_printer.ml, tests/syntax_tests/data/printer/pattern/expected/record.res.txt, tests/syntax_tests/data/printer/pattern/record.res
Handle the case when no fields are specified when pattern matching.
Fix https://github.com/rescript-lang/rescript/issues/7179
=> Fix formatter handling of wildcard pattern matching in record

CHANGELOG.md, analysis/src/TypeUtils.ml, tests/analysis_tests/tests/package-lock.json, tests/analysis_tests/tests/src/Support.res, tests/analysis_tests/tests/src/TypeArgCtx.res, tests/analysis_tests/tests/src/expected/Completion.res.txt, tests/analysis_tests/tests/src/expected/CompletionJsxProps.res.txt, tests/analysis_tests/tests/src/expected/TypeArgCtx.res.txt
Ports https://github.com/rescript-lang/rescript-vscode/pull/1064
=> Editor: Fix issue where type arg ctx was not passed along properly

CHANGELOG.md, compiler/core/js_exp_make.ml, tests/tests/src/test_zero_nullable.mjs, tests/tests/src/test_zero_nullable.res
Fixes https://github.com/rescript-lang/rescript/issues/7225
=> Fix leftover assert false in code for `null != undefined`

CHANGELOG.md, analysis/src/CompletionFrontEnd.ml, tests/analysis_tests/tests/src/CompletionObjects.res, tests/analysis_tests/tests/src/expected/CompletionObjects.res.txt, tst.res
Port of https://github.com/rescript-lang/rescript-vscode/pull/1065, which fixes completion inside of object bodies.
=> Editor: Iterate objects

CHANGELOG.md, compiler/frontend/bs_builtin_ppx.ml, compiler/ml/ast_async.ml, compiler/syntax/src/jsx_common.ml, compiler/syntax/src/jsx_v4.ml, compiler/syntax/src/res_core.ml, compiler/syntax/src/res_parens.ml, compiler/syntax/src/res_parsetree_viewer.ml, compiler/syntax/src/res_parsetree_viewer.mli, compiler/syntax/src/res_printer.ml, tests/analysis_tests/tests-generic-jsx-transform/package-lock.json, tests/analysis_tests/tests-incremental-typechecking/package-lock.json, tests/analysis_tests/tests-reanalyze/deadcode/package-lock.json, tests/analysis_tests/tests-reanalyze/termination/package-lock.json, tests/analysis_tests/tests/package-lock.json, tests/syntax_tests/data/parsing/grammar/expressions/expected/async.res.txt, tests/syntax_tests/data/parsing/grammar/expressions/expected/locallyAbstractTypes.res.txt, tests/syntax_tests/data/printer/comments/expected/expr.res.txt, tests/syntax_tests/data/printer/expr/expected/newtype.res.txt, tests/tools_tests/package-lock.json
AST: always put type parameters first in function definitions.
Normalize function definitions to be of the form `(type a b c, x, y) => ...`, moving all the types first if they are not already.
=> Ast types first

CHANGELOG.md, analysis/reanalyze/src/Arnold.ml, analysis/reanalyze/src/SideEffects.ml, analysis/src/Utils.ml, compiler/frontend/bs_ast_invariant.ml, compiler/frontend/bs_ast_mapper.ml, compiler/frontend/bs_builtin_ppx.ml, compiler/ml/ast_helper.ml, compiler/ml/ast_helper.mli, compiler/ml/ast_iterator.ml, compiler/ml/ast_mapper.ml, compiler/ml/ast_mapper_from0.ml, compiler/ml/ast_mapper_to0.ml, compiler/ml/depend.ml, compiler/ml/parsetree.ml, compiler/ml/pprintast.ml, compiler/ml/printast.ml, compiler/ml/printtyped.ml, compiler/ml/rec_check.ml, compiler/ml/tast_iterator.ml, compiler/ml/tast_mapper.ml, compiler/ml/translcore.ml, compiler/ml/typecore.ml, compiler/ml/typedtree.ml, compiler/ml/typedtree.mli, compiler/ml/typedtreeIter.ml, compiler/syntax/src/res_ast_debugger.ml, compiler/syntax/src/res_printer.ml
Pexp_new is not used in the untyped tree.
=> AST: Remove Pexp_new

.github/workflows/ci.yml
Now that [Linux arm64 hosted runners are available for free in public repositories](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/), we can get rid of the BuildJet runners. 🎉
=> Use GitHub Linux ARM runners

compiler/core/js_name_of_module_id.ml, packages/playground-bundling/package-lock.json, packages/playground-bundling/package.json, packages/playground-bundling/rollup.config.cjs, packages/playground-bundling/scripts/generate_cmijs.js, playground/upload_bundle.sh
To load stdlib JS files in the playground, we need to bundle them and upload them to the CDN.
=> Bundle stdlib runtime for playground

CHANGELOG.md, compiler/syntax/src/res_printer.ml, tests/syntax_tests/data/printer/comments/expected/jsx.res.txt, tests/syntax_tests/data/printer/expr/expected/jsx.res.txt, tests/syntax_tests/data/printer/expr/jsx.res
Fix https://github.com/rescript-lang/rescript/issues/7204
=> Allow single empty line between JSX expressions

CHANGELOG.md, compiler/syntax/src/jsx_v4.ml, tests/tests/src/alias_default_value_test.mjs, tests/tests/src/alias_default_value_test.res
Fixes #7257
@cristianoc or @cknitt how can I add a test for this?
Worked for my local sample.
=> Copy attributes from original binding expression

CHANGELOG.md, compiler/ml/ast_mapper_to0.ml, tests/tools_tests/ppx/TestPpx.res, tests/tools_tests/src/expected/TestPpx.res.jsout
Fix issue where attributes on an application were not preserved by the AST conversion for ppx.
Fixes https://github.com/rescript-lang/rescript/issues/7261
=> Fix issue with ppx and await.

CHANGELOG.md, compiler/frontend/ast_attributes.ml, compiler/frontend/ast_attributes.mli, compiler/frontend/bs_builtin_ppx.ml, compiler/syntax/src/res_core.ml, tests/build_tests/super_errors/expected/ModuleAwait.res.expected, tests/build_tests/super_errors/fixtures/ModuleAwait.res, tests/tests/src/async_await.mjs, tests/tests/src/async_await.res
The check was not firing for `module M: ModTyp` as it was looking for attributes in the wrong place.
=> Fix async context checking for module await.

CHANGELOG.md, compiler/syntax/src/res_scanner.ml
Apply recommendation from  https://github.com/rescript-lang/rescript/pull/7279#discussion_r1944202437
=> remove ignore in res_scanner

CHANGELOG.md, analysis/src/CompletionBackEnd.ml, analysis/src/Packages.ml, analysis/src/SharedTypes.ml, analysis/src/TypeUtils.ml, tests/analysis_tests/tests-generic-jsx-transform/package-lock.json, tests/analysis_tests/tests-generic-jsx-transform/src/expected/GenericJsxCompletion.res.txt, tests/analysis_tests/tests/src/Completion.res, tests/analysis_tests/tests/src/CompletionDicts.res, tests/analysis_tests/tests/src/CompletionExpressions.res, tests/analysis_tests/tests/src/CompletionInferValues.res, tests/analysis_tests/tests/src/CompletionJsx.res, tests/analysis_tests/tests/src/CompletionJsxProps.res, tests/analysis_tests/tests/src/CompletionPipeChain.res, tests/analysis_tests/tests/src/CompletionTypeT.res, tests/analysis_tests/tests/src/DotPipeCompletionSpec.res, tests/analysis_tests/tests/src/Hover.res, tests/analysis_tests/tests/src/PolyRec.res, tests/analysis_tests/tests/src/SignatureHelp.res, tests/analysis_tests/tests/src/expected/Completion.res.txt, tests/analysis_tests/tests/src/expected/CompletionDicts.res.txt, tests/analysis_tests/tests/src/expected/CompletionExpressions.res.txt, tests/analysis_tests/tests/src/expected/CompletionInferValues.res.txt, tests/analysis_tests/tests/src/expected/CompletionJsx.res.txt, tests/analysis_tests/tests/src/expected/CompletionPattern.res.txt, tests/analysis_tests/tests/src/expected/CompletionPipeChain.res.txt, tests/analysis_tests/tests/src/expected/CompletionTypeT.res.txt, tests/analysis_tests/tests/src/expected/DotPipeCompletionSpec.res.txt, tests/analysis_tests/tests/src/expected/ExhaustiveSwitch.res.txt, tests/analysis_tests/tests/src/expected/RecordCompletion.res.txt
* Removes the `builtInModules` config concept, since Core is now in the compiler repo and Js/Belt is never to be preferred
* Moves all tests in analysis to use Core
* Removes/cleans up a few things/checks related to handling multiple versions of the ReScript compiler - the current editor tooling only ever deals with exactly the version of the compiler it's included in
=> Analysis tests fixes

CHANGELOG.md, lib/es6/Stdlib_List.js, lib/js/Stdlib_List.js, runtime/Stdlib_List.res, runtime/Stdlib_List.resi, runtime/Stdlib_Result.resi, tests/analysis_tests/tests/src/expected/Auto.res.txt, tests/analysis_tests/tests/src/expected/Completion.res.txt, tests/analysis_tests/tests/src/expected/Definition.res.txt
- remove `List.t`
- rename `toShuffled` to `shuffle` and deprecate it
- deprecate `List.*Assoc` functions
I think this solves most issues raised in rescript-lang/rescript-core/issues/192.
I have no good idea for `List.concatMany` so I just kept it.
I'd rather keep `List.has` and `List.length` as it is today and maybe we could add `Array.has` for consistency.
=> Clean list API

CHANGELOG.md, compiler/core/lam_compile.ml, compiler/ml/ast_untagged_variants.ml, tests/tests/src/UntaggedVariants.mjs, tests/tests/src/UntaggedVariants.res, tests/tests/src/core/Core_JsonTests.mjs, tests/tests/src/json_decorders.mjs
Fixes https://github.com/rescript-lang/rescript/issues/7289
The check emitted for case `Object` was simply `type of ... === "object"`, though that is insufficient when the variant has one case corresponding to `null`. Now we check if such a variant case exists, and emit `... != null` in addition.
=> Fix issue with untagged variants and object when null is one case.

CHANGELOG.md, lib/es6/Stdlib_JSON.js, lib/js/Stdlib_JSON.js, runtime/Stdlib_JSON.res
=> Simplify JSON.Decode implementation

CHANGELOG.md, playground/upload_bundle.sh
example of such truncated files:
https://cdn.rescript-lang.org/v12.0.0-alpha.8/compiler-builtins/stdlib/Belt_MapInt.js
=> Backport use TLS 1.2 to upload files to CDN using FTP

CHANGELOG.md, compiler/ml/ast_untagged_variants.ml, compiler/ml/typedecl.ml, tests/tests/src/UntaggedVariants.mjs, tests/tests/src/UntaggedVariants.res
Fixes https://github.com/rescript-lang/rescript/issues/7314
- Delay untagged variant well-formedness checks until after environment construction
- Collect all untagged variant checks during type declaration processing
- Perform checks once all recursive types are available in the environment
- Add test case for valid recursive untagged variant type definitions
This fixes issues where recursive references in untagged variants would fail validation due to premature checking before the full type environment was built.
=> Fix recursive untagged variant type checking

CHANGELOG.md, runtime/Stdlib_Date.res, runtime/Stdlib_Date.resi, tests/analysis_tests/tests/src/expected/CompletionTypeT.res.txt, tests/tests/src/core/intl/Core_Intl_DateTimeFormatTest.res
Using `~date` is ambiguous and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date) references `day`anyway.
=> replace ~date with ~day for Date.make*

CHANGELOG.md, runtime/Stdlib.res
Fixes rescript-lang/rescript-core#240
=> deprecate unsafe host-specific bindings from stdlib

CHANGELOG.md, compiler/ml/typecore.ml, tests/build_tests/super_errors/expected/fun_return_poly1.res.expected, tests/build_tests/super_errors/expected/fun_return_poly2.res.expected, tests/build_tests/super_errors/fixtures/fun_return_poly1.res, tests/build_tests/super_errors/fixtures/fun_return_poly2.res
Fixes https://github.com/rescript-lang/rescript/issues/7323
When typing application there's a special treatment for polymorphic types, where the arity and kinds of arguments are inferred. For example: `f => f(~lbl1, ~lbl2)` assigns a polymorphic type `'a` to `f` initially which is then instantated to `(~lbl1:t1, ~lbl2:t2) => t3`.
That same mechanism currently applies when a function is annotated to return a polymorphic type such as `(string, ~wrongLabelName: int=?) => 'a`, where the `'a` is further instantiated to extend the function type with additional arguments. This mechanism is OK for curried function, but incorrect for uncurried functions: while e.g. `'a => 'b` with curried function designates any function where the first argument is unlabeled, with uncurried function it only …
=> Fix issue with typing application and polymorphic types.

packages/artifacts.txt, runtime/Stdlib_Symbol.res, runtime/Stdlib_Symbol.resi
This adds a `.resi` file for `Stdlib_Symbol` with documentation for most of the common uses for Symbols. I added a `description` and `toString` to the bindings.
A good chunk of what Symbols are used for aren't really applicable or possible with ReScript, such as the static [properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#static_properties). I'm not sure if there is value in including those bindings in the stdlib, but for now I just omitted documentation.
=> Add some docs to stblib Symbol

lib/es6/Stdlib_BigInt.js, lib/es6/Stdlib_Int.js, lib/js/Stdlib_BigInt.js, lib/js/Stdlib_Int.js, runtime/Stdlib_BigInt.res, runtime/Stdlib_Int.res, runtime/Stdlib_Int.resi, tests/analysis_tests/tests/src/expected/CompletionJsx.res.txt
- [Left Shift](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Left_shift)
- [Right Shift](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Right_shift)
- [Unsigned Right Shift](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Unsigned_right_shift)
- [Bitwise AND](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_AND)
So on
=> Stdlib: rename binary operations to match JavaScript terms

.github/workflows/prepare_package_upload.js, CHANGELOG.md, cli/rescript.js, scripts/prebuilt.js, scripts/setVersion.js
=> Do not use experimental JSON import feature

CHANGELOG.md, compiler/gentype/TranslateTypeExprFromTypes.ml, tests/gentype_tests/typescript-react-example/src/Core.gen.tsx, tests/gentype_tests/typescript-react-example/src/Core.res, tests/gentype_tests/typescript-react-example/src/Core.res.js
Fixes https://github.com/rescript-lang/rescript/issues/7157
Map `JSON.t` to `unknown`.
=> Fix issue with gentype and stdlib json.

CHANGELOG.md, compiler/ml/typetexp.ml, tests/build_tests/super_errors/expected/suggest_module_for_missing_identifier.res.expected, tests/build_tests/super_errors/expected/suggest_module_for_missing_identifier_with_spellcheck.res.expected, tests/build_tests/super_errors/fixtures/suggest_module_for_missing_identifier.res, tests/build_tests/super_errors/fixtures/suggest_module_for_missing_identifier_with_spellcheck.res, tests/build_tests/super_errors/input.js
There are some subtle differences between how certain common things are called in ReScript vs in JS. One example is logging to the console:
```
// JS
console.log("Hello")
// ReScript
Console.log("Hello")
```
This difference (value vs module) can be subtle and not easily discoverable. So, this PR does a small addition to the "missing value" error message, and suggests the module version of the identifier _if it exists in scope_. This is intended to give a small hint for what you _might_ be looking for, instead of just telling you to "go fish".
=> Error message: Suggest module in place of value where it makes sense

CHANGELOG.md, runtime/Stdlib_RegExp.res, runtime/Stdlib_RegExp.resi, tests/analysis_tests/tests/src/expected/CompletionExpressions.res.txt
While the type `RegExp.Result.t` (`array<option<string>>`) is correct, `matches` was typed as `array<string>` even though it can contain `undefined`.
I've also used this PR to make `RegExp.fromString` more ergonomic by adding an optional `flags` argument and deprecating `RegExp.fromStringWithFlags`.
=> Fix type of RegExp.Result.matches

CHANGELOG.md, compiler/frontend/bs_ast_mapper.ml, compiler/frontend/bs_builtin_ppx.ml, compiler/ml/ast_helper.ml, compiler/ml/ast_helper.mli, compiler/ml/ast_mapper.ml, compiler/ml/ast_mapper_from0.ml, compiler/ml/parsetree.ml, compiler/ml/printast.ml, compiler/syntax/src/res_core.ml
This is useful in recovery scenarios:
```
let x  = 
switch y {
| None => 0
|
}
```
```
[
structure_item 
Pstr_value Nonrec
[
<def>
pattern 
Ppat_var "x" 
expression 
Pexp_match
expression 
Pexp_ident "y" 
[
<case>
| [3,25+8]
pattern 
Ppat_construct "None" 
None
expression 
Pexp_constant PConst_int (0,None)
<case>
| [4,45+8]
pattern 
Ppat_extension "rescript.patternhole"
[]
expression 
Pexp_extension "rescript.exprhole"
[]
]
]
]
```
we can pinpoint a cursor position between the bar and the end of the switch.
Easily telling us that we are inside an empty case.
=> Add bar position to case

analysis/bin/main.ml, analysis/src/CmtViewer.ml, analysis/src/SharedTypes.ml
Some helper code that shows what is inside a `.cmt` file.
=> Inital dump of cmt

runtime/Belt_Array.resi, runtime/Belt_Float.resi, runtime/Belt_HashMap.resi, runtime/Belt_List.resi, runtime/Belt_Map.resi, runtime/Belt_MapDict.resi, runtime/Belt_MutableSet.resi, runtime/Belt_Option.resi, runtime/Belt_Range.resi, runtime/Belt_Result.resi, runtime/Belt_SetDict.resi, runtime/Belt_SortArray.resi, runtime/Stdlib_List.resi, runtime/Stdlib_Math.resi, tests/analysis_tests/tests/src/expected/Completion.res.txt, tests/analysis_tests/tests/src/expected/Definition.res.txt
adds `assertEqual` to missing stdlib modules:
- `Belt`
- `Array`
- `Float`
- `HashMap`
- `List`
- `Map`
- `MapDict`
- `MutableSet`
- `Option`
- `Range`
- `Result`
- `SetDict`
- `SortArray`
- `Stdlib`
- `SortArray`
- `List`
- `Math`
closes #7374
=> add assertEqual to docstrings

CHANGELOG.md, lib/es6/Stdlib_BigInt.js, lib/js/Stdlib_BigInt.js, runtime/Stdlib_BigInt.res, tests/tests/src/core/Core_TempTests.mjs, tests/tests/src/core/Core_TempTests.res, tests/tests/src/core/Core_TestTests.mjs, tests/tests/src/core/Core_TestTests.res
fixes #7089
⚠️ breaking change
=> make BigInt.fromFloat error-safe

CHANGELOG.md, compiler/syntax/src/jsx_v4.ml
`ref` as prop is now allowed in React 19, see https://react.dev/blog/2024/12/05/react-19#ref-as-a-prop
=> Do not error on `ref` as prop

analysis/reanalyze/src/Paths.ml, analysis/reanalyze/src/Reanalyze.ml, analysis/src/CompletionDecorators.ml, compiler/bsb/bsb_build_util.ml, compiler/bsb/bsb_build_util.mli, compiler/bsb/bsb_exception.ml, compiler/bsb/bsb_ninja_rule.mli, compiler/bsb/bsb_pkg.ml, compiler/bsb/bsb_watcher_gen.mli, compiler/bsb_exe/rescript_main.ml, compiler/jsoo/jsoo_playground_main.ml, compiler/ml/typetexp.ml, docs/JSXV4.md, rewatch/tests/snapshots/remove-file.txt, rewatch/tests/snapshots/rename-file-internal-dep-namespace.txt, rewatch/tests/snapshots/rename-file-internal-dep.txt, runtime/Belt.res, tests/analysis_tests/tests/src/expected/Completion.res.txt, tests/build_tests/case/input.js, tests/build_tests/case2/input.js, tests/build_tests/super_errors/expected/modules1.res.expected, tests/build_tests/weird_deps/input.js, tests/build_tests/weird_devdeps/input.js
=> bsconfig.json -> rescript.json in error messages + comments

CHANGELOG.md, compiler/syntax/src/res_printer.ml, tests/syntax_tests/data/printer/comments/expected/jsx.res.txt, tests/syntax_tests/data/printer/comments/jsx.res
Fix https://github.com/rescript-lang/rescript/issues/7416
=> Fix comments removed in JSX

compiler/core/js_dump.ml, compiler/core/js_dump_property.ml, compiler/core/js_dump_property.mli, tests/tests/src/preserve_jsx_test.mjs, tests/tests/src/preserve_jsx_test.res
Fixes https://rescript-lang.org/try?version=v12.0.0-alpha.10&module=esmodule&code=LYewJgrgNgpgBAWQJ4HUYEsBOYDCJgAOIAdjMQC5wC8cA3gFBxzlIHwGYgEDO1dAOgCJkaLGAAKnAoIBccdBQC+9RnFiVgAQwDW8Ghy68qAPjgAlGJoDG5AHQLyACgM9bQkRmySuggJT1lenU4AH0+AB4PMTxCEjJKd1RPCSlBKgAWACY4AHpjeiA
example
=> Escape prop name in preserve jsx

tests/tests/src/preserve_jsx_test.mjs, tests/tests/src/preserve_jsx_test.res
I am slowly coming to terms with the potential limitation of the `preserve-jsx` feature, which may require `@react.component` or `@react.componentWithProps`.
=> Add @react.componentWithProps to MyWeirdComponent test

CHANGELOG.md, runtime/Jsx.res
Tested successfully against a project using both React web and React Native.
=> Remove unused type Jsx.ref

.github/workflows/ci.yml
There were quite a few fixes/improvements to setup-ocaml lately, so let's upgrade to the latest version.
=> setup-ocaml 3.3.2

compiler/core/js_dump.ml, tests/tests/src/jsx_preserve_test.mjs
Unfortunately, if the string contains escape sequences like `\"` for example, the result is not valid JSX if the string is not wrapped in braces. 😭
=> Revert "Further improve JSX preserve output (#7445)"

compiler/jsoo/dune, compiler/jsoo/jsoo_playground_main.ml, rescript.opam, rescript.opam.template
~~But playground should adopt module.~~
PPX seems to be buggy.
=> Fix playground bundle API

CHANGELOG.md, compiler/ml/error_message_utils.ml, compiler/ml/typecore.ml, tests/build_tests/super_errors/expected/promise_needs_await.res.expected, tests/build_tests/super_errors/fixtures/promise_needs_await.res
A small improvement to detect when you're trying to use a promise before awaiting/chaining it. Suggestions for further improvement welcome!
=> Suggest awaiting promise before using it when type mismatches

compiler/ml/typecore.ml, compiler/ml/typecore.mli, tests/build_tests/super_errors/expected/arity_mismatch.res.expected, tests/build_tests/super_errors/expected/arity_mismatch2.res.expected, tests/build_tests/super_errors/expected/arity_mismatch4.res.expected, tests/build_tests/super_errors/expected/fun_return_poly1.res.expected, tests/build_tests/super_errors/expected/fun_return_poly2.res.expected, tests/build_tests/super_errors/expected/method_arity_mismatch.res.expected, tests/build_tests/super_errors/expected/missing_label.res.expected, tests/build_tests/super_errors/expected/missing_labels.res.expected, tests/build_tests/super_errors/expected/moreArguments1.res.expected, tests/build_tests/super_errors/expected/moreArguments2.res.expected, tests/build_tests/super_errors/expected/moreArguments3.res.expected, tests/build_tests/super_errors/expected/moreArguments4.res.expected, tests/build_tests/super_errors/expected/moreArguments5.res.expected, tests/build_tests/super_errors/expected/non_function_uncurried_apply.res.expected, tests/build_tests/super_errors/expected/opt_args_arity.res.expected, tests/build_tests/super_errors/expected/partial_app.res.expected, tests/build_tests/super_errors/expected/primitives3.res.expected, tests/build_tests/super_errors/expected/primitives4.res.expected, tests/build_tests/super_errors/expected/recursive_type.res.expected, tests/build_tests/super_errors/expected/uncurried_wrong_label.res.expected, tests/build_tests/super_errors/expected/warnings1.res.expected, tests/build_tests/super_errors/fixtures/arity_mismatch4.res
This reworks the function apply error messages some to make them clearer and easier to understand.
Feedback very welcome.
Closes https://github.com/rescript-lang/rescript/issues/7055
=> Improve function apply error messages

CHANGELOG.md, analysis/src/TypeUtils.ml, compiler/frontend/ast_comb.ml, compiler/frontend/ast_comb.mli, compiler/frontend/ast_exp_extension.ml, compiler/frontend/ast_literal.ml, compiler/frontend/ast_literal.mli, tests/analysis_tests/tests/src/CompletionRegexp.res, tests/analysis_tests/tests/src/expected/CompletionPipeChain.res.txt, tests/analysis_tests/tests/src/expected/CompletionRegexp.res.txt
Closes https://github.com/rescript-lang/rescript/issues/7159
~~Might want to think another round on whether this is the right fix. Maybe we should point out `Stdlib_RegExp` explicitly instead of the shorthand.~~
EDIT: Ended up finding a better way to do this. Now ready for review.
=> Change completions of regex literals

CHANGELOG.md, runtime/Stdlib_Console.res, runtime/Stdlib_Console.resi
`console.dir` supports an [optional `options` argument](https://developer.mozilla.org/en-US/docs/Web/API/console/dir_static#options), with `options.depth` being particularly useful for logging nested data structures.
=> Add optional `~options` argument to `Console.dir`

.github/workflows/ci.yml
This reverts commit 4836f3cd6bd9ff31552029a017f354aa7bf667a8.
=> CI: reactivate caching

runtime/Belt_HashMap.resi, runtime/Stdlib_Console.resi, runtime/Stdlib_String.resi, scripts/format_check.sh, tests/analysis_tests/tests/src/expected/CompletionJsx.res.txt, tests/docstring_tests/DocTest.res, tests/docstring_tests/DocTest.res.js
Makes it possible to change `assertEqual` to `==` in doc comments to improve readability, while keeping the test safety
=> Turn eqeq in doc comments to asserts for testing

CHANGELOG.md, compiler/ml/typecore.ml, tests/tests/src/PartialApplicationNoRuntimeCurry.mjs, tests/tests/src/PartialApplicationNoRuntimeCurry.res
Fixes https://github.com/rescript-lang/rescript/issues/7544
Fix an issue in type checking partial application in the presence of user-defined function types. The type checking code, when extracting the arity of the type annotation given to a function being applied, was expecting a concrete function type instead of looking up a possible type definition.
=> Fix issue with partial application and user defined types.

.github/workflows/ci.yml, runtime/Stdlib_Array.resi, tests/analysis_tests/tests/src/expected/Completion.res.txt, yarn.config.cjs
#7555 was adding API docs in an extra subfolder, this PR fixes this.
=> fix api docs download path

runtime/Stdlib_Null.resi
Part of https://github.com/rescript-lang/rescript/issues/7546
=> Add docstring for Null.compare and Null.equal

CHANGELOG.md, compiler/core/js_dump.ml
See https://github.com/rescript-lang/rescript/issues/6496
While deprecation is being discussed, this prevents the compiler crashes.
=> Fix crash when `-bs-g` is used on untagged variants.

rewatch/tests/legacy.sh
=> Fix: Remove extra spaces in rewatch legacy test output and reset changed file.

packages/artifacts.txt, runtime/Stdlib_BigInt.res, runtime/Stdlib_BigInt.resi
Mostly AI written, but looks good to me.
https://github.com/rescript-lang/rescript/issues/7546
=> Docstrings for BigInt

packages/artifacts.txt, runtime/Stdlib_ArrayBuffer.res, runtime/Stdlib_ArrayBuffer.resi
Also mostly AI written, but again seems good.
https://github.com/rescript-lang/rescript/issues/7546
=> Docstrings for ArrayBuffer

CHANGELOG.md, rewatch/src/build.rs, rewatch/src/build/compile.rs, rewatch/src/build/packages.rs, rewatch/src/config.rs
This fixes: #7564 
The warning configuration for non-local dependencies is ignored.
=> fix: ignore warning config for non local deps

CHANGELOG.md, rewatch/src/build/packages.rs
Upstreams https://github.com/rescript-lang/rewatch/pull/167
plus adds missing changelog entries for yesterday's upstreams
=> Rewatch: fix panic if package.json name different from module name

CHANGELOG.md, analysis/src/Commands.ml, analysis/src/CreateInterface.ml, analysis/src/Xform.ml, compiler/ml/location.ml, compiler/ml/location.mli, compiler/syntax/src/res_diagnostics.ml, compiler/syntax/src/res_diagnostics.mli, compiler/syntax/src/res_multi_printer.ml, compiler/syntax/src/res_multi_printer.mli, compiler/syntax/src/res_printer.ml, compiler/syntax/src/res_printer.mli, dune-project, runtime/Stdlib_Result.resi, tests/tools_tests/src/docstrings-format/FormatDocstringsTest1.res, tests/tools_tests/src/docstrings-format/FormatDocstringsTest1.resi, tests/tools_tests/src/docstrings-format/FormatDocstringsTest2.res, tests/tools_tests/src/docstrings-format/FormatDocstringsTestError.res, tests/tools_tests/src/docstrings-format/FormatRescriptBlocks.md, tests/tools_tests/src/expected/FormatDocstringsTest1.res.expected, tests/tools_tests/src/expected/FormatDocstringsTest1.resi.expected, tests/tools_tests/src/expected/FormatDocstringsTest2.res.expected, tests/tools_tests/src/expected/FormatDocstringsTestError.res.expected, tests/tools_tests/src/expected/FormatRescriptBlocks.md.expected, tests/tools_tests/test.sh, tools.opam, tools/bin/main.ml, tools/src/dune, tools/src/tools.ml
Adds an experimental command to `tools` for formatting ReScript code blocks in docstrings.
I put it under `tools` just because that was the easiest place to put it. Feedback gladly accepted on where to put it.
I ran formatting on `Stdlib_Result.resi` so you can see an example of the results easily.
=> Experimental command to format code blocks embedded in docstrings

.github/workflows/ci.yml, packages/artifacts.txt
Re-enable artifact list check which got lost in #7412.
=> Re-enable artifact list check

CHANGELOG.md, compiler/core/js_dump.ml, tests/tests/src/core/Test.mjs, tests/tests/src/core/Test.res
Fixes https://github.com/rescript-lang/rescript/issues/7641
=> Fix issue with invalid code when emitting typeof with a function.

CHANGELOG.md, rewatch/src/build/clean.rs, rewatch/src/helpers.rs
Fixes https://github.com/rescript-lang/rescript/issues/7488
=> Use root package suffix in clean log messages

CHANGELOG.md, compiler/ml/error_message_utils.ml, tests/build_tests/super_errors/expected/extract_from_none_file.res.expected, tests/build_tests/super_errors/fixtures/extract_from_none_file.res
Fixes https://github.com/rescript-lang/rescript/issues/7610
=> Prevent trying to read non-existing file when extracting extra info for error messages

CHANGELOG.md, rewatch/Cargo.lock, rewatch/Cargo.toml, rewatch/src/cli.rs, rewatch/src/format.rs, rewatch/src/lib.rs, rewatch/src/main.rs, rewatch/tests/format.sh, rewatch/tests/suite-ci.sh, scripts/format.sh, scripts/format_check.sh
Do not forward the `rescript format` command to the legacy JS cli anymore, instead implement the functionality natively in Rust.
=> Rust implementation of "rescript format"

CHANGELOG.md, compiler/ml/typecore.ml, compiler/ml/typecore.mli
Fixes #7468.
(I accidentally pushed the commit with the fix to the master already, this PR is for documentation.)
=> Fix fatal error when JSX not configured in rescript.json

CHANGELOG.md, compiler/frontend/ast_core_type.ml, compiler/frontend/ast_core_type.mli, compiler/frontend/ast_derive_abstract.ml, compiler/frontend/ast_derive_js_mapper.ml, compiler/frontend/ast_derive_projector.ml, compiler/frontend/ast_exp_handle_external.ml, compiler/frontend/ast_external_process.ml, compiler/frontend/ast_typ_uncurry.ml, compiler/ml/ast_mapper_from0.ml, compiler/ml/parsetree.ml, compiler/ml/pprintast.ml, compiler/ml/printtyped.ml, compiler/ml/typedtree.ml, compiler/ml/typedtree.mli, compiler/ml/typetexp.ml, compiler/syntax/src/jsx_v4.ml, compiler/syntax/src/res_core.ml, compiler/syntax/src/res_parsetree_viewer.ml, compiler/syntax/src/res_parsetree_viewer.mli, compiler/syntax/src/res_printer.ml, tests/syntax_tests/data/parsing/grammar/typexpr/expected/es6Arrow.res.txt, tests/syntax_tests/data/ppx/react/expected/mangleKeyword.res.txt, tests/syntax_tests/data/printer/typexpr/expected/arrow.res.txt
Functions of several arguments are stored as nested `Ptyp_arrow` ast nodes, with attributes at toplevel in the node. This change adds an attribute field to type arguments, makin it impossible to distinguish attributes on arguments from attributes on the entire function.
=> AST: store the attributes directly on function arguments.

rewatch/tests/utils.sh
=> Revert utils.sh

.github/workflows/ci.yml
It is somewhat weird that we build in release mode but do not run the tests as such.
=> Run Rewatch tests in release mode.

.github/workflows/ci.yml, CHANGELOG.md, rewatch/src/build.rs, rewatch/src/build/compile.rs, rewatch/src/build/compile/dependency_cycle.rs, rewatch/src/build/deps.rs, rewatch/src/build/namespaces.rs, rewatch/src/build/packages.rs, rewatch/src/build/parse.rs, rewatch/src/build/read_compile_state.rs, rewatch/src/config.rs, rewatch/src/format.rs, rewatch/src/helpers.rs, rewatch/src/lock.rs, rewatch/src/sourcedirs.rs, rewatch/src/watcher.rs
=> ci: add clippy

packages/playground/package.json, packages/playground/scripts/generate_cmijs.mjs, rescript.json, rewatch/testrepo/package.json, scripts/res/package.json, tests/analysis_tests/tests-generic-jsx-transform/package.json, tests/analysis_tests/tests-incremental-typechecking/package.json, tests/analysis_tests/tests-reanalyze/deadcode/package.json, tests/analysis_tests/tests-reanalyze/termination/package.json, tests/analysis_tests/tests/package.json, tests/docstring_tests/package.json, tests/gentype_tests/typescript-react-example/package.json, tests/gentype_tests/typescript-react-example/rescript.json, tests/tools_tests/package.json
The `"@tests/gentype-react-example"` project is using the root `node_modules` and without a top level `rescript.json`, rewatch doesn't know where to find the right files to clean.
This makes sense to me, let me know if it does for you.
=> Remove legacy clean

.github/workflows/ci.yml, rewatch/Cargo.lock, rewatch/Cargo.toml, rewatch/src/main.rs, rewatch/tests/suite-ci.sh, scripts/copyExes.js
Fixes https://github.com/rescript-lang/rescript/issues/7674
=> Rename rewatch to rescript

analysis/src/FindFiles.ml, analysis/src/Packages.ml, compiler/gentype/GenTypeConfig.ml, compiler/ml/typetexp.ml, rewatch/tests/snapshots/bs-dev-dependency-used-by-non-dev-source.txt, rewatch/tests/snapshots/remove-file.txt, rewatch/tests/snapshots/rename-file-internal-dep-namespace.txt, rewatch/tests/snapshots/rename-file-internal-dep.txt, tests/build_tests/super_errors/expected/modules1.res.expected
This adjusts more stuff to the `bs-*` deprecations.
I pretty much simply trust that the build system will error if both are defined, so I don't care too much about that type of logic for this.
I couldn't add proper tests for this in the analysis, because this requires rewatch and I can't get the analysis tests to build with rewatch right now.
I don't think this needs a changelog since https://github.com/rescript-lang/rescript/pull/7658 already has one.
=> Adjust to bs-* deprecations

CHANGELOG.md, compiler/ml/typecore.ml, tests/build_tests/super_errors/expected/arity_mismatch3.res.expected, tests/build_tests/super_errors/expected/arity_mismatch_fewer.res.expected, tests/build_tests/super_errors/expected/curried_expected.res.expected, tests/build_tests/super_errors/fixtures/arity_mismatch_fewer.res
This just does a small touch up of the arity mismatch message that I feel makes the error clearer.
=> Clarify arity mismatch message

CHANGELOG.md, rewatch/src/cli.rs, rewatch/src/main.rs
=> Remove dump command from rewatch cli

CHANGELOG.md, cli/common/bins.js
Errors on determining the bin path using dynamic import may actually be due to a node version that is too old.
Report the correct error for that case.
=> Add node version check

CHANGELOG.md, runtime/Stdlib_Array.res, runtime/Stdlib_Array.resi, runtime/Stdlib_BigInt64Array.res, runtime/Stdlib_BigUint64Array.res, runtime/Stdlib_Float32Array.res, runtime/Stdlib_Float64Array.res, runtime/Stdlib_Int16Array.res, runtime/Stdlib_Int32Array.res, runtime/Stdlib_Int8Array.res, runtime/Stdlib_String.res, runtime/Stdlib_String.resi, runtime/Stdlib_TypedArray.res, runtime/Stdlib_Uint16Array.res, runtime/Stdlib_Uint32Array.res, runtime/Stdlib_Uint8Array.res, runtime/Stdlib_Uint8ClampedArray.res, tests/analysis_tests/tests/src/expected/Completion.res.txt, tests/analysis_tests/tests/src/expected/CompletionInferValues.res.txt, tests/analysis_tests/tests/src/expected/CompletionJsx.res.txt
=> Use more optional args in stdlib and deprecate some functions

CHANGELOG.md, compiler/syntax/src/res_printer.ml, tests/syntax_tests/data/printer/structure/expected/moduleBinding.res.txt, tests/syntax_tests/data/printer/structure/moduleBinding.res
Fix https://github.com/rescript-lang/rescript/issues/7720
=> Fix formatter removed parens from functor type

CHANGELOG.md, rewatch/src/build/packages.rs, rewatch/testrepo/packages/with-dev-deps/package.json, rewatch/testrepo/packages/with-dev-deps/rescript.json, rewatch/testrepo/yarn.lock, rewatch/tests/snapshots/bs-dev-dependency-used-by-non-dev-source.txt, rewatch/tests/snapshots/dependency-cycle.txt, rewatch/tests/snapshots/remove-file.txt, rewatch/tests/snapshots/rename-file-internal-dep-namespace.txt, rewatch/tests/snapshots/rename-file-internal-dep.txt, rewatch/tests/snapshots/rename-file-with-interface.txt, rewatch/tests/snapshots/rename-file.txt, rewatch/tests/snapshots/rename-interface-file.txt
I'm in a very confused state writing this, but this PR might hold an answer to https://github.com/rescript-lang/rewatch/issues/124#issuecomment-3131420682
I could be wrong, but I don't think it makes sense to compile the `devDependencies` of your own non-local dependencies.
In the sample of https://github.com/greenfinity/rescript-sample-v12, a local package has:
`"bs-dependencies": ["rescript-nodejs"],`.
If I were to build that package with `--dev`, I don't think we want to build any `devDependencies` of `rescript-nodejs`. Like, why would we? For all we know, the sources are missing as in the `node_modules` anyway.
@jfrolich, @Bushuo, @cknitt any thoughts?
=> Move is_local_dep to Dependency struct

CHANGELOG.md, docs/docson/build-schema.json
- `"mode"` was removed.
- Added `"preserve"`.
=> Update jsx configuration schema

CHANGELOG.md, CONTRIBUTING.md, compiler/syntax/cli/res_cli.ml, compiler/syntax/src/res_core.ml, compiler/syntax/src/res_scanner.ml, compiler/syntax/src/res_scanner.mli, compiler/syntax/src/res_token.ml, compiler/syntax/src/res_token_debugger.ml, compiler/syntax/src/res_token_debugger.mli, tests/analysis_tests/tests-generic-jsx-transform/package.json, tests/analysis_tests/tests-incremental-typechecking/package.json, tests/analysis_tests/tests-reanalyze/deadcode/package.json, tests/analysis_tests/tests-reanalyze/termination/package.json, tests/analysis_tests/tests/package.json, tests/analysis_tests/tests/src/expected/CompletionJsx.res.txt, tests/syntax_tests/data/parsing/errors/expressions/expected/jsx.res.txt, tests/syntax_tests/data/parsing/errors/expressions/jsx.res, tests/syntax_tests/data/parsing/grammar/expressions/expected/jsx.res.txt, tests/syntax_tests/data/parsing/grammar/expressions/jsx.res
I was experimenting with the parser related to JSX and noticed that we have a somewhat convoluted mechanism for handling `/>` and `-` in identifier names.
First, I created a token dump tool in `res_parser`, which was previously missing.
Currently, the parser employs a sequence of `Scanner.set_jsx_mode p.Parser.scanner;` and `Scanner.pop_mode p.scanner Jsx;` while processing elements to distinguish between parser JSX and non-JSX. However, this is mainly used in the following cases:
- Allowing a `-` inside an identifier. This logic belongs in the parser, but it currently resides in the scanner, which feels inappropriate. 
- Combining a `<` + `/` into a `</` token. I would prefer using a lookahead for when a `<` is encountered. This would clarify that it's specific to JSX parsing. Even …
=> Refactor jsx mode in parser

CHANGELOG.md, rewatch/src/build/packages.rs
Use-case which @jderochervlk has with Deno.
@jfrolich setup is the following:
```
some-project
- rescript.json
- deno.json
```
User has no `package.json`, so we fallback to rescript.json for the name.
Do you see any problems with this?
=> Try and read package name from rescript.json if package.json is not present

CHANGELOG.md, lib/es6/Stdlib_Array.js, lib/es6/Stdlib_Dict.js, lib/es6/Stdlib_Map.js, lib/es6/Stdlib_Set.js, lib/es6/Stdlib_String.js, lib/js/Stdlib_Array.js, lib/js/Stdlib_Dict.js, lib/js/Stdlib_Map.js, lib/js/Stdlib_Set.js, lib/js/Stdlib_String.js, runtime/Stdlib_Array.res, runtime/Stdlib_Array.resi, runtime/Stdlib_Dict.res, runtime/Stdlib_Dict.resi, runtime/Stdlib_Map.res, runtime/Stdlib_Map.resi, runtime/Stdlib_Set.res, runtime/Stdlib_Set.resi, runtime/Stdlib_String.res, runtime/Stdlib_String.resi, tests/analysis_tests/tests-reanalyze/deadcode/package.json, tests/analysis_tests/tests/package.json, tests/analysis_tests/tests/src/expected/Completion.res.txt
- String.capitalize
- String.isEmpty
- Dict.size
- Dict.isEmpty
- Array.isEmpty
- Map.isEmpty
- Set.isEmpty
Let me know if I need to cherry-pick some changes.
=> Add a few Stdlib helpers

CHANGELOG.md, rewatch/src/build/clean.rs, rewatch/src/project_context.rs
=> Show both suffixes if multiple package specs with different extensions

CHANGELOG.md, compiler/syntax/src/res_core.ml, tests/syntax_tests/data/parsing/grammar/typedefinition/expected/missingPipeBeforeConstructorAttribute.res.txt, tests/syntax_tests/data/parsing/grammar/typedefinition/missingPipeBeforeConstructorAttribute.res, tests/syntax_tests/data/printer/typeDef/expected/missingPipeBeforeConstructorAttribute.res.txt, tests/syntax_tests/data/printer/typeDef/missingPipeBeforeConstructorAttribute.res
Fixes https://github.com/rescript-lang/rescript/issues/7578 by simply allowing it instead.
@shulhi GPT5 figured most of this out, but to me it looks reasonable and good. WDYT?
=> Allow skipping leading pipe in definitions of variants with attribute on leading constructor

CHANGELOG.md, compiler/syntax/src/res_core.ml, tests/tests/src/nested_records.mjs, tests/tests/src/nested_records.res
Fixes https://github.com/rescript-lang/rescript/issues/7756.
=> Pass and extend current_type_path in missing place

CHANGELOG.md, analysis/src/CompletionBackEnd.ml, analysis/src/CompletionFrontEnd.ml, analysis/src/Hover.ml, analysis/src/ProcessCmt.ml, analysis/src/ProcessExtra.ml, analysis/src/StructureUtils.ml, tests/analysis_tests/tests/src/FirstClassModules.res, tests/analysis_tests/tests/src/expected/FirstClassModules.res.txt
This improves the situation around first class modules, support completions for them, and enhancing hovers.
Ended up a bit more involved than I had hoped, but I think it worked out well in the end.
=> Support completions and better hovers for first class modules

CHANGELOG.md, rewatch/src/build.rs, rewatch/src/build/packages.rs, rewatch/src/build/parse.rs, rewatch/src/config.rs, rewatch/src/helpers.rs
This is another attempt to solve ppx resolution in monorepos.
The gist is that some workspaces can have `node_modules` on the root and the package level.
We take this into account for finding dependencies but didn't for ppx.
In this PR, I've refactored the same resolution code and reused it when looking for ppx.
I didn't add a test as it is very difficult to reproduce this in a yarn workspace.
It is my understanding that yarn will only show this behaviour when it fails to resolve a single version for the entire workspace.
@tsnobip could you give this one a go?
=> Reuse package resolution for ppx

CHANGELOG.md, compiler/ml/error_message_utils.ml, compiler/ml/typecore.ml, tests/build_tests/super_errors/expected/array_literal_passed_to_tuple.res.expected, tests/build_tests/super_errors/expected/object_literal_passed_when_record_expected.res.expected, tests/build_tests/super_errors/expected/pass_braced_identifier_to_record.res.expected, tests/build_tests/super_errors/expected/pass_braced_identifier_to_record_fn_argument.res.expected, tests/build_tests/super_errors/expected/string_constant_to_polyvariant.res.expected, tests/build_tests/super_errors/expected/string_constant_to_variant.res.expected, tests/build_tests/super_errors/fixtures/pass_braced_identifier_to_record.res, tests/build_tests/super_errors/fixtures/pass_braced_identifier_to_record_fn_argument.res
This is a pretty common gotcha - `{ident}` is counted as a block with an ident, not a record expr with a single field.
=> Error for braced single identifier to record

CHANGELOG.md, compiler/ml/typecore.ml, tests/build_tests/super_errors/expected/moreArguments1.res.expected, tests/build_tests/super_errors/expected/moreArguments4.res.expected
Just a small tweak. Happy for feedback on the hint message itself.
I'll add a changelog just before merging.
=> Hint about partial application in error where required labels are missing

CHANGELOG.md, analysis/src/CompletionFrontEnd.ml, analysis/src/ProcessCmt.ml, tests/analysis_tests/tests/src/FirstClassModules.res, tests/analysis_tests/tests/src/expected/FirstClassModules.res.txt
This refactors a bit and further improves completions around some cases with modules.
=> More improvements to completions involving modules

CHANGELOG.md, compiler/ml/typecore.ml, tests/build_tests/super_errors/expected/inline_record_escape.res.expected, tests/build_tests/super_errors/fixtures/inline_record_escape.res
An attempt to improve the (IMO quite cryptic) error message for inline records possibly escaping its scope. What do you think?
=> Try to improve error message about inline record escaping scope

.github/workflows/ci.yml
(No effect on the npm package, they are already excluded there.)
=> Do not include .ast/.iast files in lib-ocaml.zip artifact

.github/workflows/ci.yml
The default will change to `windows-2025` on Sep 2.
However, moving to `windows-2025` will require updating setup-ocaml and adapting our caching logic to the changed paths, see https://github.com/ocaml/setup-ocaml/pull/991.
=> CI: windows-latest -> windows-2022

CHANGELOG.md, compiler/syntax/src/res_outcome_printer.ml, tests/analysis_tests/tests/src/CreateInterface.res, tests/analysis_tests/tests/src/expected/CreateInterface.res.txt
When creating an interface file with `rescript-editor-analysis createInterface SomeFile.res`, invalid syntax was being generated for module types containing multiple type constraints.
For example:
```rescript
let make = (
type value identity,
~id: module(Belt.Id.Comparable with type t = value and type identity = identity),
): t<value, identity> => {
// ...
}
```
was being converted to interface:
```rescript
let make: (~id: module(Belt.Id.Comparable with type identity = 'a with type t = 'b)) => t<'b, 'a>
```
but `with type identity = 'a with type t = 'b` is invalid syntax and should have been `with type identity = 'a and type t = 'b` (notice the second `with` becomes `and`).
`res_outcome_printer` did have existing logic to emit `and` instead of `with`, but it relied on a ref counter that …
=> Fix generation of interfaces for module types containing multiple type constraints

compiler/bsb/bsb_exception.ml, compiler/core/js_packages_info.ml, compiler/depends/bs_exception.ml, compiler/ext/warnings.ml, compiler/frontend/bs_ast_invariant.ml, compiler/ml/typemod.ml, compiler/syntax/src/jsx_v4.ml, tests/build_tests/super_errors/expected/gadt_rec_missing.res.expected, tests/build_tests/super_errors/expected/react_component_with_props.res.expected
> Avoid the word “please,” except in situations in which the user is asked to do something inconvenient (such as creating a GitHub issue) or the software is to blame for the situation.
Fixes this: https://github.com/rescript-lang/rescript/pull/7830#discussion_r2316669680
=> Error messages cleanup: Don't please the user

CHANGELOG.md, rewatch/src/build/parse.rs, rewatch/src/config.rs, rewatch/tests/experimental.sh
The parser arguments were not added for new `LetUnwrap` features.
Note: in the future we might want to split up `get_experimental_features_args` to differentiate  between parser and compiler. But for now that doesn't apply and I didn't bother.
=> Fix experimental rescript config

CHANGELOG.md, cli/rescript.js
Replaced execFileSync with spawn to prevent blocking the event loop, allowing for proper signal forwarding and cleanup on termination. This change enhances the user experience during watch mode by ensuring that the Rust watcher can exit cleanly and that the parent process does not terminate prematurely. Added signal handling for SIGINT, SIGTERM, SIGHUP, and SIGQUIT to manage child process termination effectively.
This is to prevent the terminal being blocked after sending `ctrl + c` during watch mode.
Problem goes away after this PR:
=> Refactor CLI to use spawn for better signal handling in watch mode

CHANGELOG.md, analysis/bin/main.ml, analysis/src/Commands.ml, tests/analysis_tests/tests/src/PrepareRename.res, tests/analysis_tests/tests/src/expected/PrepareRename.res.txt
This adds a `prepareRename` command to the analysis bin that the editor tooling can use to get quick feedback for whether the target thing can be renamed or not.
Background for this is that our current rename functionality feels _slow_, and that's because it does all the heavy lifting of figuring out all places a rename needs to be applied, plus producing the actual text edits, twice - once to simply check if something can be renamed, and then again to do the actual rename. The command added in this PR replaces the first with a light weight super fast command that only looks at the untyped AST.
Will need adjustments in the editor tooling repo too for this to actually work.
=> Add prepareRename command

biome.json, cli/common/bsb.js, cli/rescript.js, package.json
Biome would sometimes report problems locally, but not in CI because of the `--changed` flag.
As there are not so many such problems anyway, just remove the `--changed` and commit the fixes.
=> Have biome check all files, not just changed ones

.github/workflows/ci.yml, package.json, packages/@rescript/darwin-arm64/package.json, packages/@rescript/darwin-x64/package.json, packages/@rescript/linux-arm64/package.json, packages/@rescript/linux-x64/package.json, packages/@rescript/runtime/package.json, packages/@rescript/win32-x64/package.json
The largest supply chain attack has recently affected many popular packages. It was a simple phishing attack targeted the maintainer's account and 2FA token.
While this doesn't prevent attacks directly targeting maintainers, it does make package usage more secure.
- [Trusted publishers](https://docs.npmjs.com/trusted-publishers) allow tokenless workflows via OIDC and prevent abuse of authorized maintainer access tokens.
- [Provenance](https://docs.npmjs.com/generating-provenance-statements) allows you to verify that a version was published through a reviewed workflow.
administration guide:
- Set up the trusted publisher first in the NPM package settings page.  (I don't have permission, maybe @cknitt has?)
- Disallow publishing via token, bypassing the 2FA.
- Remove the NPM token from this …
=> setup trusted publishers and provenance

.github/workflows/ci.yml, rewatch/Cargo.toml, rewatch/src/build/parse.rs
I’ve had some builds that install version 1.90 unexpectedly. Please pin it to version 1.88 until we intentionally move to a newer version. Any upgrade should be a conscious decision.
Failed build: https://github.com/rescript-lang/rescript/actions/runs/17830424349/job/50693695893#step:11:138
Notice
```
rustc 1.90.0 (1159e78c4 2025-09-14)
binary: rustc
commit-hash: 1159e78c4747b02ef996e55082b704c09b970588
commit-date: 2025-09-14
host: x86_64-unknown-linux-gnu
release: 1.90.0
LLVM version: 20.1.8
```
=> Use Rust 1.88 during CI

CHANGELOG.md, compiler/syntax/src/res_core.ml, tests/syntax_tests/data/parsing/errors/other/dict_spread.res, tests/syntax_tests/data/parsing/errors/other/expected/dict_spread.res.txt
We do not support spreads in dict literals yet, but one day we will. This gives a proper error for the spread in the meantime.
=> Dedicated error for dict literal spread

rewatch/src/build.rs, rewatch/src/build/build_types.rs, rewatch/src/build/clean.rs, rewatch/src/build/compile.rs, rewatch/src/build/compiler_info.rs, rewatch/src/build/packages.rs, rewatch/src/build/parse.rs
Fixes https://github.com/rescript-lang/rescript/issues/7436
It produces a `lib/bs/compiler-info.json` file which contains:
```json
{
"version": "12.0.0-beta.12",
"bsc_path": "/Users/nojaf/Projects/vrindelycker/node_modules/@rescript/darwin-arm64/bin/bsc.exe",
"bsc_hash": "7d113813ca550965be97771da2ce2d47f85d297eda9e568763e54d31e0b8098d",
"rescript_config_hash": "226055db0876bea957f7b3b597478f95fdaefb4547704d6557c5dceb64772a1b",
"runtime_path": "/Users/nojaf/Projects/vrindelycker/node_modules/@rescript/runtime",
"generated_at": "1757936814848"
}
```
`"runtime_path"` and `"bsc_path"` might be interesting for tooling to pick up.
That hash compare is also really useful when working with a local compiler.
=> Keep track of compiler info during build

CHANGELOG.md, compiler/core/lam_pass_remove_alias.ml, tests/tests/src/gpr_3980_test.mjs, tests/tests/src/option_optimisation.mjs, tests/tests/src/option_optimisation.res, tests/tests/src/record_regression.mjs
Optimizes the option alias pass so we skip the redundant is-not-none guard whenever the compiler already knows the value is `Some`, which trims the JS we emit for simple constant cases.
=> Improve option optimization for constants

.github/workflows/ci.yml, CHANGELOG.md
https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/
> The macOS 13 runner image will be retired by December 4th, 2025.
=> CI: macos runners: use macos-15/macos-15-intel

CHANGELOG.md, analysis/reanalyze/src/Arnold.ml, analysis/reanalyze/src/DeadOptionalArgs.ml, analysis/reanalyze/src/DeadValue.ml, analysis/src/CompletionBackEnd.ml, analysis/src/CompletionFrontEnd.ml, analysis/src/CreateInterface.ml, analysis/src/SharedTypes.ml, analysis/src/SignatureHelp.ml, analysis/src/TypeUtils.ml, compiler/gentype/TranslateCoreType.ml, compiler/gentype/TranslateStructure.ml, compiler/gentype/TranslateTypeExprFromTypes.ml, compiler/ml/asttypes.ml, compiler/ml/btype.ml, compiler/ml/btype.mli, compiler/ml/ctype.ml, compiler/ml/ctype.mli, compiler/ml/printtyp.ml, compiler/ml/printtyp.mli, compiler/ml/printtyped.ml, compiler/ml/typecore.ml, compiler/ml/typecore.mli, compiler/ml/typedtree.ml, compiler/ml/typedtree.mli, compiler/ml/types.ml, compiler/ml/types.mli, compiler/ml/typetexp.ml
This migrates fn arguments to use the AST nodes with locations in the typed tree as well. It was previously just used for the parsetree.
Lays the foundations for some other refactors as well.
=> Migrate typed tree to use AST with locs for fn arguments
